CREATE TABLE [Retail_Miniapps].[FinancialBudgetForecast] (

	[fbf_storetype] char(8) NULL, 
	[fbf_accountNum] varchar(10) NULL, 
	[fbf_database] char(12) NULL, 
	[fbf_storeID] char(4) NOT NULL, 
	[fbf_unit] char(7) NULL, 
	[fbf_storeLocation] varchar(60) NULL, 
	[fbf_year] int NULL, 
	[fbf_period] int NULL, 
	[fbf_date] datetime2(6) NOT NULL, 
	[fbf_budget_wrt_cogs] decimal(13,4) NULL, 
	[fbf_budget_wrt_sales] decimal(13,4) NULL, 
	[fbf_derivedups] decimal(13,4) NULL, 
	[fbf_closeratio] decimal(13,4) NULL, 
	[fbf_avg_tkt] decimal(13,4) NULL, 
	[fbf_spg] decimal(13,4) NULL, 
	[fbf_budget_inv_cogs] decimal(13,4) NULL, 
	[fbf_budget_inv_sales] decimal(13,4) NULL, 
	[fbf_budget_deliveryincome_rate] decimal(13,4) NULL, 
	[fbf_budget_deliveryincome_wrt_sales] decimal(13,4) NULL, 
	[fbf_budget_deliveryincome_inv_sales] decimal(13,4) NULL, 
	[fbf_budget_finance_fees_rate] decimal(13,4) NULL, 
	[fbf_budget_finance_fees_wrt_sales] decimal(13,4) NULL, 
	[fbf_budget_finance_fees_inv_sales] decimal(13,4) NULL, 
	[LastUpdateDate] datetime2(6) NOT NULL
);