CREATE TABLE [Retail_Miniapps].[Salesman] (

	[operation] varchar(20) NULL, 
	[ID] varchar(20) NULL, 
	[NAME] varchar(50) NULL, 
	[ADDR_1] varchar(50) NULL, 
	[ADDR_2] varchar(10) NULL, 
	[AMT_LAST_MTH] varchar(10) NULL, 
	[AMT_YTD] varchar(20) NULL, 
	[CAN_RSVD_MTD] varchar(10) NULL, 
	[CAN_RSVD_YTD] varchar(10) NULL, 
	[CITY] varchar(40) NULL, 
	[CMSN_RATE] varchar(10) NULL, 
	[NCR_MTD] varchar(10) NULL, 
	[NCR_YTD] varchar(10) NULL, 
	[PHONE_NO] varchar(10) NULL, 
	[SOFT_LOCK] varchar(10) NULL, 
	[ST] varchar(20) NULL, 
	[ZIP] varchar(20) NULL, 
	[HSTORE] varchar(20) NULL, 
	[CSTORE] varchar(20) NULL, 
	[SMTYP] varchar(20) NULL, 
	[MGRID] varchar(20) NULL, 
	[SPCLS] int NULL, 
	[people_id] int NULL, 
	[lastdate] datetime2(6) NULL, 
	[active_status] bit NULL, 
	[CreatedDate] datetime2(6) NULL, 
	[CreatedBy] varchar(20) NULL, 
	[ChangedDate] datetime2(6) NULL, 
	[ChangedBy] varchar(20) NULL, 
	[CommissionCategory] varchar(20) NULL, 
	[CommissionReportIndicator] bit NULL, 
	[PrimaryID] varchar(20) NULL, 
	[InitialPrimaryID] varchar(20) NULL, 
	[TeamID] int NULL
);