CREATE TABLE [Retail_Miniapps].[VIPCustCommLog] (

	[Operation] char(3) NULL, 
	[ID] int NOT NULL, 
	[SalesOrder] varchar(255) NULL, 
	[LocationID] varchar(255) NULL, 
	[CustomerID] varchar(255) NULL, 
	[CustomerFirstName] varchar(255) NULL, 
	[CustomerLastName] varchar(255) NULL, 
	[CustomerPhoneNumber] varchar(255) NULL, 
	[ReasonForCancellationRequest] varchar(8000) NULL, 
	[WhatHasBeenDoneToSaveSale] varchar(8000) NULL, 
	[AmountAtRisk] float NULL, 
	[AdditionalInformation] varchar(8000) NULL, 
	[Results] int NULL, 
	[NATCRCode] int NULL, 
	[NATCRComment] varchar(8000) NULL, 
	[Followed Date] datetime2(6) NULL, 
	[PendingComment] varchar(8000) NULL, 
	[FullOrderSaved] bit NULL, 
	[PartialSavedAmount] bit NULL, 
	[Discount] bit NULL, 
	[AmountOfDiscount] float NULL, 
	[FreeDelivery] bit NULL, 
	[AmountDelivery] float NULL, 
	[ProductLocated] bit NULL, 
	[EarlierDelivery] bit NULL, 
	[CorrectedOrder] bit NULL, 
	[PartOrdered] bit NULL, 
	[ServiceSet] bit NULL, 
	[Reselected] bit NULL, 
	[Communication] bit NULL, 
	[Other] bit NULL, 
	[OtherComment] varchar(8000) NULL, 
	[DiscountAmount] float NULL, 
	[AmountSaved] float NULL, 
	[OriginalAmount] float NULL, 
	[Taxes] float NULL, 
	[ReasonIfCancelled] int NULL, 
	[WhyCouldItNotBeSaved] varchar(8000) NULL, 
	[CoSalesComments] varchar(8000) NULL, 
	[RowDeleted] bit NULL, 
	[IssueLoggedBy] varchar(50) NULL, 
	[IssueLoggedDate] datetime2(6) NULL, 
	[IssueLastCompletedBy] varchar(255) NULL, 
	[IssueLastCompletedDate] datetime2(6) NULL, 
	[DataSource] varchar(50) NULL, 
	[RequestFrom] int NULL, 
	[SubCategReasonIfCancelled] int NULL, 
	[StatusOfDelivery] int NULL, 
	[LastCancelledDate] datetime2(6) NULL
);