CREATE TABLE [Customers].[ShippingLocations]
    (
        [CustomerNumber]               CHAR(8)        NULL,
        [ShiptoNumber]                 CHAR(4)        NULL,
        [MapicsSequenceNumber]         SMALLINT       NULL,
        [Name]                         VARCHAR(35)    NULL,
        [Address1]                     VARCHAR(25)    NULL,
        [Address2]                     VARCHAR(25)    NULL,
        [Address3]                     VARCHAR(25)    NULL,
        [ZipCode]                      VARCHAR(10)    NULL,
        [State]                        CHAR(2)        NULL,
        [Country]                      CHAR(3)        NULL,
        [Phone]                        VARCHAR(15)    NULL,
        [Faxtn]                        VARCHAR(15)    NULL,
        [TaxExempt]                    CHAR(5)        NULL,
        [Website]                      VARCHAR(40)    NULL,
        [Email]                        VARCHAR(50)    NULL,
        [CommissionCode]               CHAR(3)        NULL,
        [FreightCode]                  CHAR(3)        NULL,
        [PriceCode]                    CHAR(6)        NULL,
        [DiscountCode]                 CHAR(3)        NULL,
        [CommissionSplit]              DECIMAL(7, 4)  NULL,
        [DefaultWarehouse]             CHAR(3)        NULL,
        [ShippingTerritory]            CHAR(5)        NULL,
        [BusinessType]                 CHAR(2)        NULL,
        [ShipType]                     CHAR(2)        NULL,
        [TranscomPrimaryID]            VARCHAR(13)    NULL,
        [Contact]                      CHAR(25)       NULL,
        [Comment1]                     VARCHAR(25)    NULL,
        [Comment2]                     VARCHAR(25)    NULL,
        [TerritoryEffectivityDate]     DATETIME2(6)   NULL, ---DATETIME2(6) 
        [ServiceRepID]                 CHAR(5)        NULL,
        [CRMPhone]                     VARCHAR(15)    NULL,
        [CRMFax]                       VARCHAR(15)    NULL,
        [CRMContact]                   VARCHAR(25)    NULL,
        [CRMEmail]                     VARCHAR(50)    NULL,
        [Memo]                         VARCHAR(8000)  NULL, --VARCHAR(MAX)
        [MSA_FIPS]                     CHAR(4)        NULL,
        [RMCityNumber]                 INT            NULL,
        [TranscomAlternateID]          CHAR(8)        NULL,
        [Directions]                   VARCHAR(150)   NULL,
        [CrossStreet]                  VARCHAR(35)    NULL,
        [ChgAddr]                      BIT            NULL,
        [ChgShip]                      BIT            NULL,
        [ChgShipExt]                   BIT            NULL,
        [ChgCust]                      BIT            NULL,
        [commaudit]                    BIT            NULL,
        [commaudit2]                   BIT            NULL,
        [AddedByUser]                         VARCHAR(30)    NULL,
        [DateAdded]                         DATETIME2(6)   NULL, -- DATETIME2(6) 
        [ChangeByUser]                         VARCHAR(30)    NULL,
        [DateChange]                         DATETIME2(6)   NULL, ---DATETIME2(6) 
        [ActiveRecord]                        CHAR(1)        NULL,
        [County]                       CHAR(3)        NULL,
        [BlockRepOrderEntry]           BIT            NULL,
        [CustomerSegment]              INT        NULL,
        [LastStatusChangeDate]         DATETIME2(6)   NULL, ---DATETIME2(6) 
        [BuyerAddressID]               INT            NULL,
        [PartyLocationID]              INT            NULL,
        [RouteAddressID]               INT            NULL,
        [DefaultOrderType1]            CHAR(1)        NULL,
        [DefaultOrderType2]            CHAR(1)        NULL,
        [DefaultOrderType3]            CHAR(1)        NULL,
        [DefaultOrderType4]            CHAR(1)        NULL,
        [ShippingLeadTime]             SMALLINT       NULL,
        [ApplicationCode]              INT            NULL,
        [AllowFax]                     CHAR(1)        NULL,
        [DirectConsumer]               CHAR(1)        NULL,
        [DeliveryUnitOfMeasure]        CHAR(1)        NULL,
        [DeliveryUnitOfMeasureFence]   DECIMAL(7, 2)  NULL,
        [ExportsLCLConsolidationFlag]  CHAR(1)        NULL,
        [ExportsDocumentCountry]       CHAR(3)        NULL,
        [ExportsProductOnPallets]      CHAR(1)        NULL,
        [ExportsAppointmentsRequired]  CHAR(1)        NULL,
        [HasDock]                      BIT            NULL,
        [HasDockUserDate]              VARCHAR(50)    NULL,
        [ExpressShippingMethod]        CHAR(3)        NULL,
        [DirectIncludeShipto]          CHAR(1)        NULL,
        [ExpressHandlingCharge]        DECIMAL(4, 3)  NULL,
        [ExpressMinimum]               DECIMAL(10, 2) NULL,
        [ExpressMaximum]               DECIMAL(10, 2) NULL,
        [DefaultLanguage]              CHAR(8)        NULL,
        [ExpressServiceContractNumber] VARCHAR(50)    NULL,
        [UseNegotiatedFreightRate]     CHAR(1)        NULL,
        [UseStandardFreightRate]       CHAR(1)        NULL,
        [DoNotRepriceOrders]           CHAR(1)        NULL,
        [PricingUseOfflineFiles]       CHAR(1)        NULL,
        [ReturnAddressID]              INT            NULL,
        [ReturnAddressName]            VARCHAR(35)    NULL
    );
--- DATA_SOURCE = [AzureStorageGen2a],
--- LOCATION = N'/Wholesale/Customers/ShippingLocations/AFI_Sales_tblCustomerShippingLocations.snappy.parquet',
--- FILE_FORMAT = [ParquetFileFormatSnappy],
