CREATE TABLE [Retail_Sales_Enh].[SalesPersonUPBoardHistory] (

	[Source] varchar(5) NOT NULL, 
	[StoreID] int NOT NULL, 
	[ScoreboardStoreID] int NOT NULL, 
	[SalesPersonID] varchar(30) NULL, 
	[ScoreboardSalesPersonID] int NULL, 
	[SalesPersonName] varchar(100) NULL, 
	[SalesPersonUserName] varchar(30) NULL, 
	[StatusStartTime] datetime2(3) NOT NULL, 
	[StatusEndTime] datetime2(3) NULL, 
	[StatusStartDate] date NOT NULL, 
	[StatusStartHour] int NULL, 
	[RecordedUpDate] date NULL, 
	[RecordedUpHour] int NULL, 
	[SPUBStatusID] int NULL, 
	[GuestName] varchar(100) NULL, 
	[isCountedAsUP] int NULL, 
	[isSale] int NULL, 
	[StrikeCount] int NULL, 
	[Shot] int NULL, 
	[FinApp] int NULL, 
	[ReasonManagerAddWith] varchar(500) NULL, 
	[ReasonManagerAddSP] varchar(500) NULL, 
	[ReasonManagerAddUps] varchar(500) NULL, 
	[ReasonManagerRemoveSP] varchar(500) NULL, 
	[ManagerCoachingNotes] varchar(500) NULL, 
	[ManagerCoachingNotesTime] datetime2(3) NULL, 
	[IsStrike] bit NULL, 
	[IsStrikeOut] bit NULL, 
	[ConsecutiveStrikes] int NULL, 
	[ConsecutiveStrikeOuts] int NULL
);