CREATE TABLE [Retail_OOM_Enh].[Buckets] (

	[BucketID] int NULL, 
	[LocationID] varchar(50) NOT NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[QtyOnHand] int NULL, 
	[TotalInc] int NULL, 
	[TotalReqd] int NULL, 
	[QtyRsvd] int NULL, 
	[UnitCost] decimal(18,2) NULL, 
	[LeadDays] int NULL, 
	[POPadDays] int NULL, 
	[ProcessStatus] int NULL, 
	[BatchID] int NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[ATPPeriodID] int NULL, 
	[InvSubBucketID] varchar(50) NULL, 
	[ABCCode] char(1) NULL, 
	[SvcLocationID] varchar(50) NULL, 
	[LandedAvgCost] decimal(18,2) NULL, 
	[AverageRoS] decimal(18,2) NULL, 
	[LTDeviation] decimal(18,2) NULL, 
	[QtyComtd] int NULL, 
	[CarrierLeadDays] int NULL, 
	[ATPPadDays] int NULL, 
	[VendorAtpQty] int NULL, 
	[ATPLeadDate] date NULL, 
	[CurrentAtpQA] int NULL
);