CREATE TABLE [Retail_OOM_Enh].[OpenOrderSummaryDetail] (

	[BODTransDate] date NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[OrderDate] date NULL, 
	[StoreID] varchar(50) NOT NULL, 
	[ShipLocationID] varchar(50) NULL, 
	[OrderType] varchar(60) NULL, 
	[FulfillmentMethod] varchar(10) NULL, 
	[FulfillmentStatus] varchar(10) NULL, 
	[ContactStatus] varchar(20) NULL, 
	[ContactDate] date NULL, 
	[FulfillmentDate] date NULL, 
	[PastDue] varchar(1) NOT NULL, 
	[Filled] varchar(1) NOT NULL, 
	[CustomerID] varchar(50) NULL, 
	[CustomerName] varchar(255) NULL, 
	[SalesPerson] varchar(50) NULL, 
	[MerchSubTot] decimal(38,2) NULL, 
	[TaxAmt] decimal(38,2) NULL, 
	[DlvyChrg] decimal(38,2) NULL, 
	[TotalFulfilment] int NULL, 
	[TotalPieces] int NULL, 
	[ReservedPieces] int NULL, 
	[TotalCost] decimal(38,2) NULL, 
	[ReservedCost] decimal(38,2) NULL, 
	[TotalSales] decimal(38,2) NULL, 
	[ReservedSales] decimal(38,2) NULL, 
	[TotalVolume] decimal(38,2) NULL, 
	[ReservedVolume] decimal(38,2) NULL, 
	[TotalWeight] decimal(38,2) NULL, 
	[ReservedWeight] decimal(38,2) NULL
);