CREATE TABLE [Retail_Ecommerce].[RetailDiscountStaging] (

	[DefinitionGroup] varchar(60) NOT NULL, 
	[ExecutionId] varchar(90) NOT NULL, 
	[IsSelected] int NOT NULL, 
	[TransferStatus] int NOT NULL, 
	[ConcurrencyMode] int NOT NULL, 
	[CurrencyCode] char(3) NOT NULL, 
	[DateValidationType] int NOT NULL, 
	[Description] varchar(300) NULL, 
	[Disclaimer] varchar(750) NULL, 
	[DiscountPercentValue] decimal(32,6) NOT NULL, 
	[IsDiscountCodeRequired] int NOT NULL, 
	[Name] varchar(60) NOT NULL, 
	[OfferId] varchar(20) NOT NULL, 
	[PeriodicDiscountTYPE] int NOT NULL, 
	[Status] int NOT NULL, 
	[ValidationPeriodId] varchar(10) NOT NULL, 
	[ValidFrom] datetime2(6) NOT NULL, 
	[ValidTo] datetime2(6) NOT NULL, 
	[MultiBuyDiscountType] int NOT NULL, 
	[ThresholdCountNonDiscountITEMS] int NOT NULL, 
	[MixAndMatchDealPrice] decimal(32,6) NOT NULL, 
	[MixAndMatchDiscountAmount] decimal(32,6) NOT NULL, 
	[MixAndMatchDiscountType] int NOT NULL, 
	[MixAndMatchNoofLeastExpensiveLines] int NOT NULL, 
	[MixAndMatchLeastExpensiveMode] int NOT NULL, 
	[DiscountCode] varchar(60) NOT NULL, 
	[BarCode] varchar(80) NOT NULL, 
	[DiscountLedgerDimensionDisplayValue] varchar(500) NOT NULL, 
	[DiscountRecordId] bigint NOT NULL, 
	[OfferQuantityLimit] int NOT NULL, 
	[Partition] varchar(20) NOT NULL, 
	[PrintDescriptionOnFiscalReceipt] varchar(50) NOT NULL, 
	[PricingPriorityNumber] int NOT NULL, 
	[MatchAllAssociatedPriceGroups] int NOT NULL, 
	[ProcessingStatus] int NOT NULL, 
	[DisabledSince] datetime2(6) NOT NULL, 
	[AFRPromoCode] varchar(50) NOT NULL, 
	[DataAreaId] char(4) NOT NULL, 
	[SyncStartDatetime] datetime2(6) NOT NULL, 
	[RecId] bigint NOT NULL
);