CREATE TABLE [Retail_DW_Core].[DimProduct] (

	[ProductKey] bigint NOT NULL, 
	[SKU] varchar(50) NOT NULL, 
	[AFISKU] varchar(30) NULL, 
	[ProductBrandID] varchar(20) NULL, 
	[SKUName] varchar(100) NULL, 
	[VendorModelNumber] varchar(50) NULL, 
	[VendorID] varchar(20) NULL, 
	[VendorStyle] varchar(50) NULL, 
	[VendorName] varchar(50) NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[CategoryID] varchar(40) NOT NULL, 
	[PrimaryCategory] int NOT NULL, 
	[SubGroupID] varchar(20) NULL, 
	[SubGroupName] varchar(100) NULL, 
	[CollectionID] varchar(50) NULL, 
	[CollectionName] varchar(100) NULL, 
	[ListPrice] decimal(18,4) NULL, 
	[SalePrice] decimal(18,4) NULL, 
	[ReplacementCost] decimal(18,4) NULL, 
	[PurchaseStatus] char(1) NULL, 
	[ProductStatus] varchar(50) NULL, 
	[SeriesID] varchar(20) NULL, 
	[PPPGroupID] varchar(20) NULL, 
	[ProductCollectionLifestyle] varchar(50) NULL, 
	[VendorStyleID] varchar(30) NULL, 
	[PricePointSegmentation] varchar(20) NULL, 
	[PricePoint] decimal(18,4) NULL, 
	[DespisedDate] datetime2(3) NULL, 
	[CubicFeet] decimal(18,4) NULL, 
	[SpecialOrderFlag] bit NULL
);