CREATE TABLE [Retail_DW_Core].[DimSalesPerson] (
    [SalesPersonKey]    BIGINT          NOT NULL,
    [SalesPersonID]     VARCHAR (30)    NOT NULL,
    [StaffID]           VARCHAR (30)    NULL,
    [EmployeeNumber]    VARCHAR (20)    NULL,
    [StaffTypeID]       VARCHAR (20)    NULL,
    [SalesPersonName]   VARCHAR (255)   NULL,
    [SalesPersonTypeID] VARCHAR (20)    NULL,
    [ActiveStatus]      VARCHAR (20)    NULL,
    [ManagerID]         VARCHAR (20)    NULL,
    [Address1]          VARCHAR (100)   NULL,
    [Address2]          VARCHAR (100)   NULL,
    [City]              VARCHAR (50)    NULL,
    [State]             VARCHAR (20)    NULL,
    [PostalCode]        VARCHAR (50)    NULL,
    [PhoneNumber]       VARCHAR (20)    NULL,
    [HomeStore]         VARCHAR (30)    NULL,
    [CommissionStore]   VARCHAR (30)    NULL,
    [CommissionRate]    DECIMAL (19, 4) NULL,
    [PeopleID]          VARCHAR (20)    NULL,
    [PrimaryID]         VARCHAR (30)    NULL,
    [InitialPrimaryID]  VARCHAR (30)    NULL,
    [DateCreated]       DATETIME2 (3)   NULL,
    [DateChanged]       DATETIME2 (3)   NULL,
    [HireDate]          DATETIME2 (3)   NULL
);