CREATE TABLE [Retail_DW_Core].[DimTimeSheetSummary] (
	[SourceDataID] [int] NULL,
	[TransDate] [date] NULL,
	[LocationID] [int] NULL,
	[LocationKey] [int] NULL,
	[LocationName] [varchar](255) NULL,
	[LocationType] [varchar](5) NULL,
	[Productive] [int] NULL,
	[PayCodeID] [int] NULL,
	[PayCodeName] [varchar](50) NULL,
	[TaskCodeID] [int] NULL,
	[TaskCodeName] [varchar](100) NULL,
	[TimeCodeID] [int] NULL,
	[TotalHours] [decimal](18,2) NULL,
	[RegularHours] [decimal](18,2) NULL,
	[OverTimeHours] [decimal](18,2) NULL,
	[ExternalHours] [decimal](18,2) NULL,
	[InternalHours] [decimal](18,2) NULL,
	[TotalCost] [decimal](18,2) NULL,
	[RegularCost] [decimal](18,2) NULL,
	[OverTimeCost] [decimal](18,2) NULL,
	[ExternalCost] [decimal](18,2) NULL,
	[InternalCost] [decimal](18,2) NULL,
	[Benefit] [decimal](18,4) NULL,
	[IsExternal] [bit] NULL,
	[ApprovedByManager] [bit] NULL,
	[DataSource] [varchar](5) NOT NULL
);