CREATE TABLE [Retail_DW_Core].[FactStorePulseFinal] (
    [Division]                                        VARCHAR (50)     NULL,
    [Region]                                          VARCHAR (50)     NULL,
    [OrderChangeDate_M]                               DATE             NULL,
    [CalendarYear_M]                                  SMALLINT         NULL,
    [Alt_CalendarWeek_M]                              INT              NULL,
    [Alt_CalendarWeekLastDate]                        DATE             NULL,
    [Alt_CalendarWeekIndicator_M]                     INT              NULL,
    [CalendarMonthLastDate_M]                         DATE             NULL,
    [CalendarMonthFirstDate_M]                        DATE             NULL,
    [CalendarMonthIndicator_M]                        INT              NULL,
    [Alt_CalendarYearIndicator_M]                     INT              NULL,
    [Datekey_M]                                       INT              NULL,
    [CompLocation_M]                                  VARCHAR (3)      NULL,
    [StoreLocation_M]                                 VARCHAR (255)    NULL,
    [Updated_Region_M]                                VARCHAR (50)     NULL,
    [Written_Gross_Sales_M]                           NUMERIC (38, 2)  NULL,
    [REAC_Per_M]                                      NUMERIC (38, 2)  NULL,
    [Numerator_REAC_M]                                NUMERIC (38, 2)  NULL,
    [Denominator_REAC_M]                              NUMERIC (38, 2)  NULL,
    [Written_Sales_Dol_M]                             NUMERIC (38, 2)  NULL,
    [Written_Sales.d_Dol_M]                           NUMERIC (38, 2)  NULL,
    [Written_GM_Dol_M]                                NUMERIC (38, 2)  NULL,
    [Written_GM_Per_M]                                NUMERIC (38, 6)  NULL,
    [Numerator_WrittenGMPer_M]                        NUMERIC (38, 2)  NULL,
    [Denominator_WrittenGMPer_M]                      NUMERIC (38, 2)  NULL,
    [GMFF_Per_M]                                      NUMERIC (38, 6)  NULL,
    [Numerator_GMFFPer_M]                             NUMERIC (38, 2)  NULL,
    [Denominator_WrittenGMFFPer_M]                    NUMERIC (38, 2)  NULL,
    [Delivered_Sales_Dol_M]                           NUMERIC (38, 2)  NULL,
    [Delivered_GM_Dol_M]                              NUMERIC (38, 2)  NULL,
    [Delivered_GM_Per_M]                              NUMERIC (38, 6)  NULL,
    [Numerator_DeliveredGMPer_M]                      NUMERIC (38, 2)  NULL,
    [Denominator_DeliveredGMPer_M]                    NUMERIC (38, 2)  NULL,
    [SPG_M]                                           NUMERIC (38, 6)  NULL,
    [Numerator_SPG_M]                                 NUMERIC (38, 2)  NULL,
    [Denominator_SPG_M]                               DECIMAL (38, 2)  NULL,
    [SPG.d_M]                                         NUMERIC (38, 6)  NULL,
    [Numerator_SPGd_M]                                NUMERIC (38, 2)  NULL,
    [Denominator_SPGd_M]                              DECIMAL (38, 2)  NULL,
    [Average_Sales_Dol_M]                             INT              NOT NULL,
    [Numerator_AvgSalesDol_M]                         NUMERIC (38, 2)  NULL,
    [Denominator_AvgSalesDol_M]                       DECIMAL (38, 4)  NULL,
    [Average_Sales.d_Dol_M]                           INT              NOT NULL,
    [Numerator_AvgSalesdDol_M]                        NUMERIC (38, 2)  NULL,
    [Denominator_AvgSalesdDol_M]                      INT              NOT NULL,
    [Close_Per__TG__M]                                INT              NOT NULL,
    [Numerator_Close_M]                               DECIMAL (38, 4)  NULL,
    [Denominator_Close_M]                             DECIMAL (38, 2)  NULL,
    [Delivery_Fee_Dol_M]                              NUMERIC (38, 2)  NULL,
    [Delivery_SPG_Dol_M]                              NUMERIC (38, 6)  NULL,
    [Numerator_DelSPG_M]                              NUMERIC (38, 2)  NULL,
    [Denominator_DelSPG_M]                            DECIMAL (38, 2)  NULL,
    [Delivery_Per_of_Sales_M]                         NUMERIC (38, 6)  NULL,
    [Numerator_DelPerofSales_M]                       NUMERIC (38, 2)  NULL,
    [Denominator_DelPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Email_Capture_Per_M]                             INT              NOT NULL,
    [Numerator_EmailCapture_M]                        INT              NULL,
    [Numerator_EmailCaptureSuperOrder_M]              INT              NULL,
    [Denominator_EmailCapture_M]                      INT              NULL,
    [Sales_Count_M]                                   INT              NULL,
    [Email_Count_z_M]                                 INT              NULL,
    [ValidCaptureCount_M]                             INT              NULL,
    [Traffic_Guests__TG__M]                           DECIMAL (38, 2)  NULL,
    [Recorded_Guests__RG__M]                          INT              NULL,
    [Capture_Rate_M]                                  INT              NOT NULL,
    [Sleep_Assessments/Rest_Tests_M]                  INT              NULL,
    [Attachment_PowerBase_to_Mattresses_M]            INT              NOT NULL,
    [Numerator_AttPBtoMatt_M]                         NUMERIC (38, 2)  NULL,
    [Denominator_AttPBtoMatt_M]                       NUMERIC (38, 2)  NULL,
    [Bedding_Dol_M]                                   NUMERIC (38, 2)  NULL,
    [Bedding_GM_Per_M]                                NUMERIC (38, 6)  NULL,
    [Numerator_BeddingGMPer_M]                        NUMERIC (38, 2)  NULL,
    [Denominator_BeddingGMPer_M]                      NUMERIC (38, 2)  NULL,
    [Bedding_SPG_Dol_M]                               NUMERIC (38, 6)  NULL,
    [Numerator_BeddingSPG_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_BeddingSPG_M]                        DECIMAL (38, 2)  NULL,
    [Bedding_Per_of_Sales_M]                          NUMERIC (38, 6)  NULL,
    [Numerator_BeddingPerOfSales_M]                   NUMERIC (38, 2)  NULL,
    [Denominator_BeddingPerOfSales_M]                 NUMERIC (38, 2)  NULL,
    [Bedding_AUSP_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_BeddingAUSP_M]                         NUMERIC (38, 2)  NULL,
    [Denominator_BeddingAUSP_M]                       INT              NULL,
    [ACCESS_GM_Per_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_ACCESSGMPer_M]                         NUMERIC (38, 2)  NULL,
    [Denominator_ACCESSGMPer_M]                       NUMERIC (38, 2)  NULL,
    [ACCESS_SPG_Dol_M]                                NUMERIC (38, 6)  NULL,
    [Numerator_ACCESS_SPG_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_ACCESS_SPG_M]                        DECIMAL (38, 2)  NULL,
    [ACCESS_Per_of_Sales_M]                           NUMERIC (38, 6)  NULL,
    [Numerator_AccessPerofSales_M]                    NUMERIC (38, 2)  NULL,
    [Denominator_AccessPerofSales_M]                  NUMERIC (38, 2)  NULL,
    [BEDRO_GM_Per_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_BEDROGMPer_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_BEDROGMPer_M]                        NUMERIC (38, 2)  NULL,
    [BEDRO_SPG_Dol_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_BEDRO_SPG_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_BEDRO_SPG_M]                         DECIMAL (38, 2)  NULL,
    [BEDRO_Per_of_Sales_M]                            NUMERIC (38, 6)  NULL,
    [Numerator_BEDROPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Denominator_BEDROPerofSales_M]                   NUMERIC (38, 2)  NULL,
    [CASEG_GM_Per_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_CASEGGMPer_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_CASEGGMPer_M]                        NUMERIC (38, 2)  NULL,
    [CASEG_SPG_Dol_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_CASEG_SPG_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_CASEG_SPG_M]                         DECIMAL (38, 2)  NULL,
    [CASEG_Per_of_Sales_M]                            NUMERIC (38, 6)  NULL,
    [Numerator_CASEGPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Denominator_CASEGPerofSales_M]                   NUMERIC (38, 2)  NULL,
    [DININ_GM_Per_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_DININGMPer_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_DININGMPer_M]                        NUMERIC (38, 2)  NULL,
    [DININ_SPG_Dol_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_DININ_SPG_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_DININ_SPG_M]                         DECIMAL (38, 2)  NULL,
    [DININ_Per_of_Sales_M]                            NUMERIC (38, 6)  NULL,
    [Numerator_DININPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Denominator_DININPerofSales_M]                   NUMERIC (38, 2)  NULL,
    [MOTION_GM_Per_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_MOTIONGMPer_M]                         NUMERIC (38, 2)  NULL,
    [Denominator_MOTIONGMPer_M]                       NUMERIC (38, 2)  NULL,
    [MOTION_SPG_Dol_M]                                NUMERIC (38, 6)  NULL,
    [Numerator_MOTION_SPG_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_MOTION_SPG_M]                        DECIMAL (38, 2)  NULL,
    [MOTION_Per_of_Sales_M]                           NUMERIC (38, 6)  NULL,
    [Numerator_MOTIONPerofSales_M]                    NUMERIC (38, 2)  NULL,
    [Denominator_MOTIONPerofSales_M]                  NUMERIC (38, 2)  NULL,
    [OUTDR_GM_Per_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_OUTDRGMPer_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_OUTDRGMPer_M]                        NUMERIC (38, 2)  NULL,
    [OUTDR_SPG_Dol_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_OUTDR_SPG_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_OUTDR_SPG_M]                         DECIMAL (38, 2)  NULL,
    [OUTDR_Per_of_Sales_M]                            NUMERIC (38, 6)  NULL,
    [Numerator_OUTDRPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Denominator_OUTDRPerofSales_M]                   NUMERIC (38, 2)  NULL,
    [UPHOL_GM_Per_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_UPHOLGMPer_M]                          NUMERIC (38, 2)  NULL,
    [Denominator_UPHOLGMPer_M]                        NUMERIC (38, 2)  NULL,
    [UPHOL_SPG_Dol_M]                                 NUMERIC (38, 6)  NULL,
    [Numerator_UPHOL_SPG_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_UPHOL_SPG_M]                         DECIMAL (38, 2)  NULL,
    [UPHOL_Per_of_Sales_M]                            NUMERIC (38, 6)  NULL,
    [Numerator_UPHOLPerofSales_M]                     NUMERIC (38, 2)  NULL,
    [Denominator_UPHOLPerofSales_M]                   NUMERIC (38, 2)  NULL,
    [WARR_GM_Per_M]                                   NUMERIC (38, 6)  NULL,
    [Numerator_WARRGMPer_M]                           NUMERIC (38, 2)  NULL,
    [Denominator_WARRGMPer_M]                         NUMERIC (38, 2)  NULL,
    [WARR_SPG_Dol_M]                                  NUMERIC (38, 6)  NULL,
    [Numerator_WARR_SPG_M]                            NUMERIC (38, 2)  NULL,
    [Denominator_WARR_SPG_M]                          DECIMAL (38, 2)  NULL,
    [WARR_Per_of_Sales_M]                             NUMERIC (38, 6)  NULL,
    [Numerator_WARRPerofSales_M]                      NUMERIC (38, 2)  NULL,
    [Denominator_WARRPerofSales_M]                    NUMERIC (38, 2)  NULL,
    [Apps_to_Traffic_Guest_Per_M]                     INT              NULL,
    [Numerator_AppsToTrafficGuest_M]                  INT              NULL,
    [Denominator_AppsToTrafficGuest_M]                DECIMAL (38, 2)  NULL,
    [Finance_Transaction_Per_M]                       DECIMAL (38, 4)  NULL,
    [Numerator_FinanceTransactionPer_M]               DECIMAL (38, 4)  NULL,
    [Denominator_FinanceTransactionPer_M]             DECIMAL (38, 4)  NULL,
    [Short_Term_Finance_Per_M]                        INT              NOT NULL,
    [Numerator_ShortFinancePer_M]                     INT              NULL,
    [Denominator_ShortFinancePer_M]                   INT              NULL,
    [Long_Term_Finance_Per_M]                         INT              NULL,
    [Numerator_LongFinancePer_M]                      INT              NULL,
    [Denominator_LongFinancePer_M]                    INT              NULL,
    [Other_Finance_Per_M]                             INT              NOT NULL,
    [Overall_Finance_Sales_Per_M]                     INT              NOT NULL,
    [Numerator_OverallFinanceSales_M]                 INT              NULL,
    [Denominator_OverallFinanceSales_M]               INT              NOT NULL,
    [Finance_Fees_as_a_Per_of_Sales_M]                INT              NOT NULL,
    [Numerator_FinanceFeesPerofSales_M]               INT              NOT NULL,
    [Denominator_FinanceFeesPerofSales_M]             INT              NOT NULL,
    [Down_Payment_Dol_as_a_Per_of_Financed_Sales_M]   INT              NOT NULL,
    [Numerator_DownPaymentDol_PerofSales_M]           INT              NULL,
    [Denominator_DownPaymentDol_PerofSales_M]         INT              NULL,
    [Overall_Protection_as_Per_of_Sales_M]            NUMERIC (38, 6)  NULL,
    [Numerator_OverallProtection_PerofSales_M]        NUMERIC (38, 2)  NULL,
    [Denominator_OverallProtection_PerofSales_M]      NUMERIC (38, 2)  NULL,
    [Denominator_FPP_OverallProtClosePerOpp_M]        DECIMAL (38, 4)  NULL,
    [Numerator_FPP_OverallProtClosePerOpp_M]          DECIMAL (38, 4)  NULL,
    [Overall_Protection_Close_Per_by_Opportunity_M]   INT              NOT NULL,
    [Denominator_FurnPPP_PerofOpp_M]                  DECIMAL (38, 4)  NULL,
    [Numerator__FurnPPP_PerofOpp_M]                   DECIMAL (38, 4)  NULL,
    [Furniture_PPP_as_Per_of_Opportunity_Sales_M]     NUMERIC (38, 6)  NULL,
    [Numerator_MattPadsPPP_PerofOpp_M]                DECIMAL (38, 4)  NULL,
    [Denominator_MattPadsPPP_PerofOpp_M]              DECIMAL (38, 4)  NULL,
    [Mattress_Pads_PPP_as_Per_of_Opportunity_Sales_M] NUMERIC (38, 6)  NULL,
    [Numerator_FurniturePPPClose_PerbyOpp_M]          DECIMAL (38, 4)  NULL,
    [Denominator_FurniturePPPClose_PerbyOpp_M]        DECIMAL (38, 4)  NULL,
    [Furniture_PPP_Close_Per_by_Opportunity_M]        NUMERIC (25, 13) NULL,
    [Numerator_AttachPadsToMatt_M]                    DECIMAL (38, 4)  NULL,
    [Denominator_AttachPadsToMatt_M]                  DECIMAL (38, 4)  NULL,
    [Attachment_Pads_to_Mattresses_M]                 INT              NOT NULL,
    [Numerator_FPPasPerWrittenSales_M]                NUMERIC (38, 2)  NULL,
    [Denominator_FPPasPerWrittenSales_M]              NUMERIC (38, 2)  NULL,
    [Furniture_PPP_as_Per_of_Written_Sales_M]         NUMERIC (38, 6)  NULL,
    [Numerator_MattPPPasPerWrittenSales_M]            NUMERIC (38, 4)  NULL,
    [Denominator_MattPPPasPerWrittenSales_M]          NUMERIC (38, 2)  NULL,
    [Mattress_PPP_as_Per_of_Written_Sales_M]          NUMERIC (38, 6)  NULL,
    [Budget_WrittenSalesNet_M]                        DECIMAL (38, 4)  NULL,
    [Budget_WrittenCOGS_M]                            DECIMAL (38, 4)  NULL,
    [Budget_WrittenCOF_M]                             INT              NULL,
    [Budget_WrittenGMDols_M]                          DECIMAL (38, 4)  NULL,
    [Budget_DeliveredSales_M]                         DECIMAL (38, 4)  NULL,
    [Budget_DeliveredCOGS_M]                          DECIMAL (38, 4)  NULL,
    [Budget_DeliveredGMDols_M]                        DECIMAL (38, 4)  NULL,
    [Budget_CloseRatio_M]                             INT              NOT NULL,
    [Budget_DerivedUps_M]                             DECIMAL (38, 4)  NULL,
    [Budget_AverageOrderValue_M]                      INT              NOT NULL,
    [LocationKey]                                     INT              NULL,
    [CorporateFinanceGrouping]                        VARCHAR (5)      NULL,
    [CompLocation]                                    VARCHAR (3)      NULL,
    [datekey]                                         INT              NULL,
    [FiscalDate]                                      VARCHAR (10)     NULL,
    [FiscalWeek]                                      SMALLINT         NULL,
    [FiscalMonth]                                     SMALLINT         NULL,
    [FiscalMonthName]                                 VARCHAR (100)    NULL,
    [FiscalYear]                                      SMALLINT         NULL,
    [StoreLocation]                                   VARCHAR (255)    NULL,
    [VpName]                                          VARCHAR (255)    NULL,
    [Newmarket]                                       VARCHAR (100)    NULL,
    [NewRegion]                                       VARCHAR (50)     NULL,
    [RegionalDirector]                                VARCHAR (255)    NULL,
    [GrossWrittenSales]                               NUMERIC (38, 2)  NULL,
    [NetWrittenSales]                                 NUMERIC (38, 2)  NULL,
    [REAC]                                            NUMERIC (38, 2)  NULL,
    [InvoicedSales]                                   NUMERIC (38, 2)  NULL,
    [WrittenSalesDeliveryFee]                         NUMERIC (38, 2)  NULL,
    [InvoicedSalesDeliveryFee]                        INT              NOT NULL,
    [Qty]                                             INT              NOT NULL,
    [WrittenAdjustedCOGS]                             INT              NOT NULL,
    [AdjustedInvoicedCogs]                            INT              NOT NULL,
    [Margin]                                          NUMERIC (38, 2)  NULL,
    [InvoicedMargin]                                  NUMERIC (38, 2)  NULL,
    [FinanceFeeCost]                                  DECIMAL (38, 2)  NULL,
    [InvoicedFinanceFee]                              INT              NOT NULL,
    [OrderCount_Current]                              INT              NOT NULL,
    [OrderCount_Super]                                DECIMAL (38, 4)  NULL,
    [Traffic]                                         INT              NOT NULL,
    [Guests]                                          INT              NOT NULL,
    [LongTermsales]                                   INT              NOT NULL,
    [ShortTermsales]                                  INT              NOT NULL,
    [OverallTermSales]                                INT              NOT NULL,
    [TotalTransactionCount]                           DECIMAL (38, 4)  NULL,
    [FinanceTransactionCount]                         DECIMAL (38, 4)  NULL,
    [WrittenCOFDealerOther]                           INT              NOT NULL,
    [WrittenCOFBuyDown]                               INT              NOT NULL,
    [WrittenCOFBuyDownOther]                          INT              NOT NULL,
    [COFwoDownPayment]                                INT              NOT NULL,
    [TrueCOFwoDownPayment]                            INT              NOT NULL,
    [InvoicedDiscounts]                               INT              NOT NULL,
    [InvoicedCOGS]                                    INT              NOT NULL,
    [InvoicedCOGSOther]                               INT              NOT NULL,
    [WrittenSalesBudget]                              DECIMAL (38, 4)  NULL,
    [WrittenSalesBudget.d]                            DECIMAL (38, 4)  NULL,
    [WrittenCogsBudget]                               DECIMAL (38, 4)  NULL,
    [DerivedUpsBudget]                                DECIMAL (38, 4)  NULL,
    [InvoicedSalesBudget]                             DECIMAL (38, 4)  NULL,
    [InvoicedCOGSBudget]                              DECIMAL (38, 4)  NULL,
    [WrittenSOCountBudget]                            INT              NULL,
    [ConversionRateBudget]                            INT              NULL,
    [WrittenCOFBudget]                                INT              NULL,
    [FiscalDayOfWeek]                                 SMALLINT         NULL,
    [FiscalWeekYear]                                  INT              NULL,
    [Bed_Bud_WrittenSales]                            DECIMAL (38, 4)  NULL,
    [Bed_Bud_WrittenGM]                               DECIMAL (38, 4)  NULL,
    [Access_Bud_WrittenSales]                         DECIMAL (38, 4)  NULL,
    [Access_Bud_WrittenGM]                            DECIMAL (38, 4)  NULL,
    [Bedro_Bud_WrittenSales]                          DECIMAL (38, 4)  NULL,
    [Bedro_Bud_WrittenGM]                             DECIMAL (38, 4)  NULL,
    [Caseg_Bud_WrittenSales]                          DECIMAL (38, 4)  NULL,
    [Caseg_Bud_WrittenGM]                             DECIMAL (38, 4)  NULL,
    [Dinin_Bud_WrittenSales]                          DECIMAL (38, 4)  NULL,
    [Dinin_Bud_WrittenGM]                             DECIMAL (38, 4)  NULL,
    [Motion_Bud_WrittenSales]                         DECIMAL (38, 4)  NULL,
    [Motion_Bud_WrittenGM]                            DECIMAL (38, 4)  NULL,
    [Outdr_Bud_WrittenSales]                          DECIMAL (38, 4)  NULL,
    [Outdr_Bud_WrittenGM]                             DECIMAL (38, 4)  NULL,
    [Uphol_Bud_WrittenSales]                          DECIMAL (38, 4)  NULL,
    [Uphol_Bud_WrittenGM]                             DECIMAL (38, 4)  NULL,
    [Warr_Bud_WrittenSales]                           DECIMAL (38, 4)  NULL,
    [Warr_Bud_WrittenGM]                              DECIMAL (38, 4)  NULL,
    [CloseGoalBudget]                                 DECIMAL (38, 9)  NULL,
    [dlvyBudget]                                      DECIMAL (38, 4)  NULL,
    [Furn_Oppn]                                       DECIMAL (38, 4)  NULL,
    [Furn_Closen]                                     DECIMAL (38, 4)  NULL,
    [Matt_Oppn]                                       DECIMAL (38, 4)  NULL,
    [Matt_Closen]                                     DECIMAL (38, 4)  NULL,
    [Furn_Opp_sales]                                  NUMERIC (38, 2)  NULL,
    [Furn_Close_sales]                                NUMERIC (38, 2)  NULL,
    [Matt_Opp_sales]                                  NUMERIC (38, 2)  NULL,
    [Matt_Close_sales]                                NUMERIC (38, 2)  NULL,
    [over_Oppn]                                       DECIMAL (38, 4)  NULL,
    [over_Closen]                                     DECIMAL (38, 4)  NULL
);
GO

