CREATE TABLE [Retail_DW_Core].[FactStorePulseALSTR] (
    [datekey]                     INT             NULL,
    [FiscalDate]                  VARCHAR (10)    NULL,
    [FiscalWeek]                  SMALLINT        NULL,
    [FiscalMonth]                 SMALLINT        NULL,
    [FiscalMonthName]             VARCHAR (100)   NULL,
    [FiscalYear]                  SMALLINT        NULL,
    [FiscalDayOfWeek]             SMALLINT        NULL,
    [FiscalWeekYear]              INT             NULL,
    [CalendarYear_M]              SMALLINT        NULL,
    [Alt_CalendarWeek_M]          INT             NULL,
    [Alt_CalendarWeekLastDate]    DATE            NULL,
    [Alt_CalendarWeekIndicator_M] INT             NULL,
    [CalendarMonthLastDate_M]     DATE            NULL,
    [CalendarMonthFirstDate_M]    DATE            NULL,
    [CalendarMonthIndicator_M]    INT             NULL,
    [Alt_CalendarYearIndicator_M] INT             NULL,
    [Datekey_M]                   INT             NULL,
    [CorporateFinanceGrouping]    VARCHAR (5)     NULL,
    [CompLocation]                VARCHAR (3)     NOT NULL,
    [StoreLocation]               VARCHAR (255)   NULL,
    [StoreID]                     VARCHAR (6)     NULL,
    [VpName]                      VARCHAR (255)   NULL,
    [Newmarket]                   VARCHAR (100)   NULL,
    [NewRegion]                   VARCHAR (50)    NULL,
    [RegionalDirector]            VARCHAR (255)   NULL,
    [OrderChangeDate_M]           DATE            NULL,
    [CompLocation_M]              VARCHAR (3)     NOT NULL,
    [StoreLocation_M]             VARCHAR (255)   NULL,
    [Updated_Region_M]            VARCHAR (50)    NULL,
    [LocationKey]                 INT             NULL,
    [OrderChangeDate]             DATE            NULL,
    [Written_GrossSale]           NUMERIC (38, 2) NULL,
    [Written_Sales]               NUMERIC (38, 2) NULL,
    [DLVY]                        NUMERIC (38, 2) NULL,
    [Written_GM]                  NUMERIC (38, 2) NULL,
    [Delivered_Sales]             NUMERIC (38, 2) NULL,
    [Delivered_GM]                NUMERIC (38, 2) NULL,
    [Sleep_Assessments]           INT             NULL,
    [Bedding_WrittenSales]        NUMERIC (38, 2) NULL,
    [Bedding_Written_GM]          NUMERIC (38, 2) NULL,
    [Bedding_Qty]                 NUMERIC (38, 2) NULL,
    [ACCESS_WrittenSales]         NUMERIC (38, 2) NULL,
    [ACCESS_Written_GM]           NUMERIC (38, 2) NULL,
    [BEDRO_WrittenSales]          NUMERIC (38, 2) NULL,
    [BEDRO_Written_GM]            NUMERIC (38, 2) NULL,
    [CASEG_WrittenSales]          NUMERIC (38, 2) NULL,
    [CASEG_Written_GM]            NUMERIC (38, 2) NULL,
    [DININ_WrittenSales]          NUMERIC (38, 2) NULL,
    [DININ_Written_GM]            NUMERIC (38, 2) NULL,
    [MOTION_WrittenSales]         NUMERIC (38, 2) NULL,
    [MOTION_Written_GM]           NUMERIC (38, 2) NULL,
    [OUTDR_WrittenSales]          NUMERIC (38, 2) NULL,
    [OUTDR_Written_GM]            NUMERIC (38, 2) NULL,
    [UPHOL_WrittenSales]          NUMERIC (38, 2) NULL,
    [UPHOL_Written_GM]            NUMERIC (38, 2) NULL,
    [WARR_WrittenSales]           NUMERIC (38, 2) NULL,
    [WARR_Written_GM]             NUMERIC (38, 2) NULL,
    [Derived_Ups]                 DECIMAL (38, 2) NULL,
    [OrderCount]                  DECIMAL (38, 4) NULL,
    [SOOrderCount]                DECIMAL (38, 4) NULL,
    [EmailCount]                  INT             NULL,
    [EmailCustCount]              INT             NULL,
    [Recorded_Guest]              INT             NULL,
    [AppFees]                     NUMERIC (38, 2) NULL,
    [MattUnits]                   NUMERIC (38, 2) NULL,
    [PBSUnits]                    NUMERIC (38, 2) NULL,
    [AppCount]                    INT             NULL,
    [FinancedOrders]              DECIMAL (38, 4) NULL,
    [ShortPayments]               INT             NULL,
    [LongPayments]                INT             NULL,
    [OtherPayments]               INT             NULL,
    [DownPayments]                INT             NULL,
    [TotalPayments]               INT             NULL,
    [FinanceFeeCost]              DECIMAL (38, 2) NULL,
    [Written_Sales_GM_FF]         NUMERIC (38, 2) NULL,
    [Written_GM_FF]               NUMERIC (38, 2) NULL,
    [Furn_Close_sales]            NUMERIC (38, 2) NULL,
    [Furn_Opp_sales]              NUMERIC (38, 2) NULL,
    [Matt_Close_sales]            NUMERIC (38, 2) NULL,
    [Matt_Opp_sales]              NUMERIC (38, 2) NULL,
    [Furn_Closen]                 DECIMAL (38, 4) NULL,
    [Furn_Oppn]                   DECIMAL (38, 4) NULL,
    [Matt_Closen]                 DECIMAL (38, 4) NULL,
    [Matt_Oppn]                   DECIMAL (38, 4) NULL,
    [over_Closen]                 DECIMAL (38, 4) NULL,
    [over_Oppn]                   DECIMAL (38, 4) NULL,
    [WrittenSalesBudget]          DECIMAL (38, 4) NULL,
    [dlvyBudget]                  DECIMAL (38, 4) NULL,
    [WrittenCogsBudget]           DECIMAL (38, 4) NULL,
    [InvoicedSalesBudget]         DECIMAL (38, 4) NULL,
    [InvoicedCOGSBudget]          DECIMAL (38, 4) NULL,
    [WrittenSOCountBudget]        INT             NULL,
    [AverageOrderValue]           INT             NULL,
    [ConversionRateBudget]        INT             NULL,
    [WrittenCOFBudget]            INT             NULL,
    [BEDDI_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [BEDDI_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [ACCESS_Bud_WrittenSales]     DECIMAL (38, 4) NULL,
    [ACCESS_Bud_WrittenGM]        DECIMAL (38, 4) NULL,
    [BEDRO_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [BEDRO_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [CASEG_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [CASEG_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [DININ_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [DININ_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [MOTION_Bud_WrittenSales]     DECIMAL (38, 4) NULL,
    [MOTION_Bud_WrittenGM]        DECIMAL (38, 4) NULL,
    [OUTDR_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [OUTDR_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [UPHOL_Bud_WrittenSales]      DECIMAL (38, 4) NULL,
    [UPHOL_Bud_WrittenGM]         DECIMAL (38, 4) NULL,
    [WARR_Bud_WrittenSales]       DECIMAL (38, 4) NULL,
    [WARR_Bud_WrittenGM]          DECIMAL (38, 4) NULL,
    [DerivedUpsBudget]            DECIMAL (38, 4) NULL,
    [CloseGoalBudget]             DECIMAL (38, 9) NULL
);
GO

