CREATE TABLE [Retail_DW_Core].[FactScoreboardActivity] (
    [Source]                    VARCHAR (5)   NULL,
    [StoreID]                   INT           NULL,
    [ScoreboardStoreID]         INT           NULL,
    [LocationName]              VARCHAR (255) NULL,
    [SalesPersonID]             VARCHAR (20)  NULL,
    [SalesPersonName]           VARCHAR (50)  NULL,
    [StatusStartDate]           DATE          NULL,
    [TotalStatusLength]         INT           NULL,
    [RecordCount]               INT           NULL,
    [RecordedUps]               INT           NULL,
    [RecordedClosed]            INT           NULL,
    [Strikes]                   INT           NULL,
    [StrikeOuts]                INT           NULL,
    [Shots]                     INT           NULL,
    [FinApps]                   INT           NULL,
    [MaxConsecutiveStrikes]     INT           NULL,
    [MaxConsecutiveStrikeOuts]  INT           NULL,
    [LastConsecutiveStrikes]    INT           NULL,
    [LastConsecutiveStrikeOuts] INT           NULL,
    [RedLineCrossedCount]       INT           NULL
);