CREATE TABLE [Retail_DW_Core].[FactStorePulseHolding_RealEstate] (
    [StoreID]                   INT             NOT NULL,
    [StoreName]                 VARCHAR (255)   NULL,
    [FiscalDate]                DATE            NULL,
    [ParallelDateLY]            DATE            NULL,
    [TrafficBudget]             DECIMAL (38, 4) NULL,
    [WrittenSalesBudget]        DECIMAL (38, 4) NULL,
    [FiscalMonth]               SMALLINT        NULL,
    [FiscalMonthName]           VARCHAR (100)   NULL,
    [FiscalYear]                SMALLINT        NULL,
    [Traffic]                   DECIMAL (38, 2) NULL,
    [Traffic_SP_LY]             DECIMAL (16, 2) NULL,
    [Written_Sales]             NUMERIC (38, 2) NULL,
    [Written_Sales_LY]          DECIMAL (16, 2) NULL,
    [Written_Sales_D]           NUMERIC (38, 2) NULL,
    [Written_GM]                NUMERIC (38, 2) NULL,
    [Written_GrossSale]         NUMERIC (38, 2) NULL,
    [Delivered_Sales]           NUMERIC (38, 2) NULL,
    [Delivered_GM]              NUMERIC (38, 2) NULL,
    [Delivered_GM_%]            NUMERIC (38, 6) NULL,
    [SPG]                       NUMERIC (38, 6) NULL,
    [SPG.D]                     NUMERIC (38, 6) NULL,
    [SPG_SP_LY]                 DECIMAL (16, 6) NULL,
    [SPG_Budget]                DECIMAL (38, 6) NULL,
    [Average_Ticket]            NUMERIC (38, 6) NULL,
    [AverageTicket_%_Var_SP_LY] DECIMAL (16, 4) NULL,
    [Total_OrderCount]          DECIMAL (38, 4) NULL,
    [Total_OrderCount_LY]       DECIMAL (16, 4) NULL,
    [Close_%]                   DECIMAL (38, 6) NULL,
    [Close_%_LY]                DECIMAL (16, 6) NULL,
    [REAC $]                    NUMERIC (38, 2) NULL,
    [REAC %]                    NUMERIC (38, 6) NULL
);
GO

