CREATE TABLE [Retail_DW_Core].[FactSales] (
    [SourceSystem]         VARCHAR (30)    NOT NULL,
    [Source]               CHAR (1)        NULL,
    [SourceDataID]         VARCHAR (50)    NOT NULL,
    [SalesDataTypeKey]     INT             NOT NULL,
    [TransDateTime]        DATETIME2 (3)   NULL,
    [TransDateKey]         INT             NOT NULL,
    [OrderDateKey]         INT             NULL,
    [ProductKey]           BIGINT          NULL,
    [CustomerKey]          BIGINT          NULL,
    [SalesPersonKey]       BIGINT          NULL,
    [LocationKey]          BIGINT          NULL,
    [SUOrderID]            VARCHAR (50)    NULL,
    [BaseOrderID]          VARCHAR (50)    NOT NULL,
    [OrderID]              VARCHAR (50)    NOT NULL,
    [ItemID]               INT             NULL,
    [GroupID]              VARCHAR (50)    NULL,
    [TransCodeID]          INT             NOT NULL,
    [UpdateTypeID]         VARCHAR (4)     NOT NULL,
    [AsIsReasonCodeID]     VARCHAR (50)    NULL,
    [VoidedReasonCodeID]   VARCHAR (50)    NULL,
    [ItemCommCategory]     VARCHAR (10)    NULL,
    [DeliveryStatus]       VARCHAR (20)    NULL,
    [ProductDiscountCode]  VARCHAR (50)    NULL,
    [PVEReasonCodeID]      VARCHAR (50)    NULL,
    [Sales]                NUMERIC (19, 2) NOT NULL,
    [Cost]                 NUMERIC (19, 2) NOT NULL,
    [Units]                NUMERIC (19, 2) NOT NULL,
    [ProtectionPlanPrice]  DECIMAL (19, 4) NULL,
    [ProtectionPlanCost]   DECIMAL (19, 4) NULL,
    [PPPOpp]               DECIMAL (19, 4) NULL,
    [PPPClose]             DECIMAL (19, 4) NULL,
    [SalesType]            CHAR (1)        NOT NULL,
    [GrossMultiplier]      INT             NULL,
    [REACCategory]         VARCHAR (50)    NULL,
    [DateCreated]          DATETIME2 (3)   NULL,
    [DateChanged]          DATETIME2 (3)   NULL,
    [IsFinanced]           INT             NULL,
    [SalesLeadSourceID]    INT             NULL,
    [ShipLocationID]       VARCHAR (50)    NULL,
    [FRLocationID]         VARCHAR (50)    NULL,
    [PriceOverrideStaffID] VARCHAR (50)    NULL,
    [IsReturnCustomer]     INT             NULL,
    [LYComp]               INT             NULL,
    [TYComp]               INT             NULL,
    [InvSubBucketID]       VARCHAR (50)    NULL
);