CREATE TABLE [Retail_DW_Core].[FinanceProvider] (

	[Operation] varchar(50) NULL, 
	[AccountRetentionDays] int NULL, 
	[Address1] varchar(255) NULL, 
	[Address2] varchar(255) NULL, 
	[AllowFinanceB4Approval] bit NULL, 
	[AllowInQueue] bit NULL, 
	[SettlementType] varchar(50) NULL, 
	[SourceID] varchar(50) NULL, 
	[State] varchar(50) NULL, 
	[UseTaxCodeSettingForRTOTaxRemoval] bit NULL, 
	[XmitBothExchangeTransations] bit NULL, 
	[Phone] varchar(50) NULL, 
	[PhoneExt] varchar(20) NULL, 
	[PostalCodeID] varchar(20) NULL, 
	[PostMethod] varchar(50) NULL, 
	[ReadyForQueue] bit NULL, 
	[RecStatus] varchar(20) NULL, 
	[Fax] varchar(50) NULL, 
	[FinanceProviderID] varchar(50) NULL, 
	[LastBatchID] varchar(100) NULL, 
	[Name] varchar(255) NULL, 
	[NotifyFinanceProvider] bit NULL, 
	[PaymentTypeID] varchar(50) NULL, 
	[City] varchar(100) NULL, 
	[Contact] varchar(255) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DefaultPercent] decimal(18,2) NULL, 
	[DefaultTier] varchar(50) NULL
);