CREATE TABLE [Retail_DW_Core].[Relationship] (
    [Prefix]            VARCHAR (20)  NULL,
    [RecStatus]         VARCHAR (20)  NULL,
    [RelationshipId]    VARCHAR (100) NULL,
    [Suffix]            VARCHAR (20)  NULL,
    [UpdatedAt]         DATETIME2 (6) NULL,
    [Last]              VARCHAR (100) NULL,
    [LastActivity]      DATETIME2 (6) NULL,
    [Middle]            VARCHAR (50)  NULL,
    [PhoneExt]          VARCHAR (20)  NULL,
    [PhoneNumber]       VARCHAR (50)  NULL,
    [PhoneType]         VARCHAR (50)  NULL,
    [DateChanged]       DATETIME2 (6) NULL,
    [DateCreated]       DATETIME2 (6) NULL,
    [DeliveryAddressID] VARCHAR (100) NULL,
    [Description]       VARCHAR (500) NULL,
    [First]             VARCHAR (100) NULL,
    [FullName]          VARCHAR (255) NULL,
    [Operation]         VARCHAR (50)  NULL,
    [BillingAddressID]  VARCHAR (100) NULL,
    [CartId]            VARCHAR (100) NULL,
    [CreatedAt]         DATETIME2 (6) NULL,
    [CustomerId]        VARCHAR (100) NULL,
    [Email]             VARCHAR (255) NULL,
    [NxtGenBatchId]     INT           NULL
);