CREATE TABLE [Retail_DW_Core].[STGQ_FactTrafficBudget] (

	[LocationID] varchar(8000) NULL, 
	[TransDate] date NULL, 
	[TUGoal] decimal(18,6) NULL, 
	[TrafficGuest] decimal(18,6) NULL, 
	[NumOfRSAs] int NULL, 
	[Key_Field] varchar(8000) NULL, 
	[Location_Name] varchar(8000) NULL, 
	[EmployeeHours] int NULL, 
	[Display] int NULL, 
	[Month_of_Year] varchar(8000) NULL, 
	[Quarter_of_Year] varchar(8000) NULL, 
	[Sat_Week_Ending] date NULL, 
	[Sat_Week_Ending_Year] int NULL, 
	[Sat_Week_of_Year] int NULL, 
	[Sat_WeekNum_of_Year] int NULL, 
	[TransDate_Filter] int NULL, 
	[Week_Ending] date NULL, 
	[Week_Ending_Location_Key] varchar(8000) NULL, 
	[Week_of_Year] int NULL, 
	[WeekNum_of_Year] int NULL, 
	[Week_of_Year_Original] int NULL, 
	[Year_Field] int NULL
);