-- Auto Generated (Do not modify) D8FECB172C584538C694F0EA0D6A9F8405647F519469C9785ACCED07F7248700
CREATE   VIEW [Retail_DW_Core_Wrk].[v_CartHeader] AS

SELECT 
    [ID],
    [RelationshipID],
    [CartNumber],
    [LocationID],
    [CartCustomerID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [CellPhone],
    [HomePhone],
    [WorkPhone],
    [WorkPhoneExtension],
    [Address1],
    [Address2],
    [City],
    [StateOrProvince],
    [ZipCode],
    [SalespeopleID],
    [ShippingAddress1],
    [ShippingAddress2],
    [ShippingCity],
    [ShippingStateOrProvince],
    [ShippingZipCode],
    [Fees],
    [Install],
    [Tax],
    [Delivery],
    [DateUpdated],
    [DateCreated]
FROM [$(Source_Data)].[Retail_External].[CartHeader];