CREATE view [Marketing_Wrk].[v_AdNoticeDetail]
AS
SELECT
       [Andkey]
      ,[Andforeignkey]
      ,[Anditemnumber]
      ,[Andquantity]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Andwarehouse]
      ,[Andapproved]
      ,[Andcomments]
      ,[Andchangeneeded]
      ,[Andqtyavailable]
      ,[Andatpdate]
      ,[Andpreviousqty]
      ,[Anddpresponded]
  FROM [$(Source_Data)].[Wholesale_Marketing].[AdNoticeDetail]
  