CREATE view [Marketing_Wrk].[v_AFValueList]
as
SELECT  [Afvlid]
      ,[Afvlvaluetype]
      ,[Afvlvaluecode]
      ,[Afvlvaluedescription]
      ,[Afvlvaluedefault]
      ,[Afvlvaluesortorder]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Active]
      ,[Afvldivisioncode]
  FROM [$(Source_Data)].[Wholesale_Marketing].[AFValueList]