CREATE view [Marketing_Wrk].[v_Goals]
AS
SELECT  [Goagoalid]
      ,[Goagoalname]
      ,[Goagoaldate]
      ,[Goagoalsetter]
      ,[Goaproductdescription]
      ,[Goatopaccountstatus]
      ,[Goagoalyear]
      ,[Goagoalmonth]
      ,[Goadivision]
      ,[Goaproductline]
      ,[Goacustomernumber]
      ,[Goashiptonumber]
      ,[Goanetwrittengoal]
      ,[Goaplacementgoal]
      ,[Goavelocitygoal]
      ,[Goastoreaddressid]
      ,[Goashiptoaddressid]
  FROM [$(Source_Data)].[Wholesale_Marketing].[Goals]