CREATE view [Marketing_Wrk].[v_MarketCommitmentsSum]
AS
SELECT  [Mksrepid]
      ,[Mkscustomernumber]
      ,[Mksshiptonumber]
      ,[Mksitemnumber]
      ,[Mkshomestoreflag]
      ,[Mkscommitted]
      ,[Mksactual]
      ,[Mksactualmonthlyqty]
      ,[Mksgoal0]
      ,[Mksmonthlyestqty]
      ,[Mksoriginalmonthlyestqty]
      ,[Mksoriginalcommitment]
      ,[Mksuserid]
      ,[Mksdatechanged]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Mkshomestorecommitted]
      ,[Mkshomestoreoriginalcommitment]
      ,[Mksregion]
      ,[Mkshomestoreqty]
      ,[Mksnonhomestoreqty]
  FROM [$(Source_Data)].[Wholesale_Marketing].[MarketCommitmentsSum]