CREATE view [Marketing_Wrk].[v_MarketCommitments]
AS
SELECT  [Mkcmarket]
      ,[Mkcrepid]
      ,[Mkccustomernum]
      ,[Mkcshiptonum]
      ,[Mkchomestoreflag]
      ,[Mkcitemnum]
      ,[Mkcmonthlyestqty]
      ,[Mkccommitment]
      ,[Mkcuserid]
      ,[Mkcdatechanged]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Mkchomestorecommitment]
      ,[Mkcregion]
      ,[Mkchomestoreqty]
      ,[Mkcnonhomestoreqty]
  FROM [$(Source_Data)].[Wholesale_Marketing].[MarketCommitments]
  