CREATE view [Marketing_Wrk].[v_MoSeriesMargins]
AS
SELECT  [Momseries]
      ,[Momdollars]
      ,[Momorders]
      ,[Momfob]
      ,[Momcur]
      ,[Momact]
      ,[Momfob_3]
      ,[Momcur_3]
      ,[Momact_3]
      ,[Momfob_6]
      ,[Momcur_6]
      ,[Momact_6]
      ,[Momfob_12]
      ,[Momcur_12]
      ,[Momact_12]
      ,[Momgmroi_1]
      ,[Momgmroi_2]
      ,[Momgmroi_3]
      ,[Momgmroi_4]
      ,[Momgmroi_5]
      ,[Momgmroi_6]
      ,[Momgmroi_7]
      ,[Momgmroi_8]
      ,[Momgmroi_9]
      ,[Momgmroi_10]
      ,[Momgmroi_11]
      ,[Momgmroi_12]
      ,[Mommonth]
  FROM [$(Source_Data)].[Wholesale_Marketing].[MoSeriesMargins]