CREATE VIEW [Marketing_Wrk].[v_ProductLineMaster]
AS
SELECT  [Plmplcode]
      ,[Plmpldesc]
      ,[Plmpldivn]
      ,[Plmcexcode]
      ,[Plmsort]
      ,[Plmitemnumber]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
  FROM [$(Source_Data)].[Wholesale_Marketing].[ProductLineMaster]