CREATE VIEW [Marketing_Wrk].[v_Regions]
AS
SELECT [Regregion]
      ,[Regregdesc]
      ,[Regdivision]
      ,[Regvpdesc]
      ,[Regrepid]
      ,[Regmhs_name]
      ,[Regregtype]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Regalternatedivision]
      ,[Regcrmcode]
      ,CASE WHEN CAST([Lastupdatedate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([Lastupdatedate] as INT) AS CHAR(8)) AS DATE) END AS  [LastUpdateDate]
  FROM [$(Source_Data)].[Wholesale_Marketing].[Regions]