CREATE TABLE [Retail].[LocationListing_MDA_SharePoint]
    (
        [LOC_ID]               VARCHAR(25)   NULL,
        [Store_Location]       VARCHAR(50)   NULL,
        [Licensee_Name]        VARCHAR(100)  NULL,
        [Licensee_LastName]    VARCHAR(100)  NULL,
        [Licensee_FirstName]   VARCHAR(100)  NULL,
        [CorporationName]      VARCHAR(100)  NULL,
        [StoreAddress1]        VARCHAR(1000) NULL,
        [StoreAddress2]        VARCHAR(1000) NULL,
        [City]                 VARCHAR(100)  NULL,
        [StoreState]           VARCHAR(25)   NULL,
        [StoreCountry]         VARCHAR(50)   NULL,
        [StoreZip]             VARCHAR(25)   NULL,
        [Classification1]      VARCHAR(50)   NULL,
        [Classification2]      VARCHAR(50)   NULL,
        [District_Manager]     VARCHAR(100)  NULL,
        [MarketTier]           VARCHAR(25)   NULL,
        [LocationStatus]       VARCHAR(100)  NULL,
        [SoftOpenDate]         VARCHAR(25)   NULL,
        [CloseDate]            VARCHAR(25)   NULL,
        [dummy]                VARCHAR(25)   NULL,
        [RetailSqFt]           VARCHAR(25)   NULL,
        [OnDMR]                VARCHAR(25)   NULL,
        [Clearance/Outlet]     VARCHAR(25)   NULL,
        [Ashcomm/Ecomm]        VARCHAR(25)   NULL,
        [DMA]                  VARCHAR(25)   NULL,
        [DMAName]              VARCHAR(100)  NULL,
        [WarehouseAddress1]    VARCHAR(1000) NULL,
        [WarehouseAddress2]    VARCHAR(1000) NULL,
        [WarehouseCity]        VARCHAR(100)  NULL,
        [WarehouseState]       VARCHAR(25)   NULL,
        [WarehouseCountry]     VARCHAR(25)   NULL,
        [WarehouseZip]         VARCHAR(25)   NULL,
        [CurrentAccountNumber] VARCHAR(50)   NULL,
        [CurrentRetailShipto]  VARCHAR(25)   NULL,
        [Kit_number]           VARCHAR(25)   NULL,
        [SODate+450]           VARCHAR(25)   NULL,
        [CompStatus]           VARCHAR(25)   NULL,
        [ERP]                  VARCHAR(50)   NULL,
        [DTCTechnology]        VARCHAR(100)  NULL,
        [DTCBrand]             VARCHAR(100)  NULL,
        [TrafficDivisor]       VARCHAR(25)   NULL,
        [Currency]             VARCHAR(25)   NULL,
        [6.0_UpgradeFacade]    VARCHAR(50)   NULL,
        [6.0_UpgradeInterior]  VARCHAR(50)   NULL,
        [CurrentStoreModel]    VARCHAR(50)   NULL,
        [TUA_Expiration_Date]  VARCHAR(50)   NULL
    );


--DATA_SOURCE = [AzureStorageGen2a],
--LOCATION = N'/Retail/MasterData/LocationListingMDA/LocationListMDA.csv',
--FILE_FORMAT = [CSVFileFormat_SkipHeaders],

