CREATE TABLE [Wholesale_PartyContacts].[AddressMaster] (

	[paaAddressID] int NULL, 
	[paaAddress1] varchar(35) NULL, 
	[paaAddress2] varchar(35) NULL, 
	[paaAddress3] varchar(35) NULL, 
	[paaAddress4] varchar(45) NULL, 
	[paaAddress5] varchar(35) NULL, 
	[paaCity] varchar(35) NULL, 
	[paaState] char(2) NULL, 
	[paaCountry] char(3) NULL, 
	[paaGeocodeLatitude] numeric(8,4) NULL, 
	[paaGeocodeLongitude] numeric(8,4) NULL, 
	[paaZipCode] varchar(10) NULL, 
	[paaCountyCode] char(3) NULL, 
	[paaCustomsIDNumber] varchar(20) NULL, 
	[paaGeocodeAccuracy] int NULL, 
	[paaTranscomCityCode] int NULL, 
	[paaDirections] varchar(150) NULL, 
	[paaCrossStreet] varchar(35) NULL, 
	[paaGeocodeVerificationDate] datetime2(6) NULL, 
	[paaTimeZone] char(3) NULL, 
	[paaGeocodeType] char(1) NULL, 
	[paaMsa_Fips] char(4) NULL, 
	[paaShortAddress1] varchar(35) NULL, 
	[paaShortAddress2] varchar(35) NULL, 
	[paaShortAddress3] varchar(25) NULL, 
	[paaShortAddress4] varchar(25) NULL, 
	[paaShortCity] varchar(25) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL
);