CREATE TABLE [CostAccounting_Wrk].[GrossMarginCubeData] (

	[gmcFiscalYear] decimal(29,0) NULL, 
	[gmcFiscalMonth] decimal(29,0) NULL, 
	[gmcMarginWarehouse] char(3) NULL, 
	[gmcItemNumber] varchar(15) NULL, 
	[gmcSeries] varchar(10) NULL, 
	[gmcSeriesDescription] varchar(40) NULL, 
	[gmcItemClass] char(4) NULL, 
	[gmcItemClassDescription] varchar(25) NULL, 
	[gmcItemDescription] varchar(30) NULL, 
	[gmcManufacturingStatusCode] char(1) NULL, 
	[gmcImportOffice] char(5) NULL, 
	[gmcFinancialDivision] char(1) NULL, 
	[gmcFinancialDivisionDesc] varchar(30) NULL, 
	[gmcMonthEndDate] datetime2(6) NULL, 
	[gmcFOBValue] decimal(29,6) NULL, 
	[gmcNetQuantityOrdered] decimal(29,0) NULL, 
	[gmcNetAmountOrdered] decimal(29,2) NULL, 
	[gmcAverageSellingPrice] decimal(29,2) NULL, 
	[gmcAverageInventoryValue] decimal(29,2) NULL, 
	[gmcGMROISales] decimal(29,2) NULL, 
	[gmcGMROICostOfSales] decimal(29,2) NULL, 
	[gmcGMROIMargin] decimal(29,2) NULL, 
	[gmcGMROINetSales] decimal(29,2) NULL, 
	[gmcGMROIActualCostOfSales] decimal(29,2) NULL, 
	[gmcAverageReturnsAmount] decimal(29,2) NULL, 
	[gmcAverageAllowanceAmount] decimal(29,2) NULL, 
	[gmcAverageShortShipAmount] decimal(29,2) NULL
);