CREATE TABLE [Retail_Corporate_Wrk].[BtaData] (

	[Operation] varchar(15) NULL, 
	[ApplyTo_OrderID] varchar(50) NULL, 
	[AsIsSale_ReasonCodeID] varchar(50) NULL, 
	[Base_OrderID] varchar(50) NULL, 
	[BrandID] varchar(50) NOT NULL, 
	[BtaID] varchar(50) NOT NULL, 
	[BtaSummaryDate] date NULL, 
	[CalcRank] varchar(10) NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[CollectionID] varchar(50) NOT NULL, 
	[CollectionID10] varchar(50) NULL, 
	[CollectionID2] varchar(50) NULL, 
	[CollectionID3] varchar(50) NULL, 
	[CollectionID4] varchar(50) NULL, 
	[CollectionID5] varchar(50) NULL, 
	[CollectionID6] varchar(50) NULL, 
	[CollectionID7] varchar(50) NULL, 
	[CollectionID8] varchar(50) NULL, 
	[CollectionID9] varchar(50) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[Custom1] varchar(50) NULL, 
	[Custom2] varchar(50) NULL, 
	[Custom3] varchar(50) NULL, 
	[CustomerID] varchar(50) NOT NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DiscntCode] varchar(10) NULL, 
	[DiscntPct] decimal(18,2) NULL, 
	[DistrictID] varchar(50) NOT NULL, 
	[DlvyStoreID] varchar(50) NOT NULL, 
	[DlvyTypeCodeID] varchar(50) NOT NULL, 
	[Family] varchar(50) NOT NULL, 
	[FisPeriod] int NOT NULL, 
	[FisWeek] int NOT NULL, 
	[FisYear] int NOT NULL, 
	[GrossProfit] decimal(19,4) NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[Kit_IDNumber] int NULL, 
	[Kit_ProductID] varchar(50) NULL, 
	[KitOrderItemID] int NULL, 
	[KitStatus] char(5) NOT NULL, 
	[LastBatchID] int NULL, 
	[NetCost] decimal(19,4) NULL, 
	[NetDiscnt] decimal(19,4) NULL, 
	[NetSales] decimal(19,4) NULL, 
	[NetUnits] decimal(19,2) NULL, 
	[ObsoleteID] varchar(10) NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[OrderItemID] int NULL, 
	[PostalCodeID] varchar(50) NOT NULL, 
	[ProductAdjID] varchar(50) NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[ProductTypeID] char(4) NOT NULL, 
	[ProtectionPlan_NetCost] numeric(19,4) NULL, 
	[ProtectionPlan_NetSales] numeric(19,4) NULL, 
	[ProtectionPlan_RtnCost] decimal(19,4) NULL, 
	[ProtectionPlan_RtnPrice] decimal(19,4) NULL, 
	[ProtectionPlan_SlsCost] decimal(19,4) NULL, 
	[ProtectionPlan_SlsPrice] decimal(19,4) NULL, 
	[ProtectionPlanID] varchar(50) NULL, 
	[ProtectionPlanRegisterID] varchar(50) NULL, 
	[PurchaseStatusCodeID] varchar(50) NULL, 
	[PurchaseStatusID] varchar(10) NOT NULL, 
	[RecStatus] char(1) NULL, 
	[RtnCost] decimal(19,4) NOT NULL, 
	[RtnDiscnt] decimal(19,4) NOT NULL, 
	[RtnPrice] decimal(19,4) NOT NULL, 
	[RtnReasonCodeID] varchar(50) NULL, 
	[RtnUnits] decimal(18,2) NOT NULL, 
	[SalespersonID] varchar(50) NOT NULL, 
	[ServiceChrgRespTypeID] varchar(10) NULL, 
	[ServiceChrgVendorID] varchar(50) NULL, 
	[ServiceChrgWarrantyID] varchar(50) NULL, 
	[ServiceStaffID] varchar(50) NULL, 
	[ServiceTechStaffID] varchar(50) NULL, 
	[ServiceTypeID] varchar(10) NULL, 
	[SlsCost] decimal(19,4) NOT NULL, 
	[SlsDiscnt] decimal(19,4) NOT NULL, 
	[SlsPrice] decimal(19,4) NOT NULL, 
	[SlsUnits] decimal(18,2) NOT NULL, 
	[SoftKit_ProductID] varchar(50) NULL, 
	[Source] varchar(10) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[SpecialOrder] bit NULL, 
	[SpecialOrderOpt1] varchar(50) NOT NULL, 
	[SpecialOrderOpt2] varchar(50) NULL, 
	[SpecialOrderOpt3] varchar(50) NULL, 
	[SpecialOrderOpt4] varchar(50) NULL, 
	[StoreID] varchar(50) NOT NULL, 
	[Time] datetime2(6) NULL, 
	[TransCodeID] int NOT NULL, 
	[TransDate] date NOT NULL, 
	[UpdateBy_StaffID] varchar(100) NULL, 
	[UpdateDateTime] datetime2(6) NULL, 
	[UpdateTypeID] char(4) NOT NULL, 
	[VendorID] varchar(50) NOT NULL, 
	[VoidedReasonCodeID] varchar(50) NULL, 
	[WrittenFlag] int NOT NULL
);