CREATE TABLE [Retail_Corporate_Wrk].[FinanceProvider] (

	[Operation] varchar(15) NULL, 
	[AccountRetentionDays] int NULL, 
	[Address1] varchar(255) NULL, 
	[Address2] varchar(255) NULL, 
	[AllowFinanceB4Approval] bit NULL, 
	[AllowInQueue] bit NULL, 
	[City] varchar(255) NULL, 
	[Contact] varchar(255) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DefaultPercent] decimal(18,2) NULL, 
	[DefaultTier] int NULL, 
	[Fax] varchar(12) NULL, 
	[FinanceProviderID] varchar(50) NOT NULL, 
	[LastBatchID] int NULL, 
	[Name] varchar(255) NULL, 
	[NotifyFinanceProvider] bit NULL, 
	[PaymentTypeID] varchar(50) NULL, 
	[Phone] varchar(12) NULL, 
	[PhoneExt] varchar(10) NULL, 
	[PostalCodeID] varchar(50) NULL, 
	[PostMethod] char(5) NULL, 
	[ReadyForQueue] bit NULL, 
	[RecStatus] char(1) NULL, 
	[SettlementType] varchar(10) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[State] varchar(10) NULL, 
	[UseTaxCodeSettingForRTOTaxRemoval] bit NULL, 
	[XmitBothExchangeTransations] bit NULL
);