CREATE TABLE [Retail_Corporate_Wrk].[Groups] (

	[Operation] varchar(15) NULL, 
	[AutoReplPrimStoreID] varchar(50) NULL, 
	[AutoReplQuatStoreID] varchar(50) NULL, 
	[AutoReplQuinStoreID] varchar(50) NULL, 
	[AutoReplScndStoreID] varchar(50) NULL, 
	[AutoReplTertStoreID] varchar(50) NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[Cubes] decimal(18,2) NOT NULL, 
	[Custom1] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DeliveryCubes] decimal(18,2) NULL, 
	[Description] varchar(50) NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[InvType] varchar(10) NOT NULL, 
	[IsActive] bit NULL, 
	[LabelQty] decimal(18,2) NULL, 
	[LabelType] char(5) NULL, 
	[LastBatchID] int NULL, 
	[MinGrossProfit] decimal(18,4) NOT NULL, 
	[OTBDept] varchar(20) NULL, 
	[RecStatus] char(1) NULL, 
	[ReductionPercent] decimal(18,2) NULL, 
	[Repossessable] bit NULL, 
	[RestockFeePercentage] decimal(18,2) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StaffID] varchar(50) NULL, 
	[UnloadTime] datetime2(6) NULL, 
	[Weight] decimal(18,2) NOT NULL, 
	[WrittenSOZeroCostPercent] decimal(18,2) NULL
);