CREATE TABLE [Retail_Corporate_Wrk].[ProductInventory] (

	[Operation] varchar(15) NULL, 
	[Addon1CommittedCost] decimal(19,4) NULL, 
	[Addon1Cost] decimal(19,4) NULL, 
	[Addon1NSCommittedCost] decimal(19,4) NULL, 
	[Addon1NSCost] decimal(19,4) NULL, 
	[Addon2CommittedCost] decimal(19,4) NULL, 
	[Addon2Cost] decimal(19,4) NULL, 
	[Addon2NSCommittedCost] decimal(19,4) NULL, 
	[Addon2NSCost] decimal(19,4) NULL, 
	[Addon3CommittedCost] decimal(19,4) NULL, 
	[Addon3Cost] decimal(19,4) NULL, 
	[Addon3NSCommittedCost] decimal(19,4) NULL, 
	[Addon3NSCost] decimal(19,4) NULL, 
	[Addon4CommittedCost] decimal(19,4) NULL, 
	[Addon4Cost] decimal(19,4) NULL, 
	[Addon4NSCommittedCost] decimal(19,4) NULL, 
	[Addon4NSCost] decimal(19,4) NULL, 
	[BrandID] varchar(50) NULL, 
	[CategoryID] varchar(50) NULL, 
	[CollectionID] varchar(50) NULL, 
	[COMCommittedCost] decimal(19,4) NULL, 
	[COMCost] decimal(19,4) NULL, 
	[COMNSCommittedCost] decimal(19,4) NULL, 
	[COMNSCost] decimal(19,4) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[CostCommitted] decimal(19,4) NULL, 
	[CostNonSale] decimal(19,4) NULL, 
	[CostNSCommitted] decimal(19,4) NULL, 
	[CostNSReserved] decimal(19,4) NULL, 
	[CostReserved] decimal(19,4) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[FisPeriod] int NULL, 
	[FisQtr] int NULL, 
	[FisWeek] int NULL, 
	[FisYear] int NULL, 
	[GroupID] varchar(50) NULL, 
	[KitStatus] varchar(10) NOT NULL, 
	[LandedFreight] decimal(19,4) NULL, 
	[LandedFreightCommittedCost] decimal(19,4) NULL, 
	[LandedFreightNSCommittedCost] decimal(19,4) NULL, 
	[LandedFreightNSCost] decimal(19,4) NULL, 
	[MaterialCommittedCost] decimal(19,4) NULL, 
	[MaterialCost] decimal(19,4) NULL, 
	[MaterialNSCommittedCost] decimal(19,4) NULL, 
	[MaterialNSCost] decimal(19,4) NULL, 
	[NetQtyBackOrdered] decimal(19,2) NULL, 
	[PieceStatusID] int NOT NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[ProductTypeID] char(4) NULL, 
	[QtyBackOrdered] decimal(18,2) NULL, 
	[QtyCommitted] decimal(18,2) NULL, 
	[QtyNonSale] decimal(18,2) NULL, 
	[QtyNSCommitted] decimal(18,2) NULL, 
	[QtyNSReserved] decimal(18,2) NULL, 
	[QtyOnHand] decimal(18,2) NULL, 
	[QtyOnOrder] decimal(18,2) NULL, 
	[QtyReserved] decimal(18,2) NULL, 
	[QtySoftCommitted] decimal(18,2) NULL, 
	[RecStatus] char(1) NULL, 
	[SellingPrice] decimal(19,4) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StoreID] varchar(50) NOT NULL, 
	[TotalCost] decimal(19,4) NULL, 
	[TransDate] date NOT NULL, 
	[VendorID] varchar(50) NOT NULL
);