CREATE TABLE [Retail_Corporate_Wrk].[Relationship] (

	[Operation] varchar(15) NULL, 
	[BillingAddressID] varchar(100) NULL, 
	[CartId] varchar(100) NULL, 
	[CreatedAt] datetime2(6) NULL, 
	[CustomerId] varchar(100) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DeliveryAddressID] varchar(100) NULL, 
	[Description] varchar(510) NULL, 
	[First] varchar(300) NULL, 
	[FullName] varchar(500) NULL, 
	[Last] varchar(300) NULL, 
	[LastActivity] datetime2(6) NULL, 
	[Middle] varchar(300) NULL, 
	[PhoneExt] varchar(100) NULL, 
	[PhoneNumber] varchar(100) NULL, 
	[PhoneType] varchar(100) NULL, 
	[Prefix] varchar(50) NULL, 
	[RecStatus] char(2) NULL, 
	[RelationshipId] varchar(100) NULL, 
	[Suffix] varchar(50) NULL, 
	[UpdatedAt] datetime2(6) NULL, 
	[Email] varchar(250) NULL, 
	[NxtGenBatchId] bigint NULL
);