CREATE TABLE [Retail_Corporate_Wrk].[Staff] (

	[operation] char(3) NULL, 
	[AllowPassthroughLogon] bit NULL, 
	[AllowPutawayChange] bit NULL, 
	[AllowRemoveFloat] bit NULL, 
	[CompanyID] char(5) NOT NULL, 
	[Custom65] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Default_StoreID] varchar(50) NULL, 
	[District_LocationAccessCodeID] varchar(50) NULL, 
	[DistrictManagerID] varchar(50) NULL, 
	[EmailAddress] varchar(70) NULL, 
	[EmployeeNbr] varchar(50) NULL, 
	[EnableDefaultLogonLocation] bit NULL, 
	[IsServiceEmployee] bit NULL, 
	[LanguageCode] varchar(50) NULL, 
	[LastBatchID] int NULL, 
	[LastLoginDate] datetime2(6) NULL, 
	[LockedOut] bit NULL, 
	[MaxConcurrentSessions] int NULL, 
	[MaximumCreditLimit] numeric(19,4) NULL, 
	[Name] varchar(100) NULL, 
	[OSLogon] varchar(50) NULL, 
	[PhoneExtension] varchar(50) NULL, 
	[PrimaryPhone] varchar(15) NULL, 
	[ProtectionPlan_CancellationDaysAllowOverride] bit NULL, 
	[RecStatus] char(1) NULL, 
	[Region_LocationAccessCodeID] varchar(50) NULL, 
	[RFUserCodeID] varchar(50) NULL, 
	[SalespersonID] varchar(50) NULL, 
	[ServiceLaborCost] numeric(19,4) NULL, 
	[ServiceLaborRate] numeric(19,4) NULL, 
	[ServiceLocationID] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StaffID] varchar(50) NOT NULL, 
	[StaffTypeID] varchar(50) NULL, 
	[WorkHoursPastMidnight] numeric(18,2) NULL
);