CREATE TABLE [Retail_Sales].[CreditReview] (

	[AmountApproved] decimal(19,4) NULL, 
	[CreditApplicationID] varchar(50) NULL, 
	[CreditReportDate] date NULL, 
	[CreditRequestStatusCodeID] int NULL, 
	[CreditReviewStatusCodeID] varchar(10) NULL, 
	[CreditReviewID] varchar(50) NOT NULL, 
	[CreditScore] varchar(50) NULL, 
	[CreditSourceTypeID] varchar(10) NOT NULL, 
	[CustomerID] varchar(50) NULL, 
	[ConditionalLetterRequired] bit NULL, 
	[CosignerCustomerID] varchar(50) NULL, 
	[CreditBureauID] varchar(50) NULL, 
	[FinalLetterRequired] bit NULL, 
	[IsHistory] bit NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[FinanceAccountNumber] varchar(50) NULL, 
	[FinanceProviderID] varchar(50) NULL, 
	[FinanceReferenceNumber] varchar(50) NULL, 
	[QueuedDateTime] datetime2(3) NULL, 
	[RequestCompletionDateTime] datetime2(3) NULL, 
	[RequestDateTime] datetime2(3) NULL, 
	[RequestStatusChangeDateTime] datetime2(3) NULL, 
	[ReviewStatusChangeDateTime] datetime2(3) NULL, 
	[RouteToStaffID] varchar(50) NULL, 
	[SalesPersonID] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StoreID] int NULL, 
	[SuggestedCreditLimit] decimal(19,4) NULL, 
	[SuggestedDownPaymentPercent] int NULL, 
	[CreditStorisReferenceNumber] varchar(50) NULL, 
	[RecStatus] varchar(1) NULL, 
	[OriginalQueuedDateTime] datetime2(3) NULL, 
	[CreditAppNumber] int NULL, 
	[AppCount] int NULL, 
	[AdjustedStatusCodeID] int NULL
);