CREATE TABLE [Retail_Sales].[SalesOrderLine] (

	[SourceSystem] varchar(30) NOT NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[BaseOrderID] varchar(20) NOT NULL, 
	[SourceOrderID] varchar(20) NOT NULL, 
	[LineNumber] int NOT NULL, 
	[PurchaseOrderID] varchar(50) NULL, 
	[PurchaseOrderLineID] int NULL, 
	[AutoTransOrderItemID] varchar(50) NULL, 
	[InvoiceDate] date NULL, 
	[ItemDescription] varchar(255) NULL, 
	[QuantityOrdered] int NULL, 
	[QuantityCommitted] int NULL, 
	[QuantityDelivered] int NULL, 
	[QuantityUndelivered] int NULL, 
	[RequestedDate] date NULL, 
	[SKU] varchar(20) NOT NULL, 
	[KitProductID] varchar(50) NULL, 
	[UnitSellPrice] decimal(19,4) NULL, 
	[UnitListPrice] decimal(19,4) NULL, 
	[TotalSaleAmount] decimal(19,4) NULL, 
	[TotalInvoiceAmount] decimal(19,4) NULL, 
	[LineStatus] varchar(30) NOT NULL, 
	[ProtectionPlanSKU] varchar(20) NULL, 
	[ProductTypeID] varchar(4) NULL, 
	[IsServiceItem] bit NULL, 
	[ProtectionPlanID] varchar(50) NULL, 
	[HasProtectionPlan] bit NULL, 
	[WarrantyEndDate] date NULL, 
	[OrderDate] date NOT NULL, 
	[OrderFulfillmentID] varchar(50) NULL, 
	[KitOrPackageQuantity] int NULL, 
	[KitOrPackageSKU] varchar(20) NULL, 
	[KitGroupNumber] varchar(20) NULL, 
	[StoreID] int NOT NULL, 
	[OriginalInvoiceID] varchar(50) NULL, 
	[VendorModelNumber] varchar(255) NULL, 
	[TransCodeID] int NOT NULL, 
	[DeliveryDate] datetime2(3) NULL, 
	[DeliveryStatus] varchar(10) NULL, 
	[DeliveryType] varchar(50) NULL, 
	[DelievryStoreID] varchar(50) NULL, 
	[DeliverySubTotal] decimal(19,4) NULL, 
	[LineCost] decimal(19,4) NULL, 
	[Addon1Cost] decimal(19,4) NULL, 
	[Addon2Cost] decimal(19,4) NULL, 
	[LandedFreight] decimal(19,4) NULL, 
	[OtherDiscount] decimal(19,4) NULL, 
	[ProductDiscountCode] varchar(50) NULL, 
	[WrittenDate] datetime2(3) NULL, 
	[PriceVarianceExceptionReasonCodeID] varchar(50) NULL, 
	[VendorID] varchar(50) NULL, 
	[VoidedReasonCodeID] varchar(50) NULL, 
	[ProtectionPlanPrice] decimal(19,4) NULL, 
	[ProtectionPlanCost] decimal(19,4) NULL, 
	[ProtectionPlanRegisterID] varchar(50) NULL, 
	[PriceOverrideStaffID] varchar(50) NULL, 
	[PurchaseStatusCodeID] varchar(50) NULL, 
	[StockLocationID] varchar(50) NULL, 
	[ShipLocationID] varchar(50) NULL, 
	[ServiceMerchandiseOrderID] varchar(50) NULL, 
	[ServiceMerchandiseItemID] int NULL, 
	[ServiceProblemCodeID] varchar(50) NULL, 
	[ServiceOrderOrderID] varchar(50) NULL, 
	[ServiceOrderItemID] int NULL, 
	[ServiceStatusCodeID] varchar(20) NULL, 
	[ServiceTechStaffID] varchar(50) NULL, 
	[Comments] varchar(255) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[SerialNumber] varchar(50) NULL, 
	[ItemCommCategory] varchar(10) NULL, 
	[NewEntryFlag] int NULL, 
	[SpecialOrderFlag] bit NULL, 
	[RecStatus] char(1) NULL
);