CREATE TABLE [Wholesale_ProductSourcing_AFI_Wrk].[Container] (

	[concontainer] varchar(18) NOT NULL, 
	[conID] int NOT NULL, 
	[concreated] datetime2(6) NULL, 
	[conviacode] char(3) NOT NULL, 
	[concarrierid] int NOT NULL, 
	[conmothervessel] varchar(30) NOT NULL, 
	[conmothervoyage] int NOT NULL, 
	[conreceipttostock] datetime2(6) NULL, 
	[conreceiver] datetime2(6) NULL, 
	[conoblsent] datetime2(6) NULL, 
	[confeedervessel] varchar(20) NOT NULL, 
	[confeedervoyage] int NOT NULL, 
	[conbookingnum] varchar(30) NOT NULL, 
	[conEquipmentReturned] datetime2(6) NULL, 
	[conEquipmentStatusCode] char(2) NOT NULL, 
	[conPallets] decimal(10,3) NOT NULL, 
	[conTruckLoad] bit NOT NULL, 
	[conPickUpDate] datetime2(6) NULL, 
	[conETA] datetime2(6) NULL, 
	[conOnBoard] datetime2(6) NULL, 
	[conEquipmentID] varchar(30) NOT NULL, 
	[conSealNumber] varchar(20) NOT NULL, 
	[conASNModificationStatus] int NOT NULL, 
	[conContainerOwnerID] smallint NOT NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[conReportedEmpty] datetime2(6) NULL, 
	[conCargoReceived] datetime2(6) NULL, 
	[conCheckDigit] int NULL, 
	[conSCAC] char(4) NOT NULL, 
	[conProNumber] varchar(30) NULL, 
	[conDeliveredDate] datetime2(6) NULL, 
	[conCNRUnumber] varchar(30) NULL, 
	[conRailSCAC] char(4) NULL, 
	[conExpectedDelivery] datetime2(6) NULL, 
	[conOutgateForDelivery] datetime2(6) NULL, 
	[conLastFreeDay] datetime2(6) NULL
);