CREATE TABLE [Wholesale_Invoicing_AFI].[DW013EW1] (

	[RECPST] char(1) NULL, 
	[EXCPTN] char(1) NULL, 
	[TRIPNO] numeric(5,0) NULL, 
	[DROPNO] numeric(2,0) NULL, 
	[ORDNO#] char(7) NULL, 
	[ITMSEQ] numeric(7,0) NULL, 
	[ITEMNO] varchar(15) NULL, 
	[SERNBR] numeric(15,0) NULL, 
	[CUSTNO] numeric(8,0) NULL, 
	[REFNBR] numeric(6,0) NULL, 
	[SCNQTY] numeric(4,0) NULL, 
	[REGNO] char(2) NULL, 
	[WHSNO] char(3) NULL, 
	[SCANNO] varchar(10) NULL, 
	[EQPNBR] varchar(15) NULL, 
	[BADGE] char(5) NULL, 
	[SUPBDG] char(5) NULL, 
	[GROUP#] char(3) NULL, 
	[SEQNO#] numeric(12,0) NULL, 
	[PALLT#] numeric(6,0) NULL, 
	[UCCNBR] varchar(20) NULL, 
	[ADDUSR] varchar(15) NULL, 
	[ADDDAT] numeric(8,0) NULL, 
	[ADDTIM] numeric(6,0) NULL, 
	[ADDSCN] varchar(10) NULL, 
	[MNTUSR] varchar(10) NULL, 
	[MNTDAT] numeric(8,0) NULL, 
	[MNTTIM] numeric(6,0) NULL, 
	[MNTSCN] varchar(10) NULL, 
	[CUSTID] varchar(20) NULL
);