CREATE TABLE [Wholesale_Invoicing_AFI].[TSINXN] (

	[XNINVR] numeric(9,0) NULL, 
	[XNORNO] char(7) NULL, 
	[XNTRPN] numeric(6,0) NULL, 
	[XNMAIL] char(1) NULL, 
	[XNSLS2] numeric(5,0) NULL, 
	[XNCOM1] numeric(3,0) NULL, 
	[XNCOM2] numeric(3,0) NULL, 
	[XNFRAM] numeric(9,2) NULL, 
	[XPYMT#] numeric(1,0) NULL, 
	[XORDAR] char(2) NULL, 
	[XADVTS] char(1) NULL, 
	[XREFNU] numeric(6,0) NULL, 
	[XORDTY] char(1) NULL, 
	[XOCRDT] numeric(8,0) NULL, 
	[XOTYP1] char(1) NULL, 
	[XOTYP2] char(1) NULL, 
	[XOTYP3] char(1) NULL, 
	[XOTYP4] char(1) NULL, 
	[XCONTA] varchar(25) NULL, 
	[XPRICC] char(3) NULL, 
	[XDSCNC] char(3) NULL, 
	[XCOMMC] char(3) NULL, 
	[XFRGHC] char(3) NULL, 
	[XUSREN] varchar(10) NULL, 
	[XRQDTE] numeric(8,0) NULL, 
	[XPROM#] char(7) NULL, 
	[XCAPR#] varchar(15) NULL, 
	[XDROP#] numeric(2,0) NULL, 
	[XTIMAD] numeric(6,0) NULL, 
	[XINVPF] char(1) NULL
);