CREATE TABLE [Wholesale_Invoicing_AFI].[TSITIN] (

	[ITINVR] numeric(9,0) NULL, 
	[ITORNO] char(7) NULL, 
	[ITITNO] varchar(15) NULL, 
	[ITITSQ] numeric(7,0) NULL, 
	[ITWHSE] char(3) NULL, 
	[ITUNCS] numeric(19,8) NULL, 
	[ITNOIV] numeric(1,0) NULL, 
	[ITORQT] numeric(10,3) NULL, 
	[ITSHQT] numeric(10,3) NULL, 
	[ITBOQT] numeric(10,3) NULL, 
	[ITUNMS] char(2) NULL, 
	[ITUNPC] numeric(13,3) NULL, 
	[ITDSAM] numeric(13,2) NULL, 
	[ITNTSL] numeric(13,3) NULL, 
	[ITCRCD] char(1) NULL, 
	[ITPRIC] numeric(13,2) NULL, 
	[ITPCCV] numeric(7,3) NULL, 
	[ITPCUM] char(2) NULL, 
	[ITIDDT] numeric(8,0) NULL, 
	[ITITCL] char(4) NULL, 
	[ITITDS] varchar(30) NULL, 
	[ITPSCD] char(1) NULL, 
	[ITEXWT] numeric(11,3) NULL, 
	[ITITTP] char(1) NULL, 
	[ITMFDT] numeric(8,0) NULL, 
	[ITIVAM] numeric(13,2) NULL, 
	[ITSNUM] varchar(20) NULL, 
	[ITRIDT] numeric(8,0) NULL, 
	[ITCSNO] numeric(8,0) NULL, 
	[ITSPNO] char(4) NULL, 
	[ITPONO] varchar(22) NULL
);