CREATE TABLE [retail_marketing].[ashleyguestcarthistoryload] (

	[CartCreationDateTime] datetime2(6) NULL, 
	[CartId] varchar(8000) NULL, 
	[CustomerName] varchar(8000) NULL, 
	[EmailAddress] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[AccountOwnerName] varchar(8000) NULL, 
	[RSAEmail] varchar(8000) NULL, 
	[StoreName] varchar(8000) NULL, 
	[RsaId] varchar(8000) NULL, 
	[StoreId] varchar(8000) NULL, 
	[PersonEmailOptIn] varchar(8000) NULL, 
	[ZipPostalCode] varchar(8000) NULL, 
	[Stage] varchar(8000) NULL, 
	[ContactOptInRecorded] varchar(8000) NULL, 
	[ProductSKU] varchar(8000) NULL, 
	[ProductName] varchar(8000) NULL, 
	[ProductDescription] varchar(8000) NULL, 
	[ProductQty] int NULL, 
	[ProductPrice] decimal(15,2) NULL, 
	[ProductTotalPrice] decimal(15,2) NULL, 
	[ProductColor] varchar(8000) NULL, 
	[ProductImageURL] varchar(8000) NULL, 
	[POS] varchar(8000) NULL, 
	[LoadDate] datetime2(6) NULL
);