CREATE TABLE [retail_marketing].[marketingjobsummary] (

	[MessageID] varchar(max) NULL, 
	[EventDate] datetime2(6) NULL, 
	[AttributedWrittenSales] decimal(16,9) NULL, 
	[AttributedWrittenSalesOpenClick] decimal(16,9) NULL, 
	[AttributedWrittenSalesSends] decimal(17,9) NULL, 
	[SFMCStoreBrandId] varchar(max) NULL, 
	[Sends] bigint NULL, 
	[UniqueSends] bigint NULL, 
	[OpenCount3Day] bigint NULL, 
	[UniqueOpenCount3Day] bigint NULL, 
	[BounceCount3Day] bigint NULL, 
	[UniqueBounceCount3Day] bigint NULL, 
	[ClickCount3Day] bigint NULL, 
	[UniqueClickCount3Day] bigint NULL, 
	[UnsubscribeCount3Day] bigint NULL, 
	[UniqueUnsubscribeCount3Day] bigint NULL, 
	[Journey] bigint NULL, 
	[DeploymentId] varchar(max) NULL, 
	[EmailSubject] varchar(max) NULL, 
	[EmailName] varchar(max) NULL, 
	[JobId] varchar(max) NULL, 
	[SourceSystem] varchar(max) NULL, 
	[CreatedDate] datetime2(6) NULL, 
	[CreatedBy] varchar(max) NULL, 
	[UpdatedDate] datetime2(6) NULL, 
	[UpdatedBy] varchar(max) NULL, 
	[StoreBrandID] varchar(max) NULL
);