CREATE TABLE [retail_marketing].[marketingactivity] (

	[EventID] varchar(8000) NULL, 
	[ContactValue] varchar(8000) NULL, 
	[Channel] varchar(8000) NULL, 
	[ChannelAction] varchar(8000) NULL, 
	[ActivityDateTimeUtc] datetime2(6) NULL, 
	[CampaignID] varchar(8000) NULL, 
	[CampaignName] varchar(8000) NULL, 
	[SubjectLine] varchar(8000) NULL, 
	[LinkName] varchar(8000) NULL, 
	[LinkTag] varchar(8000) NULL, 
	[LinkUrl] varchar(8000) NULL, 
	[DeviceCategory] varchar(8000) NULL, 
	[DeviceSubcategory] varchar(8000) NULL, 
	[DeviceType] varchar(8000) NULL, 
	[Audience] varchar(8000) NULL, 
	[SourceSystem] varchar(8000) NULL, 
	[CustomerID] varchar(8000) NULL, 
	[AlternateCustomerID] varchar(8000) NULL, 
	[MessageID] varchar(8000) NULL, 
	[CampaignType] varchar(8000) NULL, 
	[CampaignTags] varchar(8000) NULL, 
	[BusinessType] varchar(8000) NULL, 
	[DeploymentID] varchar(8000) NULL, 
	[CampaignVersionName] varchar(8000) NULL, 
	[CampaignABTestVersion] varchar(8000) NULL, 
	[MarketingRegion] varchar(8000) NULL, 
	[UtmSource] varchar(8000) NULL, 
	[GeoStateProvinceSubdivision] varchar(8000) NULL, 
	[GeoCountryCode] varchar(8000) NULL, 
	[GeoCity] varchar(8000) NULL, 
	[GeoLatitude] decimal(9,5) NULL, 
	[GeoLongitude] decimal(9,5) NULL, 
	[EventDate] date NULL, 
	[LoadDate] datetime2(6) NULL, 
	[LightboxID] varchar(8000) NULL
);