CREATE TABLE [MasterData_HR_UKG_Wrk].[LocationMaster] (

	[LocationKey] bigint NULL, 
	[LocationID] varchar(50) NULL, 
	[LocationIDDisplay] varchar(50) NULL, 
	[LocationType] varchar(5) NULL, 
	[PrimaryLocationID] varchar(50) NULL, 
	[MapToLocationID] varchar(50) NULL, 
	[ServiceLocationID] varchar(50) NULL, 
	[StockLocationID] varchar(50) NULL, 
	[ShipLocationID] varchar(50) NULL, 
	[HRLocationID] varchar(50) NULL, 
	[StoreBrandID] varchar(20) NULL, 
	[LocationName] varchar(50) NULL, 
	[Address1] varchar(100) NULL, 
	[Address2] varchar(100) NULL, 
	[City] varchar(100) NULL, 
	[PostalCodeID] varchar(50) NULL, 
	[Phone] varchar(15) NULL, 
	[RegionID] varchar(50) NULL, 
	[RegionName] varchar(100) NULL, 
	[DistrictID] varchar(50) NULL, 
	[DistrictName] varchar(50) NULL, 
	[HasTrafficCounter] bit NULL, 
	[TotalSquareFeet] int NULL, 
	[OpenDate] date NULL, 
	[Owner] varchar(200) NULL, 
	[OwnerGroup] varchar(200) NULL, 
	[OwnerNumber] varchar(50) NULL, 
	[HasPulse] bit NULL, 
	[SameStoreDate] date NULL, 
	[State] varchar(50) NULL, 
	[ProductiveSquareFeet] decimal(18,2) NULL, 
	[SCMLocationID] varchar(50) NULL, 
	[ReceiveMonday] bit NULL, 
	[ReceiveTuesday] bit NULL, 
	[ReceiveWednesday] bit NULL, 
	[ReceiveThursday] bit NULL, 
	[ReceiveFriday] bit NULL, 
	[ReceiveSaturday] bit NULL, 
	[ReceiveSunday] bit NULL, 
	[IsVirtual] bit NULL, 
	[SameStoreDateClosed] date NULL, 
	[AdjustedLocationName] varchar(50) NULL, 
	[LocationIDPadded] varchar(20) NOT NULL
);