CREATE VIEW [CostAccounting_DW_Wrk].[v_FactMargins]
AS SELECT	 [Month End Date]				    = GMCMONTHENDDATE
				,[Item Number]					= TRIM(GMCITEMNUMBER)
				,[Margin Warehouse]				= GMCMARGINWAREHOUSE
				,[Fiscal Year Period]			= CONVERT(VARCHAR(4),CAST(GMC.GMCFISCALYEAR AS INT)) + CASE WHEN GMC.GMCFISCALMONTH  < 10 THEN '0' ELSE '' END + CONVERT(VARCHAR(2),CAST(GMC.GMCFISCALMONTH AS INT))
				,[Security Tag]					= 'Mrgn'
				,[FOB Value]					= CASE WHEN GMCFOBVALUE <> 0 THEN GMCFOBVALUE ELSE NULL END
				,[Quantity Ordered]				= CASE WHEN GMCNETQUANTITYORDERED <> 0 THEN GMCNETQUANTITYORDERED ELSE NULL END
				,[Amount Ordered]				= CASE WHEN GMCNETAMOUNTORDERED <> 0 THEN GMCNETAMOUNTORDERED ELSE NULL END
				,[Average Selling Price]		= CASE WHEN GMCAVERAGESELLINGPRICE <> 0 THEN GMCAVERAGESELLINGPRICE ELSE NULL END
				,[Average Inventory On-Hand]	= CASE WHEN GMCAVERAGEINVENTORYVALUE <> 0 THEN GMCAVERAGEINVENTORYVALUE ELSE NULL END
				,[GMROI - Sales]				= CASE WHEN GMCGMROISALES <> 0 THEN GMCGMROISALES ELSE NULL END
				,[GMROI - Cost of Sales]		= CASE WHEN GMCGMROICOSTOFSALES <> 0 THEN GMCGMROICOSTOFSALES ELSE NULL END
				,[GMROI - Margin]				= CASE WHEN GMCGMROIMARGIN <> 0 THEN GMCGMROIMARGIN ELSE NULL END
				,[GMROI - Net Sales]			= CASE WHEN GMCGMROINETSALES <> 0 THEN GMCGMROINETSALES ELSE NULL END
				,[GMROI - Actual Cost of Sales]	= CASE WHEN GMCGMROIACTUALCOSTOFSALES <> 0 THEN GMCGMROIACTUALCOSTOFSALES ELSE NULL END
				,[Returns Percent]				= CASE WHEN GMCAVERAGERETURNSAMOUNT <> 0 THEN GMCAVERAGERETURNSAMOUNT ELSE NULL END
				,[Allowance Percent]			= CASE WHEN GMCAVERAGEALLOWANCEAMOUNT <> 0 THEN GMCAVERAGEALLOWANCEAMOUNT ELSE NULL END
				,[Short Shipment Percent]		= CASE WHEN GMCAVERAGESHORTSHIPAMOUNT <> 0 THEN GMCAVERAGESHORTSHIPAMOUNT ELSE NULL END
				,[MarginDetailsKey]				= ISNULL(DMD.[MarginDetailsKey],1)
		FROM	[$(Databricks)].costaccounting.[fif115] GMC LEFT JOIN 

		[CostAccounting_DW].[DimMarginDetails] DMD on
		(
		ISNULL(CONVERT(VARCHAR(4),CAST(GMC.GMCFISCALYEAR AS INT)) + CASE WHEN GMC.GMCFISCALMONTH  < 10 THEN '0' ELSE '' END + CONVERT(VARCHAR(2),CAST(GMC.GMCFISCALMONTH AS INT)),'') = ISNULL(DMD.[Fiscal Year Period],'')

			AND ISNULL(GMC.GMCITEMNUMBER,'') = ISNULL(DMD.[Item Number],'')

			AND ISNULL(GMC.GMCMARGINWAREHOUSE,'') = ISNULL(DMD.[Margin Warehouse],''));
GO



