CREATE TABLE [AFISales_DW].[DimCustomers] (

	[Account And Shipto Number] char(13) NULL, 
	[Customer Name] varchar(25) NULL, 
	[Customer Account Number] char(8) NULL, 
	[Customer Shipto Number] char(4) NULL, 
	[Account Exception Flag] int NULL, 
	[Discount Code] char(3) NULL, 
	[Discount Code Description] varchar(30) NULL, 
	[AFI Discount Description] varchar(35) NULL, 
	[Price Code] char(6) NULL, 
	[Price Code Description] varchar(30) NULL, 
	[AFI Price Description] varchar(38) NULL, 
	[Freight Code] char(3) NULL, 
	[Freight Code Description] varchar(30) NULL, 
	[AFI Freight Description] varchar(35) NULL, 
	[Commission Code] char(3) NULL, 
	[Commission Code Description] varchar(30) NULL, 
	[AFI Commission Code] varchar(35) NULL, 
	[Customer Shipto Name] varchar(35) NULL, 
	[Customer Segment] int NULL, 
	[Business Type Code] char(2) NULL, 
	[Business Type] varchar(30) NOT NULL, 
	[Reporting Business Type] varchar(50) NULL, 
	[Customer Service Repid] char(5) NOT NULL, 
	[Customer Service Agent Name] varchar(50) NOT NULL, 
	[Customer Service Group ID] char(2) NOT NULL, 
	[Customer Service Group Leader] varchar(10) NOT NULL, 
	[Store Address ID] int NULL, 
	[Shipto AddressID] int NULL, 
	[Primary Sales Territory] char(5) NULL, 
	[Shipto Sales Territory] char(5) NULL, 
	[Customer Account Status] char(1) NULL, 
	[DFI Account Flag] char(1) NOT NULL, 
	[AFI Credit Terms] varchar(30) NULL, 
	[Terms Code] char(3) NULL, 
	[Credit Territory Code] int NULL, 
	[Default Warehouse] char(3) NULL, 
	[Terms Description] varchar(25) NULL, 
	[Route Zone] char(3) NOT NULL, 
	[Route Region] char(3) NOT NULL, 
	[Bill To Address 1] varchar(35) NULL, 
	[Bill To Address 2] varchar(35) NULL, 
	[Bill To Address 3] varchar(35) NULL, 
	[Bill To Address 4] varchar(35) NULL, 
	[Bill To Address 5] varchar(35) NULL, 
	[Bill To City] varchar(35) NULL, 
	[Bill To State] char(2) NULL, 
	[Bill To Zip Code] varchar(10) NULL, 
	[Bill To Country] char(3) NULL, 
	[Bill To-Buyer Name] varchar(50) NULL, 
	[Bill To-Buyer Phone] varchar(50) NULL, 
	[Bill To-Buyer Fax] varchar(50) NULL, 
	[Bill To-Buyer Email] varchar(50) NULL, 
	[Bill To-Receiving Name] varchar(50) NULL, 
	[Bill To-Receiving Phone] varchar(50) NULL, 
	[Bill To-Receiving Fax] varchar(50) NULL, 
	[Bill To-Receiving Email] varchar(50) NULL, 
	[Ship To-Buyer Name] varchar(50) NULL, 
	[Ship To-Buyer Phone] varchar(50) NULL, 
	[Ship To-Buyer Fax] varchar(50) NULL, 
	[Ship To-Buyer Email] varchar(50) NULL, 
	[Ship To-Receiving Name] varchar(50) NULL, 
	[Ship To-Receiving Phone] varchar(50) NULL, 
	[Ship To-Receiving Fax] varchar(50) NULL, 
	[Ship To-Receiving Email] varchar(50) NULL, 
	[Shipto Details] varchar(80) NULL, 
	[ACI Amount] decimal(15,2) NULL, 
	[Outstanding Balance] decimal(14,2) NOT NULL, 
	[Days Beyond Terms - 90] decimal(14,0) NOT NULL, 
	[Days Beyond Terms - 365] decimal(14,0) NOT NULL, 
	[Credit Limit] decimal(14,0) NOT NULL, 
	[Invoice Type] char(1) NULL, 
	[EPay Flag] char(1) NULL, 
	[Currency Type] char(3) NULL, 
	[Highest Credit] decimal(28,2) NOT NULL, 
	[ABC Account-Current Year] char(1) NOT NULL, 
	[ABC Account-Previous Year] char(1) NOT NULL, 
	[ABC Account-2 Years Ago] char(1) NOT NULL, 
	[HS Owner] varchar(50) NULL, 
	[District Manager] varchar(50) NULL, 
	[CustomerandAccountNumber] varchar(50) NULL
);