CREATE TABLE [Purchasing_AFI].[VendorMaster](
	[VendorNumber] [char](8) NULL,
	[VendorName] [varchar](50) NULL,
	[NameAbbreviaton] [varchar](20) NULL,
	[Address1] [varchar](25) NULL,
	[Address2] [varchar](25) NULL,
	[City] [varchar](25) NULL,
	[State] [char](2) NULL,
	[ZipCode] [varchar](10) NULL,
	[Country] [char](3) NULL,
	[PhoneNumber] [varchar](20) NULL,
	[FaxNumber] [varchar](20) NULL,
	[AmountToDate] [decimal](13, 2) NULL,
	[AmountYTD] [decimal](13, 2) NULL,
	[AmountLastYear] [decimal](13, 2) NULL,
	[LastPaymentDate] [decimal](7, 0) NULL,
	[DiscountsYTD] [decimal](13, 2) NULL,
	[DiscountsLastYear] [decimal](13, 2) NULL,
	[DiscountsLostYTD] [decimal](13, 2) NULL,
	[DiscountsLostLastyear] [decimal](13, 2) NULL,
	[DateLastMaintained] [decimal](28, 0) NULL,
	[TaxID] [varchar](11) NULL,
	[NEC_AmountYTD] [decimal](13, 2) NULL,
	[NEC_AmountLastYear] [decimal](13, 2) NULL,
	[TermsCode] [char](3) NULL,
	[TermsDescription] [varchar](25) NULL,
	[MultiLinePOFlag] [char](1) NULL,
	[Contact] [varchar](25) NULL,
	[ClosedAcknowledgementFlag] [char](1) NULL,
	[MultiShiptoFlag] [char](1) NULL,
	[ContractNumber] [char](5) NULL,
	[LastVendorRating] [decimal](13, 2) NULL,
	[AverageVendorRating] [decimal](13, 2) NULL,
	[BlanketAllowed] [char](1) NULL,
	[POAcceptanceFlag] [char](1) NULL,
	[AssigneeNumber] [char](6) NULL,
	[POSuspendedForVendor] [char](1) NULL,
	[FreeOnBoardCode] [char](3) NULL,
	[FreeOnBoardDescription] [varchar](15) NULL,
	[CurrencyCode] [char](3) NULL,
	[TaxSuffix] [char](5) NULL,
	[SalesTaxID1] [varchar](15) NULL,
	[SalesTaxID2] [varchar](15) NULL,
	[EnterpriseCode] [char](6) NULL,
	[ShipViaCode] [char](3) NULL,
	[ShipViaDescription] [varchar](15) NULL,
	[OurCustomerNumber] [varchar](20) NULL,
	[PaymentMethodCode] [char](3) NULL,
	[UserFieldA] [char](1) NULL,
	[UserFieldC] [char](5) NULL,
	[UserFieldT25] [varchar](25) NULL,
	[EmailAddress] [varchar](70) NULL
) ON [PRIMARY]
