CREATE TABLE [Retail_Corporate].[Category] (

	[Operation] varchar(15) NULL, 
	[Accessory] bit NOT NULL, 
	[AutoReplPrimStoreID] varchar(50) NULL, 
	[AutoReplQuatStoreID] varchar(50) NULL, 
	[AutoReplQuinStoreID] varchar(50) NULL, 
	[AutoReplScndStoreID] varchar(50) NULL, 
	[AutoReplTertStoreID] varchar(50) NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[CategoryType] varchar(10) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[Custom1] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Description] varchar(50) NULL, 
	[Family] varchar(100) NULL, 
	[InvType] varchar(10) NOT NULL, 
	[IsActive] bit NULL, 
	[LastBatchID] int NULL, 
	[MinGrossProfit] decimal(18,2) NULL, 
	[OTBDept] varchar(20) NULL, 
	[RecStatus] char(1) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StaffID] varchar(50) NULL, 
	[WrittenSOZeroCostPercent] decimal(18,2) NULL
);