CREATE TABLE [Retail_Corporate].[Deposits] (

	[Operation] char(3) NULL, 
	[CustomerID] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DepositDate] date NULL, 
	[DepositsId] varchar(50) NULL, 
	[IsFinanced] bit NULL, 
	[IsHistory] bit NULL, 
	[LastBatchID] int NULL, 
	[OrderID] varchar(50) NULL, 
	[PaymentAmt] numeric(19,4) NULL, 
	[PaymentAuthNbr] varchar(100) NULL, 
	[PaymentDLorCheckNumber] varchar(100) NULL, 
	[PaymentExpDate] date NULL, 
	[PaymentNbr] varchar(100) NULL, 
	[PaymentNSFReference] varchar(100) NULL, 
	[PaymentTypeID] varchar(50) NULL, 
	[RecStatus] char(1) NULL, 
	[ReferenceNbr] varchar(200) NULL, 
	[Sequence] int NULL, 
	[SourceID] varchar(50) NULL, 
	[WorkStatus] varchar(100) NULL
);