CREATE TABLE [Retail_Corporate].[Groups] (

	[Operation] varchar(15) NULL, 
	[AutoReplPrimStoreID] varchar(50) NULL, 
	[AutoReplQuatStoreID] varchar(50) NULL, 
	[AutoReplQuinStoreID] varchar(50) NULL, 
	[AutoReplScndStoreID] varchar(50) NULL, 
	[AutoReplTertStoreID] varchar(50) NULL, 
	[CategoryID] varchar(50) NULL, 
	[CompanyID] varchar(50) NULL, 
	[Cubes] numeric(18,2) NULL, 
	[Custom1] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DeliveryCubes] numeric(18,2) NULL, 
	[Description] varchar(50) NULL, 
	[GroupID] varchar(50) NULL, 
	[InvType] varchar(10) NULL, 
	[IsActive] bit NULL, 
	[LabelQty] numeric(18,2) NULL, 
	[LabelType] char(5) NULL, 
	[LastBatchID] int NULL, 
	[MinGrossProfit] numeric(18,4) NULL, 
	[OTBDept] varchar(20) NULL, 
	[RecStatus] char(1) NULL, 
	[ReductionPercent] numeric(18,2) NULL, 
	[Repossessable] bit NULL, 
	[RestockFeePercentage] numeric(18,2) NULL, 
	[SourceID] varchar(50) NULL, 
	[StaffID] varchar(50) NULL, 
	[UnloadTime] datetime2(6) NULL, 
	[Weight] numeric(18,2) NULL, 
	[WrittenSOZeroCostPercent] numeric(18,2) NULL
);