CREATE TABLE [Retail_Corporate].[InvoiceItem_ProductInfo_HISTORY] (

	[Operation] varchar(15) NULL, 
	[Addon1Cost] numeric(19,4) NULL, 
	[Addon2Cost] numeric(19,4) NULL, 
	[Addon3Cost] numeric(19,4) NULL, 
	[Addon4Cost] numeric(19,4) NULL, 
	[CompanyID] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[ItemID] int NULL, 
	[LandedFreight] numeric(19,4) NULL, 
	[LineID] int NULL, 
	[LocatorNbr] varchar(50) NULL, 
	[OrderID] varchar(50) NULL, 
	[PieceID] int NULL, 
	[ProductID] varchar(50) NULL, 
	[PurchaseOrderID] varchar(50) NULL, 
	[RcvdByBarCode] varchar(50) NULL, 
	[ReasonCodeID] varchar(50) NULL, 
	[RecStatus] char(1) NULL, 
	[RFLabel] varchar(50) NULL, 
	[RFStatus] varchar(50) NULL, 
	[SerialNbr] varchar(50) NULL, 
	[SourceID] varchar(50) NULL, 
	[TotCost] numeric(19,4) NULL, 
	[WhseMgmtQtyReceived] int NULL, 
	[WhseMgmtQtyShipped] int NULL
);