CREATE TABLE [Retail_Corporate].[OpenBookSalesSplitAudit] (

	[Operation] varchar(15) NULL, 
	[ID] int NOT NULL, 
	[TypeOrder] char(1) NULL, 
	[StoreID] char(3) NULL, 
	[OrderID] varchar(50) NULL, 
	[WrittenDate] datetime2(6) NULL, 
	[WrittenTime] varchar(20) NULL, 
	[CustomerID] varchar(50) NULL, 
	[CustomerName] varchar(150) NULL, 
	[CustomerPhoneNumber] varchar(50) NULL, 
	[CustomerEmail] varchar(150) NULL, 
	[CustomerAddress] varchar(150) NULL, 
	[CustomerCity] varchar(150) NULL, 
	[CustomerState] varchar(15) NULL, 
	[MerchSubTot] numeric(18,3) NULL, 
	[TotMerchCost] numeric(18,3) NULL, 
	[ProtectionPlanPrice] numeric(18,3) NULL, 
	[ProtectionPlanCost] numeric(18,3) NULL, 
	[SalesMargin] numeric(18,3) NULL, 
	[NetMargin] numeric(18,3) NULL, 
	[FinanceAmt] numeric(18,3) NULL, 
	[DlvyChrg] numeric(18,3) NULL, 
	[PaymentMethod] varchar(4000) NULL, 
	[SalesPersonName] varchar(250) NULL, 
	[ProductCategory] varchar(50) NULL, 
	[FinanceTermCode] varchar(50) NULL, 
	[DlvyMethod] varchar(50) NULL, 
	[ActionTaken] varchar(50) NULL, 
	[ActionTakenDate] datetime2(6) NULL, 
	[SnapshotDate] datetime2(6) NULL, 
	[RecStatus] char(1) NULL, 
	[DuplicatedByAddress] bit NOT NULL, 
	[DuplicatedByPhone] bit NOT NULL, 
	[DuplicatedByEmail] bit NOT NULL
);