CREATE TABLE [Wholesale_Marketing].[Adfundsrequest] (

	[afRequestID] int NULL, 
	[afAccountName] varchar(80) NULL, 
	[afAccountNumber] varchar(820) NULL, 
	[afShipTo] varchar(10) NULL, 
	[afOwner] varchar(60) NULL, 
	[afVicePresident] varchar(80) NULL, 
	[afStatus] varchar(60) NULL, 
	[afAmount] decimal(8,2) NULL, 
	[afCreatedDate] datetime2(6) NULL, 
	[afFundType] varchar(45) NULL, 
	[afNotes] varchar(max) NULL, 
	[afDivision] varchar(70) NULL, 
	[afEventName] varchar(80) NULL, 
	[afSpecialDiscountCode] varchar(300) NULL, 
	[usra] varchar(50) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(50) NULL, 
	[dtec] datetime2(6) NULL, 
	[afEventStartDate] datetime2(6) NULL, 
	[afEventEndDate] datetime2(6) NULL, 
	[afUsedFor] varchar(50) NULL, 
	[afgoal] varchar(80) NULL, 
	[afPercentOrAmount] varchar(80) NULL, 
	[afCategoryFocusedOn] varchar(80) NULL, 
	[afCreditIssuedBy] varchar(150) NULL, 
	[afCreditIssuedOn] datetime2(6) NULL, 
	[afApprovedBy] varchar(150) NULL, 
	[afApprovedOn] datetime2(6) NULL, 
	[afRejectedBy] varchar(150) NULL, 
	[afRejectedOn] datetime2(6) NULL, 
	[afParentVicePresident] varchar(150) NULL, 
	[afCreditCode] varchar(30) NULL, 
	[afCreditMemoComments] varchar(350) NULL, 
	[afDoNotPrint] char(6) NULL
);