CREATE TABLE [Wholesale_Marketing].[CRMVelocityDriver] (

	[Cvdid] int NULL, 
	[Cvdregioncode] char(3) NULL, 
	[Cvdrepid] char(5) NULL, 
	[Cvddivisioncode] char(1) NULL, 
	[Cvdaccountnumber] char(8) NULL, 
	[Cvdshipto] char(4) NULL, 
	[Cvdcreateddate] datetime2(6) NULL, 
	[Cvdmarkethook1] varchar(102) NULL, 
	[Cvdmarkethook2] varchar(102) NULL, 
	[Cvdmarkethook3] varchar(102) NULL, 
	[Cvdmarkethook4] varchar(102) NULL, 
	[Cvdmarkethook5] varchar(102) NULL, 
	[Cvdmarkethook6] varchar(102) NULL, 
	[Cvdcustomhook] varchar(52) NULL, 
	[Cvdeventname] varchar(102) NULL, 
	[Cvdvelocitydrivername] varchar(102) NULL, 
	[Cvdmarketdate] datetime2(6) NULL, 
	[Cvdeventenddate] datetime2(6) NULL, 
	[Cvdmediacircularflag] bit NULL, 
	[Cvdmediadirectmailflag] bit NULL, 
	[Cvdmediainternetflag] bit NULL, 
	[Cvdmediasocialmediaflag] bit NULL, 
	[Cvdmedianewspaperflag] bit NULL, 
	[Cvdmediaotherflag] varchar(102) NULL, 
	[Cvdmediaradioflag] bit NULL, 
	[Cvdmediatvflag] bit NULL, 
	[Cvdwilltheyrunthisagainflag] bit NULL, 
	[Cvdvelocitydriverstatuscode] int NULL, 
	[Cvdvelocitydriverstatusdescr] varchar(102) NULL, 
	[Cvdvelocitydrivercount] decimal(18,3) NULL
);