CREATE TABLE [Wholesale_Marketing].[MarketCommitmentsSum] (

	[Mksrepid] char(5) NULL, 
	[Mkscustomernumber] char(8) NULL, 
	[Mksshiptonumber] char(4) NULL, 
	[Mksitemnumber] varchar(17) NULL, 
	[Mkshomestoreflag] bit NULL, 
	[Mkscommitted] int NULL, 
	[Mksactual] int NULL, 
	[Mksactualmonthlyqty] decimal(5,2) NULL, 
	[Mksgoal0] int NULL, 
	[Mksmonthlyestqty] decimal(5,2) NULL, 
	[Mksoriginalmonthlyestqty] decimal(5,2) NULL, 
	[Mksoriginalcommitment] int NULL, 
	[Mksuserid] varchar(32) NULL, 
	[Mksdatechanged] datetime2(6) NULL, 
	[Usra] varchar(32) NULL, 
	[Dtea] datetime2(6) NULL, 
	[Usrc] varchar(32) NULL, 
	[Dtec] datetime2(6) NULL, 
	[Mkshomestorecommitted] int NULL, 
	[Mkshomestoreoriginalcommitment] int NULL, 
	[Mksregion] char(3) NULL, 
	[Mkshomestoreqty] int NULL, 
	[Mksnonhomestoreqty] int NULL
);