CREATE TABLE [Wholesale_Marketing].[MoSeriesMargins] (

	[Momseries] varchar(17) NULL, 
	[Momdollars] decimal(12,2) NULL, 
	[Momorders] decimal(12,2) NULL, 
	[Momfob] decimal(8,2) NULL, 
	[Momcur] decimal(8,2) NULL, 
	[Momact] decimal(8,2) NULL, 
	[Momfob_3] decimal(8,2) NULL, 
	[Momcur_3] decimal(8,2) NULL, 
	[Momact_3] decimal(8,2) NULL, 
	[Momfob_6] decimal(8,2) NULL, 
	[Momcur_6] decimal(8,2) NULL, 
	[Momact_6] decimal(8,2) NULL, 
	[Momfob_12] decimal(8,2) NULL, 
	[Momcur_12] decimal(8,2) NULL, 
	[Momact_12] decimal(8,2) NULL, 
	[Momgmroi_1] decimal(8,1) NULL, 
	[Momgmroi_2] decimal(8,1) NULL, 
	[Momgmroi_3] decimal(8,1) NULL, 
	[Momgmroi_4] decimal(8,1) NULL, 
	[Momgmroi_5] decimal(8,1) NULL, 
	[Momgmroi_6] decimal(8,1) NULL, 
	[Momgmroi_7] decimal(8,1) NULL, 
	[Momgmroi_8] decimal(8,1) NULL, 
	[Momgmroi_9] decimal(8,1) NULL, 
	[Momgmroi_10] decimal(8,1) NULL, 
	[Momgmroi_11] decimal(8,1) NULL, 
	[Momgmroi_12] decimal(8,1) NULL, 
	[Mommonth] int NULL
);