CREATE TABLE [Wholesale_Marketing].[TravelBooks] (

	[Tbrequestid] int NOT NULL, 
	[Tbenteredby] varchar(102) NOT NULL, 
	[Tbentereddate] datetime2(6) NOT NULL, 
	[Tbenteredrole] varchar(32) NULL, 
	[Tbenteredemail] varchar(102) NULL, 
	[Tbrecipient] varchar(102) NOT NULL, 
	[Tbrecipientrole] varchar(32) NULL, 
	[Tbrecipientemail] varchar(102) NULL, 
	[Tbpostvisitstatus] varchar(52) NULL, 
	[Tbpostvisitcomments] varchar(8000) NULL, 
	[Tbdateofvisitorreview] datetime2(6) NULL, 
	[Tbdeliverydate] datetime2(6) NULL, 
	[Tbprintchart] bit NULL, 
	[Tbprintgrid] bit NULL, 
	[Tbdivision] char(3) NOT NULL, 
	[Tbaccountname] varchar(102) NULL, 
	[Tbaccountnumber] varchar(52) NOT NULL, 
	[Tbshipto] varchar(12) NOT NULL, 
	[Tbstatus] varchar(52) NOT NULL, 
	[Tbvisitonly] bit NULL, 
	[Tbenteredname] varchar(102) NULL, 
	[Tbrecipientname] varchar(102) NULL, 
	[Usra] varchar(32) NULL, 
	[Dtea] datetime2(6) NULL, 
	[Usrc] varchar(32) NULL, 
	[Dtec] datetime2(6) NULL, 
	[Tbcomments] varchar(8000) NULL
);