CREATE TABLE [Wholesale_Purchasing_AFI].[VENEXT] (

	[VENDORNUMBER] char(8) NULL, 
	[CLASSIFICATION] char(5) NULL, 
	[VENDORTYPE] char(5) NULL, 
	[CATEGORY] char(5) NULL, 
	[PRODUCTTYPE] char(5) NULL, 
	[LOCATIONORIGIN] char(5) NULL, 
	[SOURCETYPE] char(5) NULL, 
	[USERFIELDA] char(5) NULL, 
	[USERFIELDB] varchar(15) NULL, 
	[USERFIELDC] varchar(25) NULL, 
	[USERFIELD1] decimal(28,3) NULL, 
	[CREATEUSER] varchar(10) NULL, 
	[CREATEPRGM] varchar(10) NULL, 
	[CREATEDATE] decimal(28,0) NULL, 
	[CREATETIME] decimal(28,0) NULL, 
	[CHANGEUSER] varchar(10) NULL, 
	[CHANGEPROGRAM] varchar(10) NULL, 
	[CHANGEDATE] decimal(28,0) NULL, 
	[CHANGETIME] decimal(28,0) NULL
);