CREATE TABLE [MasterData_ItemMaster_AFI].[Price] (

	[JOENTL] numeric(10,0) NULL, 
	[JOSEQN] numeric(10,0) NULL, 
	[JOCODE] char(1) NULL, 
	[JOENTT] char(2) NULL, 
	[JODATE] char(6) NULL, 
	[JOTIME] numeric(10,0) NULL, 
	[JOJOB] char(10) NULL, 
	[JOUSER] char(10) NULL, 
	[JONBR] numeric(10,0) NULL, 
	[JOPGM] char(10) NULL, 
	[JOOBJ] char(10) NULL, 
	[JOLIB] char(10) NULL, 
	[JOMBR] char(10) NULL, 
	[JOCTRR] numeric(10,0) NULL, 
	[JOFLAG] char(1) NULL, 
	[JOCCID] numeric(10,0) NULL, 
	[JOUSPF] char(10) NULL, 
	[JOSYNM] char(8) NULL, 
	[JOINCDAT] char(1) NULL, 
	[JOMINESD] char(1) NULL, 
	[JORES] char(18) NULL, 
	[PRICCD] char(6) NOT NULL, 
	[PITEM] char(15) NOT NULL, 
	[PAMNT] numeric(13,3) NOT NULL, 
	[PCMADJ] numeric(13,3) NOT NULL, 
	[PWHSOP] numeric(6,4) NOT NULL
);