Create TABLE [Wholesale_SalesHistory_AFI_Wrk].[InvoiceSerialNumberManufactured](
	[Invoicedate] [datetime2](6) NOT NULL,
	[Invoicenumber] [decimal](9, 0) NOT NULL,
	[Serialnumber] [varchar](17) NULL,
	[Ordernumber] [varchar](12) NULL,
	[Itemnumber] [varchar](17) NULL,
	[Itemseqnumber] [decimal](7, 0) NOT NULL,
	[Mfgordernumber] [varchar](12) NULL,
	[Customernumber] [char](8) NULL,
	[Shiptonumber] [char](4) NULL,
	[Dropnumber] [decimal](2, 0) NOT NULL,
	[Wheremade] [char](5) NOT NULL,
	[Usergroup] [varchar](12) NULL,
	[Mfgdate] [datetime2](6) NULL,
	[Scanname] [varchar](15) NULL,
	[Loaddate] [datetime2](6) NOT NULL,
	[Trucknumber] [varchar](17) NULL,
	[Carrier] [varchar](27) NULL,
	[Warehouse] [char](3) NULL,
	[Department] [char](5) NULL,
	[Workcenter] [char](5) NULL,
	[Group] [decimal](5, 0) NOT NULL,
	[Shift] [decimal](1, 0) NOT NULL,
	[Supervisornumber] [decimal](5, 0) NOT NULL,
	[Aatwarehouse] [char](3) NULL
);