CREATE TABLE [MasterData_Retail_Wrk].[StorisHourlySalesData] (

	[transactionId] varchar(50) NULL, 
	[serverTime] datetime2(6) NULL, 
	[id] varchar(20) NULL, 
	[orderId] varchar(20) NULL, 
	[orderItemId] varchar(20) NULL, 
	[productId] varchar(30) NULL, 
	[customerId] varchar(30) NULL, 
	[salespersonId] varchar(10) NULL, 
	[storeId] varchar(10) NULL, 
	[transactionCodeId] varchar(10) NULL, 
	[transactionDate] datetime2(6) NULL, 
	[netCost] numeric(10,2) NULL, 
	[netSales] numeric(10,2) NULL, 
	[netUnits] numeric(10,2) NULL, 
	[grossProfit] numeric(10,2) NULL, 
	[protection_plan_id] varchar(30) NULL, 
	[protection_plan_return_cost] numeric(10,2) NULL, 
	[protection_plan_return_price] numeric(10,2) NULL, 
	[protection_plan_sales_cost] numeric(10,2) NULL, 
	[protection_plan_sales_price] numeric(10,2) NULL, 
	[updateTypeId] varchar(10) NULL, 
	[writtenFlag] bit NULL, 
	[dwLoadDateTime] datetime2(6) NULL, 
	[startDate] datetime2(6) NULL, 
	[source] char(2) NULL
);