CREATE TABLE [Manufacturing_ProductionPlanning_AFI].[MSIORD] (

	[ITNBR] varchar(15) NULL, 
	[SEQNR] decimal(7,0) NULL, 
	[ITMSQ] decimal(7,0) NULL, 
	[POQTY] decimal(10,3) NULL, 
	[POSTD] decimal(7,0) NULL, 
	[POSOR] decimal(1,0) NULL, 
	[PODUD] decimal(7,0) NULL, 
	[PMCDE] char(1) NULL, 
	[PODAZ] decimal(3,0) NULL, 
	[POSHK] decimal(10,3) NULL, 
	[POERC] decimal(2,0) NULL, 
	[MSOCC] char(1) NULL, 
	[POLVL] decimal(2,0) NULL, 
	[CONO] decimal(2,0) NULL, 
	[ORTP] char(1) NULL, 
	[SDMD] char(7) NULL, 
	[LNSQ] decimal(7,0) NULL, 
	[RLNB] decimal(5,0) NULL, 
	[KTRL] decimal(5,0) NULL, 
	[WHID] char(3) NULL, 
	[ALTS] varchar(10) NULL, 
	[ITRV] char(6) NULL, 
	[RTID] varchar(15) NULL, 
	[RTVR] char(6) NULL, 
	[STID] char(3) NULL, 
	[RRN] decimal(10,0) NULL
);