CREATE TABLE [ProductKnowledge].[ItemMaster]
    (
        [SeriesCode]              VARCHAR(16)   NOT NULL,
        [ItemName]                VARCHAR(100)  NOT NULL,
        [ItemSKU]                 VARCHAR(15)   NOT NULL,
        [Dimension]               VARCHAR(25)   NOT NULL,
        [Finish]                  VARCHAR(25)   NOT NULL,
        [Material]                VARCHAR(25)   NOT NULL,
        [Colors]                  VARCHAR(25)   NOT NULL,
        [Features]                VARCHAR(5000) NOT NULL,
        [Retail]                  DECIMAL(9,2)  NOT NULL,
        [Active]                  BIT           NOT NULL,
        [Photo]                   VARCHAR(50)   NOT NULL,
        [SchematicDrawing]        VARCHAR(35)   NOT NULL,
        [PriceRange]              VARCHAR(15)   NOT NULL,
        [InstructionSet]          VARCHAR(35)   NOT NULL,
        [warrenty]                VARCHAR(35)   NOT NULL,
        [IsNewItem]               BIT           NOT NULL,
        [UpholsteryFabric]        VARCHAR(30)   NOT NULL,
        [UpholsteryFrame]         VARCHAR(30)   NOT NULL,
        [Discontinued]            BIT           NOT NULL,
        [DiscoDate]               DATE          NULL,
        [ItemIsMarketInfo]        BIT           NOT NULL,
        [ItemDead]                BIT           NOT NULL,
        [Excl]                    BIT           NOT NULL,
        [KeyItem]                 BIT           NOT NULL,
        [ShowInPrBk]              BIT           NOT NULL,
        [DrwChgDate]              DATETIME2(6)  NULL,
        [InstrChgDate]            DATETIME2(6)  NULL,
        [AddedByUser]                    VARCHAR(30)   NULL,
        [DateAdded]                    DATETIME2(6)  NULL,
        [ChangeByUser]                    VARCHAR(30)   NULL,
        [DateChange]                    DATETIME2(6)  NULL,
        [ActiveRecord]                   CHAR(1)       NOT NULL,
        [Market]                  VARCHAR(10)   NOT NULL,
        [MasterGrpCode]           VARCHAR(10)   NOT NULL,
        [GeneralColor]            VARCHAR(10)   NOT NULL,
        [DarkLight]               VARCHAR(10)   NOT NULL,
        [StdMaterial]             VARCHAR(10)   NOT NULL,
        [StdFinFeature]           VARCHAR(10)   NOT NULL,
        [ShowroomVisual]          VARCHAR(45)   NOT NULL,
        [QtyInBox]                NUMERIC(4)    NULL,
        [TrackingPiece]           BIT           NOT NULL,
        [LeatherMatch]            BIT           NOT NULL,
        [Fobarc]                  DECIMAL(8, 2) NOT NULL,
        [IntroImage]              VARCHAR(50)   NOT NULL,
        [PhotoLastModified]       DATETIME2(6)  NULL,
        [ExclusiveComment]        VARCHAR(60)   NOT NULL,
        [ItemCodeID]              INT           NOT NULL,
        [Status]                  CHAR(1)       NOT NULL,
        [ConsumerDescription]     VARCHAR(100)  NOT NULL,
        [PackageCode]             BIT           NULL,
        [Description]             VARCHAR(30)   NULL,
        [GeneralDescription]      VARCHAR(40)   NULL,
        [Gdescd]                  INT           NULL,
        [QtyPerCarton]            INT           NULL,
        [Nbseat]                  DECIMAL(5, 2) NOT NULL,
        [PrimarySite]             CHAR(3)       NOT NULL,
        [ImportDomesticCode]      CHAR(1)       NOT NULL,
        [RDNo]                    VARCHAR(15)   NOT NULL,
        [PromoDescription]        VARCHAR(100)  NOT NULL,
        [DataUser]                VARCHAR(250)  NOT NULL,
        [ReleasedDate]            DATETIME2(6)  NULL,
        [ItemTypeDesc]            VARCHAR(25)   NOT NULL,
        [Release]                 BIT           NOT NULL,
        [ItemWhs]                 VARCHAR(30)   NOT NULL,
        [UPCCode]                 DECIMAL(10)   NULL,
        [PreviousStatus]          CHAR(1)       NULL,
        [ItemStatusChangeDate]    DATE          NULL,
        [MFGWarrantyNumberOfDays] INT           NOT NULL,
        [UPCPrefix]               DECIMAL(1)    NULL,
        [UPCCheckDigit]           DECIMAL(1)    NULL,
        [RetailTypeID]            INT           NULL,
        [ColorID]                 INT           NOT NULL,
        [EngDivID]                INT           NOT NULL,
        [IsARVRReady]             BIT           NOT NULL,
        [MerchGridOverridePhoto]  VARCHAR(50)   NOT NULL,
        [RetailBrandNameID]       INT           NOT NULL,
        [ManufacturerSKU]         VARCHAR(15)   NOT NULL,
        [AssemblyTime]            INT           NULL
    );

---    LOCATION = N'/MasterData/ProductKnowledge/ItemMaster/GBL_ProductKnowledge_tbl_Item.snappy.parquet',
---    FILE_FORMAT = [ParquetFileFormatSnappy],
---    REJECT_TYPE = VALUE,
