CREATE TABLE [ProductKnowledge].[Item]
    (
        [ItemSKU]                          VARCHAR(15)   NOT NULL,
        [Description]                      VARCHAR(30)   NOT NULL,
        [Class]                            CHAR(4)       NOT NULL,
        [Style]                            CHAR(3)       NOT NULL,
        [StandardCost]                     DECIMAL(9, 3) NOT NULL,
        [StandardPrice]                    DECIMAL(8, 2) NOT NULL,
        [StatusCode]                       CHAR(1)       NOT NULL,
        [Weight]                           DECIMAL(7, 3) NOT NULL,
        [Cubes]                            DECIMAL(5, 2) NOT NULL,
        [SalesClass]                       CHAR(2)       NOT NULL,
        [NumberOfSeats]                    DECIMAL(5, 2) NOT NULL,
        [AtpItemNumber]                    VARCHAR(15)   NOT NULL,
        [CommissionClass]                  CHAR(2)       NOT NULL,
        [DiscountClass]                    CHAR(2)       NOT NULL,
        [FreightClass]                     CHAR(2)       NOT NULL,
        [WidthMetric]                      NUMERIC(7, 2) NOT NULL,
        [WidthInches]                      NUMERIC(7, 2) NOT NULL,
        [HeightMetric]                     NUMERIC(7, 2) NOT NULL,
        [HeightInches]                     NUMERIC(7, 2) NOT NULL,
        [DepthMetric]                      NUMERIC(7, 2) NOT NULL,
        [DepthInches]                      NUMERIC(7, 2) NOT NULL,
        [ItemStatusChangeDate]             DATETIME2(6)  NULL,
        [PreviousStatus]                   CHAR(1)       NOT NULL,
        [GroupCode]                        VARCHAR(10)   NOT NULL,
        [GeneralDescriptionCode]           SMALLINT      NOT NULL,
        [OtherDimensionInches]             DECIMAL(6, 2) NOT NULL,
        [DivisionCode]                     CHAR(1)       NOT NULL,
        [QuantityPerCarton]                INT       NOT NULL,
        [GroupCodeLength]                  SMALLINT      NOT NULL,
        [SalesCategory]                    CHAR(3)       NOT NULL,
        [BlockCode]                        CHAR(5)       NOT NULL,
        [UPCPrefix]                        NUMERIC(1)    NOT NULL,
        [UPCCode]                          NUMERIC(10)   NOT NULL,
        [UPCCheckDigit]                    NUMERIC(1)    NOT NULL,
        [UnitOfMeasure]                    CHAR(2)       NOT NULL,
        [HTSNumber]                        VARCHAR(10)   NOT NULL,
        [ItemTypeCode]                     CHAR(1)       NOT NULL,
        [ImportDomestic]                   CHAR(1)       NOT NULL,
        [CountryOfOrigin]                  CHAR(5)       NOT NULL,
        [LastChangedDate]                  DATETIME2(6)  NULL,
        [GTINCode]                         VARCHAR(14)   NOT NULL,
        [SeriesCode]                       VARCHAR(16)   NOT NULL,
        [Dimension]                        VARCHAR(50)   NOT NULL,
        [Color]                            VARCHAR(50)   NOT NULL,
        [FinishShade]                      VARCHAR(10)   NOT NULL,
        [Features]                         VARCHAR(1000) NOT NULL,
        [WebsiteActiveCode]                BIT           NOT NULL,
        [IntroductionMarket]               VARCHAR(10)   NOT NULL,
        [IntroductionImage]                VARCHAR(50)   NOT NULL,
        [Image]                            VARCHAR(50)   NOT NULL,
        [ImageModifiedDate]                DATETIME2(6)  NULL,
        [PartsDrawing]                     VARCHAR(35)   NOT NULL,
        [PartsDrawingModifiedDate]         DATETIME2(6)  NULL,
        [AssemblyInstructions]             VARCHAR(35)   NOT NULL,
        [AssemblyInstructionsModifiedDate] DATETIME2(6)  NULL,
        [MechanismDrawing]                 VARCHAR(30)   NOT NULL,
        [DiscontinuedStatus]               BIT           NOT NULL,
        [DiscontinuedDate]                 DATETIME2(6)  NULL,
        [DeadItem]                         BIT           NOT NULL,
        [ExclusiveItem]                    BIT           NOT NULL,
        [ExclusiveComment]                 VARCHAR(60)   NOT NULL,
        [KeyItem]                          BIT           NOT NULL,
        [QuantityInBox]                    NUMERIC(2)    NOT NULL,
        [TrackingItem]                     BIT           NOT NULL,
        [LeatherMatch]                     BIT           NOT NULL,
        [FobarcPrice]                      DECIMAL(8, 2) NOT NULL,
        [ItemCodeID]                       INT           NOT NULL,
        [ManufacturerSKU]                  VARCHAR(35)   NOT NULL,
        [PurchaseItemNumber]               VARCHAR(15)   NOT NULL,
        [ProfitItemID]                     VARCHAR(12)   NOT NULL,
        [Vendor]                           CHAR(8)       NOT NULL,
        [OrderMultiple]                    SMALLINT      NOT NULL,
        [SetTableView]                     VARCHAR(3)    NOT NULL,
        [FriendlyDescription]              VARCHAR(200)  NOT NULL,
        [commaudit]                        BIT           NOT NULL,
        [ActiveRecord]                     VARCHAR(1)    NOT NULL,
        [AddedByUser]                      VARCHAR(30)   NULL,
        [DateAdded]                        DATETIME2(6)  NULL,
        [ChangeByUser]                     VARCHAR(30)   NULL,
        [DateChange]                       DATETIME2(6)  NULL,
        [GeneralDescription]               VARCHAR(40)   NOT NULL,
        [ConsumerDescription]              VARCHAR(200)  NOT NULL,
        [ConsumerStyle]                    VARCHAR(64)   NOT NULL,
        [PackageCode]                      BIT           NOT NULL,
        [GoodBetterBest]                   VARCHAR(6)    NOT NULL,
        [CommonCarrier_ITMUC1B]            CHAR(1)       NOT NULL,
        [ExpressService_ITMUC1A]           CHAR(1)       NOT NULL,
        [DeliverInPackage]                 BIT           NOT NULL
    );

--  DATA_SOURCE = [AzureStorageGen2a],
-- LOCATION = N'/MasterData/ProductKnowledge/Item/GBL_ProductKnowledge_tblItem.snappy.parquet',
-- FILE_FORMAT = [ParquetFileFormatSnappy],

