CREATE TABLE [CostAccounting_Enh].[AFI_ADH_OutBill_PreviousWeek_Historical] (
    [Trip Number]                                    INT             NULL,
    [Warehouse]                                      VARCHAR (5)     NULL,
    [TripType]                                       VARCHAR (50)    NULL,
    [Fiscal_WeekEnding]                              DATE            NULL,
    [FiscalMonthYearName]                            VARCHAR (20)    NULL,
    [Fiscal Year Period]                             INT             NULL,
    [Account]                                        VARCHAR (20)    NULL,
    [Shipto]                                         VARCHAR (20)    NULL,
    [Account And Shipto Number]                      VARCHAR (100)   NULL,
    [Customer Name]                                  VARCHAR (100)   NULL,
    [Reporting Business Type]                        VARCHAR (20)    NULL,
    [Freight Code]                                   VARCHAR (50)    NULL,
    [Freight Code Description]                       VARCHAR (50)    NULL,
    [AFI Freight Code]                               VARCHAR (50)    NULL,
    [Route Zone]                                     VARCHAR (10)    NULL,
    [Ext_LineItemFreight]                            DECIMAL (16, 8) NULL,
    [Ext_CommAdjFreight]                             DECIMAL (16, 8) NULL,
    [SpcCharge_Freight]                              DECIMAL (16, 8) NULL,
    [Total_AFIFreight_Revenue]                       DECIMAL (16, 8) NULL,
    [AFI Outbound Freight Exp from ADS Billing]      DECIMAL (16, 8) NULL,
    [AFI Outbound Freight Exp from ADL Billing]      DECIMAL (16, 8) NULL,
    [Flag_ADH_Responsible]                           VARCHAR (10)    NULL,
    [ADS_Region]                                     VARCHAR (20)    NULL,
    [Billing_Static_Date]                            VARCHAR (100)   NULL,
    [Flag_Container]                                 VARCHAR (20)    NULL,
    [Flag_Invoiced]                                  VARCHAR (20)    NULL,
    [Flag_Multi_TripType]                            VARCHAR (10)    NULL,
    [Invoice_Week_ADS]                               DATE            NULL,
    [Invoice_Week_ADL]                               VARCHAR (20)    NULL,
    [Current_Accrual_Week_ADS]                       VARCHAR (10)    NULL,
    [Current ADS Outbound In Transit Accrual]        VARCHAR (20)    NULL,
    [First_Accrual_Week_ADS]                         VARCHAR (15)    NULL,
    [Previous ADS Outbound In Transit Accrual]       VARCHAR (20)    NULL,
    [Current_Accrual_Week_ADL]                       VARCHAR (15)    NULL,
    [Current ADL Outbound In Transit Accrual]        VARCHAR (15)    NULL,
    [First_Accrual_Week_ADL]                         VARCHAR (15)    NULL,
    [Previous ADL Outbound In Transit Accrual]       VARCHAR (15)    NULL,
    [ADH - Data Source]                              VARCHAR (40)    NULL,
    [TransactionalBilling - Freight Solution Reason] VARCHAR (35)    NULL,
    [TransactionalBilling - Fuel Solution Reason]    VARCHAR (35)    NULL,
    [AFI_Unit]                                       VARCHAR (15)    NULL,
    [AFI_Nature]                                     VARCHAR (15)    NULL
)
