
CREATE TABLE [CostAccounting_Enh].[AFI_ADH_OutBill_CurrentNotInvoiced]
(
	[Trip Number] [int] NULL,
	[Warehouse] [char](5) NULL,
	[TripType] [varchar](100) NULL,
	[Fiscal_WeekEnding] [date] NULL,
	[FiscalMonthYearName] [varchar](50) NULL,
	[FiscalMonthEnding] [date] NULL,
	[Fiscal Year Period] [int] NULL,
	[Account] [varchar](20) NULL,
	[Shipto] [varchar](20) NULL,
	[Account And Shipto Number] [varchar](30) NULL,
	[Customer Name] [varchar](100) NULL,
	[Reporting Business Type] [varchar](100) NULL,
	[Freight Code] [varchar](10) NULL,
	[Freight Code Description] [varchar](500) NULL,
	[AFI Freight Code] [varchar](500) NULL,
	[Route Zone] [varchar](10) NULL,
	[Ext_LineItemFreight] [decimal](20, 10) NULL,
	[Ext_CommAdjFreight] [decimal](20, 10) NULL,
	[SpcCharge_Freight] [decimal](20, 10) NULL,
	[Total_AFIFreight_Revenue] [decimal](20, 10) NULL,
	[AFI Outbound Freight Exp from ADS Billing] [decimal](20, 10) NULL,
	[AFI Outbound Freight Exp from ADL Billing] [decimal](20, 10) NULL,
	[Flag_ADH_Responsible] [varchar](10) NULL,
	[Billing_Static_Date] [date] NULL,
	[ADS_Region] [varchar](50) NULL,
	[Flag_Container] [varchar](100) NULL,
	[Flag_Invoiced] [varchar](100) NULL,
	[Flag_Multi_TripType] [varchar](10) NULL,
	[Invoice_Week_ADS] [date] NULL,
	[Invoice_Week_ADL] [date] NULL,
	[Current_Accrual_Week_ADS] [varchar](20) NULL,
	[Current ADS Outbound In Transit Accrual] [decimal](20, 10) NULL,
	[First_Accrual_Week_ADS] [date] NULL,
	[Previous ADS Outbound In Transit Accrual] [decimal](20, 10) NULL,
	[Current_Accrual_Week_ADL] [date] NULL,
	[Current ADL Outbound In Transit Accrual] [decimal](20, 10) NULL,
	[First_Accrual_Week_ADL] [date] NULL,
	[Previous ADL Outbound In Transit Accrual] [decimal](20, 10) NULL,
	[ADH - Data Source] [varchar](500) NULL,
	[TransactionalBilling - Freight Solution Reason] [varchar](50) NULL,
	[TransactionalBilling - Fuel Solution Reason] [varchar](500) NULL,
	[ME Accrual] [decimal](20, 10) NULL,
	[ME Non-Accrual] [decimal](20, 10) NULL,
	[ME Non-Accrual - Fiscal Month] [varchar](50) NULL,
	[BRKASH] [varchar](50) NULL,
	[ASH_TripFreightRevenueAllocation] [decimal](20, 10) NULL,
	[ASH_TripFuelRevenueAllocation] [decimal](20, 10) NULL,
	[ASH_CalculatedFreightVariance] [decimal](20, 10) NULL,
	[ASH_CalculatedFuelVariance] [decimal](20, 10) NULL,
	[BRK_AFI Transfer Freight Credit] [decimal](20, 10) NULL,
	[BRK_AFI Transfer Fuel Credit] [decimal](20, 10) NULL,
	[BRK_Proj Carrier Exp] [decimal](20, 10) NULL,
	[BRK_AFI(Freight+Fuel+CommAdj)] [decimal](20, 10) NULL,
	[ADS_Unit] [varchar](100) NULL,
	[ADS_Nature_Freight] [varchar](10) NULL,
	[ADS_Nature_Fuel] [varchar](10) NULL,
	[AFI_Unit] [varchar](10) NULL,
	[AFI_Nature] [varchar](10) NULL,
	[UniqueKey] [varchar](500) NULL
)
