---create schema PartyContacts_Wrk AUTHORIZATION dbo

create view [PartyContacts_Wrk].[v_AddressMaster]
as
SELECT [paaAddressID]
      ,[paaAddress1]
      ,[paaAddress2]
      ,[paaAddress3]
      ,cast([paaAddress4] as varchar(35)) as [paaAddress4]
      ,[paaAddress5]
      ,[paaCity]
      ,[paaState]
      ,[paaCountry]
      ,[paaGeocodeLatitude]
      ,[paaGeocodeLongitude]
      ,[paaZipCode]
      ,[paaCountyCode]
      ,[paaCustomsIDNumber]
      ,[paaGeocodeAccuracy]
      ,[paaTranscomCityCode]
      ,[paaDirections]
      ,[paaCrossStreet]
      ,[paaGeocodeVerificationDate]
      ,[paaTimeZone]
      ,[paaGeocodeType]
      ,[paaMsa_Fips]
      ,cast([paaShortAddress1] as varchar(25)) as [paaShortAddress1]    
      ,cast([paaShortAddress2] as varchar(25)) as [paaShortAddress2]   
      ,[paaShortAddress3]      
      ,[paaShortAddress4]    
      ,[paaShortCity]  
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
  FROM [$(Source_Data)].[Wholesale_PartyContacts].[AddressMaster]
GO

