create view PartyContacts_Wrk.v_ProfileDetail
as
SELECT  [cpdCompanyNo]
      ,[cpdPartnerNo]
      ,[cpdPartnerShipTo]
      ,[cpdTransactionCode]
      ,[cpdTransactionDirection]
      ,[cpdAllShipTos]
      ,[cpdTransactionType]
      ,[cpdTransactionStyle]
      ,[cpdEDITradingPartner]
      ,[cpdEDIVersion]
      ,[cpdEDISend997]
      ,[cpdEDITransactionProgram]
      ,[cpdTransactionFormatID]
      ,[cpdUseDeliveryTable]
      ,[cpdDeliveryTypeID]
      ,[cpdSourceAddress]
      ,[cpdSendFunctionalAck]
      ,[cpdPartnerTypeID]
      ,[cpdLanguageCode]
      ,[cpdXRefType]
      ,[cpdDestinationAddress]
      ,[cpdEffectiveFrom]
      ,[cpdEffectiveTo]
      ,[acrec]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[cpdAuthorizedBy]
      ,[cpdChangedBy]
      ,[cpdChangedDate]
      ,[cpdPartyID]
      ,[cpdLocationID]
      ,[cpdLastUserChanged]
  FROM [$(Source_Data)].[Wholesale_PartyContacts].[ProfileDetail]
GO

