CREATE TABLE [MasterData_Retail].[SiteMaster] (

	[OperationalStatus] varchar(20) NULL, 
	[AccountNumber] int NULL, 
	[ShipToNum] varchar(4) NULL, 
	[AcctShipTo] varchar(15) NULL, 
	[SourceId] varchar(25) NULL, 
	[RetailSystemNumber] varchar(4) NULL, 
	[RetailSystemNumberReference] varchar(4) NULL, 
	[ErpDatabaseName] varchar(10) NULL, 
	[TimeZone] varchar(9) NULL, 
	[SiteName] varchar(45) NULL, 
	[SiteCountryCode] varchar(2) NULL, 
	[FLegalEntityId] int NULL, 
	[OperationID] int NULL, 
	[ProfitCenter] int NULL, 
	[Name] varchar(70) NULL, 
	[LicContact] varchar(12) NULL, 
	[CompanyCode] varchar(3) NULL, 
	[StoreAddress] varchar(50) NULL, 
	[City] varchar(30) NULL, 
	[State] varchar(4) NULL, 
	[Zip] varchar(5) NULL, 
	[Country] varchar(3) NULL, 
	[MigratedtoStoris] varchar(3) NULL, 
	[MigrationDate] date NULL, 
	[isCompStore] int NULL, 
	[isEnterpriseStore] int NULL, 
	[market] varchar(45) NULL, 
	[isEcomFulfiller] int NULL, 
	[financialUnitNumber] int NULL
);