CREATE TABLE [MasterData_Retail].[Warehouse] (

	[account] varchar(7) NULL, 
	[erpSystemName] varchar(19) NULL, 
	[id] varchar(22) NULL, 
	[isActive] varchar(5) NULL, 
	[isEcomFulfiller] varchar(5) NULL, 
	[market] varchar(16) NULL, 
	[name] varchar(45) NULL, 
	[numberOfDockDoors] varchar(3) NULL, 
	[operationId] varchar(3) NULL, 
	[operationName] varchar(12) NULL, 
	[primaryPhone] varchar(15) NULL, 
	[profitCenter] varchar(3) NULL, 
	[region] varchar(12) NULL, 
	[retailSystemNumber] varchar(3) NULL, 
	[shipTo] varchar(4) NULL, 
	[siteType] varchar(9) NULL, 
	[timezoneUtcOffset] varchar(9) NULL, 
	[warehouseAreaSqFt] int NULL, 
	[streetAddress] varchar(29) NULL, 
	[addressLine2] varchar(45) NULL, 
	[city] varchar(16) NULL, 
	[stateOrProvinceCode] varchar(2) NULL, 
	[zipOrPostalCode] varchar(10) NULL, 
	[countryCode] varchar(3) NULL, 
	[latitude] decimal(9,6) NULL, 
	[longitude] decimal(11,6) NULL, 
	[dacid] varchar(10) NULL, 
	[googleId] varchar(10) NULL, 
	[financialUnitNumber] varchar(5) NULL, 
	[companyCode] varchar(23) NULL, 
	[ownerId] varchar(3) NULL, 
	[ownerName] varchar(58) NULL, 
	[primaryContactName] varchar(35) NULL, 
	[dmaId] varchar(3) NULL, 
	[dmaName] varchar(34) NULL
);