CREATE TABLE [Transportation].[TripHeader]
    (
        [UpdateStatus]        CHAR(1)        NOT NULL,
        [ErrorProgram]        VARCHAR(10)    NOT NULL,
        [TripNumber]          NUMERIC(5)     NOT NULL,
        [Warehouse]           CHAR(3)        NOT NULL,
        [TripStatus]          CHAR(1)        NOT NULL,
        [PreviousTripStatus]  CHAR(1)        NOT NULL,
        [ContainerID]         VARCHAR(9)     NOT NULL,
        [ContainerNumber]     CHAR(6)        NOT NULL,
        [CrewName]            VARCHAR(10)    NOT NULL,
        [ProNumber]           VARCHAR(30)    NOT NULL,
        [SCAC_Code]           CHAR(4)        NOT NULL,
        [DockDoor]            NUMERIC(4)     NOT NULL,
        [DropNumber]          NUMERIC(2)     NOT NULL,
        [LastCompletedDrop]   NUMERIC(2)     NOT NULL,
        [SealNumber1]         VARCHAR(10)    NOT NULL,
        [SealNumber2]         VARCHAR(10)    NOT NULL,
        [SealNumber3]         VARCHAR(10)    NOT NULL,
        [SealNumber4]         VARCHAR(10)    NOT NULL,
        [TotalPieceCount]     NUMERIC(6)     NOT NULL,
        [TotalDropCount]      NUMERIC(2)     NOT NULL,
        [TotalCubes]          NUMERIC(10, 2) NOT NULL,
        [TotalWeight]         NUMERIC(10, 2) NOT NULL,
        [TotalScans]          NUMERIC(5)     NOT NULL,
        [TotalNoTagScans]     NUMERIC(5)     NOT NULL,
        [TotalScanExceptions] NUMERIC(5)     NOT NULL,
        [AddUser]             VARCHAR(10)    NOT NULL,
        [AddDate]             DATE           NULL, --- NUMERIC(8)     NOT NULL,
        [AddTime]             NUMERIC(6)     NOT NULL,
        [AddProgram]          VARCHAR(10)    NOT NULL,
        [ReleaseUser]         VARCHAR(10)    NOT NULL,
        [ReleaseDate]         DATE           NULL, --NUMERIC(8)     NOT NULL,
        [ReleasedTime]        NUMERIC(6)     NOT NULL,
        [ReleaseProgram]      VARCHAR(10)    NOT NULL,
        [ReopenByUser]        VARCHAR(10)    NOT NULL,
        [ReopenDate]          DATE           NULL, --NUMERIC(8)     NOT NULL,
        [ReopenTime]          NUMERIC(6)     NOT NULL,
        [ReopenProgram]       VARCHAR(10)    NOT NULL,
        [CloseByUser]         VARCHAR(10)    NOT NULL,
        [CloseDate]           DATE,                -- NUMERIC(8)     NOT NULL,
        [CloseTime]           NUMERIC(6)     NOT NULL,
        [CloseProgram]        VARCHAR(10)    NOT NULL,
        [DeleteUser]          VARCHAR(10)    NOT NULL,
        [DeleteDate]          DATE           NULL, --NUMERIC(8)     NOT NULL,
        [Deleteime]           NUMERIC(6)     NOT NULL,
        [DeleteProgram]       VARCHAR(10)    NOT NULL,
        [StartUser]           VARCHAR(10)    NOT NULL,
        [StartDate]           DATE           NULL, --NUMERIC(8)     NOT NULL,
        [StartTime]           NUMERIC(6)     NOT NULL,
        [StartProgram]        VARCHAR(10)    NOT NULL,
        [EndUser]             VARCHAR(10)    NOT NULL,
        [EndDate]             DATE           NULL, -- NUMERIC(8)     NOT NULL,
        [EndTime]             NUMERIC(6)     NOT NULL,
        [EndProgram]          VARCHAR(10)    NOT NULL,
        [ChangedUser]         VARCHAR(10)    NOT NULL,
        [ChangedDate]         DATE           NULL,   -- NUMERIC(8)  --  NOT NULL,
        [ChangedTime]         NUMERIC(6)     NOT NULL,
        [ChangedProgram]      VARCHAR(10)    NOT NULL,
        [ChangedType]         CHAR(1)        NOT NULL
    );
--   DATA_SOURCE = [AzureStorageGen2a],
--    LOCATION = N'/Wholesale/CODIS/BTTRIPH/AFI_Codis_BTTRIPH.snappy.parquet',
--    FILE_FORMAT = [ParquetFileFormatSnappy],

