CREATE TABLE [ProductKnowledge].[ItemDimensions]
    (
        [ItemSKU]        VARCHAR(15)   NULL,
        [HeightM]        DECIMAL(7, 2) NULL,
        [WidthM]         DECIMAL(7, 2) NULL,
        [DepthM]         DECIMAL(7, 2) NULL,
        [HeightCartonM]  DECIMAL(7, 2) NULL,
        [WidthCartonM]   DECIMAL(7, 2) NULL,
        [DepthCartonM]   DECIMAL(7, 2) NULL,
        [DimOtherM]      DECIMAL(7, 2) NULL,
        [HeightIn]       DECIMAL(7, 2) NULL,
        [WidthIn]        DECIMAL(7, 2) NULL,
        [DepthIn]        DECIMAL(7, 2) NULL,
        [HeightCartonIn] DECIMAL(7, 2) NULL,
        [WidthCartonIn]  DECIMAL(7, 2) NULL,
        [DepthCartonIn]  DECIMAL(7, 2) NULL,
        [DimOtherIn]     DECIMAL(7, 2) NULL,
        [DimString]      VARCHAR(25)   NULL,
        [DimConfirmed]   BIT           NULL,
        [DimChgDate1]    DATETIME2(6)  NULL,
        [DimChgBy1]      VARCHAR(30)   NULL,
        [DimChgDate2]    DATETIME2(6)  NULL,
        [DimChgBy2]      VARCHAR(30)   NULL,
        [DimChgDate3]    DATETIME2(6)  NULL,
        [DimChgBy3]      VARCHAR(30)   NULL,
        [Comment1]       VARCHAR(30)   NULL,
        [Comment2]       VARCHAR(30)   NULL,
        [Comment3]       VARCHAR(30)   NULL,
        [TimesChgd]      DECIMAL(3)    NULL,
        [AddedByUser]           VARCHAR(30)   NULL,
        [DateAdded]           DATETIME2(6)  NULL,
        [ChangeByUser]           VARCHAR(30)   NULL,
        [DateChange]           DATETIME2(6)  NULL,
        [Cubes]          DECIMAL(5, 2) NULL,
        [CubesM]         DECIMAL(5, 2) NULL,
        [Weight]         DECIMAL(7, 3) NULL,
        [WeightM]        DECIMAL(7, 3) NULL,
        [SupWeight]      DECIMAL(7, 3) NULL,
        [SupWeightM]     DECIMAL(7, 3) NULL,
        [UnitOfMeasure]  VARCHAR(2)    NULL,
        [WeightUOM]      CHAR(2)       NULL,
        [SupWeightUOM]   CHAR(2)       NULL,
        [ShipWidhtIn]    DECIMAL(7, 2) NOT NULL,
        [ShipDepthIn]    DECIMAL(7, 2) NOT NULL,
        [ShipHeightIn]   DECIMAL(7, 2) NOT NULL,
        [ShipWidhtM]     DECIMAL(7, 2) NOT NULL,
        [ShipDepthM]     DECIMAL(7, 2) NOT NULL,
        [ShipHeightM]    DECIMAL(7, 2) NOT NULL
    );
-- DATA_SOURCE = [AzureStorageGen2a],
-- LOCATION = N'/MasterData/ProductKnowledge/ItemDimensions/GBL_ProductKnowledge_tblItemDimensions.snappy.parquet',
-- FILE_FORMAT = [ParquetFileFormatSnappy],
