CREATE TABLE  [ProductKnowledge].[ItemSeries]
    (
        [Showroom]               VARCHAR(25)   NULL,
        [Grouping]               SMALLINT      NULL,
        [SeriesName]             VARCHAR(100)  NULL,
        [SeriesCode]              VARCHAR(16)   NULL,
        [Style]                  VARCHAR(60)   NULL,
        [Description]            VARCHAR(2000) NULL,
        [Features]               VARCHAR(2000) NULL,
        [Retail]                 DECIMAL(12,2)         NULL,
        [Active]                 BIT           NULL,
        [Division]               VARCHAR(25)   NULL,
        [Date_Archived]          DATETIME2(6)  NULL,
        [Ad_Template]            VARCHAR(35)   NULL,
        [News_Template]          VARCHAR(35)   NULL,
        [Discontinued]           BIT           NULL,
        [IsMarketInfo]           BIT           NULL,
        [IsNewSeries]            BIT           NULL,
        [IsFeaturedItem]         BIT           NULL,
        [DiscoDate]              DATETIME2(6)  NULL,
        [SeriesDead]             BIT           NULL,
        [Excl]                   BIT           NULL,
        [Old_Style]              VARCHAR(60)   NULL,
        [Knockout]               VARCHAR(20)   NULL,
        [ChildStyleCode]         CHAR(3)       NULL,
        [CodeLen]                SMALLINT      NULL,
        [ShowInPrBk]             BIT           NULL,
        [AddedByUser]                   VARCHAR(30)   NULL,
        [DateAdded]                   DATETIME2(6)  NULL,
        [ChangeByUser]                   VARCHAR(30)   NULL,
        [DateChange]                   DATETIME2(6)  NULL,
        [ActiveRecord]                  CHAR(1)       NULL,
        [LeatherMatchItem]       BIT           NULL,
        [RepairKit]              VARCHAR(35)   NULL,
        [RepairKitDate]          DATETIME2(6)  NULL,
        [ExclusiveComment]       VARCHAR(60)   NULL,
        [SeriesColor]            VARCHAR(60)   NULL,
        [Status]                 CHAR(1)       NULL,
        [RetailSalesCategory]    INT           NULL,
        [ColorID]                INT           NULL,
        [DivisionCode]           CHAR(1)       NULL,
        [SupplierDirectShipOnly] BIT           NULL
    );

--- DATA_SOURCE = [AzureStorageGen2a],
--- LOCATION = N'/MasterData/ProductKnowledge/ItemSeries/GBL_ProductKnowledge_tbl_Series.snappy.parquet',
--- FILE_FORMAT = [ParquetFileFormatSnappy],
