CREATE TABLE [MasterData_HR_UKG_DSG_Wrk].[PersonDetails] (

	[additionalName1] varchar(50) NULL, 
	[additionalName2] varchar(50) NULL, 
	[companyId] varchar(10) NULL, 
	[dateChanged] datetime2(6) NULL, 
	[dateCreated] datetime2(6) NULL, 
	[emailAddress] varchar(100) NULL, 
	[emailAddressAlternate] varchar(100) NULL, 
	[employeeId] varchar(20) NULL, 
	[firstName] varchar(50) NULL, 
	[formerName] varchar(50) NULL, 
	[lastName] varchar(50) NULL, 
	[lastNameNotSameAsSSCard] varchar(10) NULL, 
	[middleName] varchar(50) NULL, 
	[nameFormer] varchar(50) NULL, 
	[namePrefix] varchar(10) NULL, 
	[nameSuffix] varchar(10) NULL, 
	[personId] varchar(50) NULL, 
	[preferredName] varchar(50) NULL, 
	[userName] varchar(50) NULL, 
	[key] int NULL, 
	[dwLoadDateTime] datetime2(6) NULL, 
	[dataSource] varchar(10) NULL, 
	[Generation] varchar(30) NULL
);