CREATE TABLE [MasterData_Retail_Wrk].[SalespersonUPBoardHistoryDSG] (

	[StoreID] char(5) NULL, 
	[SalespersonID] int NULL, 
	[SalespersonName] varchar(50) NULL, 
	[SalespersonUsername] varchar(10) NULL, 
	[StatusStartTime] datetime2(6) NULL, 
	[StatusEndTime] datetime2(6) NULL, 
	[StatusStartDate] date NULL, 
	[StatusStartHour] int NULL, 
	[RecordedUpDate] date NULL, 
	[RecordedUpHour] int NULL, 
	[SPUB_StatusID] int NULL, 
	[GuestName] varchar(75) NULL, 
	[isCountedAsUP] int NULL, 
	[isSale] int NULL, 
	[StrikeCount] int NULL, 
	[Shot] int NULL, 
	[FinApp] int NULL, 
	[ReasonManagerAddWith] varchar(300) NULL, 
	[ReasonManagerAddSP] varchar(300) NULL, 
	[ReasonManagerAddUps] varchar(300) NULL, 
	[ReasonManagerRemoveSP] varchar(300) NULL, 
	[ManagerCoachingNotes] varchar(500) NULL, 
	[ManagerCoachingNotesTime] datetime2(6) NULL, 
	[IsStrike] bit NULL, 
	[IsStrikeOut] bit NULL, 
	[ConsecutiveStrikes] int NULL, 
	[ConsecutiveStrikeOuts] int NULL
);