CREATE TABLE [MasterData_RealEstate].[RentOption] (

	[Company] varchar(128) NULL, 
	[Tree2_Bottom_Group] varchar(128) NULL, 
	[File_ID] varchar(128) NULL, 
	[File_Name] varchar(255) NULL, 
	[Address] varchar(255) NULL, 
	[City] varchar(50) NULL, 
	[State] varchar(20) NULL, 
	[Record_Type] varchar(50) NULL, 
	[Subtype] varchar(50) NULL, 
	[Uom_Type] varchar(10) NULL, 
	[Size] decimal(10,2) NULL, 
	[Commencement] date NULL, 
	[Expiration] date NULL, 
	[Type] varchar(50) NULL, 
	[Category] varchar(50) NULL, 
	[Comment] varchar(3500) NULL, 
	[Currency_Adj] varchar(10) NULL, 
	[Base_Rent] decimal(18,2) NULL, 
	[CAM_Amount] decimal(18,2) NULL, 
	[Insurance] decimal(18,2) NULL, 
	[RE_Tax] decimal(18,2) NULL, 
	[HVAC_Overtime_Amount] decimal(18,2) NULL, 
	[Other_Amount] decimal(18,2) NULL, 
	[Signage_Amount] decimal(18,2) NULL, 
	[Trash_Amount] decimal(18,2) NULL, 
	[Utilities_Amount] decimal(18,2) NULL
);