CREATE TABLE [CustomerOrders_AFI].[ExtendedOrder] ---EXTORD
    (
        [OrderNumber]          CHAR(7)       NULL,
        [RequestDate]          DATE          NULL,  --Decimal
        [OrderUseFlags]        VARCHAR(10)   NULL,
        [OrderArrivalCode]     CHAR(2)       NULL,
        [AdvertisingSpeical]   CHAR(1)       NULL,
        [SetCount]             DECIMAL(3)    NULL,
        [OrderReference]       CHAR(7)       NULL,
        [OrderLinkNumber]      DECIMAL(6)    NULL,
        [CustomerServiceRepID] DECIMAL(5)    NULL,
        [Country]              CHAR(3)       NULL,
        [State]                CHAR(2)       NULL,
        [OrderType1]           CHAR(1)       NULL,
        [OrderType2]           CHAR(1)       NULL,
        [OrderType3]           CHAR(1)       NULL,
        [OrderType4]           CHAR(1)       NULL,
        [MaintenanceCount]     DECIMAL(3)    NULL,
        [RouteFreezeDate]      DATE          NULL,  --Decimal
        [ShiptoName]           VARCHAR(25)   NULL,
        [Warehouse]            CHAR(3)       NULL,
        [CustomerNumber]       CHAR(8)       NOT NULL,
        [ShiptoNumber]         CHAR(4)       NOT NULL,
        [OrderTakenDate]       DATE          NULL,
        [TripReferenceNumber]  DECIMAL(6, 0) NULL,
        [HoldDate]             DATE          NULL,
        [DropNumber]           DECIMAL(2, 0) NULL,
        [TripNumber]           DECIMAL(6, 0) NULL,
        [CreditReviewed]       CHAR(1)       NULL,
        [CheditCheckRequired]  CHAR(1)       NULL,
        [CreditApprovalNumber] VARCHAR(15)   NULL,
        [EnteredByUser]        VARCHAR(10)   NULL,
        [CreditHoldUser]       VARCHAR(10)   NULL,
        [TerritoryCode]        CHAR(2)       NULL,
        [Contact]              VARCHAR(25)   NULL,
        [PhonesNumber]         VARCHAR(20)   NULL,
        [ReferenceNumber]      DECIMAL(6, 0) NULL,
        [ShipRecievedCash]     CHAR(1)       NULL,
        [CreditApprovalDate]   DATE          NULL,
        [CreditOverrideFlag]   CHAR(1)       NULL,
        [CreditOverrideDate]   DATE          NULL,
        [CreditOverrideAnalyst]VARCHAR(10)   NULL,
        [DateContacted]        DATE          NULL,
        [ChangedByUser]        VARCHAR(10)   NULL,
        [DateChanged]          DATE          NULL,
        [TimeChanged]          DECIMAL(6, 0) NULL,
        [OrderType]            CHAR(3)       NULL,
        [CommissionCode]       CHAR(3)       NULL,
        [DiscountCode]         CHAR(3)       NULL,
        [PriceCode]            CHAR(6)       NULL,
        [FreightCode]          CHAR(3)       NULL,
        [ZipCode]              VARCHAR(10)   NULL,
        [AutoReleaseZonde]     CHAR(2)       NULL,
        [AutoReleaseSequence]  DECIMAL(2, 0) NULL,
        [AutoReleaseDate]      DATE          NULL,
        [PromotionNumber]      VARCHAR(10)   NULL
    );

-- DATA_SOURCE = [AzureStorageGen2a],
-- LOCATION = N'/Wholesale/codis_afi/ExtendedOrder/AFI_codis_afi_ExtendedOrder.snappy.parquet',
-- FILE_FORMAT = [ParquetFileFormatSnappy],




