CREATE TABLE [Wholesale_Purchasing_AFI].[EXTVNDR] (

	[VEND_NUM] char(8) NULL, 
	[ALT_NAME] varchar(35) NULL, 
	[ALT_FAX2] varchar(30) NULL, 
	[ALT_FAX3] varchar(30) NULL, 
	[VND_CODE] char(2) NULL, 
	[ISSUE_DYS] decimal(5,0) NULL, 
	[ACTIVE] decimal(1,0) NULL, 
	[LEAD_TIME] decimal(5,0) NULL, 
	[NXT_ORD#] decimal(9,0) NULL, 
	[DFT_CARRY] decimal(9,0) NULL, 
	[SUPPLIER] decimal(1,0) NULL, 
	[GEO_LAT] decimal(13,4) NULL, 
	[GEO_LONG] decimal(13,4) NULL, 
	[GEO_ACCUR] decimal(9,0) NULL, 
	[GEO_TYPE] char(1) NULL, 
	[EDI_FLAG] char(4) NULL, 
	[Alt_Addr1] varchar(40) NULL, 
	[Alt_Addr2] varchar(40) NULL, 
	[Alt_City] varchar(40) NULL, 
	[Alt_State] varchar(20) NULL, 
	[Alt_Zip] varchar(20) NULL, 
	[Alt_Cntry] char(3) NULL, 
	[Alt_Phone] varchar(30) NULL, 
	[Alt_Fax] varchar(30) NULL, 
	[Alt_Contct] varchar(30) NULL, 
	[Alt_Addr3] varchar(40) NULL, 
	[AshleySupplierFlow] char(1) NULL, 
	[ProductOrigin] char(1) NULL, 
	[InternationalCommercialTerms] char(3) NULL
);