CREATE TABLE [Wholesale_Codis_AFI].[OpenOrderConsumerAddress] (

	[CAOORDERNUMBER] varchar(8000) NULL, 
	[CAOSALESORDERNUMBER] varchar(8000) NULL, 
	[CAOSEQUENCE] decimal(38,18) NULL, 
	[CAOCONSUMERLASTNAME] varchar(8000) NULL, 
	[CAOCONSUMERFIRSTNAME] varchar(8000) NULL, 
	[CAOCONSUMERADDRESS1] varchar(8000) NULL, 
	[CAOCONSUMERADDRESS2] varchar(8000) NULL, 
	[CAOCONSUMERADDRESS3] varchar(8000) NULL, 
	[CAOCONSUMERADDRESS4] varchar(8000) NULL, 
	[CAOCONSUMERADDRESS5] varchar(8000) NULL, 
	[CAOCITY] varchar(8000) NULL, 
	[CAOSTATE] varchar(8000) NULL, 
	[CAOZIPCODE] varchar(8000) NULL, 
	[CAOCOUNTRY] varchar(8000) NULL
);