CREATE TABLE [Wholesale_Codis_AFI].[YAAJREL3] (

	[AdminDivisionId] varchar(10) NULL, 
	[NatureStructureId] varchar(10) NULL, 
	[NatureStructureName] varchar(26) NULL, 
	[ChildNatureAdminDiv] varchar(10) NULL, 
	[ChildNature] varchar(10) NULL, 
	[ChildNatureName] varchar(26) NULL, 
	[ChildNatureNameOverrde] varchar(40) NULL, 
	[NatureStructureLevelId] decimal(3,0) NULL, 
	[NatureStructureSequence] decimal(5,0) NULL, 
	[ParentNatureAdminDiv] varchar(10) NULL, 
	[ParentNature] varchar(10) NULL, 
	[ParentNatureName] varchar(26) NULL, 
	[NatureIntraTotalLevel] char(1) NULL, 
	[NatStrMbrStrFldHdg] decimal(7,0) NULL, 
	[StrValColHeadingOne] varchar(20) NULL, 
	[StrValColHeadingTwo] varchar(20) NULL, 
	[StrValColHeadingThree] varchar(20) NULL, 
	[StrValLeftHandText] varchar(40) NULL, 
	[StrTotColHeadingOne] varchar(20) NULL, 
	[StrTotLeftHandText] varchar(40) NULL, 
	[StrTotColHeadingTwo] varchar(20) NULL, 
	[StrTotColHeadingThree] varchar(20) NULL, 
	[RecordStatus] char(1) NULL, 
	[AuditStampRecordSts] decimal(11,0) NULL, 
	[AuditStampEntry] decimal(11,0) NULL, 
	[AuditStampLastChange] decimal(11,0) NULL, 
	[CreateDate] decimal(7,0) NULL, 
	[CreateTime] decimal(6,0) NULL, 
	[ChangeDate] decimal(7,0) NULL, 
	[ChangeTime] decimal(6,0) NULL, 
	[CreateUser] varchar(10) NULL, 
	[ChangeUser] varchar(10) NULL
);