CREATE TABLE [Wholesale_Quality_AFI_Wrk].[ReturnAllowanceHeader] (

	[Rahenterdate] char(8) NOT NULL, 
	[Rahentertime] char(6) NOT NULL, 
	[Rahpono] varchar(24) NOT NULL, 
	[Rahpodate] char(8) NOT NULL, 
	[Rahpopurpose] decimal(2,0) NOT NULL, 
	[Rahcompanyno] decimal(2,0) NOT NULL, 
	[Rahcustno] char(8) NOT NULL, 
	[Rahshipno] char(4) NOT NULL, 
	[Rahshipname] varchar(37) NOT NULL, 
	[Rahshipaddr1] varchar(37) NOT NULL, 
	[Rahshipaddr2] varchar(37) NOT NULL, 
	[Rahshipcity] varchar(37) NOT NULL, 
	[Rahshipstate] char(2) NOT NULL, 
	[Rahshipzip] varchar(12) NOT NULL, 
	[Rahwarehouse] char(3) NOT NULL, 
	[Rahbillname] varchar(37) NOT NULL, 
	[Rahbilladdr1] varchar(37) NOT NULL, 
	[Rahbilladdr2] varchar(37) NOT NULL, 
	[Rahbillcity] varchar(37) NOT NULL, 
	[Rahbillstate] char(2) NOT NULL, 
	[Rahbillzip] varchar(12) NOT NULL, 
	[Rahorddate] char(8) NOT NULL, 
	[Rahscheddelwk] char(8) NOT NULL, 
	[Rahreqdate] char(8) NOT NULL, 
	[Rahcontactname] varchar(52) NOT NULL, 
	[Rahcontactphone] varchar(22) NOT NULL, 
	[Rahmode] char(2) NOT NULL, 
	[Rahprojord] char(1) NOT NULL, 
	[Rahadvertising] char(1) NOT NULL, 
	[Rahordtype] char(1) NOT NULL, 
	[Rahrano] int NOT NULL, 
	[Rahinvno] int NOT NULL, 
	[Rahcreditcode] char(1) NOT NULL, 
	[Rahcrinvno] decimal(9,0) NOT NULL, 
	[Rahapplycd] char(1) NOT NULL, 
	[Rahaprvdny] char(1) NOT NULL, 
	[Rahproccd] char(1) NOT NULL, 
	[Rahprocdt] char(8) NOT NULL, 
	[Rahusername] varchar(22) NOT NULL, 
	[Rahvcbno] varchar(25) NOT NULL, 
	[Rahsubmitdate] datetime2(6) NULL, 
	[Rahaprvdnydate] datetime2(6) NULL, 
	[Rahenterdatetime] datetime2(6) NULL, 
	[Rahwitherrs] bit NOT NULL, 
	[Usra] varchar(32) NULL, 
	[Dtea] datetime2(6) NULL, 
	[Usrc] varchar(32) NULL, 
	[Dtec] datetime2(6) NULL, 
	[Rahchgusername] varchar(22) NULL, 
	[Rahdeniedresubmit] char(1) NOT NULL, 
	[Rahpendingemailsent] bit NOT NULL
);