CREATE TABLE [Wholesale_DemandPlanning].[DailySupplyPlanDetail] (

	[dspItem] varchar(15) NULL, 
	[dspWarehouse] char(3) NULL, 
	[dspDayOfEnding] datetime2(6) NULL, 
	[dspBeginingBalance] decimal(10,0) NULL, 
	[dspFirmDemands] decimal(10,0) NULL, 
	[dspNetForecast] decimal(10,0) NULL, 
	[dspFirmTransferOut] decimal(10,0) NULL, 
	[dspFirmProduction] decimal(10,0) NULL, 
	[dspFirmPurchaseOrders] decimal(10,0) NULL, 
	[dspInTransitTransferIn] decimal(10,0) NULL, 
	[dspOnOrderTransferIn] decimal(10,0) NULL, 
	[dspPlannedTransferIn] decimal(10,0) NULL, 
	[dspPlannedTransferOut] decimal(10,0) NULL, 
	[dspPlannedProduction] decimal(10,0) NULL, 
	[dspPlannedPurchaseOrders] decimal(10,0) NULL, 
	[dspTotalReceipts] decimal(10,0) NULL, 
	[dspShippableInventory] decimal(10,0) NULL, 
	[dspSafetyStock] decimal(10,0) NULL, 
	[dspMonthsOfSupply] decimal(10,2) NULL, 
	[dspResultantForecast] decimal(10,0) NULL, 
	[dspPromotionalLift] decimal(10,0) NULL, 
	[dspDemandFulfillment] decimal(10,0) NULL, 
	[dspWeeklyPromotionalLift] decimal(10,0) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL
);