CREATE TABLE [wholesale_productsourcing].[asnregulatorydata] (

	[ardASPONumber] varchar(8000) NULL, 
	[ardASItemNumber] varchar(8000) NULL, 
	[ardSerialStart] decimal(38,18) NULL, 
	[ardSerialEnd] decimal(38,18) NULL, 
	[ardFabricatorLotNumber] varchar(8000) NULL, 
	[ardFabricatorPONumber] varchar(8000) NULL, 
	[ardManufacturerName] varchar(8000) NULL, 
	[ardManufacturerLotNumber] varchar(8000) NULL, 
	[ardComplianceLevel] varchar(8000) NULL, 
	[ardTPCNumber] varchar(8000) NULL, 
	[ardContainerID] int NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[ardCertifiedQty] decimal(38,18) NULL, 
	[ardFabricationDate] datetime2(6) NULL, 
	[ardManufactureDate] datetime2(6) NULL, 
	[ardCertificationNumber] varchar(8000) NULL, 
	[ardItemSequence] int NULL, 
	[ardFabricatorPartType] varchar(8000) NULL, 
	[ardAshleyLotNumber] varchar(8000) NULL, 
	[ardFabricatorPartThickness] varchar(8000) NULL, 
	[ardTransactionID] varchar(8000) NULL, 
	[ardAshleyRegistrationNumber] int NULL, 
	[ardInvalidData] int NULL
);

