CREATE TABLE [wholesale_productsourcing].[customsitemclassification] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[cicItemOrSetNumber] varchar(8000) NULL, 
	[cicHTSNumber] varchar(8000) NULL, 
	[cicPreClass] varchar(8000) NULL, 
	[cicReportingA] varchar(8000) NULL, 
	[cicReportingB] varchar(8000) NULL, 
	[cicReportingC] varchar(8000) NULL, 
	[cicReportingQtyA] decimal(38,18) NULL, 
	[cicReportingQtyB] decimal(38,18) NULL, 
	[cicReportingQtyC] decimal(38,18) NULL, 
	[cicBindingRuling] varchar(8000) NULL, 
	[cicQuotaCategory] varchar(8000) NULL, 
	[cicQuotaCategoryApplied] bit NULL, 
	[cicCustomsDescription] varchar(8000) NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[cicLastReviewed] datetime2(6) NULL, 
	[cicIgnoreRptA] bit NULL, 
	[cicIgnoreRptB] bit NULL, 
	[cicIgnoreRptC] bit NULL, 
	[cicManualEntryRequired] bit NULL, 
	[cicManualEntryReasonCode] int NULL
);

