CREATE TABLE [Security].[SalesProfile]
    (
        [MHS_Name]         CHAR(8)        NULL,
        [MSM_Name]         VARCHAR(10)    NULL,
        [SalesCode]        CHAR(5)        NULL,
        [Descrip]          VARCHAR(50)    NULL,
        [Active]           BIT            NULL,
        [Assyst]           BIT            NULL,
        [Hist_Data]        BIT            NULL,
        [Reg_Cnt]          INT        NULL,
        [Days_Hist]        SMALLINT       NULL,
        [Memo]             VARCHAR(500)   NULL,
        [Type]             INT        NULL,
        [Machine]          CHAR(1)        NULL,
        [Sum_Curr]         BIT            NULL,
        [Sum_Hist]         BIT            NULL,
        [Slave]            BIT            NULL,
        [Sum_Period]       CHAR(2)        NULL,
        [Model]            VARCHAR(20)    NULL,
        [Chip]             CHAR(6)        NULL,
        [Diskspace]        SMALLINT       NULL,
        [Available]        SMALLINT       NULL,
        [Windows]          BIT            NULL,
        [Dos]              DECIMAL(13, 3) NULL, --- FLOAT(53) 
        [Ram]              INT        NULL,
        [Dblspace]         BIT            NULL,
        [Laptop]           BIT            NULL,
        [Trained]          CHAR(5)        NULL,
        [Days]             INT        NULL,
        [Comm]             BIT            NULL,
        [Defect]           BIT            NULL,
        [Act_Comm]         BIT            NULL,
        [Ashmil]           CHAR(1)        NULL,
        [Market]           CHAR(2)        NULL,
        [Comm_Hist]        BIT            NULL,
        [Raactive]         BIT            NULL,
        [Day1]             BIT            NULL,
        [Day2]             BIT            NULL,
        [Day3]             BIT            NULL,
        [Day4]             BIT            NULL,
        [Day5]             BIT            NULL,
        [Day6]             BIT            NULL,
        [Day7]             BIT            NULL,
        [Priority]         INT        NULL,
        [Prodline]         VARCHAR(10)    NULL,
        [Pricelist]        BIT            NULL,
        [Whse]             VARCHAR(50)    NULL,
        [Chain]            BIT            NULL,
        [Internet]         BIT            NULL,
        [Email]            VARCHAR(50)    NULL,
        [Password]         VARCHAR(12)    NULL,
        [Franchise]        BIT            NULL,
        [Timestamp_Column] VARCHAR(40)    NULL,
        [OutlookMail]      BIT            NULL,
        [SendType]         CHAR(1)        NULL,
        [NodeId]           CHAR(8)        NULL,
        [EmailAddress]     VARCHAR(125)   NULL,
        [Install]          BIT            NULL,
        [AddedByUser]             VARCHAR(30)    NULL,
        [DateAdded]             DATETIME2(6)   NULL, --DATETIME2 (7)
        [ChangeByUser]             VARCHAR(30)    NULL,
        [DateChange]             DATETIME2(6)   NULL, --DATETIME2 (7)
        [ActiveRecord]            CHAR(1)        NULL
    );

--  DATA_SOURCE = [AzureStorageGen2a],
--  LOCATION = N'/MasterData/Security/SalesProfile/AFI_Sales_tblSecuritySalesProfile.snappy.parquet',
--  FILE_FORMAT = [ParquetFileFormatSnappy],


