CREATE TABLE [Security].[UserProfile]
    (
        [Id]                        INT          NULL,
        [UserLogin]                 VARCHAR(25)  NULL,
        [Description]               VARCHAR(50)  NULL,
        [Password]                  VARCHAR(50)  NULL,
        [Client_Type]               VARCHAR(50)  NULL,
        [Address]                   VARCHAR(35)  NULL,
        [City]                      VARCHAR(35)  NULL,
        [State]                     CHAR(2)      NULL,
        [Zip]                       VARCHAR(10)  NULL,
        [Country]                   CHAR(8)      NULL,
        [Email]                     VARCHAR(100) NULL,
        [Phone]                     VARCHAR(25)  NULL,
        [Cellular]                  VARCHAR(25)  NULL,
        [Fax]                       VARCHAR(25)  NULL,
        [Photo]                     VARCHAR(50)  NULL,
        [Security_Millennium]       BIT          NULL,
        [Security_Casegoods]        BIT          NULL,
        [Security_Upholstery]       BIT          NULL,
        [Security_Lady]             BIT          NULL,
        [Security_Successories]     BIT          NULL,
        [Security_Bedding]          BIT          NULL,
        [Security_Ashtonyork]       BIT          NULL,
        [Security_Sales]            BIT          NULL,
        [Security_HR]               BIT          NULL,
        [Security_Customer_Service] BIT          NULL,
        [Security_Transportation]   BIT          NULL,
        [Security_Engineering]      BIT          NULL,
        [Security_Imports]          BIT          NULL,
        [Security_International]    BIT          NULL,
        [Security_Executive]        BIT          NULL,
        [Security_IS]               BIT          NULL,
        [Security_IT]               BIT          NULL,
        [Security_Manufacturing]    BIT          NULL,
        [Security_Dealer]           BIT          NULL,
        [Security_Homestore]        BIT          NULL,
        [Security_Other]            BIT          NULL,
        [Security_MillSigDesign]    BIT          NULL,
        [Security_UphSigDesign]     BIT          NULL,
        [Security_CaseSigDesign]    BIT          NULL,
        [MHS]                       VARCHAR(8)   NULL,
        [Type]                      INT      NULL,
        [VHS]                       VARCHAR(16)  NULL,
        [FirstName]                 VARCHAR(25)  NULL,
        [LastName]                  VARCHAR(35)  NULL,
        [CertificateNumber]         VARCHAR(50)  NULL,
        [DownloadType]              CHAR(1)      NULL,
        [SupervisorNo]              INT          NULL,
        [StatFlag]                  CHAR(2)      NULL,
        [DefaultCusno]              CHAR(8)      NULL,
        [DefaultShpno]              CHAR(4)      NULL,
        [EmpNo]                     VARCHAR(9)   NULL,
        [ADSCode]                   VARCHAR(25)  NULL,
        [AddedByUser]                         VARCHAR(40)  NULL,
        [DateAdded]                         DATETIME2(6) NULL, -- DATETIME2(6)
        [ChangeByUser]                         VARCHAR(40)  NULL,
        [DateChange]                         DATETIME2(6) NULL, -- DATETIME2(6)
        [ActiveRecord]                        CHAR(1)      NULL,
        [Security_Motion]           BIT          NULL,
        [Security_MotionSigDesign]  BIT          NULL,
        [Security_BedSigDesign]     BIT          NULL,
        [Security_AccSigDesign]     BIT          NULL,
        [Security_OutdoorSigDesign] BIT          NULL,
        [Security_Accessory]        BIT          NULL
    );

--   DATA_SOURCE = [AzureStorageGen2a],
--   LOCATION = N'/MasterData/Security/UserProfile/GBL_Sales_tblUserProfile.snappy.parquet',
--    FILE_FORMAT = [ParquetFileFormatSnappy],

