CREATE TABLE [Wholesale_Codis_Wrk].[codatan] (

	[JOENTL] decimal(10,0) NULL, 
	[JOSEQN] decimal(10,0) NULL, 
	[JOCODE] char(1) NULL, 
	[JOENTT] char(2) NULL, 
	[JODATE] char(6) NULL, 
	[JOTIME] decimal(10,0) NULL, 
	[JOJOB] char(10) NULL, 
	[JOUSER] char(10) NULL, 
	[JONBR] decimal(10,0) NULL, 
	[JOPGM] char(10) NULL, 
	[JOOBJ] char(10) NULL, 
	[JOLIB] char(10) NULL, 
	[JOMBR] char(10) NULL, 
	[JOCTRR] decimal(10,0) NULL, 
	[JOFLAG] char(1) NULL, 
	[JOCCID] decimal(10,0) NULL, 
	[JOUSPF] char(10) NULL, 
	[JOSYNM] char(8) NULL, 
	[JOINCDAT] char(1) NULL, 
	[JOMINESD] char(1) NULL, 
	[JORES] char(18) NULL, 
	[Rcdcd] char(2) NOT NULL, 
	[Ordno] char(7) NOT NULL, 
	[Itnbr] char(15) NOT NULL, 
	[House] char(3) NOT NULL, 
	[Itmsq] decimal(7,0) NOT NULL, 
	[Whslc] char(7) NOT NULL, 
	[Unitc] decimal(19,8) NOT NULL, 
	[Itdsc] char(30) NOT NULL, 
	[Noinv] decimal(1,0) NOT NULL, 
	[Itcls] char(4) NOT NULL, 
	[Coqty] decimal(10,3) NOT NULL, 
	[Qtysh] decimal(10,3) NOT NULL, 
	[Qtybo] decimal(10,3) NOT NULL, 
	[Unmsr] char(2) NOT NULL, 
	[Extwo] decimal(1,0) NOT NULL, 
	[Extwt] decimal(11,3) NOT NULL, 
	[Negpr] decimal(15,3) NOT NULL, 
	[Untpo] decimal(1,0) NOT NULL, 
	[Price] decimal(15,3) NOT NULL, 
	[Updmc] decimal(1,0) NOT NULL, 
	[Updmp] decimal(5,3) NOT NULL, 
	[Qpdpt] decimal(5,3) NOT NULL, 
	[Islpo] decimal(1,0) NOT NULL, 
	[Islpr] decimal(15,3) NOT NULL, 
	[Insao] decimal(1,0) NOT NULL, 
	[Insam] decimal(13,2) NOT NULL, 
	[Ittyp] char(1) NOT NULL, 
	[Weght] decimal(7,3) NOT NULL, 
	[Crcod] char(1) NOT NULL, 
	[Moflg] char(1) NOT NULL, 
	[Saflg] decimal(1,0) NOT NULL, 
	[Mrdte] decimal(8,0) NOT NULL, 
	[Lpmno] char(1) NOT NULL, 
	[Iaflg] decimal(1,0) NOT NULL, 
	[Pmult] decimal(7,3) NOT NULL, 
	[Ptrcd] decimal(1,0) NOT NULL, 
	[Lstum] char(2) NOT NULL, 
	[Orflg] decimal(1,0) NOT NULL, 
	[Iscpr] decimal(17,7) NOT NULL, 
	[Corel] char(1) NOT NULL, 
	[Rqidt] decimal(8,0) NOT NULL, 
	[Rdovr] decimal(1,0) NOT NULL, 
	[Mfidt] decimal(8,0) NOT NULL, 
	[Mdovr] decimal(1,0) NOT NULL, 
	[Mordn] char(7) NOT NULL, 
	[Itdsi] char(30) NOT NULL, 
	[Expad] char(3) NOT NULL, 
	[Negrh] decimal(15,3) NOT NULL, 
	[Prich] decimal(15,3) NOT NULL, 
	[Islph] decimal(15,3) NOT NULL, 
	[Insah] decimal(13,2) NOT NULL, 
	[Iscph] decimal(17,7) NOT NULL, 
	[Pradj] decimal(5,2) NOT NULL, 
	[Txind] char(3) NOT NULL, 
	[Ccusno] decimal(8,0) NOT NULL, 
	[Cshpno] char(4) NOT NULL, 
	[Lslddtch] date NOT NULL, 
	[Prvlddte] date NOT NULL, 
	[Prlddtch] date NOT NULL, 
	[Earlddt] date NOT NULL, 
	[Latlddt] date NOT NULL, 
	[Numlddtchg] decimal(3,0) NOT NULL, 
	[Itmltlddt] char(1) NOT NULL, 
	[Itmprcsts] char(1) NOT NULL, 
	[Arrvlmode] char(2) NOT NULL, 
	[Markfor] char(50) NOT NULL
);