CREATE TABLE [manufacturing_inventory_afi].[taginvd] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[TDTAG#] bigint NULL, 
	[TDSKU#] bigint NULL, 
	[TDITEM] varchar(8000) NULL, 
	[TDREC#] bigint NULL, 
	[TDAPO#] varchar(8000) NULL, 
	[TDRLSD] decimal(38,18) NULL, 
	[TDPDAT] decimal(38,18) NULL, 
	[TDTSTS] varchar(8000) NULL, 
	[TDSORD] bigint NULL, 
	[TDSORL] bigint NULL, 
	[TDAINV] varchar(8000) NULL, 
	[TDTTYP] varchar(8000) NULL, 
	[TDDHOW] varchar(8000) NULL, 
	[TDIVC#] bigint NULL, 
	[TDSEQ#] bigint NULL, 
	[TDTRAK] varchar(8000) NULL, 
	[TDTQTY] bigint NULL, 
	[TD#PRT] bigint NULL, 
	[TDREG#] bigint NULL, 
	[TDWHSE] varchar(8000) NULL, 
	[TDAREA] varchar(8000) NULL, 
	[TDASLE] bigint NULL, 
	[TDSEC] varchar(8000) NULL, 
	[TDTIER] bigint NULL, 
	[TDMDAT] decimal(38,18) NULL, 
	[TDMTME] decimal(38,18) NULL, 
	[TDMUSR] varchar(8000) NULL, 
	[TDMPGM] varchar(8000) NULL, 
	[TDVDAT] decimal(38,18) NULL, 
	[TDPDAT_DATE] datetime2(6) NULL, 
	[TDMDAT_DATE] datetime2(6) NULL, 
	[TDVDAT_DATE] datetime2(6) NULL
);

