CREATE TABLE [Wholesale_DemandPlanning_AFI].[DemandInventory] (

	[dinItem] varchar(15) NOT NULL, 
	[dinWarehouse] char(3) NOT NULL, 
	[dinFiscalMonth] decimal(6,0) NOT NULL, 
	[dinInvPlanningVendor] char(8) NOT NULL, 
	[dinDemandPlanner] varchar(40) NOT NULL, 
	[dinSafetyStock] decimal(9,0) NOT NULL, 
	[dinBuildQuantity] decimal(9,0) NOT NULL, 
	[dinSnapshot] datetime2(6) NULL, 
	[dinOMinSafetyStock] decimal(9,0) NULL, 
	[dinOMaxSafetyStock] decimal(9,0) NULL, 
	[dinOSafetyStock] decimal(9,0) NULL, 
	[dinMakeBuyCode] char(1) NULL, 
	[dinPrimaryVendorNumber] char(40) NULL, 
	[dinPrimaryVendorName] varchar(40) NULL, 
	[dinPrimaryVendorSplit] varchar(40) NULL, 
	[dinSecondaryVendorNumber] char(40) NULL, 
	[dinSecondaryVendorName] varchar(40) NULL, 
	[dinSecondaryVendorSplit] varchar(40) NULL, 
	[dinInvPlanning4thChoice] varchar(36) NULL, 
	[dinInvPlanning1stChoice] varchar(36) NULL, 
	[dinSource1] varchar(40) NULL, 
	[dinOnHandQuantity] numeric(9,0) NULL, 
	[dinOrderQuantity] numeric(9,0) NULL, 
	[dinAlternanteABCCode1] char(1) NULL, 
	[dinAlternanteABCCode3] char(1) NULL, 
	[dinInventoryPlanningABCCode] char(1) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[dinReplenishmentLeadTime] numeric(3,0) NULL
);