CREATE TABLE [Wholesale_DemandPlanning_AFI].[DemandForecast] (

	[dfcItem] varchar(15) NOT NULL, 
	[dfcWarehouse] char(3) NOT NULL, 
	[dfcFiscalMonth] decimal(6,0) NOT NULL, 
	[dfcMainPiece] varchar(40) NOT NULL, 
	[dfcCollectiveClass] varchar(40) NOT NULL, 
	[dfcResultantForecast] decimal(9,0) NULL, 
	[dfcPromotionalLift] decimal(9,0) NULL, 
	[dfcForcedForecast] decimal(9,0) NOT NULL, 
	[dfcValidDemandMonths] decimal(3,0) NOT NULL, 
	[dfcSnapshot] datetime2(6) NULL, 
	[dfcPermComptQty] numeric(11,2) NOT NULL, 
	[dfcUsr25Text] varchar(40) NULL, 
	[dfcUsr32Text] varchar(40) NULL, 
	[dfcFCSTTypeCode] char(1) NOT NULL, 
	[dfcDerivedFCSTID] varchar(120) NULL, 
	[dfcDerivedFCSTFctr] numeric(5,3) NOT NULL, 
	[dfcOrderFutureQty] numeric(9,0) NOT NULL, 
	[dfcMgmtCode] char(1) NOT NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[DfcCustomerGroups] varchar(100) NULL
);