CREATE TABLE [PowerBI_Retail].[OpenOrder_FactOrderDetail] (

	[OrderID] varchar(50) NULL, 
	[OrderDate] date NULL, 
	[LineStatus] varchar(50) NULL, 
	[ItemID] int NULL, 
	[ProductID] varchar(50) NULL, 
	[ProductKey] int NULL, 
	[UnitSellPrice] decimal(10,5) NULL, 
	[DeliveryDate] datetime2(0) NULL, 
	[DeliveryStatus] varchar(50) NULL, 
	[DeliveryType] varchar(50) NULL, 
	[Description] varchar(100) NULL, 
	[QtyOrdered] int NULL, 
	[QtyCommitted] int NULL, 
	[QtyDelivered] int NULL, 
	[OrderFulfillmentID] varchar(250) NULL, 
	[ShpLocationID] varchar(20) NULL, 
	[StkLocationID] varchar(20) NULL, 
	[RouteCodeID] varchar(50) NULL, 
	[DeliveryVolume] decimal(10,5) NULL, 
	[TransRoute] varchar(50) NULL, 
	[DeliveryContactStatusID] varchar(100) NULL, 
	[DeliveryContactDate] date NULL, 
	[FulfillmentDate] date NULL, 
	[Filled] varchar(5) NULL, 
	[Qtytrans] int NULL, 
	[Dfilled] varchar(5) NULL
);