CREATE TABLE [MasterData_Ent].[CustomerInfo] (
    [CustomerID]                 VARCHAR (50)    NOT NULL,
    [FirstName]                  VARCHAR (100)   NULL,
    [LastName]                   VARCHAR (100)   NULL,
    [FullName]                   VARCHAR (150)   NULL,
    [HomePhone]                  VARCHAR (15)    NULL,
    [CellPhone]                  VARCHAR (15)    NULL,
    [WorkPhone]                  VARCHAR (15)    NULL,
    [WorkPhoneExt]               VARCHAR (15)    NULL,
    [Address1]                   VARCHAR (300)   NULL,
    [Address2]                   VARCHAR (300)   NULL,
    [City]                       VARCHAR (50)    NULL,
    [State]                      VARCHAR (50)    NULL,
    [PostalCode]                 VARCHAR (50)    NOT NULL,
    [EmailAddress]               VARCHAR (50)    NULL,
    [CustomerClass]              VARCHAR (20)    NULL,
    [StoreID]                    VARCHAR (20)    NOT NULL,
    [OpenDate]                   DATETIME2 (3)   NULL,
    [MembershipActive]           BIT             NULL,
    [MembershipCancellationDate] DATE            NULL,
    [MembershipCard]             VARCHAR (20)    NULL,
    [MembershipFee]              DECIMAL (18, 4) NULL,
    [MembershipLinkedCustomerID] VARCHAR (50)    NULL,
    [MembershipPaymentTypeID]    VARCHAR (50)    NULL,
    [MembershipProductID]        VARCHAR (50)    NULL,
    [MembershipRenewal]          BIT             NULL,
    [MembershipRenewDate]        DATE            NULL,
    [MembershipReviewDate]       DATE            NULL,
    [MembershipStartDate]        DATE            NULL,
    [MembershipStoreID]          INT             NULL,
    [MembershipTerms]            INT             NULL,
    [IsRetail]                   INT             NULL,
    [IsActive]                   BIT             NULL,
    [DateCreated]                DATETIME2 (3)   NULL,
    [DateChanged]                DATETIME2 (3)   NULL
);