CREATE TABLE [wholesale_productsourcing_afi].[qiscorrectionpost] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[id] int NULL, 
	[review_gate] varchar(8000) NULL, 
	[originator] varchar(8000) NULL, 
	[vendor_number] varchar(8000) NULL, 
	[issue_details] varchar(8000) NULL, 
	[assign_to] varchar(8000) NULL, 
	[priority] varchar(8000) NULL, 
	[due_date] datetime2(6) NULL, 
	[response_expectation] varchar(8000) NULL, 
	[management_type] varchar(8000) NULL, 
	[project_level] varchar(8000) NULL, 
	[category] varchar(8000) NULL, 
	[correction] varchar(8000) NULL, 
	[proposed_actions] varchar(8000) NULL, 
	[deleted] smallint NULL, 
	[status] varchar(8000) NULL, 
	[last_modified_by] varchar(8000) NULL, 
	[last_modified_on] datetime2(6) NULL, 
	[created_by] varchar(8000) NULL, 
	[created_on] datetime2(6) NULL, 
	[image_append] varchar(8000) NULL, 
	[image_remove] varchar(8000) NULL, 
	[actual_close_date] datetime2(6) NULL, 
	[project_link] varchar(8000) NULL, 
	[post_type] smallint NULL, 
	[template_type] smallint NULL, 
	[sop_require] smallint NULL, 
	[follow_up_date] datetime2(6) NULL, 
	[is_created_qie] smallint NULL
);

