CREATE TABLE [wholesale_productsourcing_afi].[spsdiscussion] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[id] int NULL, 
	[group_id] int NULL, 
	[sample_id] int NULL, 
	[market_id] int NULL, 
	[auth_id] int NULL, 
	[auth_name] varchar(8000) NULL, 
	[topic] varchar(8000) NULL, 
	[discussion_type] smallint NULL, 
	[created] int NULL, 
	[post_id] int NULL, 
	[vendor_no] varchar(8000) NULL, 
	[vendor_name] varchar(8000) NULL, 
	[item_no] varchar(8000) NULL, 
	[group_no] varchar(8000) NULL, 
	[sample_no] varchar(8000) NULL, 
	[remark] varchar(8000) NULL, 
	[is_cancel] smallint NULL, 
	[ref_table_id] int NULL, 
	[ori_type] smallint NULL, 
	[auto_generate] smallint NULL, 
	[order_by] int NULL, 
	[deleted] smallint NULL, 
	[created_on] datetime2(6) NULL, 
	[created_by] int NULL, 
	[last_modified_on] datetime2(6) NULL, 
	[last_modified_by] int NULL
);

