CREATE TABLE [wholesale_productsourcing_afi].[vvscarblacey] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[id] int NULL, 
	[sku_id] int NULL, 
	[pro_id] int NULL, 
	[item_id] int NULL, 
	[vendor_id] int NULL, 
	[wood_type] varchar(8000) NULL, 
	[other_description] varchar(8000) NULL, 
	[coo] varchar(8000) NULL, 
	[volume] decimal(38,18) NULL, 
	[density] decimal(38,18) NULL, 
	[thickness] decimal(38,18) NULL, 
	[location] varchar(8000) NULL, 
	[carb_type_code] varchar(8000) NULL, 
	[carb_image] varchar(8000) NULL, 
	[common_name] varchar(8000) NULL, 
	[genus] varchar(8000) NULL, 
	[species] varchar(8000) NULL, 
	[cut_type] varchar(8000) NULL, 
	[lacey_image] varchar(8000) NULL, 
	[changed] varchar(8000) NULL, 
	[created_by] varchar(8000) NULL, 
	[created_on] datetime2(6) NULL, 
	[updater] varchar(8000) NULL, 
	[update_time] datetime2(6) NULL, 
	[deleted] smallint NULL, 
	[vendor_confirm] smallint NULL, 
	[type] varchar(8000) NULL, 
	[supplier] varchar(8000) NULL, 
	[patent_number] varchar(8000) NULL
);

