Create TABLE [Wholesale_SalesHistory_AFI].[InvoiceSerialNumberManufactured](
	[InvoiceDate] [date] NULL,
	[InvoiceNumber] [numeric](9, 0) NULL,
	[SerialNumber] [varchar](15) NULL,
	[OrderNumber] [varchar](10) NULL,
	[ItemNumber] [varchar](15) NULL,
	[ItemSeqNumber] [numeric](7, 0) NULL,
	[MfgOrderNumber] [varchar](10) NULL,
	[CustomerNumber] [char](8) NULL,
	[ShiptoNumber] [char](4) NULL,
	[DropNumber] [numeric](2, 0) NULL,
	[WhereMade] [char](5) NULL,
	[UserGroup] [varchar](10) NULL,
	[MfgDate] [date] NULL,
	[ScanName] [varchar](15) NULL,
	[LoadDate] [date] NULL,
	[TruckNumber] [varchar](15) NULL,
	[Carrier] [varchar](100) NULL,
	[Warehouse] [char](3) NULL,
	[Department] [char](5) NULL,
	[WorkCenter] [char](5) NULL,
	[Group] [numeric](5, 0) NULL,
	[Shift] [numeric](1, 0) NULL,
	[SupervisorNumber] [numeric](5, 0) NULL,
	[AATWarehouse] [char](3) NULL
);