CREATE TABLE [Wholesale_SalesHistory_AFI].[ordaudh] (

	[OrderNo] char(7) NULL, 
	[WhseNo] char(3) NULL, 
	[CustomerNo] numeric(8,0) NULL, 
	[ShipToNo] char(4) NULL, 
	[PONumber] varchar(30) NULL, 
	[OrderDate] numeric(8,0) NULL, 
	[CustServAgentId] numeric(5,0) NULL, 
	[TransType] char(1) NULL, 
	[CancellationUserid] varchar(10) NULL, 
	[CancellationDate] numeric(8,0) NULL, 
	[CancellationReason] char(2) NULL, 
	[AckPrintFlag] char(1) NULL, 
	[AckEDIFlag] char(1) NULL, 
	[AckPrintDate] numeric(8,0) NULL, 
	[AckEDIDate] numeric(8,0) NULL, 
	[InvoiceCompleteFlg] char(1) NULL, 
	[InvoiceCompleteDte] numeric(8,0) NULL, 
	[LastActivityDate] numeric(8,0) NULL, 
	[ArrivalMode] char(2) NULL, 
	[OrderTypeCategryOne] char(1) NULL, 
	[OrderTypeCategryTwo] char(1) NULL, 
	[OrderTypeCategryThree] char(1) NULL, 
	[OrderTypeCategryFour] char(1) NULL, 
	[OrderTakenDate] numeric(8,0) NULL, 
	[InitialOrderValue] numeric(13,2) NULL, 
	[OfflineDate] numeric(8,0) NULL, 
	[AutoPosted] char(1) NULL, 
	[PostedFrom] char(1) NULL, 
	[Status] numeric(2,0) NULL, 
	[CancellationNumber] numeric(13,0) NULL, 
	[ReqDateatCancel] date NULL, 
	[OrderEnteredBy] varchar(10) NULL
);