CREATE TABLE [MasterData_Retail].[GLPost] (

	[Operation] char(3) NULL, 
	[GLPostID] varchar(50) NULL, 
	[SourceID] varchar(50) NULL, 
	[RecStatus] char(5) NULL, 
	[CompanyID] varchar(50) NULL, 
	[GLSourceID] varchar(50) NULL, 
	[TransDate] date NULL, 
	[StorisTransWeek] int NULL, 
	[FisWeek] int NULL, 
	[FisPeriod] int NULL, 
	[FisYear] int NULL, 
	[FisYearPeriod] int NULL, 
	[StaffID] varchar(50) NULL, 
	[StorisCreateDateTime] datetime2(6) NULL, 
	[Comment] varchar(512) NULL, 
	[Status] varchar(20) NULL, 
	[ReversingBatch] varchar(50) NULL, 
	[ReferenceSourceType] varchar(50) NULL, 
	[ReferenceSourceID] varchar(50) NULL, 
	[TPAPostDateTime] datetime2(6) NULL, 
	[TPAErrorFlag] bit NULL, 
	[TPAErrorMsg] varchar(max) NULL, 
	[TPASummaryBatchKey] varchar(50) NULL, 
	[Base_GLPostID] varchar(50) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[LastBatchID] int NULL
);