CREATE TABLE [Masterdata_Finance].[ResidentHomeWeeklyOrderBacklog] (

	[ItemID] varchar(50) NULL, 
	[EOWdate] date NULL, 
	[Channel] varchar(50) NULL, 
	[Geo] varchar(10) NULL, 
	[Company] varchar(25) NULL, 
	[ShortID] int NULL, 
	[Brand] varchar(50) NULL, 
	[Status] varchar(50) NULL, 
	[ProductName] varchar(500) NULL, 
	[WebsiteShippingTimeTo] int NULL, 
	[WebsiteShippingTimeFrom] int NULL, 
	[ShipmentSku] varchar(50) NULL, 
	[ShipmentCreated] varchar(50) NULL, 
	[ShipmentStatusFullfill] varchar(50) NULL, 
	[Wasdelivered] varchar(50) NULL, 
	[Ordertype] varchar(50) NULL, 
	[EstimatedShippedTS] datetime2(6) NULL, 
	[DeliveredTS] datetime2(6) NULL, 
	[CarrierSelectedTS] datetime2(6) NULL, 
	[ShipmentCreatedTransitBDays] float NULL, 
	[AdminPrice_NoTax] decimal(10,4) NULL, 
	[ItemPrice_IncludeTax] decimal(10,4) NULL, 
	[ItemTax] decimal(10,4) NULL, 
	[IsWgsOrder] varchar(50) NULL, 
	[IsPrice0] varchar(50) NULL, 
	[ProductCost] decimal(10,4) NULL, 
	[ShippingCost] decimal(10,4) NULL
);