CREATE TABLE [Wholesale_Invoicing_AFI_wrk].[TSCIIN] (

	[Joentl] decimal(10,0) NULL, 
	[Joseqn] decimal(10,0) NULL, 
	[Jocode] char(1) NULL, 
	[Joentt] char(2) NULL, 
	[Jodate] char(6) NULL, 
	[Jotime] decimal(10,0) NULL, 
	[Jojob] char(10) NULL, 
	[Jouser] char(10) NULL, 
	[Jonbr] decimal(10,0) NULL, 
	[Jopgm] char(10) NULL, 
	[Joobj] char(10) NULL, 
	[Jolib] char(10) NULL, 
	[Jombr] char(10) NULL, 
	[Joctrr] decimal(10,0) NULL, 
	[Joflag] char(1) NULL, 
	[Joccid] decimal(10,0) NULL, 
	[Jouspf] char(10) NULL, 
	[Josynm] char(8) NULL, 
	[Joincdat] char(1) NULL, 
	[Jominesd] char(1) NULL, 
	[Jores] char(18) NULL, 
	[Ciinvr] decimal(9,0) NULL, 
	[Ciorno] char(7) NULL, 
	[Ciitno] varchar(17) NULL, 
	[Ciitsq] decimal(7,0) NULL, 
	[Ciicsq] decimal(7,0) NULL, 
	[Ciicm1] varchar(35) NULL, 
	[Ciicm2] varchar(35) NULL, 
	[Ciicm3] varchar(35) NULL, 
	[Ciintp] decimal(1,0) NULL
);