CREATE TABLE [SalesHistory_AFI].[InvoiceDetail]
    (
        [CustomerNumber]                     CHAR(8)        NOT NULL,
        [InvoiceNumber]                      DECIMAL(9)     NOT NULL,
        [ItemSKU]                            VARCHAR(15)    NOT NULL,
        [ItemSequence]                       DECIMAL(7)     NULL,
        [QuantityShipped]                    DECIMAL(7)     NOT NULL,
        [InvoiceAmount]                      DECIMAL(9, 2)  NOT NULL,
        [OrderNumber]                        VARCHAR(10)    NOT NULL,
        [ShiptoNumber]                       CHAR(4)        NOT NULL,
        [QuantityOrdered]                    DECIMAL(7)     NOT NULL,
        [QuantityBackOrdered]                DECIMAL(7)     NOT NULL,
        [CreditCode]                         CHAR(1)        NOT NULL,
        [Warehouse]                          CHAR(3)        NOT NULL,
        [BilltoSalesman]                     CHAR(5)        NOT NULL,
        [ShiptoSalesman]                     CHAR(5)        NOT NULL,
        [Discount]                           DECIMAL(9, 2)  NOT NULL,
        [PriceAdjustment]                    DECIMAL(9, 2)  NOT NULL,
        [PostingMonth]                       CHAR(2)        NOT NULL,
        [Freight]                            DECIMAL(9, 2)  NOT NULL,
        [Price]                              DECIMAL(9, 2)  NOT NULL,
        [ItemClass]                          CHAR(4)        NOT NULL,
        [ExtendedInvoiceNumber]              VARCHAR(9)     NULL,
        [PurchaseOrder]                      VARCHAR(25)    NOT NULL,
        [RequestDate]                        DATE           NULL,
        [InvoiceDate]                        DATE           NULL,
        [DefaultDeliveryDays]                CHAR(1)        NULL,
        [TripNumber]                         DECIMAL(7)     NULL,
        [DropNumber]                         DECIMAL(2)     NULL,
        [PromisedDelivery]                   DATE           NULL,
        [OrderEntry]                         DATE           NULL,
        [PriorityCode]                       DECIMAL(2)     NULL,
        [OrderItemStatus]                    CHAR(1)        NULL,
        [OrderPriority]                      DECIMAL(2)     NULL,
        [OriginalRequestDate]                DATE           NULL,
        [ActualDelivery]                     DATE           NULL,
        [CustomerSku]                        VARCHAR(22)    NULL,
        [LineReleaseNumber]                  VARCHAR(20)    NULL,
        [NetSales]                           DECIMAL(13, 3) NULL,
        [StandardPrice]                      DECIMAL(7, 2)  NULL,
        [AdvertisingAccrual]                 DECIMAL(9, 2)  NULL,
        [DFIDiscount]                        DECIMAL(9, 2)  NULL,
        [ContractPrice]                      DECIMAL(7, 2)  NULL,
        [CurrencyCode]                       CHAR(3)        NULL,
        [DeliveryDays]                       INT            NULL,
        [DeliveryDaysOriginalPromiseDate]    INT            NULL,
        [DeliveryDaysRaw]                    INT            NULL,
        [DeliveryDaysOriginalPromiseDateRaw] INT            NULL,
        [OriginalInvoiceNumber]              DECIMAL(8)     NULL,
        [OriginalInvoiceDate]                DATE           NULL,
        [OriginalOrderNumber]                VARCHAR(10)    NULL,
        [OriginalOrderDate]                  DATE           NULL,
        [OriginalSequenceNumber]             DECIMAL(7)     NULL,
        [OriginalDeliveryMethod]             VARCHAR(30)    NULL,
        [OrderType]                          VARCHAR(30)    NULL,
        [OrderDate]                          DATE           NULL,
        [OriginalPromiseDate]                DATE           NULL,
        [CurrentRequestDate]                 DATE           NULL,
        [DeliveryDate]                       DATE           NULL,
        [TripCloseDate]                      DATE           NULL,  
        [FirstScanDate]                      DATE           NULL,
        [TripCreateDate]                     DATE           NULL,
        [CurrentPromiseDate]                 DATE           NULL,
        [PriceCode]                          CHAR(6)        NULL,
        [ItemDiscountCode]                   CHAR(3)        NULL,
        [commissioncode]                     CHAR(6)        NULL,
        [FreightCode]                        CHAR(3)        NULL,
        [DiscountSalesClass]                 CHAR(2)        NULL,
        [ExceptionID]                        DECIMAL(7, 0)  NULL,
        [FreightSalesClass]                  CHAR(2)        NULL,
        [BuyGroupCode]                       CHAR(3)        NULL,
        [GroupPricingExceptionID]            DECIMAL(10, 0) NULL,
        [WarehouseOperationPercent]          DECIMAL(6, 0)  NULL,
        [PriceAdderPercent]                  DECIMAL(6, 0)  NULL,
        [CalculatedAllowancePercent]         DECIMAL(7, 0)  NULL,
        [PackageDiscountAllocationPercent]   DECIMAL(4, 0)  NULL,
        [PackageDescription]                 VARCHAR(30)    NULL,
        [PackageID]                          VARCHAR(15)    NULL,
        [PackagePrice]                       DECIMAL(8, 0)  NULL,
        [PackageItemPrice]                   DECIMAL(8, 0)  NULL,
        [PackageItemDiscount]                DECIMAL(4, 0)  NULL,
        [OrderType3]                         CHAR(1)        NULL
    );


