CREATE TABLE [SalesHistory_AFI].[InvoiceHeader]
    (
        [CustomerNumber]      CHAR(8)        NOT NULL,
        [ShiptoNumber]        CHAR(4)        NOT NULL,
        [InvoiceNumber]       DECIMAL(9)     NOT NULL,
        [OrderNumber]         VARCHAR(10)    NOT NULL,
        [PurchaseOrder]       VARCHAR(25)    NOT NULL,
        [Warehouse]           CHAR(3)        NOT NULL,
        [InvoiceAmount]       DECIMAL(9, 2)  NOT NULL,
        [ShiptoName]          VARCHAR(50)    NOT NULL,
        [ShiptoAddress1]      VARCHAR(50)    NOT NULL,
        [ShiptoAddress2]      VARCHAR(50)    NULL,
        [ShiptoCity]          VARCHAR(50)    NOT NULL,
        [ShiptoState]         CHAR(2)        NOT NULL,
        [ShiptoZipCode]       VARCHAR(20)    NOT NULL,
        [ShiptoSalesman]      CHAR(5)        NOT NULL,
        [PostingMonth]        CHAR(2)        NOT NULL,
        [OrderArrivalCode]    CHAR(2)        NOT NULL,
        [AdvertisingFlag]     CHAR(1)        NOT NULL,
        [OrderType]           CHAR(1)        NOT NULL,
        [RequestDate]         DATE           NULL,
        [OrderDate]           DATE           NULL,
        [InvoiceDate]         DATE           NOT NULL,
        [LeadTime]            INT            NOT NULL,
        [TripNumber]          DECIMAL(7)     NOT NULL,
        [TaxAmount]           DECIMAL(13, 2) NOT NULL,
        [DropNumber]          DECIMAL(2)     NOT NULL,
        [OrderTypePrimary]    CHAR(1)        NOT NULL,
        [OrderTypeSecondary]  CHAR(1)        NOT NULL,
        [OrderTypeUsrDefine3] CHAR(1)        NOT NULL,
        [OrderTypeUsrDefine4] CHAR(1)        NOT NULL,
        [ShipInstructions]    VARCHAR(60)    NULL,
        [ShipWeight]          DECIMAL(10, 2) NULL,
        [TermsDiscount]       DECIMAL(5, 3)  NULL,
        [TripCreatedDate]     DATE           NULL,
        [CreditCode]          CHAR(1)        NULL,
        [CurrencyCode]        CHAR(3)        NULL,
        [PromotionNumber]     CHAR(7)        NULL,
        [CreditApprovalNBR]   CHAR(15)       NULL,
        [SoldtoName]          varchar(50)    NULL,
	    [ShiptoCountryName]   Char(8)        NULL,
        [Sequence]            DECIMAL(2)     NULL
 
    );

