CREATE TABLE [SalesHistory_AFI].[InvoiceConsumerInformation]
    (
        [InvoiceNumber]     DECIMAL(9)    NOT NULL,
        [OrderNumber]       VARCHAR(10)   NOT NULL,
        [SalesOrderNumber]  VARCHAR(30)   NOT NULL,
        [Sequence]          DECIMAL(2)    NOT NULL,
        [ConsumerLastName]  VARCHAR(50)   NULL,
        [ConsumerFirstName] VARCHAR(50)   NULL,
        [ConsumerAddress1]  VARCHAR(35)   NULL,
        [ConsumerAddress2]  VARCHAR(35)   NULL,
        [ConsumerAddress3]  VARCHAR(35)   NULL,
        [ConsumerAddress4]  VARCHAR(35)   NULL,
        [ConsumerAddress5]  VARCHAR(35)   NULL,
        [City]              VARCHAR(50)   NOT NULL,
        [State]             CHAR(2)       NOT NULL,
        [ZipCode]           VARCHAR(12)   NOT NULL,
        [Country]           CHAR(3)       NOT NULL,
        [HomePhone]         VARCHAR(20)   NOT NULL,
        [CellPhone]         VARCHAR(20)   NOT NULL,
        [WWorkPhone]        VARCHAR(20)   NOT NULL,
        [ComsumerNumber]    VARCHAR(40)   NOT NULL,
        [GeoCodeLatitute]   DECIMAL(9, 4) NOT NULL,
        [GeoCodeLongitude]  DECIMAL(9, 4) NOT NULL,
        [MailAddress]       VARCHAR(75)   NULL,
        [DeliveryMethod]    CHAR(3)       NOT NULL,
        [CustomerNumber]    CHAR(8)       NOT NULL,
        [ShiptoNumber]      CHAR(4)       NOT NULL,
        [InvoiceDate]       DATE          NULL
    );
