CREATE TABLE [Wholesale_Customers].[DeliveryWindow] (

	[cdwCusno] char(8) NULL, 
	[cdwShpno] char(4) NULL, 
	[cdwRc] char(1) NULL, 
	[cdwWin_ID] char(2) NULL, 
	[cdw_Open] char(8) NULL, 
	[cdw_Close] char(8) NULL, 
	[cdwDays] char(7) NULL, 
	[cdwPrim_Sec] char(1) NULL, 
	[cdwBefore] char(5) NULL, 
	[cdwAfter] char(5) NULL, 
	[cdwLstverDte] datetime2(6) NULL, 
	[cdwType] char(1) NULL, 
	[cdwExceptionSDate] datetime2(6) NULL, 
	[cdwExceptionEDate] datetime2(6) NULL, 
	[cdwCompanyNum] smallint NULL, 
	[cdwLastDeliveryDate] datetime2(6) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[acrec] char(1) NULL, 
	[cdwWindowProfitFactor] decimal(3,2) NULL, 
	[cdwUserId] varchar(35) NULL, 
	[cdwRecordID] bigint NULL, 
	[cdwRowVer] varbinary(max) NULL, 
	[cdwRecordVersion] bigint NULL
);