CREATE TABLE [wholesale_productsourcing_afi].[container] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[concontainer] varchar(8000) NULL, 
	[conID] int NULL, 
	[concreated] datetime2(6) NULL, 
	[conviacode] varchar(8000) NULL, 
	[concarrierid] int NULL, 
	[conmothervessel] varchar(8000) NULL, 
	[conmothervoyage] int NULL, 
	[conreceipttostock] datetime2(6) NULL, 
	[conreceiver] datetime2(6) NULL, 
	[conoblsent] datetime2(6) NULL, 
	[confeedervessel] varchar(8000) NULL, 
	[confeedervoyage] int NULL, 
	[conbookingnum] varchar(8000) NULL, 
	[conEquipmentReturned] datetime2(6) NULL, 
	[conEquipmentStatusCode] varchar(8000) NULL, 
	[conPallets] decimal(38,18) NULL, 
	[conTruckLoad] bit NULL, 
	[conPickUpDate] datetime2(6) NULL, 
	[conETA] datetime2(6) NULL, 
	[conOnBoard] datetime2(6) NULL, 
	[conEquipmentID] varchar(8000) NULL, 
	[conSealNumber] varchar(8000) NULL, 
	[conASNModificationStatus] int NULL, 
	[conContainerOwnerID] int NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[conReportedEmpty] datetime2(6) NULL, 
	[conCargoReceived] datetime2(6) NULL, 
	[conCheckDigit] int NULL, 
	[conSCAC] varchar(8000) NULL, 
	[conProNumber] varchar(8000) NULL, 
	[conDeliveredDate] datetime2(6) NULL, 
	[conCNRUnumber] varchar(8000) NULL, 
	[conRailSCAC] varchar(8000) NULL, 
	[conExpectedDelivery] datetime2(6) NULL, 
	[conOutgateForDelivery] datetime2(6) NULL, 
	[conLastFreeDay] datetime2(6) NULL
);

