create view [PartyContacts_Wrk].[v_ContactBase]
as
SELECT  [pccLocationID]
      ,[pccPartyID]
      ,[pccContactType]
      ,[pccContactID]
      ,[pccJobTitle]
      ,[pccDepartment]
      ,[pccIsDefault]
      ,[pccNetworkUserID]
      ,[pccAS400UserID]
      ,[pccProgramAdded]
      ,[pccActiveEndDate]
      ,[pccAdGuid]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[pccLastUserChanged]
      ,[pccDefaultLanguage]
      ,[pccForecastPlannerID]
  FROM [$(Source_Data)].[Wholesale_PartyContacts].[ContactBase]
GO

