CREATE TABLE [MasterData_Ent].[PaymentType] (
	[PaymentTypeID] [varchar](50) NOT NULL,
	[PaymentTypeName] [varchar](100) NULL,
	[PaymentClass] [varchar](10) NULL,
	[FinanceUseFee] [decimal](19, 4) NULL,
	[IsFinanced] [int] NULL,
	[PaymentTierLevel] [char](1) NULL,
	[VendorID] [varchar](20) NULL,
	[FinanceProviderName] [varchar](30) NULL,
	[PaymentTypeSubGroupID] [char](4) NULL,
	[PaymentTypeSubGroupName] [varchar](20) NULL,
	[TermsDuration] [varchar](20) NULL,
	[PaymentTermsGrouping] [varchar](50) NULL,
	[PaymentTypeGroupID] [char](2) NULL,
	[GroupID] [varchar](50) NULL,
	[RecordType] [int] NULL,
	[StoreBrandID] [varchar](15) NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[DateUpdated] [datetime2](3) NULL
);