CREATE TABLE [masterdata_hr_ukg_dsg].[hremployeehistory] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[EmployeeID] int NULL, 
	[EmployeeNumber] varchar(8000) NULL, 
	[SupID] varchar(8000) NULL, 
	[FirstName] varchar(8000) NULL, 
	[LastName] varchar(8000) NULL, 
	[EmpStatus] varchar(8000) NULL, 
	[Email] varchar(8000) NULL, 
	[EmpHourlySalary] varchar(8000) NULL, 
	[EmpFTPT] varchar(8000) NULL, 
	[EmpAddressCity] varchar(8000) NULL, 
	[EmpAddressState] varchar(8000) NULL, 
	[EmpAddressZip] varchar(8000) NULL, 
	[BirthDate] datetime2(6) NULL, 
	[HireDate] datetime2(6) NULL, 
	[LocationID] varchar(8000) NULL, 
	[JobID] int NULL, 
	[DivisionID] int NULL, 
	[DepartmentID] int NULL, 
	[RegionID] int NULL, 
	[EmployeeTypeID] int NULL, 
	[SepCode] varchar(8000) NULL, 
	[SepType] varchar(8000) NULL, 
	[SepReason] varchar(8000) NULL, 
	[SepDate] datetime2(6) NULL, 
	[TransDate] datetime2(6) NULL
);