CREATE TABLE [masterdata_hr_ukg_dsg].[peopletimesheet] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[TimeSheetID] bigint NULL, 
	[SourceDataID] varchar(8000) NULL, 
	[SourceSystemID] int NULL, 
	[PeopleID] bigint NULL, 
	[EmployeeNumber] varchar(8000) NULL, 
	[PayPeriod] int NULL, 
	[TransDateKey] int NULL, 
	[SourceLocationID] varchar(8000) NULL, 
	[LocationKey] int NULL, 
	[TimeIn] datetime2(6) NULL, 
	[TimeOut] datetime2(6) NULL, 
	[Time] float NULL, 
	[SourcePayCodeID] varchar(8000) NULL, 
	[PayCodeID] int NULL, 
	[PayCodeName] varchar(8000) NULL, 
	[SourceTaskCodeID] varchar(8000) NULL, 
	[TaskCodeID] varchar(8000) NULL, 
	[TaskCodeName] varchar(8000) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Rate] decimal(19,4) NULL, 
	[ExtCost] decimal(19,4) NULL, 
	[ApprovedByManager] bit NULL
);