Create view ProductKnowledge_Wrk.v_ItemClass
As
SELECT [iclitcls]
      ,[iclitclnm]
      ,[iclimpdom]
      ,[iclplcode]
      ,[iclslscat]
      ,[icldivcode]
      ,[iclRetailCat]
      ,[iclFinancial]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Databricks)].[masterdata_productknowledge].[itemclass]