CREATE view ProductKnowledge_Wrk.v_SeriesGroupingLookup
as
SELECT [grpLookupId]
      ,[grpLookupCode]
      ,[grpHiPrPoint]
      ,[grpLoPrPoint]
      ,[grpPrIncr]
      ,[grpPlCode]
      ,[grpSort]
      ,[grpIcon]
      ,[grpFeaturedProduct]
      ,[grpPriceBkld]
      ,[grpPriceBkCode]
      ,[grpPrPointType]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[grpItemNumber]
      ,[grpMargin]
      ,[grpPriceBookSort]
      ,[grpRoomLocation]
      ,[grpAssociationCode]
  FROM [$(Databricks)].[masterdata_productknowledge].[seriesgroupinglookup]