CREATE TABLE [CostAccounting_DW].[FactMargins] (
    [Month End Date]               DATETIME2 (6)        NULL,
    [Item Number]                  VARCHAR (15)    NOT NULL,
    [Margin Warehouse]             CHAR (3)        NOT NULL,
    [Fiscal Year Period]           VARCHAR (7)     NULL,
    [Security Tag]                 CHAR (4)        NOT NULL,
    [FOB Value]                    DECIMAL (29, 6) NULL,
    [Quantity Ordered]             DECIMAL (29)    NULL,
    [Amount Ordered]               DECIMAL (29, 2) NULL,
    [Average Selling Price]        DECIMAL (29, 2) NULL,
    [Average Inventory On-Hand]    DECIMAL (29, 2) NULL,
    [GMROI - Sales]                DECIMAL (29, 2) NULL,
    [GMROI - Cost of Sales]        DECIMAL (29, 2) NULL,
    [GMROI - Margin]               DECIMAL (29, 2) NULL,
    [GMROI - Net Sales]            DECIMAL (29, 2) NULL,
    [GMROI - Actual Cost of Sales] DECIMAL (29, 2) NULL,
    [Returns Percent]              DECIMAL (29, 2) NULL,
    [Allowance Percent]            DECIMAL (29, 2) NULL,
    [Short Shipment Percent]       DECIMAL (29, 2) NULL,
    [MarginDetailsKey]             INT             NOT NULL
)