CREATE TABLE [Retail_Sales].[SalesOrderLineHistory] (

	[SourceSystem] varchar(30) NOT NULL, 
	[BtaID] varchar(50) NOT NULL, 
	[AsIsSaleReasonCodeID] varchar(50) NULL, 
	[BaseOrderID] varchar(30) NOT NULL, 
	[SourceOrderID] varchar(30) NOT NULL, 
	[TransDate] date NOT NULL, 
	[LineNumber] int NULL, 
	[LineStatus] varchar(30) NOT NULL, 
	[ItemDescription] varchar(255) NULL, 
	[SKU] varchar(20) NOT NULL, 
	[QuantityOrdered] decimal(19,4) NOT NULL, 
	[NetPrice] decimal(19,4) NOT NULL, 
	[ProtectionPlanSKU] varchar(20) NULL, 
	[ProtectionPlanID] varchar(50) NULL, 
	[ProtectionPlanPrice] decimal(19,4) NULL, 
	[ProtectionPlanCost] decimal(19,4) NULL, 
	[IsServiceItem] bit NULL, 
	[HasProtectionPlan] bit NULL, 
	[WarrantyEndDate] date NULL, 
	[StoreID] int NOT NULL, 
	[KitOrPackageQuantity] int NULL, 
	[KitOrPackageSKU] varchar(20) NULL, 
	[NetCost] decimal(19,4) NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[GroupID] varchar(50) NULL, 
	[CustomerID] varchar(50) NOT NULL, 
	[DiscountCode] varchar(10) NULL, 
	[DeliveryStoreID] varchar(30) NOT NULL, 
	[DeliveryTypeCodeID] varchar(20) NOT NULL, 
	[SalesPersonID] varchar(50) NOT NULL, 
	[ServiceTypeID] varchar(10) NULL, 
	[TransCodeID] int NOT NULL, 
	[VendorID] varchar(50) NULL, 
	[VoidedReasonCodeID] varchar(50) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[PurchaseStatusCodeID] varchar(50) NULL, 
	[SpecialOrder] bit NULL, 
	[UpdateDateTime] datetime2(3) NULL, 
	[UpdateTypeID] varchar(4) NULL, 
	[Source] char(1) NOT NULL
);