CREATE TABLE [MasterData_Product].[ProductInfo] (

	[SKU] varchar(20) NOT NULL, 
	[AFISKU] varchar(30) NULL, 
	[SKUDescription1] varchar(50) NULL, 
	[SKUDescription2] varchar(50) NULL, 
	[SKUName] varchar(100) NULL, 
	[VendorModelNumber] varchar(50) NULL, 
	[VendorID] varchar(20)  NULL, 
	[SalePrice] decimal(19,4) NULL, 
	[ListPrice] decimal(19,4) NULL, 
	[LandedCost] decimal(19,4) NULL, 
	[AverageLandedCost] decimal(19,4) NULL, 
	[ReplacementCost] decimal(19,4) NULL, 
	[StoreBrandID] varchar(20) NULL, 
	[PurchaseStatus] varchar(20) NULL, 
	[ProductStatus] varchar(20) NULL, 
	[SeriesID] varchar(20) NULL, 
	[Depth] decimal(18,4) NULL, 
	[Height] decimal(18,4) NULL, 
	[Width] decimal(18,4) NULL, 
	[StorageDepth] decimal(18,4) NULL, 
	[StorageHeight] decimal(18,4) NULL, 
	[StorageWidth] decimal(18,4) NULL, 
	[CubicFeet] decimal(18,4) NULL, 
	[DeliveryVolume] decimal(18,4) NULL, 
	[UnloadTime] datetime2(3) NULL, 
	[SpecialOrderFlag] bit NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[SubGroupID] varchar(20) NULL, 
	[SubGroupName] varchar(100) NULL, 
	[PPPGroupID] varchar(10) NULL, 
	[CollectionID] varchar(50) NULL, 
	[CollectionName] varchar(100) NULL, 
	[ProductCollectionLifestyle] varchar(50) NULL, 
	[ProductTypeID] varchar(4) NOT NULL, 
	[ServiceProductTypeID] varchar(20) NULL, 
	[InventoryManagementStatusID] int NULL, 
	[InventoryTierID] varchar(10) NULL, 
	[AverageCost] decimal(19,4) NULL, 
	[CommonDescription] varchar(50) NULL, 
	[PurchaseStatusCodeID] varchar(20) NULL, 
	[ItemCommCategory] varchar(5) NULL, 
	[CommCostAddonPercent] decimal(19,4) NULL, 
	[IsDiscountable] char(1) NULL, 
	[IsMaster] bit NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateChanged] datetime2(3) NULL
);