CREATE VIEW [Pricing_AFI_Wrk].[v_BuyGroupDefault]
AS
SELECT [bgdBgCode]
      ,[bgdWhse]
      ,[bgdFrChrg]
      ,[bgdDate1]
      ,[bgdDate2]
      ,[bgdGcmpct]
      ,[bgdLastUserChanged]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[bgdDisc1]
      ,[bgdDisc2]
      ,[bgdDisc3]
      ,[bgdDisc4]
      ,[bgdDisc5]
      ,[bgdDisc6]
      ,[bgdDisc7]
      ,[bgdUseReduction]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[BuyGroupDefault]