CREATE VIEW [Pricing_AFI_Wrk].[v_CommissionRates]
AS
SELECT [Cracommcd]
      ,[Cracomcls]
      ,[Cracommpc]
      ,[Crasdate]
      ,[Craedate]
      ,[Cracbasad]
      ,[Commaudit]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[CommissionRates]
