CREATE VIEW [Pricing_AFI_Wrk].[v_CustomerPricingSetup]
AS
SELECT  [cprCustomerNumber]
      ,[cprShiptoNumber]
      ,[cprID]
      ,[cprStartDate]
      ,[cprCode]
      ,[cprLastUserChanged]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[commaudit2]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[CustomerPricingSetup] 