CREATE VIEW [Pricing_AFI_Wrk].[v_DiscountCodes]
AS
SELECT [dicDccode]
      ,[dicDcdesc]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[dicCurrencyCode]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[DiscountCodes]