CREATE VIEW [Pricing_AFI_Wrk].[v_FreightRates]
AS
SELECT 
       [fraFcode]
      ,[fraWhse]
      ,[fraFrtcls]
      ,[fraFrghtd]
      ,[fraFrghtp]
      ,[fraFbascd]
      ,[fraFfrmvl]
      ,[fraFtovl]
      ,[fraFminim]
      ,[fraFzone]
      ,[fraFseqno]
      ,[fraSdate]
      ,[fraEdate]
      ,[commaudit]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[FreightRates]
