CREATE VIEW [Pricing_AFI_Wrk].[v_FreightClass]
AS
SELECT  [fclFrtcls]
      ,[fclFrtdesc]
      ,[fclFrtype]
      ,[fclDivision]
      ,[fcldefwhse]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[fclExtendedCode]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[FreightClass]