CREATE VIEW [Pricing_AFI_Wrk].[v_PriceCode]
AS
SELECT  [pcoPccode]
      ,[pcoPcdesc]
      ,[pcoAshfreight]
      ,[pcoMilfreight]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[pcoDefaultBasePrice]
      ,[pcoIncludeVAT]
      ,[pcoCurrencyCode]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[PriceCode]