create view [Pricing_AFI_Wrk].[v__PriceCodeArchive]
as
SELECT [PriceCodeArchiveId]
      ,[pcoPccode]
      ,[pcoPcdesc]
      ,[pcoAshfreight]
      ,[pcoMilfreight]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[pcoCurrencyCode]
      ,[pcoDefaultBasePrice]
      ,[pcoIncludeVAT]
      ,[ArchiveStatus]
      ,[StatusDate]
      ,[UserId]
      ,[ReasonCode]
      ,[ReasonDescription]
      ,[UserNote]
      ,[HistoryFlag]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[PriceCodeArchive]
GO

