CREATE VIEW [Pricing_AFI_Wrk].[v_SalesClass]
AS
SELECT [sclSlscls]
      ,[sclSldesc]
      ,[sclDiscls]
      ,[sclFrtcls]
      ,[sclComcls]
      ,[sclDivcode]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[SalesClass]