CREATE VIEW [Transportation_Wrk].[v_TripTypeCode]
  AS SELECT [ttcTripType]
      ,[ttcTripTypeDescription]
      ,[ttcSpecialHandling]
      ,[ttcUserDefined]
      ,[ttcAddTimeStamp]
      ,[ttcAddUser]
      ,[ttcChangeTimeStamp]
      ,[ttcChangeUser]
      ,[ttcTransportMethod]
      ,[ttcResourceCapability]
      ,[ttcDeliveryModeDefault]
      ,[ttcDeliveryCategory]
  FROM [$(Source_Data)].[Wholesale_Codis_AFI].[TRPTYPCD] 
