CREATE VIEW [Transportation_Wrk].[v_TripDetail]
  AS SELECT [BDTRP#]
      ,[BDDRP#]
      ,[BDORD#]
      ,[BDISEQ]
      ,[BDITM#]
      ,[BDITMD]
      ,[BDCITM]
      ,[BDINVN]
      ,[BDREF#]
      ,[BDCUS#]
      ,[BDCTL#]
      ,[BDICLS]
      ,[BDCCLS]
      ,[BDITQT]
      ,[BDITCT]
      ,[BDITWT]
      ,[BDCUSR]
      ,CASE WHEN CAST([BDCDAT] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([BDCDAT] as INT) AS CHAR(8)) AS DATE) END AS  [BDCDAT]
      ,[BDCTIM]
      ,[BDCPGM]
  FROM [$(Databricks)].[wholesale_codis].[bttripd]
