CREATE VIEW [SSAS_AFISALES_OLAP].[DimCustomerShippingLocations]
AS
    SELECT
        [Account And Shipto Number],
        [Customer Name],
        [Customer Account Number],
        [Customer Shipto Number],
        [Account Exception Flag],
        [Discount Code],
        [Discount Code Description],
        [AFI Discount Description]              AS [AFI Discount Code],
        [Price Code],
        [Price Code Description],
        [AFI Price Description]                 AS [AFI Price Code],
        [Freight Code],
        [Freight Code Description],
        [AFI Freight Description]               AS [AFI Freight Code],
        [Commission Code],
        [Commission Code Description],
        [AFI Commission Code],
        [Customer Shipto Name],
        [Customer Segment],
        [Business Type Code],
        [Business Type],
        [Reporting Business Type],
        [Customer Service RepID],
        LEFT([Customer Service Agent Name], 25) AS [Customer Service Agent Name],
        [Customer Service Group ID],
        [Customer Service Group Leader],
        [Store Address ID],
        [Shipto AddressID],
        [Primary Sales Territory],
        [Shipto Sales Territory],
        [Customer Account Status],
        [DFI Account Flag],
        [AFI Credit Terms],
        [Terms Code],
        [Credit Territory Code],
        [Default Warehouse],
        [Terms Description],
        [Route Zone],
        [Bill To Address 1],
        [Bill To Address 2],
        [Bill To Address 3],
        [Bill To Address 4],
        [Bill To Address 5],
        [Bill To City],
        [Bill To State],
        [Bill To Zip Code],
        [Bill To Country],
        [Bill To-Buyer Name],
        [Bill To-Buyer Phone],
        [Bill To-Buyer Fax],
        [Bill To-Buyer Email],
        [Bill To-Receiving Name],
        [Bill To-Receiving Phone],
        [Bill To-Receiving Fax],
        [Bill To-Receiving Email],
        [Ship To-Buyer Name],
        [Ship To-Buyer Phone],
        [Ship To-Buyer Fax],
        [Ship To-Buyer Email],
        [Ship To-Receiving Name],
        [Ship To-Receiving Phone],
        [Ship To-Receiving Fax],
        [Ship To-Receiving Email],
        [Shipto Details],
        [ACI Amount],
        [Outstanding Balance],
        [Days Beyond Terms - 90],
        [Days Beyond Terms - 365],
        [Credit Limit],
        [Invoice Type],
        [EPay Flag],
        [Currency Type],
        [Highest Credit],
        [ABC Account-Current Year],
        [ABC Account-Previous Year],
        [ABC Account-2 Years Ago],
        [HS Owner]
    FROM
        AFISales_DW.[DimCustomers];