CREATE VIEW [SSAS_AFISALES_OLAP].[FactShippedHistory]
AS
    SELECT
            [Invoice Date],
            [Request Date],
            [Delivery Date],
            [Order Date],
            [Account And Shipto Number],
            Territory,
            RegionCode_RepID_Category,
            [Account Number],
            [Shipto Number],
            [Invoice Number],
            [Order Number],
            [Item SKU],
            [Store Address ID],
            [Shipto AddressID],
            [Marketing Specialist ID]        AS [Sales Repid SPM],
            [Sales Region Code],
            [Warehouse],
            [Item Status],
            [Order Item Status],
            [AFI Sales Category],
            [Speed To Market Base],
            [Speed to Market],
            [Delivery Days],
            [Stm Base Calc],
            [Stm Count],
            [Early],
            [On Time],
            [1 Day Late],
            [2 Days Late],
            [3 Days Late],
            [4 Days Late],
            [5 Days Late],
            [6 Days Late],
            [7 Days Late],
            [8 to 14 Days Late],
            [15 to 21 Days Late],
            [22 to 28 Days Late],
            [Over 28 Days Late],
            [Division Code],
            [Customer Shipto Division Number],
            [Promise Date]                   AS [Promised dDate],
            [Delivery Days - Promised]       AS [Speed to Market - Promised],
            [Early - Promised],
            [On Time - Promised],
            [1 Day Late - Promised],
            [2 Days Late - Promised],
            [3 Days Late - Promised],
            [4 Days Late - Promised],
            [5 Days Late - Promised],
            [6 Days Late - Promised],
            [7 Days Late - Promised],
            [8 to 14 Days Late - Promised],
            [15 to 21 Days Late - Promised],
            [22 to 28 Days Late - Promised],
            [Over 28 Days Late - Promised],
            SalesTerritoryID, ----------------
            [Sales Repid],
            [Quantity Shipped],
            [Invoice Discount],
            [Amount Shipped],
            [Other Allowances],
            [Allocated Freight],
            [Invoiced Line Item Freight],
            [Other Freight],
            [Cubes],
            [Seats],
            [Advertising Accrual],
            [Invoice DFI Discount],
            [Contract Price Amount]
    FROM
            AFISales_DW.FactShippedHistory OH
        LEFT JOIN
            AFISales_DW.DimDateFile        D
                ON OH.[Invoice Date] = D.[Transaction Date]
    WHERE
            [Fiscal Year] >= YEAR(GETDate()) - 4;