CREATE TABLE [Retail_DW_NonCore].[InventoryDailyOpen] (

	[TransDate] date NULL, 
	[ProductKey] bigint NOT NULL, 
	[SerialNbrID] varchar(50) NULL, 
	[LocationID] varchar(50) NOT NULL, 
	[StoreBrandID] varchar(50) NULL, 
	[StorageID] varchar(50) NULL, 
	[MaterialCost] numeric(18,2) NULL, 
	[LandedFreight] numeric(18,2) NULL, 
	[Addon1Cost] numeric(18,2) NULL, 
	[Addon2Cost] numeric(18,2) NULL, 
	[Addon3Cost] numeric(18,2) NULL, 
	[Addon4Cost] numeric(18,2) NULL, 
	[TotalCost] numeric(18,2) NULL, 
	[Qty] numeric(18,2) NOT NULL, 
	[QtyCommitted] numeric(18,2) NOT NULL, 
	[QtySoftCommitted] numeric(18,2) NOT NULL, 
	[DateAsls] date NULL, 
	[AslsReasonCodeID] varchar(50) NULL, 
	[InvSubBucketID] varchar(50) NULL, 
	[PieceStatusID] int NULL, 
	[TransDateKey] int NOT NULL, 
	[InvBucketID] varchar(20) NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[DateInStorageID] date NULL, 
	[DateInReasonCodeID] date NULL
);