CREATE TABLE [Retail_External].[store] (

	[operation] varchar(10) NULL, 
	[LocationID] varchar(20) NULL, 
	[LocationIDDislay] varchar(20) NULL, 
	[LocationType] varchar(20) NULL, 
	[ServiceLocationID] varchar(20) NULL, 
	[StockLocationID] varchar(20) NULL, 
	[ShipLocationID] varchar(20) NULL, 
	[StoreBrandID] varchar(20) NULL, 
	[LocationName] varchar(50) NULL, 
	[Address1] varchar(40) NULL, 
	[Address2] varchar(30) NULL, 
	[City] varchar(30) NULL, 
	[PostalCodeID] varchar(20) NULL, 
	[Phone] varchar(30) NULL, 
	[RegionID] varchar(20) NULL, 
	[RegionName] varchar(50) NULL, 
	[DistrictID] varchar(10) NULL, 
	[DistrictName] varchar(50) NULL, 
	[HasTrafficCounter] int NULL, 
	[SquareFeet] float NULL, 
	[OpenDate] datetime2(6) NULL, 
	[Owner] varchar(20) NULL, 
	[OwnerNumber] varchar(10) NULL, 
	[OwnerGroup] varchar(20) NULL, 
	[State] varchar(20) NULL, 
	[TotalSquareFeet] decimal(18,2) NULL, 
	[ProductiveSquareFeet] decimal(18,2) NULL, 
	[SCMLocationID] varchar(10) NULL, 
	[IsVirtual] bit NULL, 
	[AdjustedLocationName] varchar(50) NULL
);