CREATE TABLE [Retail_DW_Core].[DimDate] (
    [DateKey]                  INT           NULL,
    [MapicsDate]               INT           NULL,
    [DateID]                   DATE          NULL,
    [DateTimeID]               DATE          NULL,
    [CalendarDate]             DATE          NULL,
    [CalendarDateName]         VARCHAR (100) NULL,
    [FiscalYearFirstDate]      DATE          NULL,
    [FiscalYearLastDate]       DATE          NULL,
    [HolidayIndicator]         VARCHAR (100) NULL,
    [HolidayName]              VARCHAR (100) NULL,
    [WorkingDayIndicator]      VARCHAR (100) NULL,
    [WeekdayWeekend]           VARCHAR (100) NULL,
    [FiscalSemester]           SMALLINT      NULL,
    [FiscalSemesterYear]       SMALLINT      NULL,
    [FiscalYear]               SMALLINT      NULL,
    [FiscalYearName]           VARCHAR (100) NULL,
    [FiscalYearIndicator]      INT           NULL,
    [FiscalDayOfYear]          SMALLINT      NULL,
    [FiscalMonthLastDate]      DATE          NULL,
    [FiscalQuarter]            SMALLINT      NULL,
    [FiscalQuarterName]        VARCHAR (100) NULL,
    [FiscalQuarterIndicator]   INT           NULL,
    [FiscalQuarterYear]        SMALLINT      NULL,
    [FiscalQuarterYearName]    VARCHAR (100) NULL,
    [FiscalMonthYear]          INT           NULL,
    [FiscalMonthName]          VARCHAR (100) NULL,
    [FiscalMonthYearName]      VARCHAR (100) NULL,
    [FiscalDayOfMonth]         SMALLINT      NULL,
    [FiscalWeekOfMonth]        SMALLINT      NULL,
    [FiscalMonthFirstDate]     DATE          NULL,
    [FiscalWeekYear]           INT           NULL,
    [FiscalWeekYearName]       VARCHAR (100) NULL,
    [FiscalWeekFirstDate]      DATE          NULL,
    [FiscalWeekLastDate]       DATE          NULL,
    [FiscalMonth]              SMALLINT      NULL,
    [FiscalMonthIndicator]     INT           NULL,
    [FiscalDateName]           VARCHAR (100) NULL,
    [FiscalDateIndicator]      INT           NULL,
    [FiscalWeek]               SMALLINT      NULL,
    [FiscalWeekIndicator]      INT           NULL,
    [FiscalDayOfWeek]          SMALLINT      NULL,
    [FiscalDayOfWeekName]      VARCHAR (100) NULL,
    [CalendarSemesterYear]     SMALLINT      NULL,
    [CalendarYear]             SMALLINT      NULL,
    [CalendarYearName]         VARCHAR (100) NULL,
    [CalendarYearIndicator]    INT           NULL,
    [CalendarDayOfYear]        SMALLINT      NULL,
    [FiscalDate]               DATE          NULL,
    [CalendarQuarter]          SMALLINT      NULL,
    [CalendarQuarterName]      VARCHAR (100) NULL,
    [CalendarQuarterIndicator] INT           NULL,
    [CalendarQuarterYear]      SMALLINT      NULL,
    [CalendarQuarterYearName]  VARCHAR (100) NULL,
    [CalendarSemester]         SMALLINT      NULL,
    [CalendarMonthName]        VARCHAR (100) NULL,
    [CalendarMonthYearName]    VARCHAR (100) NULL,
    [CalendarDayOfMonth]       SMALLINT      NULL,
    [CalendarWeekOfMonth]      SMALLINT      NULL,
    [CalendarMonthFirstDate]   DATE          NULL,
    [CalendarMonthLastDate]    DATE          NULL,
    [CalendarDayOfWeekName]    VARCHAR (100) NULL,
    [CalendarWeekFirstDate]    DATE          NULL,
    [CalendarWeekLastDate]     DATE          NULL,
    [CalendarMonth]            SMALLINT      NULL,
    [CalendarMonthIndicator]   INT           NULL,
    [CalendarMonthYear]        INT           NULL,
    [CalendarDateIndicator]    INT           NULL,
    [CalendarWeek]             SMALLINT      NULL,
    [CalendarWeekIndicator]    INT           NULL,
    [CalendarWeekYear]         INT           NULL,
    [CalendarWeekYearName]     VARCHAR (100) NULL,
    [CalendarDayOfWeek]        SMALLINT      NULL,
    [LYDate]                   DATE          NULL,
    [LYLYDate]                 DATE          NULL,
    [NYDate]                   DATE          NULL,
    [P13Flag]                  INT           NULL,
    [PreviousP13Flag]          INT           NULL
);