CREATE TABLE [Retail_DW_Core].[DimProductMaster] (
    [ProductKey]                  BIGINT          NOT NULL,
    [SKU]                         VARCHAR (50)    NOT NULL,
    [AFISKU]                      VARCHAR (30)    NULL,
    [SKUName]                     VARCHAR (200)   NULL,
    [VendorModelNumber]           VARCHAR (50)    NULL,
    [VendorID]                    VARCHAR (50)    NULL,
    [GroupID]                     VARCHAR (50)    NULL,
    [SubGroupID]                  VARCHAR (50)    NULL,
    [SubGroupName]                VARCHAR (100)   NULL,
    [PPPGroupID]                  VARCHAR (50)    NULL,
    [CollectionID]                VARCHAR (50)    NULL,
    [CollectionName]              VARCHAR (100)   NULL,
    [ListPrice]                   DECIMAL (18, 4) NULL,
    [SalePrice]                   DECIMAL (18, 4) NULL,
    [ReplacementCost]             DECIMAL (18, 4) NULL,
    [LandedCost]                  DECIMAL (18, 4) NULL,
    [AverageLandedCost]           DECIMAL (18, 4) NULL,
    [StoreBrandID]                VARCHAR (50)    NULL,
    [PurchaseStatus]              CHAR (1)        NULL,
    [ProductStatus]               VARCHAR (50)    NULL,
    [SeriesID]                    VARCHAR (50)    NULL,
    [Depth]                       DECIMAL (18, 4) NULL,
    [Height]                      DECIMAL (18, 4) NULL,
    [Width]                       DECIMAL (18, 4) NULL,
    [StorageDepth]                DECIMAL (18, 4) NULL,
    [StorageHeight]               DECIMAL (18, 4) NULL,
    [StorageWidth]                DECIMAL (18, 4) NULL,
    [CubicFeet]                   DECIMAL (18, 4) NULL,
    [DeliveryVolume]              DECIMAL (18, 4) NULL,
    [UnloadTime]                  DATETIME2 (3)   NULL,
    [SpecialOrderFlag]            BIT             NULL,
    [ProductTypeID]               INT             NULL,
    [DateCreated]                 DATETIME2 (3)   NULL,
    [DateChanged]                 DATETIME2 (3)   NULL,
    [ProductCollectionLifestyle]  VARCHAR (50)    NULL,
    [IsKit]                       VARCHAR (1)     NULL,
    [IsMaster]                    BIT             NULL,
    [DefaultStoreBrandID]         VARCHAR (50)    NULL,
    [InventoryManagementStatusID] INT             NULL,
    [VendorStyleID]               VARCHAR (60)    NULL,
    [DominantProductID]           VARCHAR (50)    NULL,
    [PricePointSegmentation]      VARCHAR (50)    NULL,
    [PricePoint]                  DECIMAL (18, 4) NULL,
    [ProductStatusDate]           DATETIME2 (3)   NULL,
    [VendorStyle]                 VARCHAR (100)   NULL,
    [InventoryTierID]             VARCHAR (10)    NULL,
    [AverageCost]                 DECIMAL (18, 4) NULL,
    [CommCostAddonPercent]        DECIMAL (18, 4) NULL,
    [ServiceProductTypeID]        VARCHAR (20)    NULL,
    [PurchaseStatusCodeID]        CHAR (10)       NULL,
    [ItemCommCategory]            VARCHAR (50)    NULL,
    [RecordType]                  INT             NULL,
    [FinanceUseFee]               DECIMAL (19, 4) NULL,
    [IsDiscountable]              VARCHAR (1)     NULL
);