CREATE TABLE [Retail_DW_Core].[DimPeopleTimeSheet] (
	[TimeSheetID] [bigint] NOT NULL,
	[SourceDataID] [varchar](50) NOT NULL,
	[SourceSystemID] [int] NOT NULL,
	[PeopleID] [bigint] NULL,
	[EmployeeNumber] [varchar](100) NULL,
	[PayPeriod] [int] NULL,
	[TransDate] [date] NULL,
	[LocationID] [int] NULL,
	[LocationKey] [int] NULL,
	[LocationName] [varchar](255) NULL,
	[LocationType] [varchar](5) NULL,
	[Productive] [int] NULL,
	[TimeIn] [datetime2](3) NULL,
	[TimeOut] [datetime2](3) NULL,
	[Time] [decimal](18,2) NULL,
	[SourcePayCodeID] [varchar](10) NULL,
	[PayCodeID] [int] NULL,
	[PayCodeName] [varchar](50) NULL,
	[SourceTaskCodeID] [varchar](10) NULL,
	[TaskCodeID] [varchar](10) NULL,
	[TaskCodeName] [varchar](100) NULL,
	[DateCreated] [datetime2](6) NULL,
	[Rate] [decimal](18,4) NULL,
	[ExtCost] [decimal](18,2) NULL,
	[ApprovedByManager] [bit] NULL,
	[DataSource] [varchar](5) NOT NULL
);