CREATE TABLE [Retail_DW_Core].[FactProtectionPlanSalesTrans] (

	[PPSalesKey] bigint NOT NULL, 
	[SalesDataTypeKey] int NOT NULL, 
	[ProtectionPlanID] varchar(50) NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[ItemID] int NOT NULL, 
	[BaseOrderID] varchar(50) NULL, 
	[StoreID] int NOT NULL, 
	[SalesPersonID] varchar(50) NOT NULL, 
	[TransDate] date NOT NULL, 
	[TransCodeID] int NOT NULL, 
	[Sales] decimal(18,2) NOT NULL, 
	[Cost] decimal(18,2) NOT NULL, 
	[Units] decimal(18,2) NOT NULL, 
	[Source] char(1) NOT NULL, 
	[CurrentRec] int NOT NULL, 
	[DateCreated] datetime2(3) NOT NULL, 
	[CustomerID] varchar(50) NULL, 
	[LocationKey] bigint NULL, 
	[ProductKey] bigint NULL, 
	[SalesPersonKey] bigint NULL, 
	[CustomerKey] bigint NULL, 
	[SuperOrderID] varchar(50) NULL, 
	[ShipLocationID] varchar(50) NULL, 
	[FRLocationID] varchar(50) NULL, 
	[TransDateKey] int NULL, 
	[ItemCommCategory] varchar(10) NULL, 
	[OrderDateKey] int NULL, 
	[PPPOpp] int NULL, 
	[PPPClose] int NULL, 
	[UpdateTypeID] varchar(4) NULL, 
	[DeliveryStoreID] varchar(50) NULL, 
	[GrossMultiplier] int NULL, 
	[SalesLeadSourceID] int NULL
);