CREATE TABLE [Retail_DW_Core].[FactFinancialBudget]
(
	[StoreType] [char](8) NULL,
	[AccountNumber] [varchar](10) NULL,
	[Database] [char](12) NULL,
	[StoreID] [char](4) NOT NULL,
	[Unit] [char](7) NULL,
	[StoreLocation] [varchar](60) NULL,
	[BudgetYear] [int] NULL,
	[Period] [int] NULL,
	[BudgetDate] [datetime2](6) NOT NULL,
	[BudgetWrittenCogs] [decimal](13,4) NULL,
	[BudgetWrittenSales] [decimal](13,4) NULL,
	[Derivedups] [decimal](13,4) NULL,
	[CloseRatio] [decimal](13,4) NULL,
	[AverageTicket] [decimal](13,4) NULL,
	[SalesPerGuest] [decimal](13,4) NULL,
	[BudgetInvoicedCogs] [decimal](13,4) NULL,
	[BudgetInvoicedSales] [decimal](13,4) NULL,
	[BudgetDeliveryIncomeRate] [decimal](13,4) NULL,
	[BudgetDeliveryIncomeWrittenSales] [decimal](13,4) NULL,
	[BudgetDeliveryIncomeInvoicedSales] [decimal](13,4) NULL,
	[BudgetFinanceFeesRate] [decimal](13,4) NULL,
	[BudgetFinanceFeesWrittenSales] [decimal](13,4) NULL,
	[BudgetFinanceFeesInvoicedSales] [decimal](13,4) NULL,
	[LastUpdateDate] [datetime2](6) NOT NULL
);