CREATE TABLE [Retail_DW_Core].[FactScoreboardManagerNotes] (
    [Source]                VARCHAR (5)   NULL,
    [IsUP]                  VARCHAR (1)   NULL,
    [StatusName]            VARCHAR (100) NULL,
    [SalesPersonID]         VARCHAR (20)  NULL,
    [SalesPersonName]       VARCHAR (50)  NULL,
    [StoreID]               INT           NULL,
    [ScoreboardStoreID]     INT           NULL,
    [StatusStartDate]       DATE          NULL,
    [StartTime]             VARCHAR (8)   NULL,
    [EndTime]               VARCHAR (8)   NULL,
    [ManagerNotes]          VARCHAR (600) NULL,
    [IsClosed]              VARCHAR (3)   NULL,
    [StrikeCount]           INT           NULL,
    [IsStrike]              INT           NULL,
    [IsStrikeOut]           INT           NULL,
    [ConsecutiveStrikes]    VARCHAR (20)  NULL,
    [ConsecutiveStrikeOuts] VARCHAR (20)  NULL,
    [Shot]                  INT           NULL,
    [FinApp]                INT           NULL
);