CREATE TABLE [Retail_DW_Core].[FactOrderDetailTrans] (
    [OrderID]             VARCHAR (50)    NOT NULL,
    [ItemID]              INT             NULL,
    [WrittenSales]        DECIMAL (19, 4) NOT NULL,
    [WrittenCost]         DECIMAL (19, 4) NOT NULL,
    [WrittenUnits]        DECIMAL (19, 4) NOT NULL,
    [DeliveredSales]      DECIMAL (19, 4) NOT NULL,
    [DeliveredCost]       DECIMAL (19, 4) NOT NULL,
    [DeliveredUnits]      DECIMAL (19, 4) NOT NULL,
    [TransCodeID]         INT             NOT NULL,
    [UpdateTypeID]        VARCHAR (4)     NOT NULL,
    [AsIsReasonCodeID]    VARCHAR (50)    NULL,
    [VoidedReasonCodeID]  VARCHAR (50)    NULL,
    [ItemCommCategory]    VARCHAR (10)    NULL,
    [DeliveryStatus]      VARCHAR (20)    NULL,
    [ProductDiscountCode] VARCHAR (50)    NULL,
    [PVEReasonCodeID]     VARCHAR (50)    NULL,
    [Sales]               DECIMAL (19, 4) NOT NULL,
    [Cost]                DECIMAL (19, 4) NOT NULL,
    [Units]               DECIMAL (19, 4) NOT NULL,
    [SalesType]           CHAR (5)        NULL,
    [SKU]                 VARCHAR (50)    NOT NULL,
    [StoreBrandID]        VARCHAR (20)    NULL,
    [ProductName]         VARCHAR (200)   NULL,
    [VendorModelNumber]   VARCHAR (50)    NULL,
    [VendorID]            VARCHAR (50)    NULL,
    [GroupID]             VARCHAR (50)    NULL,
    [SubGroupID]          VARCHAR (50)    NULL,
    [CategoryID]          VARCHAR (50)    NULL,
    [TransDate]           DATE            NULL,
    [SalesPersonID]       VARCHAR (50)    NULL,
    [SalesPersonName]     VARCHAR (200)   NULL,
    [CommissionRate]      DECIMAL (18, 2) NULL,
    [SalesPersonTypeID]   VARCHAR (3)     NULL,
    [CustomerID]          VARCHAR (50)    NULL,
    [CustomerFirstName]   VARCHAR (100)   NULL,
    [CustomerLastName]    VARCHAR (100)   NULL,
    [StoreID]             INT             NULL,
    [LocationName]        VARCHAR (50)    NULL,
    [PPPOpp]              DECIMAL (19, 4) NULL,
    [PPPClose]            DECIMAL (19, 4) NULL,
    [PPPGroupID]          VARCHAR (50)    NULL,
    [PrimaryCategory]     INT             NULL,
    [IsRetail]            INT             NULL,
    [CustomerClass]       VARCHAR (10)    NULL
);