CREATE TABLE [Retail_DW_Core].[FactOrderFulfillment] (
    [Address1]                           VARCHAR (100)   NULL,
    [Address2]                           VARCHAR (100)   NULL,
    [CellPhone]                          VARCHAR (15)    NULL,
    [City]                               VARCHAR (100)   NULL,
    [CODAmount]                          DECIMAL (19, 4) NULL,
    [ContactName]                        VARCHAR (100)   NULL,
    [CountryID]                          VARCHAR (50)    NULL,
    [DateChanged]                        DATETIME2 (3)   NULL,
    [DateCreated]                        DATETIME2 (3)   NULL,
    [DeliverToID]                        VARCHAR (50)    NULL,
    [DeliveryContactDate]                DATE            NULL,
    [DeliveryContactStatusID]            VARCHAR (50)    NULL,
    [DeliveryInstruction]                VARCHAR (MAX)   NULL,
    [DesiredDate]                        DATE            NULL,
    [DispatchTrackDateTime]              DATETIME2 (3)   NULL,
    [DeliveryCharge]                     DECIMAL (19, 4) NULL,
    [DeliveryChargeCalculated]           DECIMAL (19, 4) NULL,
    [DeliveryChargeOverride]             BIT             NULL,
    [DeliveryChargeOverrideReasonCodeID] VARCHAR (50)    NULL,
    [EmailAddress]                       VARCHAR (70)    NULL,
    [FreightCompanyID]                   VARCHAR (50)    NULL,
    [FulfillmentDate]                    DATE            NULL,
    [FulfillmentMethod]                  VARCHAR (10)    NULL,
    [FulfillmentStatus]                  VARCHAR (10)    NULL,
    [FulfillmentStoreID]                 VARCHAR (50)    NULL,
    [HandlingMethodCode]                 VARCHAR (50)    NULL,
    [HandlingMethodOverride]             BIT             NULL,
    [HomePhone]                          VARCHAR (15)    NULL,
    [InstallationCharge]                 DECIMAL (19, 4) NULL,
    [InstallationChargeOverride]         BIT             NULL,
    [IsInvoiced]                         BIT             NULL,
    [ManifestNumber]                     VARCHAR (50)    NULL,
    [ManifestStoreID]                    VARCHAR (50)    NULL,
    [MerchSubTotal]                      DECIMAL (19, 4) NULL,
    [Name]                               VARCHAR (100)   NULL,
    [NumberOfPostponements]              INT             NULL,
    [OrderFulfillmentID]                 VARCHAR (50)    NOT NULL,
    [SourceOrderID]                      VARCHAR (50)    NULL,
    [PostalCodeID]                       VARCHAR (50)    NULL,
    [RecStatus]                          VARCHAR (1)     NULL,
    [RouteCodeID]                        VARCHAR (50)    NULL,
    [RoutingNumber]                      INT             NULL,
    [SalesTaxExemptNumber]               VARCHAR (50)    NULL,
    [StaffID]                            VARCHAR (50)    NULL,
    [State]                              VARCHAR (50)    NULL,
    [StopTime]                           VARCHAR (50)    NULL,
    [StorisCreateDateTime]               DATETIME2 (3)   NULL,
    [TruckNumber]                        VARCHAR (10)    NULL,
    [WmsShipped]                         BIT             NULL,
    [WmsTransmitted]                     BIT             NULL,
    [WorkPhone]                          VARCHAR (15)    NULL,
    [WorkPhoneExt]                       VARCHAR (10)    NULL
);
GO

