CREATE TABLE [Retail_DW_Core].[FactSalesOrderHeader] (

	[SourceSystem] varchar(30) NOT NULL, 
	[OrderKey] bigint NOT NULL, 
	[SourceOrderID] varchar(20) NOT NULL, 
	[BaseOrderID] varchar(20) NOT NULL, 
	[DateCreated] datetime2(3) NULL, 
	[LastUpdatedUTC] datetime2(3) NULL, 
	[CustomerKey] bigint NOT NULL, 
	[CustomerID] varchar(128) NOT NULL, 
	[CustomerName] varchar(150) NULL, 
	[OrderStatus] varchar(30) NOT NULL, 
	[SalesChannel] varchar(30) NOT NULL, 
	[OrderType] varchar(10) NOT NULL, 
	[CompanyCode] varchar(5) NOT NULL, 
	[IsOnHold] bit NOT NULL, 
	[TotalSales] decimal(19,4) NULL, 
	[TotalCharges] decimal(19,4) NULL, 
	[TotalPayment] decimal(19,4) NULL, 
	[TotalAdditionalTaxAmount] decimal(19,4) NULL, 
	[TotalStateTaxAmount] decimal(19,4) NULL, 
	[TotalTaxes] decimal(19,4) NULL, 
	[FinanceAmount] decimal(19,4) NULL, 
	[BalanceDue] decimal(19,4) NULL, 
	[PaymentTypeID] varchar(50) NULL, 
	[BillToStreetAddress] varchar(255) NULL, 
	[BillToAddressLine2] varchar(128) NULL, 
	[BillToCity] varchar(128) NULL, 
	[BilltoStateOrProvinceCode] char(2) NULL, 
	[BillToZipOrPostalCode] varchar(10) NULL, 
	[BillToCountryCode] char(2) NULL, 
	[ShipInstruction] varchar(255) NULL, 
	[OrderContactName] varchar(150) NULL, 
	[OrderContactEmail] varchar(128) NULL, 
	[OrderContactPhone] varchar(20) NULL, 
	[CSLastContact] date NULL, 
	[CSNextContact] date NULL, 
	[StoreAccount] varchar(8) NULL, 
	[StoreShipTo] varchar(4) NULL, 
	[StoreOperationID] int NULL, 
	[StoreID] int NOT NULL, 
	[StoreBrandID] varchar(20) NULL, 
	[FulfillerID] varchar(20) NULL, 
	[CartID] varchar(40) NULL, 
	[IsWrittenOrder] bit NULL, 
	[OrderDate] date NULL, 
	[VoidedDate] date NULL, 
	[OrderCount] char(10) NULL, 
	[OriginalInvoiceID] varchar(30) NULL, 
	[MarketingCodeID] varchar(30) NULL, 
	[TransCodeID] int NULL, 
	[TransCodeMultiplier] bit NULL, 
	[RouteCodeID] varchar(30) NULL, 
	[CreditHoldCodeID] varchar(5) NULL, 
	[ServiceStaffID] varchar(20) NULL, 
	[RequestedDate] date NULL, 
	[TransactionSaveTime] datetime2(3) NULL, 
	[TransactionStartTime] datetime2(3) NULL, 
	[PriceExceptionComment] varchar(600) NULL, 
	[InstallationCharge] decimal(19,4) NULL, 
	[DeliveryCharge] decimal(19,4) NULL, 
	[DeliveryChargeCalculated] decimal(19,4) NULL, 
	[DeliveryChargeOverUserID] varchar(5) NULL, 
	[DeliveryChargeOverride] varchar(5) NULL, 
	[DeliveryChoice] varchar(10) NULL, 
	[DeliveryChargeCompliant] int NULL, 
	[DeliveryCapAvailDate] date NULL, 
	[OriginalDeliveryDate] datetime2(3) NULL, 
	[OriginalDeliveryType] varchar(50) NULL, 
	[SFMCFulfillmentStatus] varchar(50) NULL, 
	[SFMCFulfillmentType] varchar(50) NULL, 
	[SFMCLastFulfillmentDate] datetime2(3) NULL, 
	[SFMCPrimaryOrderCategory] varchar(50) NULL, 
	[IsFinanced] int NULL, 
	[OriginalTransCodeID] int NULL, 
	[OriginalTransDate] datetime2(3) NULL, 
	[SalesPersonID] varchar(20) NULL, 
	[SuperOrderID] varchar(50) NULL, 
	[LastActivityDate] datetime2(3) NULL, 
	[DateClosed] datetime2(3) NULL, 
	[RecStatus] char(1) NULL
);