CREATE TABLE [Retail_DW_Core].[FinanceSalesAttributionorders] (
    [BuySameDay]                       VARCHAR (3)     NULL,
    [AmountApproved]                   DECIMAL (18, 2) NULL,
    [CustomerID]                       VARCHAR (50)    NULL,
    [EmailAddress]                     VARCHAR (320)   NULL,
    [ApprovedByLendor]                 VARCHAR (255)   NULL,
    [RequestDate]                      DATE            NULL,
    [SalespersonID]                    VARCHAR (100)   NULL,
    [StoreID]                          INT             NULL,
    [OrderID]                          VARCHAR (50)    NULL,
    [OrderDate]                        DATETIME2 (6)   NULL,
    [BaseOrder]                        VARCHAR (10)    NULL,
    [FinancedAmount]                   DECIMAL (18, 2) NULL,
    [FinPaymentTypeID]                 VARCHAR (50)    NULL,
    [SFMCFulfillmentStatus]            VARCHAR (50)    NULL,
    [FinanceUseFee]                    DECIMAL (18, 4) NULL,
    [TotalSales]                       DECIMAL (18, 2) NULL,
    [OrderType]                        VARCHAR (100)   NULL,
    [Region]                           VARCHAR (100)   NULL,
    [Division]                         VARCHAR (100)   NULL,
    [OrderSameDay]                     VARCHAR (50)    NULL,
    [FinancedSameDay]                  DECIMAL (18, 2) NULL,
    [TotSalesOrder]                    VARCHAR (50)    NULL,
    [TotSalesCustomerDate]             VARCHAR (50)    NULL,
    [Sends]                            VARCHAR (1)     NULL,
    [SendForOTB]                       VARCHAR (1)     NULL,
    [Recheck or Approve No Buy - 1000] VARCHAR (50)    NULL
);