CREATE TABLE [Retail_DW_Core].[LEAS_DimDate] (

	[TransDateKey] int NULL, 
	[TransDate] date NULL, 
	[WeekDaySort] int NULL, 
	[CalendarWeekDay] int NULL, 
	[Week] varchar(8000) NULL, 
	[WeekStartDate] date NULL, 
	[YearWeekSort] int NULL, 
	[Weekday] varchar(8000) NULL, 
	[Day] int NULL, 
	[Month] varchar(8000) NULL, 
	[MonthSort] int NULL, 
	[PrevMonthEnd] date NULL, 
	[PrevEndOfWeek] date NULL, 
	[YearQuarterSort] int NULL, 
	[Quarter] varchar(8000) NULL, 
	[YearMonthSort] int NULL, 
	[Year_Month] varchar(8000) NULL, 
	[Year] int NULL, 
	[Today] varchar(8000) NULL, 
	[YearKey] int NULL, 
	[YearMonthKey] int NULL, 
	[YearQuarterKey] int NULL, 
	[LYDateKey] int NULL, 
	[NYDateKey] int NULL, 
	[Month-Year] varchar(8000) NULL
);