CREATE TABLE [Retail_DW_Core].[STGQ_FactLocation] (

	[LocationID] varchar(8000) NULL, 
	[LocationType] varchar(8000) NULL, 
	[StoreBrandID] varchar(8000) NULL, 
	[LocationName] varchar(8000) NULL, 
	[Address1] varchar(8000) NULL, 
	[Address2] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[PostalCodeID] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[RegionID] varchar(8000) NULL, 
	[RegionName] varchar(8000) NULL, 
	[DistrictID] varchar(8000) NULL, 
	[DistrictName] varchar(8000) NULL, 
	[HasTrafficCounter] bit NULL, 
	[TotalSquareFeet] int NULL, 
	[OpenDate] date NULL, 
	[Owner] varchar(8000) NULL, 
	[OwnerGroup] varchar(8000) NULL, 
	[OwnerNumber] varchar(8000) NULL, 
	[HasPulse] bit NULL, 
	[SameStoreDate] date NULL, 
	[State] varchar(8000) NULL, 
	[ProductiveSquareFeet] decimal(18,4) NULL
);