CREATE TABLE [Merch_ExternalFiles].[CoreLineupforAccessories] (

	[TopSeller] varchar(4) NULL, 
	[InPlaybook] varchar(4) NULL, 
	[Purpose] varchar(171) NULL, 
	[Story] varchar(54) NULL, 
	[IntroductionDate] varchar(19) NULL, 
	[Image] varchar(44) NULL, 
	[Vendor] varchar(14) NULL, 
	[DSGSku] varchar(18) NULL, 
	[VendorSku] varchar(19) NULL, 
	[Dimensions] varchar(105) NULL, 
	[Description] varchar(101) NULL, 
	[CategoryCode] varchar(3) NULL, 
	[DsgCost] varchar(6) NULL, 
	[Margin] varchar(15) NULL, 
	[Retail] varchar(7) NULL, 
	[PricingTiers] varchar(4) NULL, 
	[MinOrderQty] int NULL, 
	[Lifestyle] varchar(28) NULL, 
	[TagType] varchar(27) NULL, 
	[TagAssignment] varchar(18) NULL, 
	[IdealOnHand] int NULL, 
	[ProfitSku] varchar(11) NULL, 
	[ConfirmenedPO] varchar(10) NULL, 
	[AshcommSku] varchar(10) NULL, 
	[QtyToOrder] int NULL
);