CREATE TABLE [Merch_ExternalFiles].[FactPowerWalkTemplate] (

	[Name] varchar(10) NULL, 
	[Created] datetime2(6) NULL, 
	[DateConversion] datetime2(6) NULL, 
	[DayofWeek] int NULL, 
	[WeekNumber] int NULL, 
	[STORENUMBER] int NULL, 
	[STORENAME] varchar(22) NULL, 
	[VPM] varchar(9) NULL, 
	[RVPM] varchar(18) NULL, 
	[VPSales] varchar(13) NULL, 
	[DirectorVisualMerchandising] varchar(18) NULL, 
	[InhibitingSales] varchar(1) NULL, 
	[Comments] varchar(10) NULL, 
	[readytoWIN] varchar(10) NULL, 
	[Comments1] varchar(10) NULL, 
	[iOwnComplete] int NULL, 
	[Comments2] varchar(10) NULL, 
	[VPMCommitments] varchar(10) NULL, 
	[SalesManagerCommitments] varchar(10) NULL, 
	[Transfer] varchar(10) NULL, 
	[notransferWhy] varchar(10) NULL, 
	[Comments3] varchar(10) NULL, 
	[ProductlittostandardsSignageTagscorrect] int NULL, 
	[Showroomclean] int NULL, 
	[Furnitureaccessorizedintentionally] int NULL, 
	[25perofvignetteslookexceptional] int NULL, 
	[Furnitureplacementintentional] int NULL, 
	[TotalWOWScore] int NULL, 
	[PerfectVignetteCompletion] varchar(3) NULL, 
	[GSBTaggedStandards] varchar(3) NULL
);