CREATE TABLE [Merch_ExternalFiles].[SlotsbyCategory] (

	[Red_Yellow] varchar(6) NULL, 
	[Store_NameID] varchar(33) NULL, 
	[Store_Rank] varchar(1) NULL, 
	[Luxe_Rank] varchar(2) NULL, 
	[Luxe_SqFt] int NULL, 
	[Clearance_SqFt] int NULL, 
	[Disco_SqFt] int NULL, 
	[Regular_Non_Luxe_Slot_SqFt] int NULL, 
	[Outdoor_SqFt] int NULL, 
	[Year_Round_Outdoor] varchar(1) NULL, 
	[Outdoor] int NULL, 
	[Bedroom] int NULL, 
	[Youth] int NULL, 
	[Dining] int NULL, 
	[Ent_TV_Stands] int NULL, 
	[Ent_Wall_Unit] int NULL, 
	[Home_Office] int NULL, 
	[Motion_incl_Recliners] int NULL, 
	[Stationary] int NULL, 
	[Bedroom_Disco] int NULL, 
	[Youth_Disco] int NULL, 
	[Dining_Disco] int NULL, 
	[Ent_Disco] int NULL, 
	[Home_Office_Disco] int NULL, 
	[Motion_Disco] int NULL, 
	[Stationary_Disco] int NULL
);