CREATE TABLE [masterdata_productknowledge].[grpprc_source] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_keys] varchar(8000) NULL, 
	[ltd_filename] varchar(8000) NULL, 
	[ltd_DropProgram] varchar(8000) NULL, 
	[ltd_DropLocation] varchar(8000) NULL, 
	[ltd_row_number1] int NULL, 
	[ltd_count1] bigint NULL, 
	[ltd_row_number2] int NULL, 
	[ltd_count2] bigint NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_mergeInsert] bit NULL, 
	[GGRPCD] varchar(8000) NULL, 
	[GITEM] varchar(8000) NULL, 
	[GWHSE] varchar(8000) NULL, 
	[GVOLUM] decimal(38,18) NULL, 
	[GNSDIS] decimal(38,18) NULL, 
	[GOPEN1] decimal(38,18) NULL, 
	[GCOOPA] decimal(38,18) NULL, 
	[GOPEN2] decimal(38,18) NULL, 
	[GDFIDS] decimal(38,18) NULL, 
	[GPRICE] decimal(38,18) NULL, 
	[GPRIC] decimal(38,18) NULL, 
	[GFRTYN] varchar(8000) NULL, 
	[GCMSN] decimal(38,18) NULL, 
	[GCMPCT] decimal(38,18) NULL, 
	[GSDATE] datetime2(6) NULL, 
	[GEDATE] datetime2(6) NULL, 
	[GSSDAT] datetime2(6) NULL, 
	[GESDAT] datetime2(6) NULL, 
	[GEXCID] decimal(38,18) NULL, 
	[GUSETB] varchar(8000) NULL
);

