CREATE TABLE [masterdata_productknowledge].[itemseries] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[showroom] varchar(8000) NULL, 
	[grouping] int NULL, 
	[series_name] varchar(8000) NULL, 
	[series_no] varchar(8000) NULL, 
	[style] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[features] varchar(8000) NULL, 
	[retail] decimal(38,18) NULL, 
	[active] bit NULL, 
	[division] varchar(8000) NULL, 
	[date_archived] datetime2(6) NULL, 
	[ad_template] varchar(8000) NULL, 
	[news_template] varchar(8000) NULL, 
	[discontinued] bit NULL, 
	[serIsMarketInfo] bit NULL, 
	[serIsNewSeries] bit NULL, 
	[serIsFeaturedItem] bit NULL, 
	[serDiscoDate] datetime2(6) NULL, 
	[serSeriesDead] bit NULL, 
	[serExcl] bit NULL, 
	[old_style] varchar(8000) NULL, 
	[serKnockout] varchar(8000) NULL, 
	[serChildStyleCode] varchar(8000) NULL, 
	[serCodeLen] int NULL, 
	[serShowInPrBk] bit NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[acrec] varchar(8000) NULL, 
	[serLeatherMatchItem] bit NULL, 
	[serRepairKit] varchar(8000) NULL, 
	[serRepairKitDate] datetime2(6) NULL, 
	[serExclusiveComment] varchar(8000) NULL, 
	[serSeriesColor] varchar(8000) NULL, 
	[serStatus] varchar(8000) NULL, 
	[serRetailSalesCategory] int NULL, 
	[serColorID] int NULL, 
	[serDivisionCode] varchar(8000) NULL, 
	[serSupplierDirectShipOnly] bit NULL
);

