CREATE TABLE [Retail_DW_NonCore].[OpenOrderSummaryDetail] (

	[BODTransDate] date NULL, 
	[OrderID] varchar(8000) NOT NULL, 
	[OrderDate] date NULL, 
	[StoreID] varchar(8000) NOT NULL, 
	[ShipLocationID] varchar(8000) NULL, 
	[OrderType] varchar(8000) NULL, 
	[FulfillmentMethod] varchar(8000) NULL, 
	[FulfillmentStatus] varchar(8000) NULL, 
	[ContactStatus] varchar(8000) NULL, 
	[ContactDate] date NULL, 
	[FulfillmentDate] date NULL, 
	[PastDue] varchar(8000) NOT NULL, 
	[Filled] varchar(8000) NOT NULL, 
	[CustomerID] varchar(8000) NULL, 
	[CustomerName] varchar(8000) NULL, 
	[SalesPerson] varchar(8000) NULL, 
	[MerchSubTot] decimal(38,2) NULL, 
	[TaxAmt] decimal(38,2) NULL, 
	[DlvyChrg] decimal(38,2) NULL, 
	[TotalFulfilment] int NULL, 
	[TotalPieces] int NULL, 
	[ReservedPieces] int NULL, 
	[TotalCost] decimal(38,2) NULL, 
	[ReservedCost] decimal(38,2) NULL, 
	[TotalSales] decimal(38,2) NULL, 
	[ReservedSales] decimal(38,2) NULL, 
	[TotalVolume] decimal(38,2) NULL, 
	[ReservedVolume] decimal(38,2) NULL, 
	[TotalWeight] decimal(38,2) NULL, 
	[ReservedWeight] decimal(38,2) NULL
);