CREATE TABLE [Retail_Sales_Wrk].[Orders] (

	[Addon1Cost] numeric(18,2) NOT NULL, 
	[Addon2Cost] numeric(18,2) NOT NULL, 
	[Addon3Cost] numeric(18,2) NULL, 
	[Addon4Cost] numeric(18,2) NULL, 
	[AlertCodeID] varchar(50) NULL, 
	[AlternateTaxJurisdictionCode] varchar(255) NULL, 
	[AlternateTaxTransactionNbr] varchar(255) NULL, 
	[AltTaxTransactionIDDate] datetime2(3) NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[BillToParentID] varchar(50) NULL, 
	[CODAmt] numeric(18,2) NOT NULL, 
	[Comments] varchar(max) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[CreditAppNbr] varchar(50) NULL, 
	[CreditCardAmt] numeric(18,2) NOT NULL, 
	[CreditCardExpDate] varchar(50) NULL, 
	[CreditCardID] varchar(100) NULL, 
	[CreditCardNbr] varchar(100) NULL, 
	[CreditHoldCodeID] varchar(50) NULL, 
	[CreditMemoAsOfDate] datetime2(3) NULL, 
	[CSLastContact] date NULL, 
	[CSNextContact] date NULL, 
	[CurrentOrderValue] numeric(18,2) NOT NULL, 
	[CustClass] varchar(10) NULL, 
	[CustCreditChkFlg] bit NULL, 
	[Custom1] varchar(max) NULL, 
	[Custom2] varchar(100) NULL, 
	[Custom3] varchar(100) NULL, 
	[Custom4] varchar(100) NULL, 
	[CustomerID] varchar(50) NOT NULL, 
	[CustomerPONumber] varchar(50) NULL, 
	[CustPONbr] varchar(50) NULL, 
	[CustPriceCategory] varchar(10) NOT NULL, 
	[CustType] int NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DeliveryContactDate] date NULL, 
	[DeliveryContactStatusID] varchar(50) NULL, 
	[DepositHoldPct] numeric(18,2) NOT NULL, 
	[DesiredDate] date NULL, 
	[DirectShip_FreightCompanyID] varchar(50) NULL, 
	[DirShipAddlTaxAmt] numeric(18,2) NOT NULL, 
	[DirShipCustDiscntAmt] numeric(18,2) NOT NULL, 
	[DirShipDate] datetime2(3) NULL, 
	[DirShipDlvyChrg] numeric(18,2) NULL, 
	[DirShipDlvyChrgOverride] varchar(10) NULL, 
	[DirShipItems] int NOT NULL, 
	[DirShipStateTaxAmt] numeric(18,2) NULL, 
	[DirShipStateTaxID] varchar(100) NULL, 
	[DirShipStateTaxRate] numeric(18,4) NULL, 
	[DirShipStatus] varchar(10) NULL, 
	[DirShipStoreID] varchar(50) NULL, 
	[DirShipSubTot] numeric(18,2) NOT NULL, 
	[DirShipWhseMgmtShipped] datetime2(3) NULL, 
	[DirShipWhseMgmtTransmitted] datetime2(3) NULL, 
	[DiscDollarOrPct] varchar(50) NULL, 
	[DiscntCode] varchar(10) NULL, 
	[DiscntPct] numeric(18,2) NOT NULL, 
	[DlvryChrgOverrideReasonCodeID] varchar(50) NULL, 
	[DlvyAddlTaxAmt] numeric(18,2) NULL, 
	[DlvyChrg] numeric(18,2) NOT NULL, 
	[DlvyChrgOverride] varchar(10) NULL, 
	[DlvyCommissionCostPercent] numeric(18,2) NULL, 
	[DlvyCommissionDeliveryAmt] numeric(18,2) NULL, 
	[DlvyCommissionPercent] numeric(18,2) NULL, 
	[DlvyCommissionType] varchar(10) NULL, 
	[DlvyCustDiscntAmt] numeric(18,2) NOT NULL, 
	[DlvyDate] datetime2(3) NULL, 
	[DlvyItems] int NOT NULL, 
	[DlvyStateTaxAmt] numeric(18,2) NULL, 
	[DlvyStateTaxID] varchar(100) NULL, 
	[DlvyStateTaxRate] numeric(18,4) NULL, 
	[DlvyStatus] varchar(10) NULL, 
	[DlvyStoreID] varchar(50) NULL, 
	[DlvySubTot] numeric(18,2) NOT NULL, 
	[DlvyWhseMgmtShipped] datetime2(3) NULL, 
	[DlvyWhseMgmtTransmitted] datetime2(3) NULL, 
	[FinanceAmt] numeric(18,2) NOT NULL, 
	[FinanceApplied_StaffID] varchar(50) NULL, 
	[FinanceAppliedDateTime] datetime2(3) NULL, 
	[FinanceApprvAmt] numeric(18,2) NOT NULL, 
	[FinanceApprvNbr] varchar(100) NULL, 
	[FinanceAuthDate] datetime2(3) NULL, 
	[FinanceAuthNbr] varchar(100) NULL, 
	[FinanceHouseType] varchar(20) NULL, 
	[FinanceInsuranceFlg] varchar(10) NULL, 
	[FinancePaymentTypeID] varchar(50) NULL, 
	[FinanceReferenceNbr] varchar(50) NULL, 
	[FreightCompanyID] varchar(50) NULL, 
	[GlobalDiscount] numeric(18,2) NULL, 
	[GlobalDiscountedSubTotal] numeric(18,2) NULL, 
	[HomePhone] varchar(15) NULL, 
	[InstallationChrg] numeric(18,2) NOT NULL, 
	[InstallationChrgOverride] varchar(10) NULL, 
	[InvoiceDate] date NULL, 
	[IsAutoLineDiscountActive] bit NULL, 
	[LandedFreight] numeric(18,2) NOT NULL, 
	[LineDiscountOperationOrder] varchar(10) NULL, 
	[LineDiscountScheduleID] varchar(50) NULL, 
	[ManifestNbr] varchar(50) NULL, 
	[MarketingCode2ID] varchar(50) NULL, 
	[MarketingCodeID] varchar(50) NULL, 
	[MerchSubTot] numeric(18,2) NOT NULL, 
	[MultiShipMasterReference] varchar(50) NULL, 
	[NbrOfInvoices] int NULL, 
	[OperInit] varchar(10) NULL, 
	[OrderBookedStoreID] varchar(50) NOT NULL, 
	[OrderDate] date NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[OrderSourceID] varchar(50) NULL, 
	[OriginalInvoiceID] varchar(50) NULL, 
	[OrigMarketingCode1ID] varchar(50) NULL, 
	[OrigMarketingCode2ID] varchar(50) NULL, 
	[OrigMarketingCodeBooked] numeric(18,2) NULL, 
	[PickListPrinted] bit NULL, 
	[PickupAddlTaxAmt] numeric(18,2) NULL, 
	[PickupChrg] numeric(18,2) NULL, 
	[PickupChrgOverride] varchar(10) NULL, 
	[PickupCustDiscntAmt] numeric(18,2) NOT NULL, 
	[PickupDate] datetime2(3) NULL, 
	[PickupItems] int NOT NULL, 
	[PickupStateTaxAmt] numeric(18,2) NULL, 
	[PickupStateTaxID] varchar(100) NULL, 
	[PickupStateTaxRate] numeric(18,4) NULL, 
	[PickupStatus] varchar(10) NULL, 
	[PickupStoreID] varchar(50) NULL, 
	[PickupSubTot] numeric(18,2) NOT NULL, 
	[PickupWhseMgmtShipped] datetime2(3) NULL, 
	[PickupWhseMgmtTransmitted] datetime2(3) NULL, 
	[PointOfTax] varchar(1) NULL, 
	[PriceExceptionComment] varchar(max) NULL, 
	[RecStatus] varchar(1) NULL, 
	[RefundChkAmt] numeric(18,2) NOT NULL, 
	[Repossession] bit NULL, 
	[RevolvingOrderStatus] varchar(20) NULL, 
	[RewardPoints] int NULL, 
	[RouteCodeID] varchar(50) NULL, 
	[SalesTaxExmpNbr] varchar(50) NULL, 
	[ServiceAddr1] varchar(255) NULL, 
	[ServiceAddr2] varchar(255) NULL, 
	[ServiceCity] varchar(50) NULL, 
	[ServicePostalCodeID] varchar(50) NULL, 
	[ServiceStaffID] varchar(50) NULL, 
	[ServiceState] varchar(50) NULL, 
	[ServiceStoreID] varchar(50) NULL, 
	[ServiceStoreName] varchar(255) NULL, 
	[ServiceType] varchar(10) NULL, 
	[ShipInstr] varchar(max) NULL, 
	[ShipToAddr1] varchar(100) NULL, 
	[ShipToAddr2] varchar(100) NULL, 
	[ShipToCellPhone] varchar(15) NULL, 
	[ShipToCity] varchar(100) NULL, 
	[ShipToContact] varchar(50) NULL, 
	[ShipToEmailAddress] varchar(70) NULL, 
	[ShipToID] varchar(50) NULL, 
	[ShipToName] varchar(100) NULL, 
	[ShipToPostalCodeId] varchar(50) NULL, 
	[ShipToState] varchar(50) NULL, 
	[ShipZone] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[SpecOrderFlg] bit NULL, 
	[StopTime] varchar(50) NULL, 
	[TakenAddlTaxAmt] numeric(18,2) NULL, 
	[TakenChrg] numeric(18,2) NULL, 
	[TakenChrgOverride] varchar(10) NULL, 
	[TakenCustDiscntAmt] numeric(18,2) NOT NULL, 
	[TakenDate] datetime2(3) NULL, 
	[TakenItems] int NOT NULL, 
	[TakenStateTaxAmt] numeric(18,2) NULL, 
	[TakenStateTaxID] varchar(100) NULL, 
	[TakenStateTaxRate] numeric(18,4) NULL, 
	[TakenStatus] varchar(10) NULL, 
	[TakenStoreID] varchar(50) NULL, 
	[TakenSubTot] numeric(18,2) NOT NULL, 
	[TakenWhseMgmtShipped] datetime2(3) NULL, 
	[TakenWhseMgmtTransmitted] datetime2(3) NULL, 
	[TaxableFlg] bit NOT NULL, 
	[TermsID] varchar(50) NULL, 
	[TotAddlTaxAmt] numeric(18,2) NULL, 
	[TotCommissionableAmt] numeric(18,2) NOT NULL, 
	[TotCustDiscntAmt] numeric(18,2) NOT NULL, 
	[TotInvcAmt] numeric(18,2) NOT NULL, 
	[TotMerchCost] numeric(18,2) NOT NULL, 
	[TotOrderValue] numeric(18,2) NOT NULL, 
	[TotPaymentAmt] numeric(18,2) NOT NULL, 
	[TotSaleAmt] numeric(18,2) NOT NULL, 
	[TotShipWeight] numeric(18,2) NOT NULL, 
	[TotSpecOrderAmt] numeric(18,2) NOT NULL, 
	[TotStateTaxAmt] numeric(18,2) NULL, 
	[Trade_CustomerID] varchar(50) NULL, 
	[TradeDiscountPercent] numeric(18,2) NULL, 
	[TradeDiscountVersion] varchar(50) NULL, 
	[TransCodeID] int NOT NULL, 
	[TruckNbr] varchar(10) NULL, 
	[VoidedDate] date NULL, 
	[VoidedOrderReasonCodeID] varchar(50) NULL, 
	[WebTaxAmount] numeric(18,2) NULL, 
	[WorkPhone] varchar(15) NULL, 
	[WorkPhoneExt] varchar(10) NULL, 
	[NewEntryFlag] bit NULL, 
	[TransactionSaveTime] datetime2(3) NULL, 
	[TransactionStartTime] datetime2(3) NULL, 
	[DlvyChrgCalculated] numeric(18,2) NULL
);