CREATE TABLE [Retail_Sales_Wrk].[OrderItem] (

	[Addon1Cost] decimal(18,2) NOT NULL, 
	[Addon2Cost] decimal(18,2) NOT NULL, 
	[AutoFillDays] int NULL, 
	[AutoTransCodeID] int NULL, 
	[AutoTransOrderItemID] varchar(50) NULL, 
	[BookedStoreID] varchar(50) NULL, 
	[BrandID] varchar(50) NULL, 
	[BrokenCaseConvFactor] int NOT NULL, 
	[BrokenCaseMultiplier] numeric(18,2) NOT NULL, 
	[CalcLineValue] decimal(18,2) NOT NULL, 
	[CasePriceDefault] decimal(18,2) NOT NULL, 
	[CasePriceOverride] decimal(18,2) NOT NULL, 
	[CaseSellingPrice] decimal(18,2) NOT NULL, 
	[CaseUOM] varchar(5) NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[CommCost] decimal(18,2) NOT NULL, 
	[Comments] varchar(max) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[ConfiguratorInfo] varchar(max) NULL, 
	[CostSource] varchar(1) NULL, 
	[Custom1] varchar(max) NULL, 
	[Custom2] varchar(100) NULL, 
	[Custom3] varchar(100) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCommitted] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateUnCommitted] datetime2(3) NULL, 
	[DaysPastCommitted] int NOT NULL, 
	[DiscntFlg] bit NULL, 
	[DiscntPct] numeric(18,6) NULL, 
	[DiscountAmt] decimal(18,2) NULL, 
	[DiscountEndPrice] decimal(18,2) NULL, 
	[DiscountPct] numeric(18,6) NULL, 
	[DiscountStartPrice] decimal(18,2) NULL, 
	[DlvyCharge] decimal(18,2) NOT NULL, 
	[DlvyChrgDefault] decimal(18,2) NOT NULL, 
	[DlvyChrgOverride] decimal(18,2) NOT NULL, 
	[DlvyDate] datetime2(3) NULL, 
	[DlvyStatus] varchar(10) NULL, 
	[DlvyTypeCodeID] varchar(50) NULL, 
	[EDISalesOrderInfo] varchar(max) NULL, 
	[ExternalReferenceKey] varchar(255) NULL, 
	[FedExcTaxAmt] decimal(18,2) NOT NULL, 
	[FedExcTaxCode] int NULL, 
	[FedExcTaxFactor] numeric(18,2) NOT NULL, 
	[GrossExtLinePrice] decimal(18,2) NOT NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[ImbeddedTaxAmt] decimal(18,2) NULL, 
	[InstallationChrg] decimal(18,2) NOT NULL, 
	[InstallationChrgDefault] decimal(18,2) NOT NULL, 
	[InstallationChrgOverride] decimal(18,2) NOT NULL, 
	[ItemID] int NOT NULL, 
	[Kit_OriginalComponentAmt] decimal(18,2) NULL, 
	[KitComponentPrice] decimal(18,2) NULL, 
	[KitGroupNumber] varchar(20) NULL, 
	[LandedFreight] decimal(18,2) NOT NULL, 
	[LineCost] decimal(18,2) NOT NULL, 
	[LinkedToItemID] varchar(50) NULL, 
	[MaxTradeDiscountPercent] numeric(18,2) NULL, 
	[MultiLinkedFrom] varchar(250) NULL, 
	[MultiLinkedTo] varchar(50) NULL, 
	[NatlTaxExempt] bit NULL, 
	[NetExtLinePrice] decimal(18,2) NOT NULL, 
	[ObsoleteID] varchar(10) NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[OrderItemType] varchar(1) NULL, 
	[PiecePriceDefault] decimal(18,2) NOT NULL, 
	[PiecePriceOverride] decimal(18,2) NOT NULL, 
	[PieceSellingPrice] decimal(18,2) NOT NULL, 
	[PieceUOM] varchar(5) NULL, 
	[POLineID] int NULL, 
	[PriceCategory] varchar(50) NULL, 
	[PriceOverrideStaffID] varchar(50) NULL, 
	[PriceVarianceExceptionReasonCodeID] varchar(50) NULL, 
	[ProdDiscntAmt] decimal(18,2) NOT NULL, 
	[ProdDiscntCode] varchar(50) NULL, 
	[ProductAdjID] varchar(50) NULL, 
	[ProductCasePrice] decimal(18,2) NOT NULL, 
	[ProductDesc] varchar(100) NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[ProductPiecePrice] decimal(18,2) NOT NULL, 
	[ProductSubstCode] varchar(50) NULL, 
	[ProductTypeID] varchar(4) NOT NULL, 
	[PurchaseOrderID] varchar(50) NULL, 
	[PurchaseStatusCodeID] varchar(50) NULL, 
	[PurchaseStatusID] varchar(10) NULL, 
	[QtyCommitted] int NOT NULL, 
	[QtyOrdered] int NOT NULL, 
	[QtyUndelivered] int NOT NULL, 
	[RcvdPODate] datetime2(3) NULL, 
	[RcvdPOLineID] int NULL, 
	[RcvdPONbr] varchar(50) NULL, 
	[RcvdPurchaseOrderID] varchar(50) NULL, 
	[ReasonCodeID] varchar(50) NULL, 
	[RecStatus] varchar(1) NULL, 
	[ResponsibilityKey] varchar(50) NULL, 
	[ResponsibilityType] varchar(50) NULL, 
	[ResponsibilityWarrantyID] varchar(50) NULL, 
	[RewardTypeCode] varchar(5) NULL, 
	[RewardValue] numeric(18,2) NOT NULL, 
	[SalesCommissionAsIsSpiffTableID] varchar(50) NULL, 
	[SalesDiscountID] varchar(50) NULL, 
	[SerialTrackFlg] bit NULL, 
	[ServiceMerchandise_ItemID] int NULL, 
	[ServiceMerchandise_OrderID] varchar(50) NULL, 
	[ServiceOrder_ItemID] int NULL, 
	[ServiceOrder_OrderID] varchar(50) NULL, 
	[ServiceOrderID] varchar(50) NULL, 
	[ServiceProblemCodeID] varchar(50) NULL, 
	[ServiceRA_OrderID] varchar(50) NULL, 
	[ServiceRA_VendorID] varchar(50) NULL, 
	[ServiceRAComments] varchar(max) NULL, 
	[ServiceRANumber] varchar(50) NULL, 
	[ServiceRAOrderDate] date NULL, 
	[ServiceRAVendor_PostalCodeID] varchar(50) NULL, 
	[ServiceRAVendorAddress1] varchar(50) NULL, 
	[ServiceRAVendorAddress2] varchar(50) NULL, 
	[ServiceRAVendorCity] varchar(35) NULL, 
	[ServiceRAVendorName] varchar(50) NULL, 
	[ServiceRAVendorState] varchar(50) NULL, 
	[ServiceReinstatedOrder_ItemID] int NULL, 
	[ServiceReinstatedOrder_OrderID] varchar(50) NULL, 
	[ServiceStatusCodeID] varchar(20) NULL, 
	[ServiceStatusLastChangeDateTime] datetime2(3) NULL, 
	[ShipLocnID] varchar(50) NULL, 
	[ShippingTrackingNbr] varchar(50) NULL, 
	[SoftKit_ProductID] varchar(50) NULL, 
	[SoftKit_ProductSubstitutionID] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[SpecialOrder_Frame] varchar(max) NULL, 
	[SpecialOrder_Option1] varchar(50) NULL, 
	[SpecialOrder_Option2] varchar(50) NULL, 
	[SpecialOrder_Option3] varchar(50) NULL, 
	[SpecialPriceSourceID] varchar(50) NULL, 
	[SpecOrderFlg] bit NULL, 
	[SpecOrderInfo] varchar(max) NULL, 
	[SpecPrice] decimal(18,2) NOT NULL, 
	[SpecPriceEnDate] datetime2(3) NULL, 
	[SpecPriceFlg] bit NULL, 
	[SpecPriceStDate] datetime2(3) NULL, 
	[SpiffOverrideAmt] decimal(18,2) NULL, 
	[StoreID] varchar(50) NULL, 
	[SubstProductID] varchar(50) NULL, 
	[SuggestedRetail] decimal(18,2) NULL, 
	[TaxableFlg] bit NOT NULL, 
	[TotCost] decimal(18,2) NOT NULL, 
	[TotDaysCommitted] int NOT NULL, 
	[TotShipWeight] numeric(18,2) NULL, 
	[TradeDiscountPercent] numeric(18,2) NULL, 
	[TradeDiscountTaken] decimal(18,2) NULL, 
	[TransCodeID] int NOT NULL, 
	[VendorID] varchar(50) NULL, 
	[VendorModelNbr] varchar(max) NULL, 
	[WarrantyID] varchar(50) NULL, 
	[WrittenDate] datetime2(3) NULL, 
	[ProductKey] bigint NULL, 
	[ProductName] varchar(500) NULL, 
	[SerialNumber] varchar(50) NULL, 
	[ItemCommCategory] varchar(20) NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[InvoiceDate] date NULL, 
	[NewEntryFlag] bit NULL, 
	[OrderFulfillmentID] varchar(50) NULL, 
	[ProtectionPlanID] varchar(50) NULL, 
	[ProtectionPlanRegisterID] varchar(50) NULL, 
	[ProtectionPlanPrice] decimal(18,2) NULL, 
	[ProtectionPlanCost] decimal(18,2) NULL, 
	[ServiceTech_StaffID] varchar(50) NULL
);