CREATE TABLE [Retail_Miniapps].[SeriesMaster] (

	[operation] varchar(8000) NULL, 
	[ACTIVE] varchar(8000) NULL, 
	[Buyer_Notes] varchar(8000) NULL, 
	[custom_orderable] bit NULL, 
	[Group_ID] varchar(8000) NULL, 
	[LifeStyle_ID] int NULL, 
	[Notes_To_Store] varchar(8000) NULL, 
	[Prod_Brand] varchar(8000) NULL, 
	[Series_ID] varchar(8000) NULL, 
	[Std_Finish] varchar(8000) NULL, 
	[StoreBrand_ID] varchar(8000) NULL, 
	[Vendor_ID] varchar(8000) NULL, 
	[Vendor_Style] varchar(8000) NULL, 
	[VendorStyle_ID] varchar(8000) NULL, 
	[dominant_product_id] varchar(8000) NULL, 
	[CAD] varchar(8000) NULL, 
	[FloorCount] int NULL, 
	[Collection] varchar(8000) NULL, 
	[StoryID] int NULL, 
	[StoryDetailID] varchar(8000) NULL, 
	[ProgramID] varchar(8000) NULL, 
	[PricePointSegmentation] varchar(8000) NULL
);