CREATE TABLE [MasterData_Product_Enh].[ProductInfo] (
    [SKU]                         VARCHAR (20)    NOT NULL,
    [AFISKU]                      VARCHAR (30)    NULL,
    [SKUDescription1]             VARCHAR (50)    NULL,
    [SKUDescription2]             VARCHAR (50)    NULL,
    [SKUName]                     VARCHAR (100)   NULL,
    [VendorModelNumber]           VARCHAR (50)    NULL,
    [VendorID]                    VARCHAR (20)    NULL,
    [SalePrice]                   DECIMAL (19, 4) NULL,
    [ListPrice]                   DECIMAL (19, 4) NULL,
    [LandedCost]                  DECIMAL (19, 4) NULL,
    [AverageLandedCost]           DECIMAL (19, 4) NULL,
    [ReplacementCost]             DECIMAL (19, 4) NULL,
    [StoreBrandID]                VARCHAR (20)    NULL,
    [DefaultStoreBrandID]         VARCHAR (20)    NULL,
    [PurchaseStatus]              VARCHAR (20)    NULL,
    [ProductStatus]               VARCHAR (20)    NULL,
    [SeriesID]                    VARCHAR (20)    NULL,
    [Depth]                       DECIMAL (18, 4) NULL,
    [Height]                      DECIMAL (18, 4) NULL,
    [Width]                       DECIMAL (18, 4) NULL,
    [StorageDepth]                DECIMAL (18, 4) NULL,
    [StorageHeight]               DECIMAL (18, 4) NULL,
    [StorageWidth]                DECIMAL (18, 4) NULL,
    [CubicFeet]                   DECIMAL (18, 4) NULL,
    [DeliveryVolume]              DECIMAL (18, 4) NULL,
    [UnloadTime]                  DATETIME2 (3)   NULL,
    [SpecialOrderFlag]            BIT             NULL,
    [GroupID]                     VARCHAR (50)    NOT NULL,
    [SubGroupID]                  VARCHAR (20)    NULL,
    [SubGroupName]                VARCHAR (100)   NULL,
    [PPPGroupID]                  VARCHAR (10)    NULL,
    [CollectionID]                VARCHAR (50)    NULL,
    [CollectionName]              VARCHAR (100)   NULL,
    [ProductCollectionLifestyle]  VARCHAR (50)    NULL,
    [ProductTypeID]               VARCHAR (4)     NOT NULL,
    [ServiceProductTypeID]        VARCHAR (20)    NULL,
    [InventoryManagementStatusID] INT             NULL,
    [InventoryTierID]             VARCHAR (10)    NULL,
    [AverageCost]                 DECIMAL (19, 4) NULL,
    [CommonDescription]           VARCHAR (50)    NULL,
    [PurchaseStatusCodeID]        VARCHAR (20)    NULL,
    [ItemCommCategory]            VARCHAR (5)     NULL,
    [CommCostAddonPercent]        DECIMAL (19, 4) NULL,
    [IsDiscountable]              CHAR (1)        NULL,
    [DateCreated]                 DATETIME2 (3)   NULL,
    [DateChanged]                 DATETIME2 (3)   NULL,
    [VendorStyleID]               VARCHAR (30)    NULL,
    [VendorStyle]                 VARCHAR (50)    NULL,
    [DominantProductID]           VARCHAR (20)    NULL,
    [PricePointSegmentation]      VARCHAR (20)    NULL,
    [PricePoint]                  DECIMAL (19, 4) NULL,
    [ProductStatusDate]           DATETIME2 (3)   NULL,
    [RecordType]                  INT             NULL,
    [FinanceUseFee]               DECIMAL (19, 4) NULL,
    [IsKit]                       CHAR (1)        NULL,
    [IsMaster]                    BIT             NULL
);