CREATE VIEW [Quality_DW_Wrk].[v_FactAFISalesForecast] AS
SELECT 
	     SCPFBRT.Scp_Seq_Nbr    AS [Sequence Number]
      ,LRF.[ItemSKU]    AS [AFI Item Number]
     -- ,LRF.[Warehouse]  AS [AFI Warehouse]
	    --,[Drp_Plnr_ID] AS [DRP Planner ID]
      ,[Fcst_1_ID]+' '+[Fcst_2_ID]+' '+[Fcst_3_ID]	   AS [Forecast ID]
      ,[Lvl_Nbr]	   AS [Forecast Level Number]
      ,[Abc_3_Code]    AS [Alternate ABC-3 Code]
      ,[Abc_Ip_Code]   AS [IP ABC Code]
      ,[Fcst_Plnr_ID] AS [Forecast Planner ID]
      ,[Usr_01_Text]   AS [Field 1]
      ,[Usr_07_Text]   AS [Product Type]
      ,[Usr_20_Text]   AS [Field 17]
	    ,CASE WHEN [Usr_22_Text] ='L' THEN 'L' ELSE '' END  AS [Product Watch Code]
      ,[Usr_25_Text]   AS [Part Flag]
      ,[Prod_Grp_ID]	 AS [Product Group ID]
      ,[Fcst_Type_Code]  AS [Forecast Type Code]
      ,[Dmd_Actl_Vld_Nbr] AS [Valid Demand]
      ,SCPFBRT.[Std_Dev_Sys_Frc_Qty] AS [Forced Sys Std Deviation]
      ,[Perm_Compt_Qty]    AS [Perminent Component Quantity]
      ,[Uprc_Value]       AS [Unit Price]
      ,[Drvd_Fcst_Fctr]    AS [Derived Forecast Factor]
      ,[Drvd_Item_ID]       AS [Derived Forecast Key]
      ,[Drvd_Fcst_Lvl_Nbr] AS [Derived Forecast Level Number]
      ,[UCost_Value]       AS [Unit Cost]
      ,[Unit_Cube_Ft_Qty]  AS [Cubic Feet]
      ,[Trend_Compt_Qty]   AS [Trend Component Quantity]
      ,[Dmd_Mgmt_Vld_Nbr]  AS [Mgnmt Valid Demand]
      ,[Abc_Primry_Code]  AS [ABC Primary Code]
      ,[Usr_09_Text]    AS [Vendor Name]
     -- ,LRF.[ResultFC1]  AS [Period 1 Resultant Forecast]
     -- ,LRF.[ResultFC2]  AS [Period 2 Resultant Forecast]
      --,LRF.[ResultFC3]  AS [Period 3 Resultant Forecast]
      --,LRF.[ResultFC4]  AS [Period 4 Resultant Forecast]
     -- ,LRF.[ResultFC5]  AS [Period 5 Resultant Forecast]
     -- ,LRF.[ResultFC6]  AS [Period 6 Resultant Forecast]
     -- ,LRF.[ResultFC7]  AS [Period 7 Resultant Forecast]
      --,LRF.[ResultFC8]  AS [Period 8 Resultant Forecast]
      --,LRF.[ResultFC9]  AS [Period 9 Resultant Forecast]
      --,LRF.[ResultFC10] AS [Period 10 Resultant Forecast]
      --,LRF.[ResultFC11] AS [Period 11 Resultant Forecast]
      --,LRF.[ResultFC12] AS [Period 12 Resultant Forecast]
	   -- ,[Uprc_Value] *(ResultFC1+ResultFC2+ResultFC3+ResultFC4+ResultFC5+
      -- ResultFC6+ResultFC7+ResultFC8+ResultFC9+ResultFC10+ResultFC11+ResultFC12)	AS [Total Forecasted Sales]
	   -- ,UCost_Value *(ResultFC1+ResultFC2+ResultFC3+ResultFC4+ResultFC5+
     --  ResultFC6+ResultFC7+ResultFC8+ResultFC9+ResultFC10+ResultFC11+ResultFC12)	AS [Total Forecasted Costs]
  FROM [$(Databricks)].[wholesale_demandplanning_afi].[scp_fcst_root] SCPFBRT 
  JOIN [$(Databricks)].[wholesale_demandplanning_afi].[logresultantforecast] LRF ON LRF.ScpSeqNbr=SCPFBRT.Scp_Seq_Nbr
 LEFT JOIN [$(Databricks)].[wholesale_demandplanning_afi].[scpiprt] SCPIPRT  ON SCPFBRT.Scp_Seq_Nbr=SCPIPRT.Scp_Seq_Nbr
WHERE Lvl_Nbr = 2
