CREATE TABLE [AFISales_DW].[FactOpenOrdersSnapshotWeekly]
    (
        [RowID]                           BIGINT          NOT NULL, -- IDENTITY (1, 1)
        [Order Taken Date]                [DATE]           NULL,
        [Order Number]                    [VARCHAR](10)    NULL,
        [Item Sequence Number]            [DECIMAL](7, 0)  NULL,
        [Account And ShipTo Number]       [VARCHAR](13)    NULL,
        [Customer Account Number]         [CHAR](8)        NULL,
        [Customer Shipto Number]          [CHAR](4)        NULL,
        [SalesTerritoryID]                [BIGINT]         NULL,
        [Territory]                       [VARCHAR](10)    NULL,
        [Item Key]                        [VARCHAR](22)    NOT NULL,
        [Item Sku]                        [VARCHAR](15)    NOT NULL,
        [Sales Division Code]             [CHAR](1)        NULL,
        [Billto Address ID]               [INT]            NULL,
        [Shipto Address ID]               [INT]            NULL,
        [Warehouse]                       [CHAR](3)        NOT NULL,
        [Item Status]                     [CHAR](3)        NULL,
        [Sales Category Code]             [CHAR](3)        NULL,
        [Open Order Amount]               [DECIMAL](19, 2) NULL,
        [Open Order Quantity]             [DECIMAL](13, 3) NULL,
        [Back Order Amount]               [DECIMAL](13, 3) NULL,
        [Order Arrival Mode]              [CHAR](2)        NULL,
        [Back Order Quantity]             [DECIMAL](13, 3) NULL,
        [Original Promise Date]           [DATE]           NULL,
        [Current Promise Date]            [DATE]           NULL,
        [Estimated Delivery Date]         [DATE]           NULL,
        [Initial Promise Date]            [DATE]           NULL,
        [Original Request Date]           [DATE]           NULL,
        [Current Request Date]            [DATE]           NULL,
        [Primary Order Type]              [VARCHAR](30)    NULL,
        [Secondary Order Type]            [VARCHAR](30)    NULL,
        [3rd Order Type]                  [VARCHAR](30)    NULL,
        [4th Order Type]                  [VARCHAR](30)    NULL,
        [Inventory Allocated Flag]        [DECIMAL](1, 0)  NULL,
        [Current Load Date]               [DATE]           NULL,
        [Count of Load Date Changes]      [DECIMAL](3, 0)  NULL,
        [Load Lead Time]                  [DECIMAL](2, 0)  NULL,
        [Shipping Instructions]           [VARCHAR](30)    NULL,
        [RegionCode_RepID_Cat]            [VARCHAR](13)    NULL,
        [Sales Region Code]               [CHAR](3)        NULL,
        [Sales Rep ID]                    [CHAR](5)        NULL,
        [Customer SKU/Package]            [VARCHAR](30)    NULL,
        [Customer Shipto Division Number] [VARCHAR](15)    NULL,
        [Open Order Discounts]            [DECIMAL](13, 3) NULL,
        [Open Order Freight]              [DECIMAL](13, 3) NULL,
        [Trip Numbers]                    [VARCHAR](650)   NULL,
        [Customer PO]                     [VARCHAR](22)    NULL,
        [SnapshotDate]                    [DATE]           NULL
    )

