CREATE TABLE [Retail_Sales_Enh].[SalesOrderLineHistory] (
    [Source]                             CHAR (1)        NULL,
    [SourceSystem]                       VARCHAR (30)    NOT NULL,
    [BtaID]                              VARCHAR (50)    NOT NULL,
    [SalesDataTypeKey]                   INT             NOT NULL,
    [AsIsSaleReasonCodeID]               VARCHAR (50)    NULL,
    [BaseOrderID]                        VARCHAR (30)    NOT NULL,
    [SourceOrderID]                      VARCHAR (30)    NOT NULL,
    [TransDate]                          DATE            NOT NULL,
    [TransDateKey]                       BIGINT          NOT NULL,
    [OrderDate]                          DATE            NULL,
    [OrderDateKey]                       BIGINT          NULL,
    [LineNumber]                         INT             NULL,
    [LineStatus]                         VARCHAR (30)    NOT NULL,
    [ItemDescription]                    VARCHAR (255)   NULL,
    [SKU]                                VARCHAR (20)    NOT NULL,
    [QuantityOrdered]                    DECIMAL (19, 4) NOT NULL,
    [NetPrice]                           DECIMAL (19, 4) NOT NULL,
    [ProtectionPlanSKU]                  VARCHAR (20)    NULL,
    [ProtectionPlanID]                   VARCHAR (50)    NULL,
    [ProtectionPlanPrice]                DECIMAL (19, 4) NULL,
    [ProtectionPlanCost]                 DECIMAL (19, 4) NULL,
    [IsServiceItem]                      BIT             NULL,
    [HasProtectionPlan]                  BIT             NULL,
    [WarrantyEndDate]                    DATE            NULL,
    [StoreID]                            INT             NOT NULL,
    [KitOrPackageQuantity]               INT             NULL,
    [KitOrPackageSKU]                    VARCHAR (20)    NULL,
    [NetCost]                            DECIMAL (19, 4) NULL,
    [CategoryID]                         VARCHAR (50)    NOT NULL,
    [GroupID]                            VARCHAR (50)    NULL,
    [CustomerID]                         VARCHAR (50)    NOT NULL,
    [DiscountCode]                       VARCHAR (10)    NULL,
    [DeliveryStoreID]                    VARCHAR (30)    NOT NULL,
    [DeliveryTypeCodeID]                 VARCHAR (20)    NOT NULL,
    [SalesPersonID]                      VARCHAR (50)    NOT NULL,
    [ServiceTypeID]                      VARCHAR (10)    NULL,
    [TransCodeID]                        INT             NOT NULL,
    [VendorID]                           VARCHAR (50)    NULL,
    [VoidedReasonCodeID]                 VARCHAR (50)    NULL,
    [DateChanged]                        DATETIME2 (3)   NULL,
    [DateCreated]                        DATETIME2 (3)   NULL,
    [PurchaseStatusCodeID]               VARCHAR (50)    NULL,
    [SpecialOrder]                       BIT             NULL,
    [UpdateDateTime]                     DATETIME2 (3)   NULL,
    [UpdateTypeID]                       VARCHAR (4)     NULL,
    [SuperOrderID]                       VARCHAR (50)    NULL,
    [TransCodeGroup]                     VARCHAR (50)    NULL,
    [ItemCommCategory]                   VARCHAR (10)    NULL,
    [DeliveryStatus]                     VARCHAR (20)    NULL,
    [ProductDiscountCode]                VARCHAR (50)    NULL,
    [PriceVarianceExceptionReasonCodeID] VARCHAR (50)    NULL,
    [PriceOverrideStaffID]               VARCHAR (50)    NULL,
    [FRLocationID]                       VARCHAR (50)    NULL,
    [GrossMultiplier]                    INT             NULL,
    [REACCategory]                       VARCHAR (50)    NULL
);