CREATE TABLE [MasterData_HR_UKG_AGR].[CompanyDetails] (

	[isMasterCompany] bit NULL, 
	[masterCompanyId] varchar(10) NULL, 
	[companyId] varchar(10) NULL, 
	[companyCode] varchar(10) NULL, 
	[companyDoingBusinessAsName] varchar(50) NULL, 
	[companyGLSegment] varchar(10) NULL, 
	[companyName] varchar(50) NULL, 
	[taxCalculationGroupId] varchar(10) NULL, 
	[contractNumber] varchar(20) NULL, 
	[addressLine1] varchar(50) NULL, 
	[addressLine2] varchar(50) NULL, 
	[addressCity] varchar(50) NULL, 
	[addressState] varchar(10) NULL, 
	[addressZipCode] varchar(20) NULL, 
	[addressCountry] varchar(10) NULL, 
	[addressCounty] varchar(50) NULL, 
	[phoneNumber] varchar(20) NULL, 
	[phoneNumberExtension] varchar(10) NULL, 
	[federalTaxId] varchar(20) NULL, 
	[otherFederalTaxId] varchar(20) NULL, 
	[organizationLevel1Label] varchar(50) NULL, 
	[organizationLevel2Label] varchar(50) NULL, 
	[organizationLevel3Label] varchar(50) NULL, 
	[organizationLevel4Label] varchar(50) NULL, 
	[currencyCode] varchar(10) NULL, 
	[dateOfBusinessClosure] varchar(50) NULL, 
	[usePositionManagement] bit NULL, 
	[useMultipleJobGroups] bit NULL, 
	[integrationRecordId] varchar(50) NULL, 
	[key] int NULL, 
	[dwLoadDateTime] datetime2(6) NULL, 
	[dataSource] varchar(10) NULL
);