
CREATE TABLE [Marketing].[AdFundsRequest](
	[RequestID] [int] NULL,
	[AccountName] [varchar](80) NULL,
	[CustomerNumber] [varchar](820) NULL,
	[ShiptoNumber] [varchar](10) NULL,
	[Owner] [varchar](60) NULL,
	[VicePresident] [varchar](80) NULL,
	[Status] [varchar](60) NULL,
	[Amount] [decimal](8, 2) NULL,
	[CreatedDate] [datetime2](6) NULL,
	[FundType] [varchar](45) NULL,
	[Notes] [varchar](max) NULL,
	[Division] [varchar](70) NULL,
	[EventName] [varchar](80) NULL,
	[SpecialDiscountCode] [varchar](300) NULL,
	[AddedByUser] [varchar](50) NULL,
	[DateAdded] [datetime2](6) NULL,
	[ChangeByUser] [varchar](50) NULL,
	[DateChange] [datetime2](6) NULL,
	[EventStartDate] [date] NULL,
	[EventEndDate] [date] NULL,
	[UsedFor] [varchar](30) NULL,
	[Goal] [varchar](50) NULL,
	[PercentOrAmount] [varchar](80) NULL,
	[CategoryFocusedOn] [varchar](100) NULL,
	[CreditIssuedBy] [varchar](150) NULL,
	[CreditIssuedOn] [datetime2](6) NULL,
	[ApprovedBy] [varchar](150) NULL,
	[ApprovedOn] [datetime2](6) NULL,
	[RejectedBy] [varchar](150) NULL,
	[RejectedOn] [datetime2](6) NULL,
	[ParentVicePresident] [varchar](150) NULL,
	[CreditCode] [varchar](10) NULL,
	[CreditMemoComments] [varchar](350) NULL,
	[DoNotPrint] [char](1) NULL
) 

