
CREATE TABLE [CostAccounting_Enh].[AFI_ADH_OutBill_PreviousWeek]
(
	[Trip Number] [int] NULL,
	[Warehouse] [varchar](5) NULL,
	[TripType] [varchar](1000) NULL,
	[Fiscal_WeekEnding] [date] NULL,
	[FiscalMonthYearName] [varchar](1000) NULL,
	[Fiscal Year Period] [varchar](1000) NULL,
	[Account] [varchar](1000) NULL,
	[Shipto] [varchar](1000) NULL,
	[Account And Shipto Number] [varchar](1000) NULL,
	[Customer Name] [varchar](1000) NULL,
	[Reporting Business Type] [varchar](1000) NULL,
	[Freight Code] [varchar](1000) NULL,
	[Freight Code Description] [varchar](1000) NULL,
	[AFI Freight Code] [varchar](1000) NULL,
	[Route Zone] [varchar](1000) NULL,
	[Ext_LineItemFreight] [varchar](1000) NULL,
	[Ext_CommAdjFreight] [varchar](1000) NULL,
	[SpcCharge_Freight] [varchar](1000) NULL,
	[Total_AFIFreight_Revenue] [varchar](1000) NULL,
	[AFI Outbound Freight Exp from ADS Billing] [varchar](1000) NULL,
	[AFI Outbound Freight Exp from ADL Billing] [varchar](1000) NULL,
	[Flag_ADH_Responsible] [varchar](1000) NULL,
	[Billing_Static_Date] [varchar](1000) NULL,
	[ADS_Region] [varchar](1000) NULL,
	[Flag_Container] [varchar](1000) NULL,
	[Flag_Invoiced] [varchar](1000) NULL,
	[Flag_Multi_TripType] [varchar](1000) NULL,
	[Invoice_Week_ADS] [varchar](1000) NULL,
	[Invoice_Week_ADL] [varchar](1000) NULL,
	[Current_Accrual_Week_ADS] [varchar](1000) NULL,
	[Current ADS Outbound In Transit Accrual] [varchar](1000) NULL,
	[First_Accrual_Week_ADS] [varchar](1000) NULL,
	[Previous ADS Outbound In Transit Accrual] [varchar](1000) NULL,
	[Current_Accrual_Week_ADL] [varchar](1000) NULL,
	[Current ADL Outbound In Transit Accrual] [varchar](1000) NULL,
	[First_Accrual_Week_ADL] [varchar](1000) NULL,
	[Previous ADL Outbound In Transit Accrual] [varchar](1000) NULL,
	[ADH - Data Source] [varchar](1000) NULL,
	[TransactionalBilling - Freight Solution Reason] [varchar](1000) NULL,
	[TransactionalBilling - Fuel Solution Reason] [varchar](1000) NULL,
	[AFI_Unit] [varchar](1000) NULL,
	[AFI_Nature] [varchar](1000) NULL
)

