CREATE TABLE [CostAccounting_Enh].[DC_LaborRollups_CalculatedData] (
    [Warehouse] VARCHAR (10) NULL,
    [Warehouse_Desc] VARCHAR (20) NULL,
    [Whse_SortOrder] INT NULL,
    [Department] VARCHAR (10) NULL,
    [Department_Desc] VARCHAR (100) NULL,
    [Activity_Desc] VARCHAR (100) NULL,
    [WeekEnding] DATE NULL,
    [Units_BED] INT NULL,
    [Units_DOM] INT NULL,
    [Units_IMP] INT NULL,
    [Units_IMPUP] INT NULL,
    [Units_UPH] INT NULL,
    [Units_RTA] INT NULL,
    [Units_Gross] INT NULL,
    [Yard_DirMovesFrom] INT NULL,
    [Yard_DirMovesTo] INT NULL,
    [Yard_UndirMoves] INT NULL,
    [Yard_TotalMoves] INT NULL,
    [GrossAmount_WithFreight] DECIMAL (16, 4) NULL,
    [GrossAmount_NoFreight] DECIMAL (16, 4) NULL,
    [FinProll_HeadCount] INT NULL,
    [FinProll_Hours_Regular] DECIMAL (16, 8) NULL,
    [FinProll_Hours_OT] DECIMAL (16, 8) NULL,
    [FinProll_Hours_Total] DECIMAL (16, 8) NULL,
    [FinProll_Hours_Other] DECIMAL (16, 8) NULL,
    [FinProll_Pay_Regular] DECIMAL (16, 8) NULL,
    [FinProll_Pay_OT] DECIMAL (16, 8) NULL,
    [FinProll_LaborDollars_Total] DECIMAL (16, 8) NULL,
    [FinProll_Direct_Percentage] DECIMAL (16, 8) NULL,
    [Avg_Reg_Rate_Prev] FLOAT (53) NULL,
    [Avg_OT_Rate_Prev] FLOAT (53) NULL,
    [PreProll_HeadCount] INT NULL,
    [PreProll_Reg_Hours] FLOAT (53) NULL,
    [PreProll_OT_Hours] FLOAT (53) NULL,
    [PreProll_Hours_Total] FLOAT (53) NULL,
    [PreProll_Other_Hours] FLOAT (53) NULL,
    [PreProll_Pay_Regular] FLOAT (53) NULL,
    [PreProll_Pay_OT] FLOAT (53) NULL,
    [PreProll_LaborDollarsTotal] FLOAT (53) NULL,
    [PreProll_Direct_Percentage] FLOAT (53) NULL,
    [FiscalWeekIndicator] INT NULL,
    [FiscalMonthIndicator] INT NULL,
    [FiscalYearIndicator] INT NULL,
    [FiscalYear] INT NULL,
    [FiscalMonthYearName] VARCHAR (30) NULL,
    [NonYard_SalesPerLaborHour] FLOAT (53) NULL,
    [NonYard_SalesPerUnit] FLOAT (53) NULL,
    [NonYard_PPH] FLOAT (53) NULL,
    [NonYard_PPH_NoOtherHrs] FLOAT (53) NULL,
    [NonYard_CostPerPiece] FLOAT (53) NULL,
    [NonYard_SalesPerEmployee] FLOAT (53) NULL,
    [NonYard_Pieces/HC_Ratio] FLOAT (53) NULL,
    [Yard_MPH] FLOAT (53) NULL,
    [Yard_MPH_NoOtherHrs] FLOAT (53) NULL,
    [Yard_CostPerMove] FLOAT (53) NULL,
    [Yard_Moves/HC_Ratio] FLOAT (53) NULL,
    [Yard_SalesPerMove] FLOAT (53) NULL,
    [Yard_UnitsSoldPerMove] FLOAT (53) NULL,
    [Flag_MostRecent_WeekEnding] VARCHAR (50) NULL,
    [RunChartCalcs_Units_Gross] INT NULL,
    [RunChartCalcs_CostPerPiece] FLOAT (53) NULL,
    [RunChartCalcs_PPH] FLOAT (53) NULL,
    [RunChartCalcs_OTLaborDollars] FLOAT (53) NULL,
    [RunChartCalcs_TotalLaborDollars] FLOAT (53) NULL,
    [RunChartCalcs_PiecesPerHC_Ratio] FLOAT (53) NULL,
    [RunChartCalcs_TotalYardMoves] FLOAT (53) NULL,
    [Hours_Moved_Out] FLOAT (53) NULL,
    [Hours_Moved_In] FLOAT (53) NULL,
    [Hours_TempLumper_In] FLOAT (53) NULL,
    [partition] VARCHAR (100) NULL,
    [Units_Gross_AVG] FLOAT (53) NULL,
    [Units_Gross_STD] FLOAT (53) NULL,
    [Units_Gross_ECL] FLOAT (53) NULL,
    [Units_Gross_LCL] FLOAT (53) NULL,
    [RunChartCalcs_CostPerPiece_AVG] FLOAT (53) NULL,
    [RunChartCalcs_CostPerPiece_STD] FLOAT (53) NULL,
    [RunChartCalcs_CostPerPiece_ECL] FLOAT (53) NULL,
    [RunChartCalcs_CostPerPiece_LCL] FLOAT (53) NULL,
    [RunChartCalcs_PPH_AVG] FLOAT (53) NULL,
    [RunChartCalcs_PPH_STD] FLOAT (53) NULL,
    [RunChartCalcs_PPH_ECL] FLOAT (53) NULL,
    [RunChartCalcs_PPH_LCL] FLOAT (53) NULL,
    [RunChartCalcs_OTLaborDollars_AVG] FLOAT (53) NULL,
    [RunChartCalcs_OTLaborDollars_STD] FLOAT (53) NULL,
    [RunChartCalcs_OTLaborDollars_ECL] FLOAT (53) NULL,
    [RunChartCalcs_OTLaborDollars_LCL] FLOAT (53) NULL,
    [RunChartCalcs_TotalLaborDollars_AVG] FLOAT (53) NULL,
    [RunChartCalcs_TotalLaborDollars_STD] FLOAT (53) NULL,
    [RunChartCalcs_TotalLaborDollars_ECL] FLOAT (53) NULL,
    [RunChartCalcs_TotalLaborDollars_LCL] FLOAT (53) NULL,
    [RunChartCalcs_PiecesPerHC_Ratio_AVG] FLOAT (53) NULL,
    [RunChartCalcs_PiecesPerHC_Ratio_STD] FLOAT (53) NULL,
    [RunChartCalcs_PiecesPerHC_Ratio_ECL] FLOAT (53) NULL,
    [RunChartCalcs_PiecesPerHC_Ratio_LCL] FLOAT (53) NULL,
    [Yard_TotalMoves_AVG] FLOAT (53) NULL,
    [Yard_TotalMoves_STD] FLOAT (53) NULL,
    [Yard_TotalMoves_ECL] FLOAT (53) NULL,
    [Yard_TotalMoves_LCL] FLOAT (53) NULL
)
    --WITH (
    --DATA_SOURCE = [AzureStorageGen2a],
    --LOCATION = N'/MasterData/Finance/DCLaborRollups/DC_LaborRollups_CalculatedData/',
    --FILE_FORMAT = [ParquetFileFormatSnappy],
    --REJECT_TYPE = VALUE,
    --REJECT_VALUE = 0
   -- );
