CREATE TABLE [masterdata_hr_ukg_dsg].[peopletimesheet_source] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_filename] varchar(max) NULL, 
	[ltd_DropProgram] varchar(max) NULL, 
	[ltd_DropLocation] varchar(max) NULL, 
	[ltd_row_number1] int NULL, 
	[ltd_count1] bigint NULL, 
	[ltd_row_number2] int NULL, 
	[ltd_count2] bigint NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_mergeInsert] bit NULL, 
	[TimeSheetID] bigint NULL, 
	[SourceDataID] varchar(max) NULL, 
	[SourceSystemID] int NULL, 
	[PeopleID] bigint NULL, 
	[EmployeeNumber] varchar(max) NULL, 
	[PayPeriod] int NULL, 
	[TransDateKey] int NULL, 
	[SourceLocationID] varchar(max) NULL, 
	[LocationKey] int NULL, 
	[TimeIn] datetime2(6) NULL, 
	[TimeOut] datetime2(6) NULL, 
	[Time] float NULL, 
	[SourcePayCodeID] varchar(max) NULL, 
	[PayCodeID] int NULL, 
	[PayCodeName] varchar(max) NULL, 
	[SourceTaskCodeID] varchar(max) NULL, 
	[TaskCodeID] varchar(max) NULL, 
	[TaskCodeName] varchar(max) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Rate] decimal(19,4) NULL, 
	[ExtCost] decimal(19,4) NULL, 
	[ApprovedByManager] bit NULL
);