CREATE TABLE [MasterData_ItemMaster_AFI_Wrk].[ITEMBL] (

	[JOENTL] numeric(10,0) NULL, 
	[JOSEQN] numeric(10,0) NULL, 
	[JOCODE] char(1) NULL, 
	[JOENTT] char(2) NULL, 
	[JODATE] char(6) NULL, 
	[JOTIME] numeric(10,0) NULL, 
	[JOJOB] char(10) NULL, 
	[JOUSER] char(10) NULL, 
	[JONBR] numeric(10,0) NULL, 
	[JOPGM] char(10) NULL, 
	[JOOBJ] char(10) NULL, 
	[JOLIB] char(10) NULL, 
	[JOMBR] char(10) NULL, 
	[JOCTRR] numeric(10,0) NULL, 
	[JOFLAG] char(1) NULL, 
	[JOCCID] numeric(10,0) NULL, 
	[JOUSPF] char(10) NULL, 
	[JOSYNM] char(8) NULL, 
	[JOINCDAT] char(1) NULL, 
	[JOMINESD] char(1) NULL, 
	[JORES] char(18) NULL, 
	[CREC] char(1) NOT NULL, 
	[ITNBR] char(15) NOT NULL, 
	[HOUSE] char(3) NOT NULL, 
	[ITCLS] char(4) NOT NULL, 
	[MALQT] numeric(11,3) NOT NULL, 
	[QTSMO] numeric(11,3) NOT NULL, 
	[ISSMO] numeric(13,3) NOT NULL, 
	[RECMO] numeric(13,3) NOT NULL, 
	[ADJMO] numeric(13,3) NOT NULL, 
	[BEGIN] numeric(10,3) NOT NULL, 
	[LTCOD] char(1) NOT NULL, 
	[LTMAN] numeric(4,1) NOT NULL, 
	[LTADM] numeric(3,1) NOT NULL, 
	[LTPUR] numeric(4,1) NOT NULL, 
	[LTVEN] numeric(4,1) NOT NULL, 
	[LTSAF] numeric(4,1) NOT NULL, 
	[LTREV] numeric(4,1) NOT NULL, 
	[LTADP] numeric(2,0) NOT NULL, 
	[MOHTQ] numeric(10,3) NOT NULL, 
	[AVCST] numeric(19,8) NOT NULL, 
	[LCOST] numeric(19,8) NOT NULL, 
	[STDUC] numeric(19,8) NOT NULL, 
	[ORDPT] numeric(10,3) NOT NULL, 
	[FXORQ] numeric(10,3) NOT NULL, 
	[SAFTY] numeric(10,3) NOT NULL, 
	[MPRPQ] numeric(10,3) NOT NULL, 
	[MPUPQ] numeric(10,3) NOT NULL, 
	[USEYR] numeric(13,3) NOT NULL, 
	[LACDT] numeric(7,0) NOT NULL, 
	[LDQOH] numeric(7,0) NOT NULL, 
	[CCFLG] char(1) NOT NULL, 
	[CCOMP] numeric(7,0) NOT NULL, 
	[CCODE] numeric(1,0) NOT NULL, 
	[CCTRN] numeric(7,0) NOT NULL, 
	[LPHDT] numeric(7,0) NOT NULL, 
	[NXCDT] numeric(7,0) NOT NULL, 
	[VNDNR] char(6) NOT NULL, 
	[PURUM] char(2) NOT NULL, 
	[UMCNV] numeric(10,5) NOT NULL, 
	[WHSLC] char(7) NOT NULL, 
	[AVCDV] char(1) NOT NULL, 
	[ISSYR] numeric(13,3) NOT NULL, 
	[USEMO] numeric(13,3) NOT NULL, 
	[QTSYR] numeric(13,3) NOT NULL, 
	[AMSMO] numeric(15,2) NOT NULL, 
	[AMSYR] numeric(15,2) NOT NULL, 
	[CAMMO] numeric(15,2) NOT NULL, 
	[CAMYR] numeric(15,2) NOT NULL, 
	[CSTMO] numeric(15,2) NOT NULL, 
	[CSTYR] numeric(15,2) NOT NULL, 
	[EAANU] numeric(13,3) NOT NULL, 
	[AVMEB] numeric(15,2) NOT NULL, 
	[AVSAL] numeric(15,2) NOT NULL, 
	[DOFLS] numeric(7,0) NOT NULL, 
	[DOFLU] numeric(7,0) NOT NULL, 
	[RPFLG] numeric(1,0) NOT NULL, 
	[CURPL] numeric(7,0) NOT NULL, 
	[PLREQ] numeric(10,3) NOT NULL, 
	[PHYOH] numeric(10,3) NOT NULL, 
	[FLSTK] char(1) NOT NULL, 
	[MDATE] numeric(7,0) NOT NULL, 
	[RECPL] numeric(10,3) NOT NULL, 
	[PALOC] numeric(10,3) NOT NULL, 
	[CRPLL] numeric(7,0) NOT NULL, 
	[FALQT] numeric(10,3) NOT NULL, 
	[CRPLB] numeric(7,0) NOT NULL, 
	[CRPLA] numeric(7,0) NOT NULL, 
	[RCPLB] numeric(10,3) NOT NULL, 
	[RCPLA] numeric(10,3) NOT NULL, 
	[FCYCT] char(1) NOT NULL, 
	[MPALC] numeric(10,3) NOT NULL, 
	[CMTLT] numeric(4,1) NOT NULL, 
	[CMFLT] numeric(4,1) NOT NULL, 
	[LTMAV] numeric(4,1) NOT NULL, 
	[LTPAV] numeric(4,1) NOT NULL, 
	[LTVAM] numeric(4,1) NOT NULL, 
	[SCPMO] numeric(13,3) NOT NULL, 
	[SCPYR] numeric(13,3) NOT NULL, 
	[SCCMO] numeric(15,2) NOT NULL, 
	[SCCYR] numeric(15,2) NOT NULL, 
	[SCPDT] numeric(7,0) NOT NULL, 
	[MPSFA] numeric(10,3) NOT NULL, 
	[SALBF] numeric(7,0) NOT NULL, 
	[SALAF] numeric(7,0) NOT NULL, 
	[LPOWU] char(10) NOT NULL, 
	[IBCTL] numeric(1,0) NOT NULL, 
	[SHPLP] numeric(9,0) NOT NULL, 
	[RECLP] numeric(13,3) NOT NULL, 
	[ITFLG] numeric(1,0) NOT NULL, 
	[ALCTL] numeric(3,0) NOT NULL, 
	[SCHCD] numeric(1,0) NOT NULL, 
	[EXTCD] char(1) NOT NULL, 
	[CFWCD] numeric(1,0) NOT NULL, 
	[PRLIN] char(5) NOT NULL, 
	[SUMCD] char(1) NOT NULL, 
	[SCHGP] char(5) NOT NULL, 
	[SMHCD] char(1) NOT NULL, 
	[SMHDT] numeric(7,0) NOT NULL, 
	[CONDS] char(4) NOT NULL, 
	[CONQT] numeric(10,3) NOT NULL, 
	[MODCD] char(4) NOT NULL, 
	[FGICD] numeric(1,0) NOT NULL, 
	[CNTLP] char(2) NOT NULL, 
	[ACALW] char(3) NOT NULL, 
	[BOMLW] char(3) NOT NULL, 
	[PLANIB] numeric(5,0) NOT NULL, 
	[FRQTIB] numeric(7,0) NOT NULL, 
	[ININ] char(1) NOT NULL, 
	[ITACIB] char(3) NOT NULL, 
	[LOTZIB] char(1) NOT NULL, 
	[BFFL] numeric(1,0) NOT NULL, 
	[UUSAIB] char(1) NOT NULL, 
	[UUSBIB] char(1) NOT NULL, 
	[UUCAIB] char(5) NOT NULL, 
	[UUCBIB] char(5) NOT NULL, 
	[UUCCIB] char(5) NOT NULL, 
	[UUQ1IB] numeric(11,3) NOT NULL, 
	[UUA1IB] numeric(15,2) NOT NULL, 
	[UUD1IB] numeric(7,0) NOT NULL, 
	[UU40IB] char(40) NOT NULL, 
	[UUIAIB] char(3) NOT NULL, 
	[STCF] char(1) NOT NULL, 
	[CCCL] char(10) NOT NULL, 
	[COTP] numeric(4,1) NOT NULL
);