CREATE TABLE [Retail_Corporate_Wrk].[ProtectionPlan] (

	[Operation] varchar(15) NULL, 
	[ATI_TaxClassID] varchar(50) NULL, 
	[CancellationDays] int NULL, 
	[CommissionPercent] decimal(18,2) NULL, 
	[Cost_GLAccountID] varchar(100) NULL, 
	[CostingMethod] varchar(10) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Description] varchar(255) NULL, 
	[IsInActive] bit NULL, 
	[IsOnlyForMembershipCustomers] bit NULL, 
	[LastBatchID] int NULL, 
	[ManagerOnly] bit NULL, 
	[MaxQuantity] int NULL, 
	[PlanID] varchar(50) NOT NULL, 
	[PlanTermsInfo] varchar(max) NULL, 
	[PricingMethod] varchar(10) NULL, 
	[ProtectionPlanID] varchar(100) NOT NULL, 
	[RecStatus] varchar(1) NULL, 
	[Sales_GLAccountID] varchar(100) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[TaxableFlag] bit NULL, 
	[TaxClassID] varchar(50) NULL, 
	[ThirdPartyCode] varchar(50) NULL, 
	[TimeStamp] datetime2(6) NULL, 
	[UseDefaultSellingPrice] bit NULL, 
	[WarrantyID] varchar(50) NULL
);