CREATE TABLE [Retail_Corporate_Wrk].[PurchaseOrder] (

	[Operation] varchar(15) NULL, 
	[ApprovalHold] int NULL, 
	[Base_PurchaseOrder] varchar(50) NULL, 
	[Base_PurchaseOrderID] varchar(50) NULL, 
	[BrokerID] varchar(40) NULL, 
	[BuyerStaffID] varchar(50) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[COMVendor] varchar(100) NULL, 
	[ContainerNumber] varchar(100) NULL, 
	[CountryID] varchar(50) NULL, 
	[Custom1] varchar(255) NULL, 
	[Custom2] varchar(255) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateClosed] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DeleteDate] datetime2(6) NULL, 
	[DlvyDate] datetime2(6) NULL, 
	[DockDate] datetime2(6) NULL, 
	[DontShipAfterDate] datetime2(6) NULL, 
	[DontShipBeforeDate] datetime2(6) NULL, 
	[EDISellingStoreID] varchar(50) NULL, 
	[EDIStatus] varchar(10) NULL, 
	[ExportDate] datetime2(6) NULL, 
	[First_HistoryID] int NULL, 
	[ForeignExchRate] decimal(18,2) NULL, 
	[ForeignFreight] decimal(18,2) NULL, 
	[ForeignMiscChrgs] decimal(18,2) NULL, 
	[ForeignTax] decimal(18,2) NULL, 
	[FreightAmt] decimal(19,4) NULL, 
	[ImportedDateTime] datetime2(6) NULL, 
	[ImportFobID] varchar(40) NULL, 
	[ImportOrderDescription] varchar(510) NULL, 
	[InventoryType] varchar(10) NULL, 
	[Landed1Active] int NULL, 
	[Landed2Active] int NULL, 
	[Last_HistoryID] int NULL, 
	[LastBatchID] int NULL, 
	[MiscChrgs] decimal(19,4) NULL, 
	[OpenAmt] decimal(19,4) NULL, 
	[OrderID] varchar(50) NULL, 
	[OrigTransDate] datetime2(6) NULL, 
	[PODate] datetime2(6) NOT NULL, 
	[POTypeID] int NOT NULL, 
	[PurchaseOrderID] varchar(50) NOT NULL, 
	[PurchaseOrderShipTypeID] varchar(50) NULL, 
	[PurchaseOrderTypeID] varchar(100) NULL, 
	[RecStatus] char(1) NULL, 
	[RequestDate] datetime2(6) NULL, 
	[SendOut] int NULL, 
	[SendOutEmailDate] datetime2(6) NULL, 
	[ShipFromID] varchar(20) NULL, 
	[ShippingTerms] varchar(510) NULL, 
	[ShipToAddr1] varchar(255) NULL, 
	[ShipToAddr2] varchar(255) NULL, 
	[ShipToCity] varchar(255) NULL, 
	[ShipToName] varchar(255) NULL, 
	[ShipToPostalCodeID] varchar(50) NULL, 
	[ShipToState] varchar(255) NULL, 
	[ShipVia] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[SpecialInstr] varchar(300) NULL, 
	[SpecialInstr2] varchar(max) NULL, 
	[SpecOrdFlg] bit NULL, 
	[StaffID] varchar(50) NULL, 
	[StoreID] varchar(50) NOT NULL, 
	[SubTotAmt] decimal(19,4) NULL, 
	[TaxAmt] decimal(19,4) NULL, 
	[TermsID] varchar(50) NULL, 
	[TotAmt] decimal(19,4) NULL, 
	[TrackingID] varchar(120) NULL, 
	[TransDate] datetime2(6) NULL, 
	[VendorAckDate] datetime2(6) NULL, 
	[VendorAckNbr] varchar(255) NULL, 
	[VendorID] varchar(50) NOT NULL, 
	[VendorReferenceNum] varchar(100) NULL, 
	[VendorShipToStoreID] varchar(50) NULL, 
	[WMSSentToDateTime] datetime2(6) NULL
);