CREATE TABLE [wholesale_productsourcing].[pendingshipnotice] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[psnVendor] varchar(8000) NULL, 
	[psnDate] datetime2(6) NULL, 
	[psnOrderNumber] varchar(8000) NULL, 
	[psnDestinationID] int NULL, 
	[psnContainer] varchar(8000) NULL, 
	[psnViaCode] varchar(8000) NULL, 
	[psnOBL] varchar(8000) NULL, 
	[psnFeederVessel] varchar(8000) NULL, 
	[psnFeederVoyage] int NULL, 
	[psnMotherVessel] varchar(8000) NULL, 
	[psnMotherVoyage] int NULL, 
	[psnCarrierID] varchar(8000) NULL, 
	[psnETD] datetime2(6) NULL, 
	[psnETDPortID] varchar(8000) NULL, 
	[psnETA] datetime2(6) NULL, 
	[psnETAPortID] int NULL, 
	[psnTotalCartons] decimal(38,18) NULL, 
	[psnComments] varchar(8000) NULL, 
	[psnBookingNumber] varchar(8000) NULL, 
	[psnMessage] varchar(8000) NULL, 
	[psnStatus] varchar(8000) NULL, 
	[psnDueDate] datetime2(6) NULL, 
	[psnWarehouse] varchar(8000) NULL, 
	[psnShipMethod] int NULL, 
	[psnSealNumber] varchar(8000) NULL, 
	[psnInvalidReasons] varchar(8000) NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[psnSellerPartyID] int NULL, 
	[psnSellingLocationID] int NULL, 
	[psnHouseBOL] varchar(8000) NULL, 
	[psnHouseSCAC] varchar(8000) NULL, 
	[psnMasterSCAC] varchar(8000) NULL, 
	[psnProNumber] varchar(8000) NULL
);

