CREATE TABLE [wholesale_productsourcing].[portmaster] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[pteID] int NULL, 
	[pteAESPortCode] varchar(8000) NULL, 
	[ptePortDescription] varchar(8000) NULL, 
	[pteCityOfPort] varchar(8000) NULL, 
	[pteStateOfPort] varchar(8000) NULL, 
	[pteCountryOfPort] varchar(8000) NULL, 
	[pteFobPortCode] varchar(8000) NULL, 
	[pteFOBPortActiveRecordFlag] bit NULL, 
	[pteEndPortCode] int NULL, 
	[pteEndPortActiveRecordFlag] bit NULL, 
	[pteLastModifiedUser] varchar(8000) NULL, 
	[pteShortPortDescription] varchar(8000) NULL, 
	[acrec] varchar(8000) NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[pteCanadaActiveRecordFlag] bit NULL, 
	[pteCanadaBorderServiceAgency] varchar(8000) NULL, 
	[pteZipCode] varchar(8000) NULL, 
	[pteGeoLatitude] decimal(38,18) NULL, 
	[pteGeoLongitude] decimal(38,18) NULL, 
	[pteGeoAccuracy] int NULL
);

