CREATE TABLE [ResidentHome].[ProductAttributeExt] (

	[ItemSKU] varchar(14) NULL, 
	[IsKit] varchar(10) NULL, 
	[CoProduced] varchar(10) NULL, 
	[IsPurchased] varchar(10) NULL, 
	[IsManufactured] varchar(10) NULL, 
	[Brand] varchar(19) NULL, 
	[Version] varchar(10) NULL, 
	[BrandVersion] varchar(23) NULL, 
	[BrandFamily] varchar(25) NULL, 
	[BU_Development] varchar(10) NULL, 
	[PrimaryBusinessUnit] varchar(10) NULL, 
	[PrimaryChannel] varchar(10) NULL, 
	[CategoryMaster] varchar(11) NULL, 
	[Category] varchar(20) NULL, 
	[TransitionMap] varchar(10) NULL, 
	[TransitionVersion] varchar(10) NULL, 
	[CalendarAssignment] varchar(10) NULL, 
	[SpecialProgram] varchar(10) NULL, 
	[JBPAtt1] varchar(10) NULL, 
	[JBPAtt2] varchar(10) NULL, 
	[JBPAtt3] varchar(10) NULL, 
	[JBPAtt4] varchar(10) NULL, 
	[JBPAtt5] varchar(10) NULL, 
	[JBPAtt6] varchar(10) NULL, 
	[JBPAtt7] varchar(10) NULL
);