create VIEW [CustomerOrders_AFI_Wrk].[v_RequestDateChangeCode]
AS
SELECT  [Rdcreasoncode]
      ,[Rdcdescription]
      ,[Rdcadddate]
      ,[Rdcadduser]
      ,[Rdcchangedate]
      ,[Rdcchangeuser]
      ,[Rdcstatus]
      ,[Rdccancelflag]
      ,[Rdcavailabletoashleydirect]
      ,[Rdcashleydirectdescription]
  FROM [$(Source_Data)].[Wholesale_Codis_AFI].[RequestDateChangeCodes]