CREATE VIEW [CustomerOrders_AFI_Wrk].[v_WarehouseFillRequest]
AS
SELECT  [FLTRIPNO]
      ,[FLHOUSE]
      ,[FLCUBES]
      ,[FLPRCCUBES]
      ,[FLCUSNO]
      ,[FLSHPNO]
      ,[FLRUSR]
      ,[FLRDTE]
      ,[FLUSRP]
      ,[FLPDTE]
      ,[FLPROC]
  FROM [$(Source_Data)].[Wholesale_Codis_AFI].[WHFILRQ]