CREATE TABLE [Wholesale_SalesHistory_AFI].[ordaudd] (

	[OrderNo] char(7) NULL, 
	[ItemNo] varchar(15) NULL, 
	[ItemSequenceNo] numeric(7,0) NULL, 
	[Quantity] numeric(7,0) NULL, 
	[NetAmount] numeric(13,2) NULL, 
	[ItemClass] char(4) NULL, 
	[PromiseDate] numeric(8,0) NULL, 
	[RequestDate] numeric(8,0) NULL, 
	[QtyDecreaseReason] char(2) NULL, 
	[UserIdChanging] varchar(10) NULL, 
	[ChangeDate] numeric(8,0) NULL, 
	[ChangeTime] numeric(6,0) NULL, 
	[CancRedFlag] char(1) NULL, 
	[OrderTakenDate] numeric(8,0) NULL, 
	[Freight] numeric(12,2) NULL, 
	[AdditionalFreight] numeric(12,2) NULL, 
	[Dicount] numeric(12,2) NULL, 
	[DFIDiscount] numeric(12,2) NULL, 
	[AdvertisingAccrual] numeric(12,2) NULL, 
	[Packageid] varchar(15) NULL, 
	[PacakgedIscAllocationPercentage] numeric(4,3) NULL, 
	[PackagePrice] numeric(8,2) NULL, 
	[ItmStatusCodeOrderTime] char(1) NULL, 
	[PackageItemPrice] numeric(8,2) NULL, 
	[PackageItemDiscount] numeric(4,3) NULL, 
	[KeyAchorItem] varchar(15) NULL, 
	[PackageDescription] varchar(30) NULL, 
	[OrderPriority] numeric(2,0) NULL
);