CREATE VIEW [SSAS_AFISALES_OLAP].[DimItemMaster]
AS
    SELECT
        [RowID],
        ItemSKU                        AS [Item SKU],
        ItemKey                        AS [Item Key],
        Item                           AS [Item],
        ItemClassCode                  AS [Item Class Code],
        [Colors],
        QtyInBox                       AS [Qty In Box],
        [UOM],
        SeriesName                     AS [Series Name],
        SeriesColor                    AS [Series Color],
        ItemDescriptionSeries          AS [Item-Description-Series],
        SHItemDescriptionSeries        AS [SH-Item-Description-Series],
        SHSeriesDescription            AS [SH-Series-Description],
        ItemDescriptionSeriesItemColor AS [Item-Description-Series-Item Color],
        ResponsibleOffice              AS [Responsible Office],
        ItemClassName                  AS [Item Class Name],
        ItemClass                      AS [Item Class],
        ProductLine                    AS [Product Line],
        RetailCategoryCode             AS [Retail Category Code],
        RetailCategoryDescription      AS [Retail Category Description],
        AFIFinanceDivision             AS [AFI Finance Division],
        ItemDescription                AS [Item Description],
        ItemStyleCode                  AS [Item Style Code],
        ItemStyleGroup                 AS [Item Style Group],
        ItemStyle                      AS [Item Style],
        ItemStyle                      AS [Item Syle],
        AFIItemStatus                  AS [AFI Item Status],
        SalesClassCode                 AS [Sales Class Code],
        SalesClassDescription          AS [Sales Class Description],
        SalesClass                     AS [Sales Class],
        DiscountClassCode              AS [Discount Class Code],
        DiscountClassDescription       AS [Discount Class Description],
        DiscountClass                  AS [Discount Class],
        CommissionClassCode            AS [Commission Class Code],
        CommissionClassDescription     AS [Commission Class Description],
        CommissionClass                AS [Commission Class],
        FreightClassCode               AS [Freight Class Code],
        FreightClassDescription        AS [Freight Class Description],
        FreightClass                   AS [Freight Class],
        ManufacturingStatus            AS [Manufacturing Status],
        AFISalesCategoryCode           AS [AFI Sales Category Code],
        AFISalesCategory               AS [AFI Sales Category],
        ImportDomesticCode             AS [Import/Domestic Code],
        CountryofOrigin                AS [Country of Origin],
        AFISalesDivisionCode           AS [AFI Sales Division Code],
        AFISalesDivision               AS [AFI Sales Division],
        CEXCode                        AS [CEX Code],
        SeriesCode                     AS [Series Number],
        ExtSeriesCode                  AS [Ext Series Number],
        MainPieceItem                  AS [Main Piece Item],
        MarketIntroducedAt             AS [Market Introduced At],
        MerchandisingCategory          AS [Merchandising Category],
        ChildStyleDescription          AS [Child Style Description],
        ParentStyleDescription         AS [Parent Style Description],
        PricePoint                     AS [Price Point],
        ItemCode                       AS [Item Code],
        ItemGrouping                   AS [Item Grouping],
        AssociationCode                AS [Association Code],
        MarketingItemStatus            AS [Marketing Item Status],
        MarketingStatusDescription     AS [Marketing Status Description],
        CommodityItem                  AS [Commodity Item],
        F123ProductFlag                AS [F123 Product Flag],
        HSCoreProductFlag              AS [HS Core Product Flag],
        HSProprietaryProductFlag       AS [HS Proprietary Product Flag],
        HSExclusiveFlag                AS [HS Exclusive Flag],
        BerklineProductFlag            AS [Berkline Product Flag],
        BenchcraftProductFlag          AS [Benchcraft Product Flag],
        NewMillenniumProductFlag       AS [New Millennium Product Flag],
        BardiniProductFlag             AS [Bardini Product Flag],
        ShanghaiStore                  AS [Shanghai Store],
        DefaultGroup                   AS [Default Group],
        SeriesDescription              AS [Series Description],
        GoodBetterBestForPricePoint    AS [Good Better Best For Price Point],
        [GBBSortID],
        IM.PrimaryVendor               AS [Primary Vendor],
        SellableItemFlag               AS [Sellable Item Flag],
        ManufacturingStatusChangeDate  AS [Manufacturing Status Change Date],
        ItemForecastPlannerID          AS [Item Forecast Planner ID],
        InitialInvoicePeriod           AS [Initial Invoice Period],
        InitialInvoiceQty              AS [Initial Invoice Qty],
        MarketBeginDate                AS [Market Begin Date],
        MarketEndDate                  AS [Market End Date],
        ItemConsumerDescription        AS [Item Consumer Description],
        RetailTypeDescription          AS [Retail Type Description],
        CommonCarrierFlag              AS [Common Carrier Flag],
        ExpressShipFlag                AS [Express Ship Flag],
        [Showroom],
        [Division],
        ItemImage                      AS [Item Image],
        FOBArcPrice                    AS [FOB Arc Price],
        NewItemFlag                    AS [New Item Flag],
        DiscontinuedFlag               AS [Discontinued Flag],
        DiscontinuedYearPeriod         AS [Discontinued Year Period],
        DiscontinuedDate               AS [Discontinued Date],
        TrendArrow                     AS [Trend Arrow],
        [Lifestyle],
        ItemMerchGridOverridePhoto     AS [Item Merch Grid Override Photo],
        FrameNumber                    AS [Frame Number],
        [Cubes],
        [Seats],
        IM.RetailCategoryName          AS [Retail Category Name],
        RetailDepartmentName           AS [Retail Department Name],
        RetailCategoryGroup            AS [Retail Category Group],
        ExclusiveComment               [Item Exclusive Comment],
        SeriesImage                    [Series Image Name],
        [SofaTableSeriesFlag]          AS [Sofa Table Series Flag],
        [ReclinerSeriesFlag]           AS [Recliner Series Flag],
        [PowerMotionSeriesFlag]        AS [Power Motion Series Flag],
        [WedgeSeriesFlag]              AS [Wedge Option Series Flag],
        [DiningSeriesFlag]             AS [Dining Bench Series Flag],
        [ItemThirdPartyItem]           AS [Third Party Flag],
        [ItemSupplierDirectShipOnly]   AS [Supplier Direct Ship Only Flag],
        ConsumerChoiceFlag             AS [Consumer Choice Flag],
        CollectiveClass                AS [Collective Class]
    FROM
        AFISales_DW.DimItemMaster IM; --- was pointing to MasterData_DW