CREATE VIEW [SSAS_AFISALES_OLAP].[DimQualityCostDetails]
AS
	SELECT
		[RowID],
		[Part Number],
		[Defect Type], [Purchase Order],
		[Invoice Number],
		[Order Number],
		[Item SKU],
		[Defect Code],
		[Location Code],
		[Credit Code],
		[Quality Code],
		[Damage Type],
		[Damaged Location],
		[Percent Allowed],
		[Serial Number],
		[Trip Number],
		[Drop Number],
		[Original Invoice],
		[Original Order],
		[Order Date],
		[Order Mode],
		[Add User],
		[Carrier],
		[Truck Number],
		[Delivery Date],
		[Scan Name],
		[Load Date],
		[Order Type],
		[Transaction Date],
		TRIM([Vendor Number]) [Vendor Number],
		[Where Made],
		[Manufacture Date],
		[User Group],
		[Sales Number],
		[Item Type],
		[Scrap Code],
		[Quality Category]
	FROM AFISales_DW.FactQualityCosts;