CREATE VIEW [SSAS_AFISALES_OLAP].[DimWarRoomPackageDetails]
AS
    SELECT
        [War Room Package ID],
        [Item Number],
        [Package Description],
        [Template ID],
        [Package Detail],
        [Package Series Number],
        [Item Merch Grid Override Photo],
        [Package Image],
        [FOB Arcadia],
        [ABC Code],
        [Logility Status],
        [Trend Arrow],
        [Series Margin FOB],
        [Series Margin Current],
        [Series Margin Actual],
        [Monthly Totals for],
        GMROI,
        [Profit Cnt His],
        [Profit Cnt Pro],
        [Profit Cnt His Std],
        [Profit Cnt Pro Std],
        [Profit Cnt His Act],
        [Profit Cnt Pro Act],
        [Logility Month Ave His],
        [Logility Month Ave Pro],
        [Logility Month Ave His Dol],
        [Logility Month Ave Pro Dol],
        [Item AVG],
        [Item STD],
        [Item ACT],
        [Rental Acct],
        Rental,
        Source,
        [Ret Pr Pt],
        [Min MU],
        [Ret MU],
        [package Type],
        [War Room Key Item],
        [Amount Returned],
        [Forecast Result1],
        [Forecast Result2],
        [Forecast Result3],
        [Forecast Result4],
        [Forecast Result5],
        [Forecast Result6],
        [Forecast Result7],
        [Forecast Result8],
        [Forecast Result9],
        [Forecast Result10],
        [Forecast Result11],
        [Forecast Result12],
        Dollars,
        [FOB price],
        [Quantity Returned],
        Discounted,
        FOB,
        ACT,
        [Package Item Flag],
        [Package FOB Arcadia Price],
        [Package Series Name],
        [Series Item Flag]
    FROM
        AFISales_DW.DimWarRoomPackageDetails;