CREATE VIEW Customers_Wrk.v_ExtendedCustomerProfile
AS
SELECT 
CAST([ecpCompanyNum] AS [int]) AS [CompanyNum],
[ecpCustomerNum] AS [CustomerNumber],
[ecpShipToNum] AS [ShiptoNumber],
[ecpEMailAddress] AS [EMailAddress],
[ecpApptRequired] AS [ApptRequired],
[ecpInforceMin] AS [InforceMin],
[ecpRouteZone] AS [RouteZone],
[ecpTimeZone] AS [TimeZone],
[ecpTruckSizeLimit1] AS [TruckSizeLimit1],
[ecpTruckSizeLimit2] AS [TruckSizeLimit2],
CAST([ecpCubeMaxPerTruck] AS [int]) AS [CubeMaxPerTruck],
[ecpReqFlagMatch] AS [ReqFlagMatch],
[ecpGEOLocId] AS [GEOLocId],
CAST([ecpGEOLat] AS [decimal](13,4)) AS [GEOLat],
CAST([ecpGEOLong] AS [decimal](13,4)) AS [GEOLong],
CAST([ecpGEOAccuracy] AS [int]) AS [GEOAccuracy],
[ecpGEOType] AS [GEOType],
CAST([ecpLastAddrVerfyDate] AS [datetime2](6)) AS [LastAddrVerfyDate],
CAST([ecpDaysBetwnAddrVerfy] AS [smallint]) AS [DaysBetwnAddrVerfy],
[ecpGrpOrdersByLoadDate] AS [GrpOrdersByLoadDate],
[ecpMethodOrdersRouted] AS [MethodOrdersRouted],
[ecpDoingBusinessAs] AS [DoingBusinessAs],
[ecpCounty] AS [County],
CAST([ecpServeTimeMinOverride] AS [int]) AS [ServeTimeMinOverride],
CAST([ecpServeTimeFixedDrop] AS [int]) AS [ServeTimeFixedDrop],
[ecpFirstOnRoute] AS [FirstOnRoute],
CAST([ecpWindowsNotRequired] AS [bit]) AS [WindowsNotRequired],
[usra] AS [AddedByUser],
CAST([dtea] AS [datetime2](6)) AS [DateAdded],
[usrc] AS [ChangeByUser],
CAST([dtec] AS [datetime2](6)) AS [DateChange],
CAST([ecpOrderMinimum] AS [decimal](7,0)) AS [OrderMinimum],
[ecpRouteRegion] AS [RouteRegion],
CAST([ecpReplicate] AS [bit]) AS [Replicate],
[ecpRPOrderEmailNotify] AS [RPOrderEmailNotify],
[ecpRPOrderEmailAddress] AS [RPOrderEmailAddress],
[ecpAutoSchedule] AS [AutoSchedule],
[ecpAutoFreeze] AS [AutoFreeze],
[ecpRPShippingLocation] AS [RPShippingLocation],
CAST([ecpNextAvailableDeliveryAppt] AS [datetime2](6)) AS [NextAvailableDeliveryAppt],
CAST([ecpRoutePosition] AS [decimal](3,0)) AS [RoutePosition],
CAST([ecpLastOnLoad] AS [decimal](1,0)) AS [LastOnLoad],
[ecpReasonCode] AS [ReasonCode],
CAST([ecpDateNextDelvryDateEntered] AS [datetime2](6)) AS [DateNextDelvryDateEntered],
[ecpCommentNextDeliveryDate] AS [CommentNextDeliveryDate],
[ecpExceptionToShipCompleteRule] AS [ExceptionToShipCompleteRule],
[ecpOnCarriageTo] AS [OnCarriageTo],
[ecpNotifyPartyName] AS [NotifyPartyName],
[ecpNotifyPartyAddress1] AS [NotifyPartyAddress1],
[ecpNotifyPartyAddress2] AS [NotifyPartyAddress2],
[ecpNotifyPartyCity] AS [NotifyPartyCity],
[ecpNotifyPartyState] AS [NotifyPartyState],
[ecpNotifyPartyZip] AS [NotifyPartyZip],
[ecpNotifyPartyCountry] AS [NotifyPartyCountry],
[ecpUltimateDestinationCity] AS [UltimateDestinationCity],
[ecpUltimateDestinationState] AS [UltimateDestinationState],
[ecpUltimateDestinationCountry] AS [UltimateDestinationCountry],
[ecpCommercialInvoiceHeading] AS [CommercialInvoiceHeading],
CAST([ecpFreightForwardingFeeOverride] AS [decimal](7,2)) AS [FreightForwardingFeeOverride],
CAST([ecpInsuranceFeeOverride] AS [decimal](7,2)) AS [InsuranceFeeOverride],
CAST([ecpCourierFee] AS [decimal](7,2)) AS [CourierFee],
[ecpParsByPurchaser] AS [ParsByPurchaser],
[ecpDefaultCarrier] AS [DefaultCarrier],
CAST([ecpOverrideRouteZone] AS [bit]) AS [OverrideRouteZone],
[ecpOverrideRouteZoneUser] AS [OverrideRouteZoneUser],
CAST([ecpOverrideRouteZoneDate] AS [datetime2](6)) AS [OverrideRouteZoneDate],
CAST([ecpShowConsolidatedATP] AS [bit]) AS [ShowConsolidatedATP],
[ecpDoNotAllowLineItemSplit] AS [DoNotAllowLineItemSplit],
CAST([ecpAllocationCubeMinimum] AS [smallint]) AS [AllocationCubeMinimum],
[ecpRestrictManualOrderEntry] AS [RestrictManualOrderEntry],
[ecpAutomateFill] AS [AutomateFill],
CAST([ecpRequestDaysOut] AS [smallint]) AS [RequestDaysOut]
FROM [$(Source_Data)].[Wholesale_Customers].[ExtendedCustomerProfile]

