
CREATE VIEW [Customers_Wrk].[v_ShippingLocations]
AS
SELECT 
[cslCustomerNumber] AS [CustomerNumber],
[cslShiptoNumber] AS [ShiptoNumber],
CAST([cslMapicsSequenceNumber] AS [smallint]) AS [MapicsSequenceNumber],
[cslName] AS [Name],
[csmShpa1] AS [Address1],
CAST([csmShpa2] AS VARCHAR(25)) AS [Address2],
[csmShpa3] AS [Address3],
[csmShpzp] AS [ZipCode],
[csmShpst] AS [State],
[csmShpco] AS [Country],
[csmPhone] AS [Phone],
[csmFaxTn] AS [Faxtn],
[cslTaxExempt] AS [TaxExempt],
[csmWebsite] AS [Website],
[csmEmail] AS [Email],
[cslCommissionCode] AS [CommissionCode],
[cslFreightCode] AS [FreightCode],
[cslPriceCode] AS [PriceCode],
[cslDiscountCode] AS [DiscountCode],
CAST([cslCommissionSplit] AS [decimal](7,4)) AS [CommissionSplit],
[cslDefaultWarehouse] AS [DefaultWarehouse],
[cslShippingTerritory] AS [ShippingTerritory],
[cslBusinessType] AS [BusinessType],
[cslShipType] AS [ShipType],
[cslTranscomPrimaryID] AS [TranscomPrimaryID],
[csmContact] AS [Contact],
[cslComment1] AS [Comment1],
[cslComment2] AS [Comment2],
CAST([cslTerritoryEffectivityDate] AS [datetime2](6)) AS [TerritoryEffectivityDate],
[cslCrmID] AS [ServiceRepID],
[csmCsPhone] AS [CRMPhone],
[csmcsFax] AS [CRMFax],
[csmcsContact] AS [CRMContact],
[csmcsEmail] AS [CRMEmail],
[cslMemo] AS [Memo],
[csmMsa_Fips] AS [MSA_FIPS],
CAST([csmRMCityNumber] AS [int]) AS [RMCityNumber],
[cslTranscomAlternateID] AS [TranscomAlternateID],
[csmDirections] AS [Directions],
[csmCrossStreet] AS [CrossStreet],
CAST([csmChgAddr] AS [bit]) AS [ChgAddr],
CAST([csmChgShip] AS [bit]) AS [ChgShip],
CAST([csmChgShipExt] AS [bit]) AS [ChgShipExt],
CAST([csmChgCust] AS [bit]) AS [ChgCust],
CAST([commAudit] AS [bit]) AS [commaudit],
CAST([commAudit2] AS [bit]) AS [commaudit2],
[usra] AS [AddedByUser],
CAST([dtea] AS [datetime2](6)) AS [DateAdded],
[usrc] AS [ChangeByUser],
CAST([dtec] AS [datetime2](6)) AS [DateChange],
[acrec] AS [ActiveRecord],
[csmCounty] AS [County],
CAST([cslBlockRepOrderEntry] AS [bit]) AS [BlockRepOrderEntry],
CAST([cslCustomerSegment] AS [int]) AS [CustomerSegment],
CAST([cslLastStatusChangeDate] AS [datetime2](6)) AS [LastStatusChangeDate],
CAST([cslBuyerAddressID] AS [int]) AS [BuyerAddressID],
CAST([cslPartyLocationID] AS [int]) AS [PartyLocationID],
CAST([cslRouteAddressID] AS [int]) AS [RouteAddressID],
[cslDefaultOrderType1] AS [DefaultOrderType1],
[cslDefaultOrderType2] AS [DefaultOrderType2],
[cslDefaultOrderType3] AS [DefaultOrderType3],
[cslDefaultOrderType4] AS [DefaultOrderType4],
CAST([csmShled] AS [smallint]) AS [ShippingLeadTime],
CAST([csmAppcd] AS [int]) AS [ApplicationCode],
[cslAllowFax] AS [AllowFax],
[cslDirectConsumer] AS [DirectConsumer],
[cslDeliveryUnitOfMeasure] AS [DeliveryUnitOfMeasure],
CAST([cslDeliveryUnitOfMeasureFence] AS [decimal](7,2)) AS [DeliveryUnitOfMeasureFence],
[cslExportsLCLConsolidationFlag] AS [ExportsLCLConsolidationFlag],
[cslExportsDocumentCountry] AS [ExportsDocumentCountry],
[cslExportsProductOnPallets] AS [ExportsProductOnPallets],
[cslExportsAppointmentsRequired] AS [ExportsAppointmentsRequired],
CAST([cslHasDock] AS [bit]) AS [HasDock],
[cslHasDockUserDate] AS [HasDockUserDate],
[cslExpressShippingMethod] AS [ExpressShippingMethod],
[cslDirectIncludeShipto] AS [DirectIncludeShipto],
CAST([cslExpressHandlingCharge] AS [decimal](4,3)) AS [ExpressHandlingCharge],
CAST([cslExpressMinimum] AS [decimal](10,2)) AS [ExpressMinimum],
CAST([cslExpressMaximum] AS [decimal](10,2)) AS [ExpressMaximum],
[cslDefaultLanguage] AS [DefaultLanguage],
[cslExpressServiceContractNumber] AS [ExpressServiceContractNumber],
[cslUseNegotiatedFreightRate] AS [UseNegotiatedFreightRate],
[cslUseStandardFreightRate] AS [UseStandardFreightRate],
[cslDoNotRepriceOrders] AS [DoNotRepriceOrders],
[cslPricingUseOfflineFiles] AS [PricingUseOfflineFiles],
CAST([cslReturnAddressID] AS [int]) AS [ReturnAddressID],
[cslReturnAddressName] AS [ReturnAddressName]
FROM [$(Source_Data)].[Wholesale_Customers].[ShippingLocations]

