CREATE TABLE [PowerBI_Retail].[PROM_FactOrderDetail] (
    [SourceOrderID]         VARCHAR (20)    NOT NULL,
    [BaseOrderID]           VARCHAR (20)    NOT NULL,
    [SKU]                   VARCHAR (20)    NOT NULL,
    [ProductKey]            BIGINT          NOT NULL,
    [QuantityOrdered]       INT             NULL,
    [UnitListPrice]         DECIMAL (19, 4) NULL,
    [UnitSellPrice]         DECIMAL (19, 4) NULL,
    [UnitOtherDiscount]     DECIMAL (19, 4) NULL,
    [OtherDiscount]         DECIMAL (19, 4) NULL,
    [UnitCost]              DECIMAL (19, 4) NULL,
    [ProductDiscountCode]   VARCHAR (50)    NULL,
    [SpecialOrderFlag]      BIT             NULL,
    [AsIsReasonCodeID]      VARCHAR (50)    NULL,
    [WrittenDate]           DATETIME2 (3)   NULL,
    [ReasonCodeID]          VARCHAR (50)    NULL,
    [ReasonCodeName]        VARCHAR (255)   NULL,
    [PriceOverrideStaffID]  VARCHAR (50)    NULL,
    [OverrideStaffName]     VARCHAR (100)   NULL,
    [CategoryID]            VARCHAR (40)    NOT NULL,
    [GroupID]               VARCHAR (50)    NOT NULL,
    [SeriesID]              VARCHAR (50)    NULL,
    [VendorStyle]           VARCHAR (100)   NULL,
    [StoreID]               INT             NOT NULL,
    [SalesPersonID]         VARCHAR (20)    NULL,
    [SalespersonName]       VARCHAR (100)   NULL,
    [PriceExceptionComment] VARCHAR (600)   NULL,
    [CustomerName]          VARCHAR (100)   NULL,
    [CustomerID]            VARCHAR (50)    NULL,
    [RetailPrice]           DECIMAL (19, 4) NULL,
    [UnitRetailPrice]       DECIMAL (19, 4) NULL,
    [SellPrice]             DECIMAL (19, 4) NULL,
    [TransDescription]      VARCHAR (50)    NULL
);