CREATE TABLE [MasterData_Retail_Ent_Wrk].[salespersonupboardhistorydsg] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[StoreId] varchar(8000) NULL, 
	[SalesPersonId] int NULL, 
	[salespersonname] varchar(8000) NULL, 
	[salespersonusername] varchar(8000) NULL, 
	[StatusStartTime] datetime2(6) NULL, 
	[StatusEndTime] datetime2(6) NULL, 
	[StatusStartDate] datetime2(6) NULL, 
	[StatusStartHour] int NULL, 
	[RecordedUpDate] datetime2(6) NULL, 
	[RecordedUpHour] int NULL, 
	[SPUB_Statusid] int NULL, 
	[GuestName] varchar(8000) NULL, 
	[isCountedAsUP] int NULL, 
	[isSale] int NULL, 
	[StrikeCount] int NULL, 
	[Shot] smallint NULL, 
	[FinApp] smallint NULL, 
	[ReasonManagerAddWith] varchar(8000) NULL, 
	[ReasonManagerAddSP] varchar(8000) NULL, 
	[ReasonManagerAddUps] varchar(8000) NULL, 
	[ReasonManagerRemoveSP] varchar(8000) NULL, 
	[ManagerCoachingNotes] varchar(8000) NULL, 
	[ManagerCoachingNotesTime] datetime2(6) NULL, 
	[IsStrike] bit NULL, 
	[IsStrikeOut] bit NULL, 
	[ConsecutiveStrikes] int NULL, 
	[ConsecutiveStrikeOuts] int NULL
);