CREATE TABLE [masterdata_productknowledge].[item_env] (

	[ltd_DropTimestamp] datetime2(6) NULL, 
	[ltd_ID] int NULL, 
	[ltd_mergeIgnore] bit NULL, 
	[ltd_count1] bigint NULL, 
	[ienItemNumber] varchar(8000) NULL, 
	[ienItemType] varchar(8000) NULL, 
	[ienItemClass] varchar(8000) NULL, 
	[ienEnvironmentCode] varchar(8000) NULL, 
	[usra] varchar(8000) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(8000) NULL, 
	[dtec] datetime2(6) NULL, 
	[ienItemLevelCountryOfOrigin] varchar(8000) NULL, 
	[ienItemLevelCityOfOrigin] varchar(8000) NULL, 
	[ienItemLevelCOOReviewed] datetime2(6) NULL, 
	[ienFutureStatus] varchar(8000) NULL, 
	[ienHoldBuyCode] varchar(8000) NULL, 
	[ienForecastPlannerID] varchar(8000) NULL, 
	[ienDirectShipItemOnly] varchar(8000) NULL, 
	[ienHTSCode] varchar(8000) NULL, 
	[ienScheduleBCode] varchar(8000) NULL, 
	[ienExpressShipCode] varchar(8000) NULL, 
	[ienDeliverInPackage] bit NULL, 
	[ienVBoard] bit NULL, 
	[ienCertifiedPackage] bit NULL, 
	[ienRDCAssemblyRequired] bit NULL, 
	[ienCustomerAssemblyOnly] bit NULL, 
	[ienUniqueSerialNumbers] int NULL
);

