CREATE TABLE [Wholesale_DemandPlanning_AFI].[IOExportedItemOutputs] (

	[ExportDate] datetime2(6) NOT NULL, 
	[SkuId] int NOT NULL, 
	[LocationId] int NOT NULL, 
	[SeasonId] int NOT NULL, 
	[Dtu] int NOT NULL, 
	[Sku] varchar(100) NOT NULL, 
	[Location] varchar(100) NOT NULL, 
	[Season] varchar(128) NOT NULL, 
	[DtuDate] datetime2(6) NOT NULL, 
	[ServiceLevel] float NULL, 
	[DemandAverage] float NULL, 
	[DemandUncertainty] float NULL, 
	[SafetyStockLevelCalculated] float NULL, 
	[SafetyStockLevelLowerLimit] float NULL, 
	[SafetyStockLevelUpperLimit] float NULL, 
	[SafetyStockLevel] float NULL, 
	[SafetyStockLevel_adjusted] float NULL, 
	[SafetyStockPOSCalculated] float NULL, 
	[SafetyStockPOSLowerLimit] float NULL, 
	[SafetyStockPOSUpperLimit] float NULL, 
	[SafetyStockPOS] float NULL, 
	[SafetyStockPOS_adjusted] float NULL, 
	[SafetyStockLevelMax] float NULL, 
	[SafetyStockPOSMax] float NULL, 
	[SafetyStockLevelMaxActual] float NULL, 
	[SafetyStockPOSMaxActual] float NULL, 
	[BaseStockLevel] float NULL, 
	[OnHandStockLevel] float NULL, 
	[OnHandStockPOS] float NULL, 
	[KanbanCardsCalculated] float NULL, 
	[KanbanCardsLowerLimit] float NULL, 
	[KanbanCardsUpperLimit] float NULL, 
	[KanbanCards] float NULL, 
	[KanbanCards_adjusted] float NULL, 
	[ReorderPointCalculated] float NULL, 
	[ReorderPointLowerLimit] float NULL, 
	[ReorderPointUpperLimit] float NULL, 
	[ReorderPoint] float NULL, 
	[ReorderPoint_adjusted] float NULL, 
	[CalculatedMinLevel] float NULL, 
	[CalculatedMinPOS] float NULL, 
	[CalculatedMaxLevel] float NULL, 
	[CalculatedMaxPOS] float NULL, 
	[SafetyStockTargetActualLevel] float NULL, 
	[SafetyStockTargetActualPOS] float NULL, 
	[KanbanCardsTargetActual] float NULL, 
	[ReorderPointTargetActual] float NULL, 
	[OnHandStockTargetActualLevel] float NULL, 
	[OnHandStockTargetActualPOS] float NULL, 
	[TargetType] char(1) NULL, 
	[DisaggregationType] char(2) NULL, 
	[DisaggregationType_adjusted] char(2) NULL, 
	[SafetyTargetLevel] float NULL, 
	[SafetyTargetLevel_adjusted] float NULL, 
	[SafetyTargetPOS] float NULL, 
	[SafetyTargetPOS_adjusted] float NULL, 
	[SafetyTimeLevel] float NULL, 
	[SafetyTimeLevel_adjusted] float NULL, 
	[SafetyTimePOS] float NULL, 
	[SafetyTimePOS_adjusted] float NULL, 
	[SafetyTargetActualLevel] float NULL, 
	[SafetyTargetActualPOS] float NULL, 
	[SafetyTimeActualLevel] float NULL, 
	[SafetyTimeActualPOS] float NULL, 
	[NetReplenishmentLeadTime] int NULL, 
	[EngineType] int NULL, 
	[ServiceTime200] int NULL, 
	[IncomingServiceTime308] int NULL, 
	[ReviewPeriod234] int NULL, 
	[BatchOrderQuantity520] float NULL, 
	[KanbanBinSize] int NULL, 
	[ReplenishmentsPerRp237] int NULL, 
	[LaunchDate] datetime2(6) NULL, 
	[LeadTimeAve] float NULL, 
	[LeadTimeStdev] float NULL
);