CREATE TABLE [Wholesale_DemandPlanning_AFI].[SupplyPlanDetail] (

	[spdItem] varchar(15) NULL, 
	[spdWarehouse] char(3) NULL, 
	[spdWeekEnding] date NULL, 
	[spdBeginingBalance] decimal(10,0) NULL, 
	[spdFirmDemands] decimal(10,0) NULL, 
	[spdNetForecast] decimal(10,0) NULL, 
	[spdFirmTransferOut] decimal(10,0) NULL, 
	[spdFirmProduction] decimal(10,0) NULL, 
	[spdFirmPurchaseOrders] decimal(10,0) NULL, 
	[spdInTransitTransferIn] decimal(10,0) NULL, 
	[spdOnOrderTransferIn] decimal(10,0) NULL, 
	[spdPlannedTransferIn] decimal(10,0) NULL, 
	[spdPlannedTransferOut] decimal(10,0) NULL, 
	[spdPlannedProduction] decimal(10,0) NULL, 
	[spdPlannedPurchaseOrders] decimal(10,0) NULL, 
	[spdTotalReceipts] decimal(10,0) NULL, 
	[spdShippableInventory] decimal(10,0) NULL, 
	[spdSafetyStock] decimal(10,0) NULL, 
	[spdMonthsOfSupply] decimal(10,2) NULL, 
	[spdResultantForecast] decimal(10,0) NULL, 
	[spdPromotionalLift] decimal(10,0) NULL, 
	[spdDemandFulfillment] decimal(10,0) NULL, 
	[spdWeeklyPromotionalLift] decimal(10,0) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL
);