CREATE TABLE [Quality_Enh].[ReplacementPartHistory]
    (
        [RPKey]                                 [INT]             NOT NULL,
        [Item Sequence]                         [DECIMAL](2, 0)   NOT NULL,
        [Part Number]                           [VARCHAR](15)     NULL,
        [Serial Number]                         [VARCHAR](15)     NULL,
        [Scrap Code]                            [CHAR](4)         NULL,
        [Item SKU]                              [VARCHAR](15)     NULL,
        [Warehouse]                             [CHAR](3)         NULL,
        [Location Code]                         [CHAR](5)         NOT NULL,
        [Mfg Warehouse Code]                    [CHAR](3)         NULL,
        [Invoice Number]                        [DECIMAL](9, 0)   NULL,
        [Invoice Date]                          [DATE]            NULL,
        [Vendor Number]                         [CHAR](8)         NULL,
        [Account And Shipto Number]             [VARCHAR](13)     NULL,
        [Ship Date]                             [DATE]            NULL,
        [Shipto AddressID]                      [INT]             NULL,
        [Replacement Part Order Count]          [NUMERIC](36, 13) NULL,
        [Replacement Part Incidents]            [NUMERIC](25, 13) NULL,
        [Parts Shipped Quantity - No Charge]    [DECIMAL](30, 13) NULL,
        [Parts Shipped Quantity - Charged Back] [DECIMAL](30, 13) NULL,
        [Parts Cost - No Charge]                [DECIMAL](38, 8)  NULL,
        [Parts Cost - Charged Back]             [DECIMAL](38, 8)  NULL,
        [Shipping Cost - No Charge]             [NUMERIC](38, 6)  NULL,
        [Shipping Cost - Charged Back]          [NUMERIC](38, 6)  NULL,
        [Allocated]                             [INT]             NOT NULL,
        [Scrap Code with CS Control Code]       [CHAR](5)         NULL,
        [Days - Entered to Shipped]             [INT]             NULL,
        [Primary Site ID]                       [CHAR](3)         NOT NULL,
        [CustomerNumber]                        [CHAR](8)         NULL,
        [OrderPackedDate]                       [DATE]            NULL,  --        [DECIMAL](8, 0)   NULL,
        [Quantity]                              [DECIMAL](4, 0)   NULL,
        [EntryPerson]                           [CHAR](10)        NULL,
        [DateEntered]                           [DECIMAL](8, 0)   NULL,
        [PONumber]                              [CHAR](22)        NULL,
        [ChargeType]                            [CHAR](1)         NULL,
    --    [ShipDate]                            [DECIMAL](8, 0)   NULL,
        [ShiptoNumber]                          [CHAR](4)         NULL,
        [SERNO_NO_ZERO]                         [VARCHAR](15)     NULL,
        [ShipVia]                               [CHAR](3)         NULL,
        [PickDate]                              [DATE]            NULL,    --- decimal
        [ShippingCost]                          [DECIMAL](6, 2)   NULL,
   --     [RowID]                               [BIGINT]          NULL,     ---IDENTITY(1, 1) NOT NULL,
        [BasePrice]                             [DECIMAL](6, 2)   NULL
    )

