CREATE TABLE [Wholesale_Codis_AFI].[AshleyWarehouseMaster] (

	[wmaWarehouse] char(3) NULL, 
	[wmaLocationId] decimal(10,0) NULL, 
	[wmaIntransitWarehouse] char(3) NULL, 
	[wmaSiteId] char(3) NULL, 
	[wmaMROSiteId] char(3) NULL, 
	[wmaWarehouseType] char(1) NULL, 
	[wmaWarehouseOrderGroup] varchar(10) NULL, 
	[wmaWarehouseSourceId] varchar(13) NULL, 
	[wmaRouteType] char(1) NULL, 
	[wmaDefaultPortId] int NULL, 
	[wmaControlled] bit NULL, 
	[wmaPrinterName] varchar(10) NULL, 
	[wmaZebraPrinter] varchar(10) NULL, 
	[wmaSendBolsToManu] char(1) NULL, 
	[wmaOrderReleaseMin] int NULL, 
	[wmaOrderReleaseMinType] char(1) NULL, 
	[wmaDefaultShipId] int NULL, 
	[wmaSortOrder] int NULL, 
	[wmaAsOverhead] int NULL, 
	[wmaAsFreight] int NULL, 
	[wmaContainerDirectWhse] char(1) NULL, 
	[acrec] char(1) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[wmaWhereMade] char(5) NULL, 
	[wmaManufacturingSite] varchar(25) NULL, 
	[wmaSellableWarehouse] bit NULL
);