CREATE TABLE [Wholesale_Codis_AFI].[EXTORD] (

	[XORDNO] char(7) NULL, 
	[RQSDAT] decimal(8,0) NULL, 
	[ORDUSE] varchar(10) NULL, 
	[ORDARR] char(2) NULL, 
	[ADVTSP] char(1) NULL, 
	[NOSETS] decimal(3,0) NULL, 
	[ORDREF] char(7) NULL, 
	[ORDLNK] decimal(6,0) NULL, 
	[CSRPID] decimal(5,0) NULL, 
	[EXTCTY] char(3) NULL, 
	[EXTSTE] char(2) NULL, 
	[OTTYP1] char(1) NULL, 
	[OTTYP2] char(1) NULL, 
	[OTTYP3] char(1) NULL, 
	[OTTYP4] char(1) NULL, 
	[MNTCNT] decimal(3,0) NULL, 
	[FRZDAT] decimal(8,0) NULL, 
	[SHPNAM] varchar(25) NULL, 
	[WHSE] char(3) NULL, 
	[CUSTNO] char(8) NOT NULL, 
	[SHPTO#] char(4) NOT NULL, 
	[TKNDAT] decimal(8,0) NULL, 
	[TRPNO] decimal(6,0) NULL, 
	[HDATE] decimal(8,0) NULL, 
	[DROP#] decimal(2,0) NULL, 
	[TRIP#] decimal(6,0) NULL, 
	[CREDVW] char(1) NULL, 
	[APVCHK] char(1) NULL, 
	[APPROV] varchar(15) NULL, 
	[ORDUSR] varchar(10) NULL, 
	[HLDUSR] varchar(10) NULL, 
	[TERRCD] char(2) NULL, 
	[CONTAC] varchar(25) NULL, 
	[PHONE#] varchar(20) NULL, 
	[REFNUM] decimal(6,0) NULL, 
	[RCVCSH] char(1) NULL, 
	[CAPRDT] decimal(8,0) NULL, 
	[CROVRD] char(1) NULL, 
	[CROVDT] decimal(8,0) NULL, 
	[CRANOV] varchar(10) NULL, 
	[CBDDAT] decimal(8,0) NULL, 
	[USRMNT] varchar(10) NULL, 
	[DATMNT] decimal(8,0) NULL, 
	[TIMMNT] decimal(6,0) NULL, 
	[ORTYPE] char(3) NULL, 
	[COMMCO] char(3) NULL, 
	[DSCNCO] char(3) NULL, 
	[PRICCO] char(6) NULL, 
	[FRGHCO] char(3) NULL, 
	[ZIPCOD] varchar(10) NULL, 
	[ARZONE] char(2) NULL, 
	[ARSEQ] decimal(2,0) NULL, 
	[ARDATE] decimal(8,0) NULL, 
	[PRMNBR] varchar(10) NULL
);