CREATE TABLE [Wholesale_Codis_AFI].[rqdtrcd] (

	[RDCREASONCODE] char(2) NULL, 
	[RDCDESCRIPTION] varchar(50) NULL, 
	[RDCADDDATE] numeric(8,0) NULL, 
	[RDCADDUSER] varchar(10) NULL, 
	[RDCCHANGEDATE] numeric(8,0) NULL, 
	[RDCCHANGEUSER] varchar(10) NULL, 
	[RDCSTATUS] char(1) NULL, 
	[RDCCANCELFLAG] char(1) NULL, 
	[RDCAVAILABLETOASHLEYDIRECT] char(1) NULL, 
	[RDCASHLEYDIRECTDESCRIPTION] varchar(25) NULL
);