Create VIEW [Quality_Enh_Wrk].[v_InvoiceSerialNumberPurchased]
AS
SELECT  [InvoiceDate]
      ,[InvoiceNumber]
      ,[SerialNumber]
      ,[OrderNumber]
      ,[ItemNumber]
      ,[ItemSeqNumber]
      ,[PONumber]
      ,[CustomerNumber]
      ,[ShiptoNumber]
      ,[VendorNumber]
      ,[SalesOffice]
      ,[CountryOfOrigin]
      ,[DropNumber]
      ,[ScanName]
      ,[LoadDate]
      ,[TruckNumber]
      ,[Carrier]
      ,[Warehouse]
      ,[AATWarehouse]
  FROM [$(Source_Data)].[Wholesale_SalesHistory_AFI].[InvoiceSerialNumberPurchased]