Create VIEW [Quality_Enh_Wrk].[v_InvoiceSerialNumberManufactured]
AS
SELECT  [InvoiceNumber]
      ,[SerialNumber]
      ,[OrderNumber]
      ,[ItemNumber]
      ,[ItemSeqNumber]
      ,[MfgOrderNumber]
      ,[CustomerNumber]
      ,[ShiptoNumber]
      ,[DropNumber]
      ,[WhereMade]
      ,[UserGroup]
      ,[MfgDate]
      ,[ScanName]
      ,[LoadDate]
      ,[TruckNumber]
      ,[Carrier]
      ,[Warehouse]
      ,[Department]
      ,[WorkCenter]
      ,[Group]
      ,[Shift]
      ,[SupervisorNumber]
      ,[AATWarehouse]
  FROM [$(Source_Data)].[Wholesale_SalesHistory_AFI].[InvoiceSerialNumberManufactured]
GO


