Create VIEW [CustomerOrders_AFI_Wrk].[v_OrderAuditHeader]
AS
SELECT 
       [OrderNo]
      ,[WhseNo]
      ,CAST(CAST(CustomerNo AS INT) AS CHAR(8)) as [CustomerNo]
      ,[ShipToNo]
      ,[PONumber]
      ,CASE WHEN CAST([OrderDate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([OrderDate] as INT) AS CHAR(8)) AS DATE) END AS  AHORDT
      ,[CustServAgentId]
      ,[TransType]
      ,[CancellationUserid]
      ,CASE WHEN CAST(CancellationDate as INT)= 0 THEN NULL ELSE CAST(CAST(CAST(CancellationDate as INT) AS CHAR(8)) AS DATE) END AS AHCNDT
      ,[CancellationReason]
      ,[AckPrintFlag]
      ,[AckEDIFlag]
	  ,CASE WHEN CAST([AckPrintDate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([AckPrintDate] as INT) AS CHAR(8)) AS DATE) END AS  [AHAKPD]
	  ,CASE WHEN CAST([AckEDIDate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([AckEDIDate] as INT) AS CHAR(8)) AS DATE) END AS  [AHAKED] 
      ,[InvoiceCompleteFlg]
      ,CASE WHEN CAST([InvoiceCompleteDte] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([InvoiceCompleteDte] as INT) AS CHAR(8)) AS DATE) END AS  [AHIVCD]
	  ,CASE WHEN CAST([LastActivityDate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([LastActivityDate] as INT) AS CHAR(8)) AS DATE) END AS  [AHLACD]
      ,[ArrivalMode]
      ,[OrderTypeCategryOne]
      ,[OrderTypeCategryTwo]
      ,[OrderTypeCategryThree]
      ,[OrderTypeCategryFour]
	  ,CASE WHEN CAST(OrderTakenDate as INT)= 0 THEN NULL ELSE CAST(CAST(CAST(OrderTakenDate as INT) AS CHAR(8)) AS DATE) END AS  AHORTD
      ,[InitialOrderValue]
	  ,CASE WHEN CAST([OfflineDate] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([OfflineDate] as INT) AS CHAR(8)) AS DATE) END AS  [AHOFFD]
      ,[AutoPosted]
      ,[PostedFrom]
      ,[Status]
      ,[CancellationNumber]
      ,[ReqDateatCancel]  
      ,[OrderEnteredBy]
  FROM [$(Source_Data)].[Wholesale_SalesHistory_AFI].[ordaudh]
