CREATE TABLE [masterdata_hr_ukg].[TimecardProcessedSegment] (

	[employeeId] int NULL, 
	[employeeQualifier] varchar(20) NULL, 
	[startDate] date NULL, 
	[segmentId] int NULL, 
	[itemId] int NULL, 
	[inProgress] bit NULL, 
	[projected] bit NULL, 
	[durationInSeconds] int NULL, 
	[durationInHours] decimal(17,6) NULL, 
	[startDateTime] datetime2(6) NULL, 
	[endDateTime] datetime2(6) NULL, 
	[roundedStartDateTime] datetime2(6) NULL, 
	[roundedEndDateTime] datetime2(6) NULL, 
	[applyDate] date NULL, 
	[segmentTypeId] int NULL, 
	[orderNumber] int NULL, 
	[transferWorkRuleId] int NULL, 
	[transferString] varchar(100) NULL, 
	[transferSystemGenerated] bit NULL, 
	[orgJobId] int NULL, 
	[orgJobQualifier] varchar(50) NULL, 
	[orgJobName] varchar(50) NULL, 
	[orgJobApplyDate] date NULL, 
	[workRuleId] int NULL, 
	[workRuleQualifier] varchar(50) NULL, 
	[workRuleName] varchar(50) NULL, 
	[laborAccountId] int NULL, 
	[laborReferenceId] int NULL, 
	[laborString] varchar(20) NULL, 
	[dwLoadDateTime] datetime2(6) NULL, 
	[dataSource] varchar(10) NULL
);