CREATE TABLE [SupplyChain_Enh].[AmazonCustomerInventory] (

	[ASIN] varchar(50) NULL, 
	[ProductTitle] varchar(500) NULL, 
	[ItemSKU] varchar(100) NULL, 
	[ProcurableProductOOS] decimal(10,2) NULL, 
	[VendorConfirmationRate] decimal(10,2) NULL, 
	[NetReceived] decimal(10,2) NULL, 
	[NetReceivedUnits] decimal(10,2) NULL, 
	[OpenPurchaseOrderQuantity] decimal(10,2) NULL, 
	[ReceiveFillRatePercentage] decimal(10,2) NULL, 
	[OverallVendorLeadTimedays] decimal(10,2) NULL, 
	[UnfilledCustomerOrderedUnits] decimal(10,2) NULL, 
	[Aged90+DaysSellableInventory] decimal(10,2) NULL, 
	[Aged90+DaysSellableUnits] decimal(10,2) NULL, 
	[SellableOnHandInventory] decimal(10,2) NULL, 
	[SellableOnHandUnits] decimal(10,2) NULL, 
	[UnsellableOnHandInventory] decimal(10,2) NULL, 
	[UnsellableOnHandUnits] decimal(10,2) NULL, 
	[SellThroughRate] decimal(10,2) NULL, 
	[UnhealthyInventory] decimal(10,2) NULL, 
	[UnhealthyUnits] decimal(10,2) NULL, 
	[JobRunDate] date NULL, 
	[SourceFoldersDate] date NULL, 
	[WeekEnding] date NULL
);