CREATE TABLE [CustomerOrders_AFI].[OrderAuditHeader] (
    [OrderNumber]           CHAR (7)        NULL,
    [Warehouse]             CHAR (3)        NULL,
    [CustomerNumber]        CHAR(8)         NOT NULL,
    [ShiptoNumber]          CHAR (4)        NOT NULL,
    [PONumber]              VARCHAR (30)    NULL,
    [OrderDate]             DATE            NULL,
    [CustomerServAgentId]   DECIMAL (5)     NULL,
    [TransactionType]       CHAR (1)        NULL,
    [CancellationUserid]    VARCHAR (10)    NULL,
    [CancellationDate]      DATE            NULL,
    [CancelledReasonedCode] CHAR (2)        NULL,
    [AckPrintFlag]          CHAR (1)        NULL,
    [AckEDIFlag]            CHAR (1)        NULL,
    [AckPrintDate]          DATE            NULL,
    [AckEDIDate]            DATE            NULL,
    [InvoiceCompleteFlg]    CHAR (1)        NULL,
    [InvoiceCompleteDte]    DATE            NULL,
    [LastActivityDate]      DATE            NULL,
    [OrderArrivalMode]      CHAR (2)        NULL,
    [OrderTypeCategryOne]   CHAR (1)        NULL,
    [OrderTypeCategryTwo]   CHAR (1)        NULL,
    [OrderTypeCategryThree] CHAR (1)        NULL,
    [OrderTypeCategryFour]  CHAR (1)        NULL,
    [OrderTakenDate]        DATE            NULL,
    [InitialOrderValue]     DECIMAL (13, 2) NULL,
    [OfflineDate]           DATE            NULL,
    [AutoPosted]            CHAR (1)        NULL,
    [PostedFrom]            CHAR (1)        NULL,
    [Status]                DECIMAL (2)     NULL,
    [CancellationNumber]    DECIMAL (13)    NULL,
    [ReqDateatCancel]       DATE            NULL,
    [OrderEnteredBy]        VARCHAR (10)    NULL
)


