CREATE TABLE [Customers].[AccountMaster]
    (
        [CustomerNumber]          CHAR(8)        NULL,
        [Phone]                   VARCHAR(12)    NULL,
        [Faxtn]                   VARCHAR(12)    NULL,
        [Contact]                 VARCHAR(25)    NULL,
        [Email]                   VARCHAR(50)    NULL,
        [PrimaryTerritory]        CHAR(5)        NULL,
        [MinimumFreightCode]      CHAR(1)        NULL,
        [CreditLimitAmount]       INT            NULL,
        [TermsCode]               CHAR(3)        NULL,
        [TermsDays]               SMALLINT       NULL,
        [CreditTerritoryID]       INT        NULL,
        [CancelBackOrders]        INT        NULL,
        [AllowPartialShipment]    INT        NULL,
        [CustomerClassCode]       CHAR(5)        NULL,
        [LanguageCode]            CHAR(3)        NULL,
        [StatementCode]           INT        NULL,
        [ItemCrossReferenceCode]  CHAR(1)        NULL,
        [TerritoryChangeDate]     DATETIME2(6)   NULL,  ----DATETIME2(6)
        [CreditAuthorizationCode] CHAR(1)        NULL,
        [Memo]                    VARCHAR(8000)   NULL,  --VARCHAR(MAX) 
        [ChgCustAr]               BIT            NULL,
        [ChgCust]                 BIT            NULL,
        [ChgCustExt]              BIT            NULL,
        [PercentAvailableCredit]  DECIMAL(3, 2)  NULL,
        [CommAudit]               BIT            NULL,
        [InheritBlocking]         BIT            NULL,
        [CustomerName]            VARCHAR(25)    NULL,
        [AddedByUser]                    VARCHAR(30)    NULL,
        [DateAdded]                    DATETIME2(6)   NULL,  --DATETIME2(6)
        [ChangeByUser]                    VARCHAR(30)    NULL,  
        [DateChange]                    DATETIME2(6)   NULL, --DATETIME2(6)
        [ActiveRecord]                   CHAR(1)        NULL,
        [LastStatusChangeDate]    DATETIME2(6)   NULL,
        [BillingAddressID]        INT            NULL,
        [DBAName]                 VARCHAR(25)    NULL,
        [LateChargePercent]       DECIMAL(5, 4)  NULL,
        [MinPreapprovalAmount]    DECIMAL(12, 2) NULL,
        [CreditAddessCode]        CHAR(3)        NULL,
        [RFCTaxIdNumber]          VARCHAR(20)    NULL,
        [DocumentationHold]       CHAR(1)        NULL,
        [PARSByPurchaser]         CHAR(1)        NULL,
        [10DigitScheduleB]        CHAR(1)        NULL,
        [TypeOfInsurance]         VARCHAR(10)    NULL,
        [InsExpirationDate]       DATETIME2(6)   NULL,  --DATETIME2(6)
        [InsCoverageRequested]    DECIMAL(10, 2) NULL,
        [InsCoverageApproved]     DECIMAL(10, 2) NULL,
        [InsuranceStatus]         VARCHAR(10)    NULL,
        [HomestoreFacingWhse]     CHAR(1)        NULL,
        [Appcd]                   INT            NULL,
        [DeductTerritoryId]       DECIMAL(2)     NULL,
        [CurrencyCode]            CHAR(3)        NULL,
        [AllowAllowanceCredits]   BIT            NULL
    );
--- DATA_SOURCE = [AzureStorageGen2a],
--- LOCATION = N'/Wholesale/Customers/AccountMaster/AFI_Sales_tblCustomerAccountMaster.snappy.parquet',
--- FILE_FORMAT = [ParquetFileFormatSnappy],
