CREATE TABLE [Customers].[ExtendedCustomerProfile]
    (
        [CompanyNum]                   INT        NULL,
        [CustomerNumber]                  CHAR(8)        NULL,
        [ShiptoNumber]                    CHAR(4)        NULL,
        [EMailAddress]                 VARCHAR(50)    NULL,
        [ApptRequired]                 CHAR(1)        NULL,
        [InforceMin]                   CHAR(1)        NULL,
        [RouteZone]                    CHAR(3)        NULL,
        [TimeZone]                     CHAR(3)        NULL,
        [TruckSizeLimit1]              CHAR(3)        NULL,
        [TruckSizeLimit2]              CHAR(3)        NULL,
        [CubeMaxPerTruck]              INT            NULL,
        [ReqFlagMatch]                 VARCHAR(12)    NULL,
        [GEOLocId]                     VARCHAR(13)    NULL,
        [GEOLat]                       DECIMAL(13, 4) NULL,
        [GEOLong]                      DECIMAL(13, 4) NULL,
        [GEOAccuracy]                  INT            NULL,
        [GEOType]                      CHAR(1)        NULL,
        [LastAddrVerfyDate]            DATETIME2(6)   NULL,
        [DaysBetwnAddrVerfy]           SMALLINT       NULL,
        [GrpOrdersByLoadDate]          CHAR(1)        NULL,
        [MethodOrdersRouted]           CHAR(1)        NULL,
        [DoingBusinessAs]              VARCHAR(25)    NULL,
        [County]                       CHAR(3)        NULL,
        [ServeTimeMinOverride]         INT            NULL,
        [ServeTimeFixedDrop]           INT            NULL,
        [FirstOnRoute]                 CHAR(1)        NULL,
        [WindowsNotRequired]           BIT            NULL,
        [AddedByUser]                         VARCHAR(30)    NULL,
        [DateAdded]                         DATETIME2(6)   NULL,
        [ChangeByUser]                         VARCHAR(30)    NULL,
        [DateChange]                         DATETIME2(6)   NULL,
        [OrderMinimum]                 DECIMAL(7)     NULL,
        [RouteRegion]                  CHAR(3)        NULL,
        [Replicate]                    BIT            NULL,
        [RPOrderEmailNotify]           CHAR(1)        NULL,
        [RPOrderEmailAddress]          VARCHAR(75)    NULL,
        [AutoSchedule]                 CHAR(1)        NULL,
        [AutoFreeze]                   CHAR(1)        NULL,
        [RPShippingLocation]           CHAR(1)        NULL,
        [NextAvailableDeliveryAppt]    DATETIME2(6)   NULL,
        [RoutePosition]                DECIMAL(3)     NULL,
        [LastOnLoad]                   DECIMAL(1)     NULL,
        [ReasonCode]                   CHAR(2)        NULL,
        [DateNextDelvryDateEntered]    DATETIME2(6)   NULL,
        [CommentNextDeliveryDate]      VARCHAR(25)    NULL,
        [ExceptionToShipCompleteRule]  CHAR(1)        NULL,
        [OnCarriageTo]                 VARCHAR(35)    NULL,
        [NotifyPartyName]              VARCHAR(35)    NULL,
        [NotifyPartyAddress1]          VARCHAR(35)    NULL,
        [NotifyPartyAddress2]          VARCHAR(35)    NULL,
        [NotifyPartyCity]              VARCHAR(35)    NULL,
        [NotifyPartyState]             CHAR(2)        NULL,
        [NotifyPartyZip]               VARCHAR(10)    NULL,
        [NotifyPartyCountry]           CHAR(3)        NULL,
        [UltimateDestinationCity]      VARCHAR(35)    NULL,
        [UltimateDestinationState]     CHAR(2)        NULL,
        [UltimateDestinationCountry]   CHAR(3)        NULL,
        [CommercialInvoiceHeading]     CHAR(1)        NULL,
        [FreightForwardingFeeOverride] DECIMAL(7, 2)  NULL,
        [InsuranceFeeOverride]         DECIMAL(7, 2)  NULL,
        [CourierFee]                   DECIMAL(7, 2)  NULL,
        [ParsByPurchaser]              CHAR(1)        NULL,
        [DefaultCarrier]               VARCHAR(25)    NULL,
        [OverrideRouteZone]            BIT            NULL,
        [OverrideRouteZoneUser]        VARCHAR(30)    NULL,
        [OverrideRouteZoneDate]        DATETIME2(6)   NULL,
        [ShowConsolidatedATP]          BIT            NULL,
        [DoNotAllowLineItemSplit]      CHAR(1)        NULL,
        [AllocationCubeMinimum]        SMALLINT       NULL,
        [RestrictManualOrderEntry]     CHAR(1)        NULL,
        [AutomateFill]                 CHAR(1)        NULL,
        [RequestDaysOut]               SMALLINT       NULL
    );


--    DATA_SOURCE = [AzureStorageGen2a],
--   LOCATION = N'/Wholesale/Customers/ExtendedCustomerProfile/AFI_Sales_tblExtendedCustomerProfile.snappy.parquet',
--   FILE_FORMAT = [ParquetFileFormatSnappy],

