CREATE TABLE [Wholesale_Codis_Wrk].[dscadjoo] (

	[Joentl] decimal(10,0) NULL, 
	[Joseqn] decimal(10,0) NULL, 
	[Jocode] char(1) NULL, 
	[Joentt] char(2) NULL, 
	[Jodate] char(6) NULL, 
	[Jotime] decimal(10,0) NULL, 
	[Jojob] char(10) NULL, 
	[Jouser] char(10) NULL, 
	[Jonbr] decimal(10,0) NULL, 
	[Jopgm] char(10) NULL, 
	[Joobj] char(10) NULL, 
	[Jolib] char(10) NULL, 
	[Jombr] char(10) NULL, 
	[Joctrr] decimal(10,0) NULL, 
	[Joflag] char(1) NULL, 
	[Joccid] decimal(10,0) NULL, 
	[Jouspf] char(10) NULL, 
	[Josynm] char(8) NULL, 
	[Joincdat] char(1) NULL, 
	[Jominesd] char(1) NULL, 
	[Jores] char(18) NULL, 
	[Dcoordernumber] char(7) NULL, 
	[Dcoitemsequence] decimal(12,0) NULL, 
	[Dcodiscounttype] char(1) NULL, 
	[Dcodiscountadjustmentcode] char(3) NULL, 
	[Dcoitemnumber] varchar(17) NULL, 
	[Dcoamount] decimal(12,2) NULL, 
	[Dcoratioamount] decimal(12,2) NULL, 
	[Dcodiscountpercent] decimal(8,4) NULL, 
	[Dcoexceptionid] decimal(12,0) NULL, 
	[Dcodiscountcode] char(3) NULL, 
	[Dcodiscountsalesclass] char(2) NULL
);