CREATE TABLE [Retail_Sales_Wrk].[Invoice] (

	[Addon1Cost] decimal(18,9) NOT NULL, 
	[Addon2Cost] decimal(18,9) NOT NULL, 
	[Addon3Cost] decimal(18,9) NULL, 
	[Addon4Cost] decimal(18,9) NULL, 
	[AlertCodeID] varchar(50) NULL, 
	[AlternateTaxJurisdictionCode] varchar(255) NULL, 
	[AlternateTaxTransactionNbr] varchar(255) NULL, 
	[AltTaxTransactionIDDate] datetime2(3) NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[Base_OrderID] varchar(50) NULL, 
	[BillToParentID] varchar(50) NULL, 
	[CODAmt] decimal(18,9) NOT NULL, 
	[Comments] varchar(max) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[CreditAppNbr] varchar(50) NULL, 
	[CreditCardAmt] decimal(18,9) NOT NULL, 
	[CreditCardExpDate] varchar(50) NULL, 
	[CreditCardID] varchar(100) NULL, 
	[CreditCardNbr] varchar(100) NULL, 
	[CreditHoldCodeID] varchar(50) NULL, 
	[CreditMemoAsOfDate] datetime2(3) NULL, 
	[CSLastContact] date NULL, 
	[CSNextContact] date NULL, 
	[CurrentOrderValue] decimal(18,9) NOT NULL, 
	[CustClass] varchar(10) NULL, 
	[CustCreditChkFlg] bit NULL, 
	[Custom1] varchar(max) NULL, 
	[Custom2] varchar(100) NULL, 
	[Custom3] varchar(100) NULL, 
	[Custom4] varchar(100) NULL, 
	[CustomerID] varchar(50) NOT NULL, 
	[CustomerPONumber] varchar(50) NULL, 
	[CustPONbr] varchar(50) NULL, 
	[CustPriceCategory] varchar(10) NOT NULL, 
	[CustType] int NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DeliveryContactDate] date NULL, 
	[DeliveryContactStatusID] varchar(50) NULL, 
	[DepositHoldPct] numeric(18,2) NOT NULL, 
	[DesiredDate] date NULL, 
	[DirectShip_FreightCompanyID] varchar(50) NULL, 
	[DirShipAddlTaxAmt] decimal(18,9) NOT NULL, 
	[DirShipCustDiscntAmt] decimal(18,9) NOT NULL, 
	[DirShipDate] datetime2(3) NULL, 
	[DirShipDlvyChrg] decimal(18,9) NULL, 
	[DirShipDlvyChrgOverride] varchar(10) NULL, 
	[DirShipItems] int NOT NULL, 
	[DirShipStateTaxAmt] decimal(18,9) NULL, 
	[DirShipStateTaxID] varchar(100) NULL, 
	[DirShipStateTaxRate] numeric(18,4) NULL, 
	[DirShipStatus] varchar(10) NULL, 
	[DirShipStoreID] varchar(50) NULL, 
	[DirShipSubTot] decimal(18,9) NOT NULL, 
	[DirShipWhseMgmtShipped] datetime2(3) NULL, 
	[DirShipWhseMgmtTransmitted] datetime2(3) NULL, 
	[DiscDollarOrPct] varchar(50) NULL, 
	[DiscntCode] varchar(10) NULL, 
	[DiscntPct] numeric(18,2) NOT NULL, 
	[DlvryChrgOverrideReasonCodeID] varchar(50) NULL, 
	[DlvyAddlTaxAmt] decimal(18,9) NULL, 
	[DlvyChrg] decimal(18,9) NOT NULL, 
	[DlvyChrgOverride] varchar(10) NULL, 
	[DlvyCommissionCostPercent] numeric(18,2) NULL, 
	[DlvyCommissionDeliveryAmt] decimal(18,9) NULL, 
	[DlvyCommissionPercent] numeric(18,2) NULL, 
	[DlvyCommissionType] varchar(10) NULL, 
	[DlvyCustDiscntAmt] decimal(18,9) NOT NULL, 
	[DlvyDate] datetime2(3) NULL, 
	[DlvyItems] int NOT NULL, 
	[DlvyStateTaxAmt] decimal(18,9) NULL, 
	[DlvyStateTaxID] varchar(100) NULL, 
	[DlvyStateTaxRate] numeric(18,4) NULL, 
	[DlvyStatus] varchar(10) NULL, 
	[DlvyStoreID] varchar(50) NULL, 
	[DlvySubTot] decimal(18,9) NOT NULL, 
	[DlvyWhseMgmtShipped] datetime2(3) NULL, 
	[DlvyWhseMgmtTransmitted] datetime2(3) NULL, 
	[FinanceAmt] decimal(18,9) NOT NULL, 
	[FinanceApplied_StaffID] varchar(50) NULL, 
	[FinanceAppliedDateTime] datetime2(3) NULL, 
	[FinanceApprvAmt] decimal(18,9) NOT NULL, 
	[FinanceApprvNbr] varchar(100) NULL, 
	[FinanceAuthDate] datetime2(3) NULL, 
	[FinanceAuthNbr] varchar(100) NULL, 
	[FinanceHouseType] varchar(20) NULL, 
	[FinanceInsuranceFlg] varchar(10) NULL, 
	[FinancePaymentTypeID] varchar(50) NULL, 
	[FinanceReferenceNbr] varchar(50) NULL, 
	[FreightCompanyID] varchar(50) NULL, 
	[GlobalDiscount] decimal(18,9) NULL, 
	[GlobalDiscountedSubTotal] decimal(18,9) NULL, 
	[HomePhone] varchar(15) NULL, 
	[InstallationChrg] decimal(18,9) NOT NULL, 
	[InstallationChrgOverride] varchar(10) NULL, 
	[InvoiceDate] date NULL, 
	[IsAutoLineDiscountActive] bit NULL, 
	[LandedFreight] decimal(18,9) NOT NULL, 
	[LineDiscountOperationOrder] varchar(10) NULL, 
	[LineDiscountScheduleID] varchar(50) NULL, 
	[ManifestNbr] varchar(50) NULL, 
	[MarketingCode2ID] varchar(50) NULL, 
	[MarketingCodeID] varchar(50) NULL, 
	[MerchSubTot] decimal(18,9) NOT NULL, 
	[MultiShipMasterReference] varchar(50) NULL, 
	[NbrOfInvoices] int NULL, 
	[OperInit] varchar(10) NULL, 
	[OrderBookedStoreID] varchar(50) NOT NULL, 
	[OrderDate] date NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[OrderSourceID] varchar(50) NULL, 
	[OriginalInvoiceID] varchar(50) NULL, 
	[OrigMarketingCode1ID] varchar(50) NULL, 
	[OrigMarketingCode2ID] varchar(50) NULL, 
	[OrigMarketingCodeBooked] decimal(18,9) NULL, 
	[PickListPrinted] bit NULL, 
	[PickupAddlTaxAmt] decimal(18,9) NULL, 
	[PickupChrg] decimal(18,9) NULL, 
	[PickupChrgOverride] varchar(10) NULL, 
	[PickupCustDiscntAmt] decimal(18,9) NOT NULL, 
	[PickupDate] datetime2(3) NULL, 
	[PickupItems] int NOT NULL, 
	[PickupStateTaxAmt] decimal(18,9) NULL, 
	[PickupStateTaxID] varchar(100) NULL, 
	[PickupStateTaxRate] numeric(18,4) NULL, 
	[PickupStatus] varchar(10) NULL, 
	[PickupStoreID] varchar(50) NULL, 
	[PickupSubTot] decimal(18,9) NOT NULL, 
	[PickupWhseMgmtShipped] datetime2(3) NULL, 
	[PickupWhseMgmtTransmitted] datetime2(3) NULL, 
	[PointOfTax] varchar(1) NULL, 
	[PriceExceptionComment] varchar(max) NULL, 
	[RecStatus] varchar(1) NULL, 
	[RefundChkAmt] decimal(18,9) NOT NULL, 
	[Repossession] bit NULL, 
	[RevolvingOrderStatus] varchar(20) NULL, 
	[RewardPoints] int NULL, 
	[RouteCodeID] varchar(50) NULL, 
	[SalesTaxExmpNbr] varchar(50) NULL, 
	[ServiceAddr1] varchar(255) NULL, 
	[ServiceAddr2] varchar(255) NULL, 
	[ServiceCity] varchar(50) NULL, 
	[ServicePostalCodeID] varchar(50) NULL, 
	[ServiceStaffID] varchar(50) NULL, 
	[ServiceState] varchar(50) NULL, 
	[ServiceStoreID] varchar(50) NULL, 
	[ServiceStoreName] varchar(255) NULL, 
	[ServiceType] varchar(10) NULL, 
	[ShipInstr] varchar(max) NULL, 
	[ShipToAddr1] varchar(100) NULL, 
	[ShipToAddr2] varchar(100) NULL, 
	[ShipToCellPhone] varchar(15) NULL, 
	[ShipToCity] varchar(100) NULL, 
	[ShipToContact] varchar(50) NULL, 
	[ShipToEmailAddress] varchar(70) NULL, 
	[ShipToID] varchar(50) NULL, 
	[ShipToName] varchar(100) NULL, 
	[ShipToPostalCodeId] varchar(50) NULL, 
	[ShipToState] varchar(50) NULL, 
	[ShipZone] varchar(50) NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[SpecOrderFlg] bit NULL, 
	[StopTime] varchar(50) NULL, 
	[TakenAddlTaxAmt] decimal(18,9) NULL, 
	[TakenChrg] decimal(18,9) NULL, 
	[TakenChrgOverride] varchar(10) NULL, 
	[TakenCustDiscntAmt] decimal(18,9) NOT NULL, 
	[TakenDate] datetime2(3) NULL, 
	[TakenItems] int NOT NULL, 
	[TakenStateTaxAmt] decimal(18,9) NULL, 
	[TakenStateTaxID] varchar(100) NULL, 
	[TakenStateTaxRate] numeric(18,4) NULL, 
	[TakenStatus] varchar(10) NULL, 
	[TakenStoreID] varchar(50) NULL, 
	[TakenSubTot] decimal(18,9) NOT NULL, 
	[TakenWhseMgmtShipped] datetime2(3) NULL, 
	[TakenWhseMgmtTransmitted] datetime2(3) NULL, 
	[TaxableFlg] bit NOT NULL, 
	[TermsID] varchar(50) NULL, 
	[TotAddlTaxAmt] decimal(18,9) NULL, 
	[TotCommissionableAmt] decimal(18,9) NOT NULL, 
	[TotCustDiscntAmt] decimal(18,9) NOT NULL, 
	[TotInvcAmt] decimal(18,9) NOT NULL, 
	[TotMerchCost] decimal(18,9) NOT NULL, 
	[TotOrderValue] decimal(18,9) NOT NULL, 
	[TotPaymentAmt] decimal(18,9) NOT NULL, 
	[TotSaleAmt] decimal(18,9) NOT NULL, 
	[TotShipWeight] numeric(18,2) NOT NULL, 
	[TotSpecOrderAmt] decimal(18,9) NOT NULL, 
	[TotStateTaxAmt] decimal(18,9) NULL, 
	[Trade_CustomerID] varchar(50) NULL, 
	[TradeDiscountPercent] numeric(18,2) NULL, 
	[TradeDiscountVersion] varchar(50) NULL, 
	[TransCodeID] int NOT NULL, 
	[TruckNbr] varchar(10) NULL, 
	[VoidedDate] date NULL, 
	[VoidedOrderReasonCodeID] varchar(50) NULL, 
	[WebTaxAmount] numeric(18,2) NULL, 
	[WorkPhone] varchar(15) NULL, 
	[WorkPhoneExt] varchar(10) NULL, 
	[NewEntryFlag] bit NULL, 
	[TransactionSaveTime] datetime2(3) NULL, 
	[TransactionStartTime] datetime2(3) NULL
);