CREATE SCHEMA [SSAS_AFISALES_OLAP]
    AUTHORIZATION [dbo];



GO
GRANT VIEW DEFINITION
    ON SCHEMA::[SSAS_AFISALES_OLAP] TO [Sg_AFI_RADAR_Finance_MS_Admin_Unv];


GO
GRANT SELECT
    ON SCHEMA::[SSAS_AFISALES_OLAP] TO [Sg_AFI_RADAR_Finance_MS_Admin_Unv];

GO
GRANT EXECUTE
    ON SCHEMA::[SSAS_AFISALES_OLAP] TO [Sg_AFI_RADAR_Finance_MS_Admin_Unv];


GO


