CREATE VIEW [Pricing_AFI_Wrk].[v_BuyGroupPrice]
AS
SELECT  [bgpBgcode]
      ,[bgpWhse]
      ,[bgpItnbr]
      ,[bgpPrice]
      ,[bgpFrchrg]
      ,[bgpDate1]
      ,[bgpDate2]
      ,[bgpGssdat]
      ,[bgpGesdat]
      ,[bgpGcmsn]
      ,[bgpGcmpct]
      ,[bgpDisc1]
      ,[bgpDisc2]
      ,[bgpDisc3]
      ,[bgpDisc4]
      ,[bgpDisc5]
      ,[bgpDisc6]
      ,[bgpDisc7]
      ,[bgpGexcid]
      ,[bgpGbpred]
      ,[commaudit]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[BuyGroupPrice]