CREATE VIEW [Pricing_AFI_Wrk].[v_DiscountRates]
  as
  SELECT [dradcode]
      ,[dradiscls]
      ,[dradisc1]
      ,[dradisc2]
      ,[dradisc3]
      ,[dradisc4]
      ,[dradisc5]
      ,[dradisc6]
      ,[dradisc7]
      ,[drasdate]
      ,[draedate]
      ,[commaudit]
      ,[usra]
      ,[dtea]

      ,[usrc]
      ,[dtec]
      ,[acrec]
    FROM [$(Source_Data)].[wholesale_pricing_afi].[DiscountRates]
