CREATE VIEW [Pricing_AFI_Wrk].[v_FreightZones]
AS
SELECT [fzoCountry]
      ,[fzoState]
      ,[fzoZip]
      ,[fzoZipext]
      ,[fzoFzone]
      ,[fzoFwhse]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[FreightZones]