CREATE VIEW [Pricing_AFI_Wrk].[v_PriceExceptions]
AS
SELECT [pexItnbr]
      ,[pexCusno]
      ,[pexShpno]
      ,[pexWhse]
      ,[pexDisc1]
      ,[pexDisc2]
      ,[pexDisc3]
      ,[pexDisc4]
      ,[pexDisc5]
      ,[pexDisc6]
      ,[pexDisc7]
      ,[pexPrice]
      ,[pexDate1]
      ,[pexDate2]
      ,[pexEfrtyn]
      ,[pexEssdat]
      ,[pexEesdat]
      ,[pexEocmmp]
      ,[pexEbpred]
      ,[pexEexcid]
      ,[pexEcmadj]
      ,[pexEordno]
      ,[pexEitseq]
      ,[pexEbtrep]
      ,[pexEstrep]
      ,[pexEstcom]
      ,[commaudit]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
  FROM [$(Source_Data)].[wholesale_pricing_afi].[PriceExceptions]