CREATE VIEW [Marketing_Wrk].[v_AdFundsRequest]
as
SELECT [afRequestID]
      ,[afAccountName]
      ,[afAccountNumber]
      ,[afShipTo]
      ,[afOwner]
      ,[afVicePresident]
      ,[afStatus]
      ,[afAmount]
      ,[afCreatedDate]
      ,[afFundType]
      ,[afNotes]
      ,[afDivision]
      ,[afEventName]
      ,[afSpecialDiscountCode]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[afEventStartDate]
      ,[afEventEndDate]
      ,[afUsedFor]
      ,[afgoal]
      ,[afPercentOrAmount]
      ,[afCategoryFocusedOn]
      ,[afCreditIssuedBy]
      ,[afCreditIssuedOn]
      ,[afApprovedBy]
      ,[afApprovedOn]
      ,[afRejectedBy]
      ,[afRejectedOn]
      ,[afParentVicePresident]
      ,[afCreditCode]
      ,[afCreditMemoComments]
      ,[afDoNotPrint]
  FROM [$(Source_Data)].[Wholesale_Marketing].[Adfundsrequest]
  
