CREATE view [Marketing_Wrk].[v_AdNotice]
as
SELECT  [Anokey]
      ,[Anocustomernumber]
      ,[Anoshipnumber]
      ,[Anouserlogin]
      ,[Anostartdate]
      ,[Anoenddate]
      ,[Anodescription]
      ,[Anocomments]
      ,[Anoemailtime]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Anospecialdescription]
      ,[Anostatus]
      ,[Anonoticetype]
      ,[Anorequestdate]
      ,[Anosubmitdate]
      ,[Anoapprovaldate]
      ,[Anouseredited]
      ,[Anoresponsedate]
      ,[Anoallshiptos]
      ,[Anoorderfulfilled]
  FROM [$(Source_Data)].[Wholesale_Marketing].[AdNotice]