CREATE view [Marketing_Wrk].[v_BusinessType]
AS
SELECT  [Btybtcode]
      ,[Btybtdesc]
      ,[Btybtgroup]
      ,[Btylocator]
      ,[Btybtyrental]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Btyrptbustype]
  FROM [$(Source_Data)].[Wholesale_Marketing].[BusinessType]