CREATE VIEW [Marketing_Wrk].v_CRMAdvertisingFunds
AS
SELECT
      [Cafid]
      ,[Cafregioncode]
      ,[Cafrepid]
      ,[Cafdivisioncode]
      ,[Cafaccountnumber]
      ,[Cafshipto]
      ,[Cafcreateddate]
      ,[Cafmarketdate]
      ,[Cafmodifieddate]
      ,[Cafmodifiedby]
      ,[Cafadfundsselecteddivision]
      ,[Cafadfundsvelocitydriver]
      ,[Caftypeoffundname]
      ,[Cafapprovalstatuscode]
      ,[Cafapprovalstatusdescr]
      ,[Cafadfundsrequested]
      ,[Cafadfundsapproved]
      ,[Cafnew_comments]
      ,[Cafnew_specialdiscountcodeifapplicable]
      ,[Cafnew_adfundsname]
  FROM [$(Source_Data)].[Wholesale_Marketing].[CRMAdvertisingFunds]