CREATE view [Marketing_Wrk].[v_Divisions]
AS
SELECT [Divdivcode]
      ,[Divdivdesc]
      ,[Divisdivdesc]
      ,[Divpresident]
      ,[Divslscls]
      ,[Divmhs_name]
      ,[Divothreg]
      ,[Divrepid]
      ,[Divitnbr]
      ,[Divitdsc]
      ,[Divitseq]
      ,[Divgrpdsc]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Divcompaniondiv]
      ,[Divcrmcode]
  FROM [$(Source_Data)].[Wholesale_Marketing].[Divisions]