create view [Marketing_Wrk].[v_ItemMaster]
AS
SELECT   [Imaitnbr]
      ,[Imadescrip]
      ,[Imaclass]
      ,[Imastyle]
      ,[Imastdcst]
      ,[Imastdprc]
      ,[Imastatus]
      ,[Imaweight]
      ,[Imacubes]
      ,[Imaslscls]
      ,[Imanbseat]
      ,[Imaatp_itnbr]
      ,[Imacomcls]
      ,[Imadiscls]
      ,[Imafrtcls]
      ,[Imacex]
      ,[Imacex2]
      ,[Imawidth1]
      ,[Imawidth2]
      ,[Imaheight1]
      ,[Imaheight2]
      ,[Imadepth1]
      ,[Imadepth2]
      ,[Imaitscdt]
      ,[Imapmfpus]
      ,[Imagrpcd]
      ,[Imagdescd]
      ,[Imaleafin]
      ,[Imadivcode]
      ,[Imaqtycr]
      ,[Imagrpcdlen]
      ,[Commaudit]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Imaslscat]
      ,[Imablockcode]
	  ,Imaunitofmeasure
      ,[Imaupcprefix]
      ,[Imaupccode]
      ,[Imaupccheckdigit]
      ,[Imahtsnumber]
      ,[Imaitemtypecode]
      ,[Imaimportdomestic]
      ,[Imacountryoforigin]
      ,[Imalastchangeddate]
      ,[Imagtincode]
      ,[Imagoodbetterbest]
   
  FROM [$(Source_Data)].[Wholesale_Marketing].[ItemMaster]
GO


 

   