CREATE view [Marketing_Wrk].[v_LocationDeliveryMode]
AS
SELECT  [Ldmrouteaddressid]
      ,[Ldmwarehouse]
      ,[Ldmtriptype]
      ,[Ldmdeliverymode]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Ldmresourcerequirements]
      ,[Ldmloadleadtime]
      ,[Ldmcubemax]
      ,[Ldmlastuserchanged]
      ,[Ldmpackinglist]
      ,[Ldmroutingleadtimeoverride]
  FROM [$(Source_Data)].[Wholesale_Marketing].[LocationDeliveryMode]