create view [Marketing_Wrk].[v_MrktSpclstMaster]
as
SELECT  [Msmslsno]
      ,[Msmslsnm]
      ,[Msmbusnm]
      ,[Msmrepid]
      ,[Msmmgrid]
      ,[Msmmhscode]
      ,[Msmposition]
      ,[Msmfid]
      ,[Msmhomec]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Msmstartdate]
      ,[Msmenddate]
      ,[Msmuse1099]
  FROM [$(Source_Data)].[Wholesale_Marketing].[MrktSpclstMaster]