CREATE VIEW [Marketing_Wrk].[v_RepCustomerFilter]
AS
SELECT  [Rcfmhs_name]
      ,[Rcfuserid]
      ,[Rcfcustomernumber]
      ,[Rcfshiptonumber]
      ,[Rcfsalesmannumber]
      ,[Rcffiltera]
      ,[Rcffilterb]
      ,[Rcffilterc]
      ,[Rcffilterd]
      ,[Acrec]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
  FROM [$(Source_Data)].[Wholesale_Marketing].[RepCustomerFilter]