CREATE VIEW [Marketing_Wrk].[v_SalesCategory]
AS
SELECT  [Scaslscat]
      ,[Scaslscnm]
      ,[Scaslsdvn]
      ,[Scamktpotfactor]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
      ,[Scaproductline]
      ,[Scahomestoreproductline]
      ,[Scaproductdivision]
      ,[Scacommissionclass]
  FROM [$(Source_Data)].[Wholesale_Marketing].[SalesCategory]