CREATE VIEW [Marketing_Wrk].[v_TerritoryQuotaWrt]
AS
SELECT [Quorepid]
      ,[Quoslscat]
      ,[Quoinpsmn]
      ,[Quoinpswk]
      ,[Quoinpsyr]
      ,[Quonetamtwrt]
      ,[Quodivision]
      ,[Quoregion]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
  FROM  [$(Source_Data)].[Wholesale_Marketing].[TerritoryQuotaWrt]