CREATE VIEW [Marketing_Wrk].[v_TerritoryAssignment]
AS
SELECT  [Tasterrcd]
      ,[Tascomcls]
      ,[Tasslsno]
      ,[Tassdate]
      ,[Tasedate]
      ,[Commaudit]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
  FROM [$(Source_Data)].[Wholesale_Marketing].[TerritoryAssignment]