CREATE VIEW [Marketing_Wrk].[v_TerritoryQuota]
AS
SELECT  [Quorepid]
      ,[Quoslscat]
      ,[Quoinpsmn]
      ,[Quoinpswk]
      ,[Quoinpsyr]
      ,[Quonetamtsh]
      ,[Quodivision]
      ,[Quoregion]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Acrec]
  FROM [$(Source_Data)].[Wholesale_Marketing].[TerritoryQuota]