CREATE VIEW [Marketing_Wrk].[v_TravelBooks]
AS
SELECT [Tbrequestid]
      ,[Tbenteredby]
      ,[Tbentereddate]
      ,[Tbenteredrole]
      ,[Tbenteredemail]
      ,[Tbrecipient]
      ,[Tbrecipientrole]
      ,[Tbrecipientemail]
      ,[Tbpostvisitstatus]
      ,[Tbpostvisitcomments]
      ,[Tbdateofvisitorreview]
      ,[Tbdeliverydate]
      ,[Tbprintchart]
      ,[Tbprintgrid]
      ,[Tbdivision]
      ,[Tbaccountname]
      ,[Tbaccountnumber]
      ,[Tbshipto]
      ,[Tbstatus]
      ,[Tbvisitonly]
      ,[Tbenteredname]
      ,[Tbrecipientname]
      ,[Usra]
      ,[Dtea]
      ,[Usrc]
      ,[Dtec]
      ,[Tbcomments]
FROM [$(Source_Data)].[Wholesale_Marketing].[TravelBooks]