CREATE TABLE [Wholesale_Invoicing_AFI].[MC2CUIL4I] (

	[CusCompny] numeric(2,0) NOT NULL, 
	[CusCusnbr] numeric(8,0) NOT NULL, 
	[Cusbrcomp] numeric(2,0) NOT NULL, 
	[CusBranch] numeric(8,0) NOT NULL, 
	[CusHdqtrs] varchar(15) NOT NULL, 
	[CusEntity] varchar(15) NOT NULL, 
	[CusAlcltx] varchar(35) NOT NULL, 
	[CusInvnbr] numeric(6,0) NOT NULL, 
	[CusInvifm] varchar(14) NOT NULL, 
	[CusTrnnbr] numeric(11,0) NULL, 
	[CusInsnbr] numeric(5,0) NULL, 
	[CusColagt] varchar(10) NULL, 
	[CusAgnsvr] varchar(10) NULL, 
	[CusSlspsn] numeric(5,0) NULL, 
	[CusTertry] char(6) NOT NULL, 
	[CusCrdanl] varchar(10) NOT NULL, 
	[CusColstr] char(6) NOT NULL, 
	[CusReasn] char(6) NOT NULL, 
	[CusRcadte] numeric(8,0) NOT NULL, 
	[CusInvtyp] char(6) NOT NULL, 
	[CusTcadte] numeric(8,0) NOT NULL, 
	[CusActopn] numeric(5,0) NOT NULL, 
	[CusRelage] numeric(5,0) NOT NULL, 
	[CusCurrid] char(6) NOT NULL, 
	[CusInvamt] numeric(15,2) NOT NULL, 
	[CusOutbal] numeric(15,2) NOT NULL, 
	[CusInvdte] numeric(8,0) NOT NULL, 
	[CusDuedte] numeric(8,0) NOT NULL, 
	[CusLstdte] numeric(8,0) NOT NULL, 
	[CusDedanl] varchar(10) NOT NULL, 
	[CusInvamtc] numeric(15,6) NOT NULL, 
	[CusOutbalc] numeric(15,6) NOT NULL, 
	[CusExprct] numeric(8,0) NOT NULL, 
	[CusExpage] numeric(5,0) NOT NULL, 
	[CusDedamt] numeric(15,2) NOT NULL, 
	[CusDedamtc] numeric(15,2) NOT NULL, 
	[CusDeddte] numeric(8,0) NOT NULL, 
	[CusDedage] numeric(5,0) NOT NULL, 
	[CusJobnbr] varchar(15) NOT NULL, 
	[CusRmanbr] varchar(40) NOT NULL, 
	[CusPodnbr] varchar(40) NOT NULL, 
	[CusChknbr] varchar(40) NOT NULL, 
	[CusRefno1] varchar(40) NOT NULL, 
	[CusRefno2] varchar(40) NOT NULL, 
	[CusCollty] char(1) NOT NULL, 
	[CusUser] varchar(10) NOT NULL, 
	[CusUdte] numeric(8,0) NOT NULL, 
	[CusTime] numeric(6,0) NOT NULL, 
	[CusJobn] varchar(10) NOT NULL
);