CREATE TABLE [Wholesale_Invoicing_AFI].[TSCAIN] (

	[CAHInvoiceNumber] numeric(9,0) NULL, 
	[CAHOrderNumber] char(7) NULL, 
	[CAHSalesOrderNumber] varchar(30) NULL, 
	[CAHSequence] numeric(2,0) NULL, 
	[CAHConsumerLastName] varchar(40) NULL, 
	[CAHConsumerFirstName] varchar(40) NULL, 
	[CAHConsumerAddress1] varchar(45) NULL, 
	[CAHConsumerAddress2] varchar(45) NULL, 
	[CAHConsumerAddress3] varchar(45) NULL, 
	[CAHConsumerAddress4] varchar(45) NULL, 
	[CAHConsumerAddress5] varchar(45) NULL, 
	[CAHCity] varchar(35) NULL, 
	[CAHState] char(2) NULL, 
	[CAHZipcode] varchar(10) NULL, 
	[CAHCountry] varchar(10) NULL, 
	[CAHHomePhone] varchar(20) NULL, 
	[CAHCellPhone] varchar(20) NULL, 
	[CAHWorkPhone] varchar(20) NULL, 
	[CAHConsumerNumber] varchar(10) NULL, 
	[CAHGeocodeLatitude] numeric(9,0) NULL, 
	[CAHGeocodeLongitude] numeric(9,0) NULL, 
	[CAHEmailAddress] varchar(80) NULL, 
	[CAHDeliveryMethod] char(3) NULL, 
	[CAHUSRC] varchar(10) NULL, 
	[CAHDTEC] datetime2(6) NULL
);