CREATE TABLE [Wholesale_Invoicing_AFI].[TSININ] (

	[ININVR] numeric(9,0) NULL, 
	[INORNO] char(7) NULL, 
	[INIVDT] numeric(8,0) NULL, 
	[INIVAM] numeric(13,2) NULL, 
	[INIDAM] numeric(13,2) NULL, 
	[ININSL] numeric(13,2) NULL, 
	[ININCS] numeric(19,9) NULL, 
	[INTXA1] numeric(13,2) NULL, 
	[INPSCD] char(1) NULL, 
	[INPSMN] numeric(2,0) NULL, 
	[INRIDT] numeric(8,0) NULL, 
	[INCONO] numeric(2,0) NULL, 
	[INCSNO] numeric(8,0) NULL, 
	[INCCLS] char(5) NULL, 
	[INPONO] varchar(22) NULL, 
	[INTMPC] numeric(5,3) NULL, 
	[INTMDS] varchar(20) NULL, 
	[INORDT] numeric(8,0) NULL, 
	[INRQDT] numeric(8,0) NULL, 
	[INSLNO] numeric(5,0) NULL, 
	[INCNNO] numeric(5,0) NULL, 
	[INSHIN] varchar(30) NULL, 
	[INCRCD] char(1) NULL, 
	[INWHSE] char(3) NULL, 
	[INORVL] numeric(13,2) NULL, 
	[INDFCD] numeric(1,0) NULL, 
	[INRODT] numeric(8,0) NULL
);