CREATE VIEW [Transportation_Wrk].[v_TripsNotLoaded]
  AS SELECT  [NTRIP]
      ,[NDROP]
      ,[ORDNO]
      ,[NISEQ]
      ,[NCUSNO]
      ,[NCSREP]
      ,[NSHPTO]
      ,[NCALL]
      ,[NITEM]
      ,[NQTYUN]
      ,[NCODE]
      ,[NTIME]
      ,CASE WHEN CAST([NDATE] as INT)= 0 THEN NULL ELSE CAST(CAST(CAST([NDATE] as INT) AS CHAR(8)) AS DATE) END AS  [NDATE]
      ,[NUSER]
      ,[NPRGM]
      ,[NTYPE1]
      ,[NTYPE2]
      ,[NTYPE3]
      ,[NTYPE4]
      ,[NCUSNM]
  FROM [$(Databricks)].[wholesale_codis].[btrsncde]

