CREATE VIEW [Transportation_Wrk].[v_TripTotalScans]
  AS SELECT [BSRSTS]
      ,[BSTRP#]
      ,[BSDRP#]
      ,[BSORD#]
      ,[BSISEQ]
      ,[BSITM#]
      ,[BSREF#]
      ,[BSITQT]
      ,[BSITQN]
  FROM [$(Databricks)].[wholesale_codis].[btitscn]
