CREATE TABLE [Wholesale_PartyContacts].[ProfileDetail] (

	[cpdCompanyNo] int NULL, 
	[cpdPartnerNo] char(8) NULL, 
	[cpdPartnerShipTo] char(4) NULL, 
	[cpdTransactionCode] char(3) NULL, 
	[cpdTransactionDirection] char(1) NULL, 
	[cpdAllShipTos] bit NULL, 
	[cpdTransactionType] char(1) NULL, 
	[cpdTransactionStyle] char(1) NULL, 
	[cpdEDITradingPartner] char(8) NULL, 
	[cpdEDIVersion] varchar(12) NULL, 
	[cpdEDISend997] char(1) NULL, 
	[cpdEDITransactionProgram] varchar(10) NULL, 
	[cpdTransactionFormatID] char(4) NULL, 
	[cpdUseDeliveryTable] bit NULL, 
	[cpdDeliveryTypeID] char(4) NULL, 
	[cpdSourceAddress] varchar(100) NULL, 
	[cpdSendFunctionalAck] char(1) NULL, 
	[cpdPartnerTypeID] char(3) NULL, 
	[cpdLanguageCode] char(3) NULL, 
	[cpdXRefType] varchar(50) NULL, 
	[cpdDestinationAddress] varchar(100) NULL, 
	[cpdEffectiveFrom] datetime2(6) NULL, 
	[cpdEffectiveTo] datetime2(6) NULL, 
	[acrec] char(1) NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[cpdAuthorizedBy] varchar(25) NULL, 
	[cpdChangedBy] varchar(25) NULL, 
	[cpdChangedDate] datetime2(6) NULL, 
	[cpdPartyID] int NULL, 
	[cpdLocationID] int NULL, 
	[cpdLastUserChanged] varchar(35) NULL
);