Create view GeographicData_Wrk.v_CountyMaster 
as
SELECT [ctnCntycd]
      ,[ctnTerrcd]
      ,[ctnState]
      ,[ctnCounty]
      ,[ctnCensus]
      ,[ctnRzone]
      ,[ctnMsa_fips]
      ,[ctnCountry]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[ctnResponsibleRegion]
      ,[ctnCountyFips]
      ,[ctnDMAName]
      ,[ctnCBSAName]
      ,[ctnCBSACode]
      ,[ctnCBSAType]
  FROM [$(Source_Data)].MasterData_GeographicData.CountyMaster