Create view GeographicData_Wrk.v_ZipCode
as
SELECT [zipZzipcd]
      ,[zipZstate]
      ,[zipZctynm]
      ,[zipZctyab]
      ,[zipZconyn]
      ,[zipZcountry]
      ,[zipMSA]
      ,[zipTimeZoneCode]
      ,[zipDayLightSavings]
      ,[zipLat]
      ,[zipLong]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[acrec]
      ,[zipPreferred]
  FROM [$(Source_Data)].MasterData_GeographicData.[ZipCode]