CREATE TABLE [Retail_OOM_Wrk].[PieceInventory] (

	[Addon1Cost] decimal(18,2) NOT NULL, 
	[Addon2Cost] decimal(18,2) NOT NULL, 
	[Addon3Cost] decimal(18,2) NOT NULL, 
	[Addon4Cost] decimal(18,2) NOT NULL, 
	[BrandID] varchar(50) NOT NULL, 
	[CategoryID] varchar(50) NOT NULL, 
	[CollectionID] varchar(50) NULL, 
	[COMCost] decimal(18,2) NOT NULL, 
	[Comments] varchar(300) NULL, 
	[CompanyID] varchar(50) NOT NULL, 
	[DateAsIs] datetime2(3) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateIn] datetime2(3) NOT NULL, 
	[FrameInfo] varchar(300) NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[InvStatus] varchar(5) NULL, 
	[LandedFreight] decimal(18,2) NOT NULL, 
	[MaterialCost] decimal(18,2) NOT NULL, 
	[MaximumPrice] decimal(18,2) NULL, 
	[PieceStatusID] int NULL, 
	[POLineID] int NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[ProductTypeID] varchar(4) NOT NULL, 
	[PurchaseOrderID] varchar(50) NULL, 
	[QtyCommitted] decimal(18,2) NOT NULL, 
	[QtyNonSale] decimal(18,2) NOT NULL, 
	[QtyNSCommitted] decimal(18,2) NULL, 
	[QtyNSReserved] decimal(18,2) NULL, 
	[QtyOnHand] decimal(18,2) NOT NULL, 
	[QtyReserved] decimal(18,2) NOT NULL, 
	[RcvdStatus] varchar(5) NULL, 
	[RcvdStoreID] varchar(50) NOT NULL, 
	[ReasonCodeID] varchar(50) NULL, 
	[RecStatus] varchar(1) NULL, 
	[Repossessed] bit NULL, 
	[SellingPrice] decimal(18,2) NOT NULL, 
	[SerialNbrID] varchar(50) NOT NULL, 
	[SourceID] varchar(50) NOT NULL, 
	[StorageID] varchar(50) NULL, 
	[StoreID] varchar(50) NOT NULL, 
	[TotalCost] decimal(18,2) NULL, 
	[TransDate] datetime2(3) NOT NULL, 
	[VendorID] varchar(50) NOT NULL, 
	[WhseMgmtTag] varchar(40) NULL, 
	[StoreBrandID] varchar(50) NULL, 
	[InvSubBucketID] char(5) NULL, 
	[TDGInvTypeID] int NULL, 
	[OrderTransCodeID] int NULL, 
	[ItemID] int NULL, 
	[OrderID] varchar(50) NULL, 
	[SoftCommitted] int NULL, 
	[LeadDays] int NULL, 
	[OrderDate] date NULL, 
	[DlvyDate] date NULL, 
	[ABC] varchar(2) NULL, 
	[PoType] char(1) NULL, 
	[DateInStorageID] date NULL, 
	[DateInReasonCodeID] date NULL
);