-- Auto Generated (Do not modify) 7DDC59EA657D9D017367C9E4EF9AADF0311064CD58B3D521FD6992D85921C69A
CREATE VIEW [Quality_Enh_Wrk].[v_InvoiceSerialNumberPurchased]
AS
SELECT  [Invoicedate]
      ,[Invoicenumber]
      ,[Serialnumber]
      ,[Ordernumber]
      ,[Itemnumber]
      ,[Itemseqnumber]
      ,[Ponumber]
      ,[Customernumber]
      ,[Shiptonumber]
      ,[Vendornumber]
      ,[Salesoffice]
      ,[Countryoforigin]
      ,[Dropnumber]
      ,[Scanname]
      ,[Loaddate]
      ,[Trucknumber]
      ,[Carrier]
      ,[Warehouse]
      ,[Aatwarehouse]
  FROM [Wholesale_SalesHistory_AFI_Wrk].[InvoiceSerialNumberPurchased]