CREATE TABLE [Wholesale_Invoicing_AFI_wrk].[TSCMADJ] (

	[Joentl] decimal(10,0) NULL, 
	[Joseqn] decimal(10,0) NULL, 
	[Jocode] char(1) NULL, 
	[Joentt] char(2) NULL, 
	[Jodate] char(6) NULL, 
	[Jotime] decimal(10,0) NULL, 
	[Jojob] char(10) NULL, 
	[Jouser] char(10) NULL, 
	[Jonbr] decimal(10,0) NULL, 
	[Jopgm] char(10) NULL, 
	[Joobj] char(10) NULL, 
	[Jolib] char(10) NULL, 
	[Jombr] char(10) NULL, 
	[Joctrr] decimal(10,0) NULL, 
	[Joflag] char(1) NULL, 
	[Joccid] decimal(10,0) NULL, 
	[Jouspf] char(10) NULL, 
	[Josynm] char(8) NULL, 
	[Joincdat] char(1) NULL, 
	[Jominesd] char(1) NULL, 
	[Jores] char(18) NULL, 
	[Cdhinvoicenumber] decimal(9,0) NULL, 
	[Cdhordernumber] char(7) NULL, 
	[Cdhitemnumber] varchar(17) NULL, 
	[Cdhitemsequence] decimal(7,0) NULL, 
	[Cdhcommissionadjustmentcode] char(3) NULL, 
	[Cdhexceptionamount] decimal(12,2) NULL, 
	[Cdhexceptionid] decimal(7,0) NULL, 
	[Cdhpricecode] char(6) NULL
);