CREATE TABLE [Wholesale_Invoicing_AFI_wrk].[TSCOIN] (

	[Joentl] decimal(10,0) NULL, 
	[Joseqn] decimal(10,0) NULL, 
	[Jocode] char(1) NULL, 
	[Joentt] char(2) NULL, 
	[Jodate] char(6) NULL, 
	[Jotime] decimal(10,0) NULL, 
	[Jojob] char(10) NULL, 
	[Jouser] char(10) NULL, 
	[Jonbr] decimal(10,0) NULL, 
	[Jopgm] char(10) NULL, 
	[Joobj] char(10) NULL, 
	[Jolib] char(10) NULL, 
	[Jombr] char(10) NULL, 
	[Joctrr] decimal(10,0) NULL, 
	[Joflag] char(1) NULL, 
	[Joccid] decimal(10,0) NULL, 
	[Jouspf] char(10) NULL, 
	[Josynm] char(8) NULL, 
	[Joincdat] char(1) NULL, 
	[Jominesd] char(1) NULL, 
	[Jores] char(18) NULL, 
	[Coinvr] decimal(9,0) NULL, 
	[Coorno] char(7) NULL, 
	[Coocsq] decimal(3,0) NULL, 
	[Coocm1] varchar(35) NULL, 
	[Coocm2] varchar(35) NULL, 
	[Coocm3] varchar(35) NULL, 
	[Cointp] decimal(1,0) NULL
);