CREATE TABLE [Wholesale_Invoicing_AFI_wrk].[TSDSCADJ] (

	[Joentl] decimal(10,0) NULL, 
	[Joseqn] decimal(10,0) NULL, 
	[Jocode] char(1) NULL, 
	[Joentt] char(2) NULL, 
	[Jodate] char(6) NULL, 
	[Jotime] decimal(10,0) NULL, 
	[Jojob] char(10) NULL, 
	[Jouser] char(10) NULL, 
	[Jonbr] decimal(10,0) NULL, 
	[Jopgm] char(10) NULL, 
	[Joobj] char(10) NULL, 
	[Jolib] char(10) NULL, 
	[Jombr] char(10) NULL, 
	[Joctrr] decimal(10,0) NULL, 
	[Joflag] char(1) NULL, 
	[Joccid] decimal(10,0) NULL, 
	[Jouspf] char(10) NULL, 
	[Josynm] char(8) NULL, 
	[Joincdat] char(1) NULL, 
	[Jominesd] char(1) NULL, 
	[Jores] char(18) NULL, 
	[Dchinvnbr] decimal(9,0) NULL, 
	[Dchordno] char(7) NULL, 
	[Dchitmseq] decimal(7,0) NULL, 
	[Dchdsctyp] char(1) NULL, 
	[Dchdscadjc] char(3) NULL, 
	[Dchitmnbr] varchar(17) NULL, 
	[Dchamount] decimal(16,6) NULL, 
	[Dchratioa] decimal(7,6) NULL, 
	[Dchdscpct] decimal(5,4) NULL, 
	[Dchexcptid] decimal(7,0) NULL, 
	[Dchdsccde] char(3) NULL, 
	[Dchdscslsc] char(2) NULL
);