CREATE VIEW Customers_Wrk.v_AccountMaster
AS
SELECT 
[cmaCustomerNumber] AS [CustomerNumber],
CAST([cmaPhone] AS [varchar](12)) AS [Phone],
CAST([cmaFaxtn] AS [varchar](12)) AS [Faxtn],
CAST([cmaContact] AS [varchar](25)) AS [Contact],
CAST([cmaEmail] AS [varchar](50)) AS [Email],
[cmaPrimaryTerritory] AS [PrimaryTerritory],
[cmaMinimumFreightCode] AS [MinimumFreightCode],
CAST([cmaCreditLimitAmount] AS [int]) AS [CreditLimitAmount],
[cmaTermsCode] AS [TermsCode],
CAST([cmaTermsDays] AS [smallint]) AS [TermsDays],
CAST([cmaCreditTerritoryID] AS [int]) AS [CreditTerritoryID],
CAST([cmaCancelBackOrders] AS [int]) AS [CancelBackOrders],
CAST([cmaAllowPartialShipment] AS [int]) AS [AllowPartialShipment],
[cmaCustomerClassCode] AS [CustomerClassCode],
[cmaLanguageCode] AS [LanguageCode],
CAST([cmaStatementCode] AS [int]) AS [StatementCode],
[cmaItemCrossReferenceCode] AS [ItemCrossReferenceCode],
CAST([cmaTerritoryChangeDate] AS [datetime2](6)) AS [TerritoryChangeDate],
[cmaCreditAuthorizationCode] AS [CreditAuthorizationCode],
CAST([cmaMemo] AS [varchar](8000)) AS [Memo],
CAST([cmaChgCustAr] AS [bit]) AS [ChgCustAr],
CAST([cmaChgCust] AS [bit]) AS [ChgCust],
CAST([cmaChgCustExt] AS [bit]) AS [ChgCustExt],
CAST([cmaPercentAvailableCredit] AS [decimal](3,2)) AS [PercentAvailableCredit],
CAST([cmaCommAudit] AS [bit]) AS [CommAudit],
CAST([cmaInheritBlocking] AS [bit]) AS [InheritBlocking],
CAST([cmaCustomerName] AS [varchar](25)) AS [CustomerName],
CAST([usra] AS [varchar](30)) AS [AddedByUser],
CAST([dtea] AS [datetime2](6)) AS [DateAdded],
CAST([usrc] AS [varchar](30)) AS [ChangeByUser],
CAST([dtec] AS [datetime2](6)) AS [DateChange],
[acrec] AS [ActiveRecord],
CAST([cmaLastStatusChangeDate] AS [datetime2](6)) AS [LastStatusChangeDate],
CAST([cmaBillingAddressID] AS [int]) AS [BillingAddressID],
CAST([cmaDBAName] AS [varchar](25)) AS [DBAName],
CAST([cmaLateChargePercent] AS [decimal](5,4)) AS [LateChargePercent],
CAST([cmaMinPreapprovalAmount] AS [decimal](12,2)) AS [MinPreapprovalAmount],
[cmaCreditAddessCode] AS [CreditAddessCode],
CAST([cmaRFCTaxIdNumber] AS [varchar](20)) AS [RFCTaxIdNumber],
[cmaDocumentationHold] AS [DocumentationHold],
[cmaPARSByPurchaser] AS [PARSByPurchaser],
[cma10DigitScheduleB] AS [10DigitScheduleB],
CAST([cmaTypeOfInsurance] AS [varchar](10)) AS [TypeOfInsurance],
CAST([cmaInsExpirationDate] AS [datetime2](6)) AS [InsExpirationDate],
CAST([cmaInsCoverageRequested] AS [decimal](10,2)) AS [InsCoverageRequested],
CAST([cmaInsCoverageApproved] AS [decimal](10,2)) AS [InsCoverageApproved],
CAST([cmaInsuranceStatus] AS [varchar](10)) AS [InsuranceStatus],
[cmaHomestoreFacingWhse] AS [HomestoreFacingWhse],
CAST([cmaAppcd] AS [int]) AS [Appcd],
CAST([cmaDeductTerritoryID] AS [decimal](2,0)) AS [DeductTerritoryId],
[cmaCurrencyCode] AS [CurrencyCode],
CAST([cmaAllowAllowanceCredits] AS [bit]) AS [AllowAllowanceCredits]
FROM [$(Source_Data)].[Wholesale_Customers].AccountMaster
GO

