CREATE TABLE [Retail_External].[stocklocationproducts] (

	[operation] varchar(10) NULL, 
	[StockLocationProductID] int NULL, 
	[ProductID] varchar(30) NULL, 
	[ShipFromSourceID] int NULL, 
	[DefaultShipFrom] bit NULL, 
	[ShipToLocationID] varchar(30) NULL, 
	[SrcFromLocationID] varchar(30) NULL, 
	[NetworkLevel] smallint NULL, 
	[MakeBuyCodeID] varchar(10) NULL, 
	[ProductionDays] smallint NULL, 
	[InTransitDays] smallint NULL, 
	[ExcludeInTransitDays] bit NULL, 
	[TotalLeadTime] smallint NULL, 
	[VendorShipFromKeepStock] bit NULL, 
	[LocationKeepStock] bit NULL, 
	[AvailableInVendorShipFrom] bit NULL, 
	[ABC] varchar(1) NULL, 
	[VendorMinimumUOMID] smallint NULL, 
	[VendorMinimumValue] decimal(13,2) NULL, 
	[VendorMinimumOverridden] bit NULL, 
	[UpdatedBy] varchar(4) NULL, 
	[DateUpdated] datetime2(6) NULL, 
	[StockLocationID] int NULL, 
	[NewItemIndicator] varchar(10) NULL, 
	[ExpectedInStockDate] datetime2(6) NULL, 
	[CalcTotalLeadTime] int NULL, 
	[ProductionDaysOverride] bit NULL, 
	[Shared] int NULL, 
	[LastATPUpdateDate] datetime2(6) NULL, 
	[RealTimePO] bit NULL, 
	[CurrentQty] int NULL, 
	[ATPUpdateFlag] bit NULL
);