CREATE TABLE [Marketing].[MoSeriesMargins]
    (
        [Series]   VARCHAR(15)    NULL,
        [Dollars]  DECIMAL(12, 2) NULL,
        [Orders]   DECIMAL(12, 2) NULL,
        [FOB]      DECIMAL(8, 2)  NULL,
        [CUR]      DECIMAL(8, 2)  NULL,
        [ACT]      DECIMAL(8, 2)  NULL,
        [FOB_3]    DECIMAL(8, 2)  NULL,
        [CUR_3]    DECIMAL(8, 2)  NULL,
        [ACT_3]    DECIMAL(8, 2)  NULL,
        [FOB_6]    DECIMAL(8, 2)  NULL,
        [CUR_6]    DECIMAL(8, 2)  NULL,
        [ACT_6]    DECIMAL(8, 2)  NULL,
        [FOB_12]   DECIMAL(8, 2)  NULL,
        [CUR_12]   DECIMAL(8, 2)  NULL,
        [ACT_12]   DECIMAL(8, 2)  NULL,
        [GMROI_1]  DECIMAL(8, 1)  NULL,
        [GMROI_2]  DECIMAL(8, 1)  NULL,
        [GMROI_3]  DECIMAL(8, 1)  NULL,
        [GMROI_4]  DECIMAL(8, 1)  NULL,
        [GMROI_5]  DECIMAL(8, 1)  NULL,
        [GMROI_6]  DECIMAL(8, 1)  NULL,
        [GMROI_7]  DECIMAL(8, 1)  NULL,
        [GMROI_8]  DECIMAL(8, 1)  NULL,
        [GMROI_9]  DECIMAL(8, 1)  NULL,
        [GMROI_10] DECIMAL(8, 1)  NULL,
        [GMROI_11] DECIMAL(8, 1)  NULL,
        [GMROI_12] DECIMAL(8, 1)  NULL,
        [Month]    INT        NULL
    );

-- DATA_SOURCE = [AzureStorageGen2a],
-- LOCATION =   N'/Wholesale/Marketing/MoSeriesMargins/AFI_Sales_tblMoSeriesMargins.snappy.parquet',
-- FILE_FORMAT = [ParquetFileFormatSnappy],
