CREATE TABLE [Marketing].[MrktSpclstInfo](
	[ID] [decimal](18, 0) NULL,
	[Title] [char](5) NULL,
	[LastName] [varchar](25) NULL,
	[FirstName] [varchar](25) NULL,
	[Spouse] [varchar](25) NULL,
	[CompanyName] [varchar](35) NULL,
	[Address1] [varchar](43) NULL,
	[Address2] [varchar](38) NULL,
	[City] [varchar](35) NULL,
	[State] [varchar](15) NULL,
	[Province] [varchar](39) NULL,
	[Country] [varchar](24) NULL,
	[Zip] [varchar](10) NULL,
	[HomePhone] [varchar](25) NULL,
	[HomeFax] [varchar](25) NULL,
	[OfficePhone] [varchar](25) NULL,
	[OfficeFax] [varchar](25) NULL,
	[Cellular] [varchar](25) NULL,
	[NightPhone] [varchar](25) NULL,
	[CarPhone] [varchar](25) NULL,
	[WarehousePhone] [varchar](25) NULL,
	[Pager] [varchar](29) NULL,
	[SocialSecurityNo] [varchar](25) NULL,
	[FedTaxNo] [varchar](25) NULL,
	[Birthday] [char](8) NULL,
	[DateHire] [char](8) NULL,
	[EndDate] [varchar](8) NULL,
	[SalesNo] [char](5) NULL,
	[RepID] [char](5) NULL,
	[MainRep] [varchar](30) NULL,
	[VPMillennium] [varchar](35) NULL,
	[VPSoftgoods] [varchar](50) NULL,
	[VPCasegoods] [varchar](35) NULL,
	[Division] [varchar](30) NULL,
	[Casegoods] [bit] NULL,
	[Softgoods] [bit] NULL,
	[Millennium] [bit] NULL,
	[Position] [varchar](30) NULL,
	[Region] [varchar](50) NULL,
	[Territory] [varchar](75) NULL,
	[PrintCode] [char](1) NULL,
	[SecretaryName] [varchar](50) NULL,
	[SecretaryPhone] [varchar](15) NULL,
	[ActiveRecord] [char](1) NULL,
	[AddedByUser] [varchar](30) NULL,
	[DateAdded] [datetime2](6) NULL,
	[ChangeByUser] [varchar](30) NULL,
	[DateChange] [datetime2](6) NULL,
	[SDCasegoods] [bit] NULL,
	[SDSoftgoods] [bit] NULL,
	[SDMillennium] [bit] NULL,
	[Email] [varchar](50) NULL,
	[MarketPagerID] [int] NULL,
	[Motion] [bit] NULL,
	[MotionSignature] [bit] NULL,
	[VPMotion] [varchar](50) NULL,
	[RepPosition] [varchar](20) NULL
);

-- DATA_SOURCE = [AzureStorageGen2a],
-- LOCATION =   N'/Wholesale/Marketing/MrktSpclstInfo/GBL_Sales_tblMrktSpclstInfo.snappy.parquet',
-- FILE_FORMAT = [ParquetFileFormatSnappy],
