CREATE TABLE [wholesale_pricing_afi].[BuyGroupPrice] (

	[bgpBgcode] char(3) NULL, 
	[bgpWhse] char(3) NULL, 
	[bgpItnbr] varchar(15) NULL, 
	[bgpPrice] numeric(8,2) NULL, 
	[bgpFrchrg] char(1) NULL, 
	[bgpDate1] datetime2(6) NULL, 
	[bgpDate2] datetime2(6) NULL, 
	[bgpGssdat] datetime2(6) NULL, 
	[bgpGesdat] datetime2(6) NULL, 
	[bgpGcmsn] numeric(8,3) NULL, 
	[bgpGcmpct] numeric(6,4) NULL, 
	[bgpDisc1] numeric(6,4) NULL, 
	[bgpDisc2] numeric(6,4) NULL, 
	[bgpDisc3] numeric(6,4) NULL, 
	[bgpDisc4] numeric(6,4) NULL, 
	[bgpDisc5] numeric(6,4) NULL, 
	[bgpDisc6] numeric(6,4) NULL, 
	[bgpDisc7] numeric(6,4) NULL, 
	[bgpGexcid] int NULL, 
	[bgpGbpred] char(1) NULL, 
	[commaudit] bit NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[acrec] char(1) NULL
);