CREATE TABLE [wholesale_pricing_afi].[PriceExceptions] (

	[pexItnbr] varchar(15) NOT NULL, 
	[pexCusno] varchar(8) NOT NULL, 
	[pexShpno] varchar(4) NOT NULL, 
	[pexWhse] varchar(3) NOT NULL, 
	[pexDisc1] decimal(5,4) NOT NULL, 
	[pexDisc2] decimal(5,4) NOT NULL, 
	[pexDisc3] decimal(5,4) NOT NULL, 
	[pexDisc4] decimal(5,4) NOT NULL, 
	[pexDisc5] decimal(5,4) NOT NULL, 
	[pexDisc6] decimal(5,4) NOT NULL, 
	[pexDisc7] decimal(5,4) NOT NULL, 
	[pexPrice] decimal(8,2) NOT NULL, 
	[pexDate1] datetime2(6) NOT NULL, 
	[pexDate2] datetime2(6) NULL, 
	[pexEfrtyn] varchar(1) NOT NULL, 
	[pexEssdat] datetime2(6) NULL, 
	[pexEesdat] datetime2(6) NULL, 
	[pexEocmmp] decimal(6,4) NOT NULL, 
	[pexEbpred] varchar(1) NOT NULL, 
	[pexEexcid] int NOT NULL, 
	[pexEcmadj] decimal(8,3) NOT NULL, 
	[pexEordno] varchar(7) NOT NULL, 
	[pexEitseq] numeric(7,0) NOT NULL, 
	[pexEbtrep] numeric(5,0) NOT NULL, 
	[pexEstrep] numeric(5,0) NOT NULL, 
	[pexEstcom] decimal(7,4) NOT NULL, 
	[commaudit] bit NOT NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[acrec] varchar(1) NULL
);