CREATE TABLE [Retail_Dart].[CartHeader] (

	[ID] varchar(200) NOT NULL, 
	[RelationshipID] varchar(200) NULL, 
	[CartNumber] varchar(100) NOT NULL, 
	[LocationID] varchar(100) NULL, 
	[CartCustomerID] varchar(200) NULL, 
	[Email] varchar(200) NULL, 
	[FirstName] varchar(200) NULL, 
	[MiddleName] varchar(200) NULL, 
	[LastName] varchar(200) NULL, 
	[CellPhone] varchar(100) NULL, 
	[HomePhone] varchar(100) NULL, 
	[WorkPhone] varchar(100) NULL, 
	[WorkPhoneExtension] varchar(100) NULL, 
	[Address1] varchar(100) NULL, 
	[Address2] varchar(100) NULL, 
	[City] varchar(100) NULL, 
	[StateOrProvince] varchar(100) NULL, 
	[ZipCode] varchar(100) NULL, 
	[SalespeopleID] varchar(100) NULL, 
	[ShippingAddress1] varchar(500) NULL, 
	[ShippingAddress2] varchar(100) NULL, 
	[ShippingCity] varchar(100) NULL, 
	[ShippingStateOrProvince] varchar(100) NULL, 
	[ShippingZipCode] varchar(100) NULL, 
	[Fees] decimal(18,2) NULL, 
	[Install] decimal(18,2) NULL, 
	[Tax] decimal(18,2) NULL, 
	[Delivery] decimal(18,2) NULL, 
	[Payments] decimal(18,2) NULL, 
	[protectionPlan] decimal(18,2) NULL, 
	[DateUpdatedUTC] datetime2(6) NULL, 
	[IsDeleted] bit NULL, 
	[DateUpdated] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[DateWrittenToDB] datetime2(6) NULL, 
	[DateCreatedUTC] datetime2(6) NULL
);