CREATE TABLE [Retail_Dart].[DMInventoryDailyOpenHistory_DayLvlAgg] (

	[TransDate] date NULL, 
	[ProductKey] bigint NOT NULL, 
	[SerialNbrID] varchar(50) NULL, 
	[LocationID] varchar(50) NOT NULL, 
	[StoreBrandID] varchar(50) NULL, 
	[StorageID] varchar(50) NULL, 
	[MaterialCost] decimal(19,4) NULL, 
	[LandedFreight] decimal(19,4) NULL, 
	[Addon1Cost] decimal(19,4) NULL, 
	[Addon2Cost] decimal(19,4) NULL, 
	[Addon3Cost] decimal(19,4) NULL, 
	[Addon4Cost] decimal(19,4) NULL, 
	[TotalCost] decimal(19,4) NULL, 
	[Qty] numeric(18,2) NOT NULL, 
	[QtyCommitted] numeric(18,2) NOT NULL, 
	[QtySoftCommitted] numeric(18,2) NOT NULL, 
	[DateAsIs] date NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[InvSubBucketID] varchar(50) NULL, 
	[PieceStatusID] int NULL, 
	[TransDateKey] int NOT NULL, 
	[InvBucketID] varchar(20) NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[DateInStorageID] date NULL, 
	[DateInReasonCodeID] date NULL
);