CREATE TABLE [Retail_Dart].[HREmployeeHistory] (

	[EmployeeID] int NOT NULL, 
	[EmployeeNumber] varchar(50) NULL, 
	[SupID] varchar(50) NULL, 
	[FirstName] varchar(50) NULL, 
	[LastName] varchar(50) NULL, 
	[EmpStatus] char(5) NULL, 
	[Email] varchar(50) NULL, 
	[EmpHourlySalary] char(5) NULL, 
	[EmpFTPT] char(5) NULL, 
	[EmpAddressCity] varchar(50) NULL, 
	[EmpAddressState] char(5) NULL, 
	[EmpAddressZip] varchar(10) NULL, 
	[BirthDate] date NULL, 
	[HireDate] date NULL, 
	[LocationID] varchar(50) NULL, 
	[JobID] int NULL, 
	[DivisionID] int NULL, 
	[DepartmentID] int NULL, 
	[RegionID] int NULL, 
	[EmployeeTypeID] int NULL, 
	[SepCode] varchar(50) NULL, 
	[SepType] char(5) NULL, 
	[SepReason] varchar(50) NULL, 
	[SepDate] date NULL, 
	[TransDate] date NULL
);