CREATE TABLE [Retail_Dart].[PeopleTimeSheet] (

	[TimeSheetID] bigint NOT NULL, 
	[SourceDataID] varchar(50) NOT NULL, 
	[SourceSystemID] int NOT NULL, 
	[PeopleID] bigint NULL, 
	[EmployeeNumber] varchar(100) NULL, 
	[PayPeriod] int NULL, 
	[TransDateKey] int NULL, 
	[SourceLocationID] varchar(50) NULL, 
	[LocationKey] int NULL, 
	[TimeIn] datetime2(6) NULL, 
	[TimeOut] datetime2(6) NULL, 
	[Time] float NULL, 
	[SourcePayCodeID] varchar(10) NULL, 
	[PayCodeID] int NULL, 
	[PayCodeName] varchar(50) NULL, 
	[SourceTaskCodeID] varchar(10) NULL, 
	[TaskCodeID] varchar(10) NULL, 
	[TaskCodeName] varchar(100) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Rate] decimal(19,9) NULL, 
	[ExtCost] decimal(19,9) NULL, 
	[ApprovedByManager] bit NULL
);