CREATE TABLE [Retail_Corporate].[InvactivityRaw] (

	[Operation] varchar(15) NULL, 
	[AdjQty] int NULL, 
	[BrandID] varchar(50) NULL, 
	[CategoryID] varchar(50) NULL, 
	[CollectionID] varchar(50) NULL, 
	[Comment] varchar(2000) NULL, 
	[CompanyID] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[FisPeriod] int NULL, 
	[FisQtr] int NULL, 
	[FisWeek] int NULL, 
	[FisYear] int NULL, 
	[GroupID] varchar(50) NULL, 
	[InStorageID] varchar(50) NULL, 
	[InvTransTypeID] int NULL, 
	[KitStatus] varchar(10) NULL, 
	[NewSellingPrice] numeric(19,4) NULL, 
	[OrderID] varchar(50) NULL, 
	[OutStorageID] varchar(50) NULL, 
	[PreviousSellingPrice] numeric(19,4) NULL, 
	[ProductID] varchar(50) NULL, 
	[ReasonCodeID] varchar(50) NULL, 
	[RecStatus] char(1) NULL, 
	[Reference] varchar(50) NULL, 
	[SerialNbrID] varchar(50) NULL, 
	[SourceID] varchar(50) NULL, 
	[StaffID] varchar(50) NULL, 
	[StoreID] varchar(50) NULL, 
	[TransDate] datetime2(6) NULL, 
	[TransDateTime] datetime2(6) NULL, 
	[UniqueID] varchar(75) NULL, 
	[UniqueID_Int] int NULL, 
	[VendorID] varchar(50) NULL
);