CREATE TABLE [Retail_Corporate].[OOMSchedulePerformanceDetails] (

	[Operation] varchar(15) NULL, 
	[BookedStoreID] varchar(50) NOT NULL, 
	[DCStoreID] varchar(50) NOT NULL, 
	[TransDate] date NOT NULL, 
	[WrittenSales] numeric(13,2) NULL, 
	[TotalScheduleStore] numeric(13,2) NULL, 
	[TotalScheduleStoreOrderCount] int NULL, 
	[TotalScheduleGRT] numeric(13,2) NULL, 
	[TotalScheduleGRTOrderCount] int NULL, 
	[TotalScheduleDTR] numeric(13,2) NULL, 
	[TotalScheduleDTROrderCount] int NULL, 
	[TotalScheduleAudit] numeric(13,2) NULL, 
	[TotalScheduleAuditOrderCount] int NULL, 
	[TotalScheduleUnassigned] numeric(13,2) NULL, 
	[TotalScheduleUnassignedOrderCount] int NULL, 
	[TotalScheduleIVR] numeric(13,2) NULL, 
	[TotalScheduleIVROrderCount] int NULL, 
	[TotalScheduleSMS] numeric(13,2) NULL, 
	[TotalScheduleSMSOrderCount] int NULL, 
	[TotalScheduleChatBot] numeric(13,2) NULL, 
	[TotalScheduleChatBotOrderCount] int NULL, 
	[AttackTarget] numeric(13,2) NULL, 
	[FilledCleanDelivery] numeric(13,2) NULL, 
	[ScheduleAtPOS] numeric(13,2) NULL, 
	[ScheduleAtPOSOrderCount] int NULL, 
	[DaysToSchedule] numeric(13,2) NULL, 
	[SMSMessagesSentCount] int NULL, 
	[AutoScheduleOrderCount] int NULL
);