CREATE TABLE [Retail_Corporate].[Payments] (

	[Operation] varchar(15) NULL, 
	[APBankDepositTypeID] varchar(100) NULL, 
	[BankID] varchar(50) NULL, 
	[CashRegisterID] varchar(50) NULL, 
	[CheckNbr] varchar(50) NULL, 
	[CompanyID] varchar(50) NULL, 
	[CustomerID] varchar(50) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[GiftCertificateID] varchar(50) NULL, 
	[GLSourceID] varchar(50) NULL, 
	[InvoiceID] varchar(50) NULL, 
	[LastBatchID] int NULL, 
	[ManagerOverride_StaffID] varchar(50) NULL, 
	[ManagerOverrideDate] date NULL, 
	[OrderID] varchar(50) NULL, 
	[PaymentAmt] numeric(19,4) NULL, 
	[PaymentClass] int NULL, 
	[PaymentDate] date NULL, 
	[PaymentNbr] varchar(100) NULL, 
	[PaymentTypeID] varchar(50) NULL, 
	[RecStatus] char(1) NULL, 
	[Reference] varchar(100) NULL, 
	[SequenceID] int NULL, 
	[SourceID] varchar(50) NULL, 
	[StaffID] varchar(50) NULL, 
	[StoreID] varchar(50) NULL, 
	[TransactionSource] varchar(50) NULL, 
	[TransCodeID] int NULL, 
	[TransDate] date NULL, 
	[TransDateTime] datetime2(6) NULL
);