CREATE TABLE [Retail_Corporate].[ProtectionPlan_Clone] (

	[Operation] varchar(15) NULL, 
	[CancellationDays] int NULL, 
	[CommissionPercent] numeric(18,2) NULL, 
	[Cost_GLAccountID] varchar(100) NULL, 
	[CostingMethod] varchar(10) NULL, 
	[DateChanged] datetime2(6) NULL, 
	[DateCreated] datetime2(6) NULL, 
	[Description] varchar(255) NULL, 
	[IsInActive] bit NULL, 
	[IsOnlyForMembershipCustomers] bit NULL, 
	[LastBatchID] int NULL, 
	[ManagerOnly] bit NULL, 
	[PlanID] varchar(50) NULL, 
	[PricingMethod] varchar(10) NULL, 
	[ProtectionPlanID] varchar(100) NULL, 
	[RecStatus] char(1) NULL, 
	[Sales_GLAccountID] varchar(100) NULL, 
	[SourceID] varchar(50) NULL, 
	[TaxableFlag] bit NULL, 
	[ThirdPartyCode] varchar(50) NULL, 
	[UseDefaultSellingPrice] bit NULL, 
	[WarrantyID] varchar(50) NULL
);