CREATE TABLE [Retail_OOM_Enh].[OrderTransDetail] (

	[OrderTransDetailID] bigint NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[ItemID] int NOT NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[WrittenDate] datetime2(3) NULL, 
	[VendorModelNumber] varchar(50) NULL, 
	[KitGroupNumber] varchar(20) NULL, 
	[TransCodeID] int NULL, 
	[Quantity] int NULL, 
	[UnitListPrice] decimal(19,4) NULL, 
	[UnitSellPrice] decimal(19,4) NULL, 
	[UnitCost] decimal(19,4) NULL, 
	[OtherDiscount] decimal(19,4) NULL, 
	[ProductDiscountCode] varchar(50) NULL, 
	[SpecialOrderFlag] bit NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[DeliveryDate] date NULL, 
	[DeliveryStatus] varchar(10) NULL, 
	[DeliveryStatusAtPOS] varchar(10) NULL, 
	[DeliveryType] varchar(4) NULL, 
	[DeliveryStoreID] varchar(50) NULL, 
	[StockLocationID] varchar(50) NULL, 
	[ReasonCodeID] varchar(50) NULL, 
	[PriceOverrideStaffID] varchar(50) NULL, 
	[NumDeliveryDateChanged] int NULL
);