CREATE TABLE [Retail_Commissions].[BRIDGESalesOrderLine_Incr] (

	[SourceDataID] varchar(50) NOT NULL, 
	[OrderID] varchar(50) NOT NULL, 
	[ItemID] int NULL, 
	[TransDateKey] int NOT NULL, 
	[TransDate] date NULL, 
	[OrderDate] date NULL, 
	[TransCodeID] int NOT NULL, 
	[ProductID] varchar(50) NOT NULL, 
	[ProductName] varchar(100) NULL, 
	[VendorID] varchar(20) NOT NULL, 
	[SubGroupID] varchar(20) NULL, 
	[SalesPersonID] varchar(30) NOT NULL, 
	[CustomerID] varchar(50) NOT NULL, 
	[Address1] varchar(300) NULL, 
	[Address2] varchar(300) NULL, 
	[CustomerName] varchar(150) NULL, 
	[SalesPersonName] varchar(255) NULL, 
	[HomeStore] varchar(30) NULL, 
	[CategoryID] varchar(40) NOT NULL, 
	[GroupID] varchar(50) NOT NULL, 
	[StoreID] int NOT NULL, 
	[StoreName] varchar(255) NULL, 
	[OwnerGroup] varchar(50) NULL, 
	[AsIsReasonCodeID] varchar(50) NULL, 
	[WrittenSales] numeric(19,2) NOT NULL, 
	[WrittenCost] numeric(19,2) NOT NULL, 
	[WrittenUnits] numeric(19,2) NOT NULL, 
	[WrittenTaxes] int NOT NULL, 
	[WrittenCharges] numeric(19,2) NOT NULL, 
	[WrittenRebates] int NOT NULL, 
	[DeliveredSales] numeric(19,2) NOT NULL, 
	[DeliveredCost] numeric(19,2) NOT NULL, 
	[DeliveredUnits] numeric(19,2) NOT NULL, 
	[DeliveryStatus] varchar(20) NULL, 
	[ProdDiscntCode] varchar(50) NULL, 
	[PriceVarianceExceptionReasonCodeID] varchar(50) NULL, 
	[CustomerLastName] varchar(100) NULL, 
	[SalesDataTypeKey] int NOT NULL, 
	[InvSubBucketID] varchar(50) NULL, 
	[PurchaseStatusID] varchar(8000) NULL, 
	[PaymentTypeIssue] int NULL, 
	[IsNotValidIssue] int NULL, 
	[MinimumDepositIssue] int NULL, 
	[MinimumPurchaseIssue] int NULL, 
	[InvoiceDlvyChrgOverride] varchar(8000) NULL, 
	[OrderDlvyChrgOverride] varchar(8000) NULL, 
	[DelChrgExcptnMgrApproval] int NULL, 
	[FinanceFees] decimal(38,2) NULL, 
	[TermsCategory] varchar(5) NULL
);