CREATE TABLE [Retail_Dart].[EmploymentDetails] (

	[id] int NOT NULL, 
	[PersonDetailKey] int NOT NULL, 
	[EmployeeNumber] varchar(10) NULL, 
	[EmployeeStatus] varchar(5) NULL, 
	[CompanyKey] int NULL, 
	[PrimaryJobKey] int NULL, 
	[OrgLevel1Key] int NULL, 
	[OrgLevel2Key] int NULL, 
	[OrgLevel3Key] int NULL, 
	[OrgLevel4Key] int NULL, 
	[OriginalHireDate] date NULL, 
	[LastHireDate] date NULL, 
	[DateInJob] date NULL, 
	[DateLastWorked] date NULL, 
	[JobChangeReasonCode] varchar(50) NULL, 
	[LeaveReasonCode] varchar(50) NULL, 
	[PlannedLeaveReason] varchar(100) NULL, 
	[DateOfTermination] date NULL, 
	[TerminationReason] varchar(50) NULL, 
	[TerminationReasonDescription] varchar(100) NULL, 
	[TerminationType] varchar(5) NULL, 
	[SupervisorEmployeeNumber] varchar(10) NULL, 
	[PayGroup] varchar(50) NULL, 
	[PayGroupDescription] varchar(100) NULL, 
	[PayPeriod] varchar(5) NULL, 
	[SalaryOrHourly] varchar(50) NULL, 
	[DateCreated] datetime2(3) NULL, 
	[DateChanged] datetime2(3) NULL, 
	[CompanyGLSegment] varchar(50) NULL, 
	[LocationGLSegment] varchar(50) NULL, 
	[FullTimeOrPartTimeCode] varchar(5) NULL
);