CREATE TABLE [Retail_Dart].[OOMSchedulePerformanceDetails] (

	[BookedStoreID] varchar(50) NOT NULL, 
	[DCStoreID] varchar(50) NOT NULL, 
	[TransDate] date NOT NULL, 
	[WrittenSales] decimal(13,2) NULL, 
	[TotalScheduleStore] decimal(13,2) NULL, 
	[TotalScheduleStoreOrderCount] int NULL, 
	[TotalScheduleGRT] decimal(13,2) NULL, 
	[TotalScheduleGRTOrderCount] int NULL, 
	[TotalScheduleDTR] decimal(13,2) NULL, 
	[TotalScheduleDTROrderCount] int NULL, 
	[TotalScheduleAudit] decimal(13,2) NULL, 
	[TotalScheduleAuditOrderCount] int NULL, 
	[TotalScheduleUnassigned] decimal(13,2) NULL, 
	[TotalScheduleUnassignedOrderCount] int NULL, 
	[TotalScheduleIVR] decimal(13,2) NULL, 
	[TotalScheduleIVROrderCount] int NULL, 
	[TotalScheduleSMS] decimal(13,2) NULL, 
	[TotalScheduleSMSOrderCount] int NULL, 
	[TotalScheduleChatBot] decimal(13,2) NULL, 
	[TotalScheduleChatBotOrderCount] int NULL, 
	[AttackTarget] decimal(13,2) NULL, 
	[FilledCleanDelivery] decimal(13,2) NULL, 
	[ScheduleAtPOS] decimal(13,2) NULL, 
	[ScheduleAtPOSOrderCount] int NULL, 
	[DaysToSchedule] decimal(13,2) NULL, 
	[SMSMessagesSentCount] int NULL, 
	[AutoScheduleOrderCount] int NULL
);