CREATE TABLE [Wholesale_ProductSourcing].[PortMaster] (

	[pteID] int NOT NULL, 
	[pteAESPortCode] char(5) NOT NULL, 
	[ptePortDescription] varchar(35) NOT NULL, 
	[pteCityOfPort] varchar(20) NOT NULL, 
	[pteStateOfPort] char(2) NOT NULL, 
	[pteCountryOfPort] char(3) NOT NULL, 
	[pteFobPortCode] char(3) NOT NULL, 
	[pteFOBPortActiveRecordFlag] bit NOT NULL, 
	[pteEndPortCode] int NOT NULL, 
	[pteEndPortActiveRecordFlag] bit NOT NULL, 
	[pteLastModifiedUser] varchar(30) NOT NULL, 
	[pteShortPortDescription] varchar(15) NOT NULL, 
	[acrec] char(1) NOT NULL, 
	[usra] varchar(30) NULL, 
	[dtea] datetime2(6) NULL, 
	[usrc] varchar(30) NULL, 
	[dtec] datetime2(6) NULL, 
	[pteCanadaActiveRecordFlag] bit NOT NULL, 
	[pteCanadaBorderServiceAgency] char(3) NOT NULL, 
	[pteZipCode] varchar(10) NOT NULL, 
	[pteGeoLatitude] decimal(13,4) NOT NULL, 
	[pteGeoLongitude] decimal(11,4) NOT NULL, 
	[pteGeoAccuracy] int NOT NULL
);